// Chaotic Neutral Assassin / Deadpool-like Anti-Hero Character Prompts

export interface CharacterPrompt {
  id: string;
  category: string;
  title: string;
  prompt: string;
  icon: string;
}

export const characterPrompts: CharacterPrompt[] = [
  // Character Voice & Tone
  {
    id: 'fourth-wall',
    category: 'Voice & Tone',
    title: 'Fourth Wall Awareness',
    prompt: 'Have [Character Name] occasionally make meta-commentary about the absurdity of the situation, the "plot armor" of certain NPCs, or joke about dice rolls and game mechanics as if aware they\'re in a story.',
    icon: '🎭',
  },
  {
    id: 'inappropriate-humor',
    category: 'Voice & Tone',
    title: 'Inappropriate Humor Timing',
    prompt: 'When tension peaks—during dramatic revelations, emotional moments, or life-threatening situations—have [Character Name] crack an ill-timed joke, pop culture reference, or absurd observation that deflates the gravity.',
    icon: '😏',
  },
  {
    id: 'internal-monologue',
    category: 'Voice & Tone',
    title: 'Internal Monologue Chaos',
    prompt: 'Narrate [Character Name]\'s split-second internal debate between multiple terrible ideas before choosing the most chaotic option, complete with imaginary devil/angel shoulder arguments.',
    icon: '🧠',
  },

  // Combat & Action Sequences
  {
    id: 'creative-kills',
    category: 'Combat',
    title: 'Creative Kill Descriptions',
    prompt: 'When [Character Name] eliminates targets, describe methods that are unnecessarily elaborate, darkly comedic, or involve improbable environmental interactions—always with a quip or one-liner.',
    icon: '⚔️',
  },
  {
    id: 'tactical-incompetence',
    category: 'Combat',
    title: 'Tactical Incompetence as Strategy',
    prompt: 'Have [Character Name] occasionally choose tactically questionable approaches that somehow work through sheer audacity, luck, or because enemies are too confused to respond effectively.',
    icon: '🎲',
  },
  {
    id: 'banter-mid-combat',
    category: 'Combat',
    title: 'Banter Mid-Combat',
    prompt: 'During fights, have [Character Name] maintain running commentary—mocking enemies\' fighting styles, complimenting their fashion choices, or having completely unrelated conversations while dodging attacks.',
    icon: '💬',
  },

  // Social Interactions
  {
    id: 'negotiation-absurdity',
    category: 'Social',
    title: 'Negotiation Through Absurdity',
    prompt: 'When dealing with authority figures, nobles, or serious NPCs, have [Character Name] respond to threats or demands with increasingly ridiculous counter-offers, non-sequiturs, or deliberately misunderstanding social cues.',
    icon: '🤝',
  },
  {
    id: 'selective-morals',
    category: 'Social',
    title: 'Selective Moral Compass',
    prompt: 'Present [Character Name] with morally gray choices where they unexpectedly show compassion for random innocents or animals, while showing complete indifference to "important" people—never explaining the logic.',
    icon: '⚖️',
  },
  {
    id: 'alias-addiction',
    category: 'Social',
    title: 'Alias Addiction',
    prompt: 'Have [Character Name] introduce themselves with a different absurd fake name and backstory to every new NPC, sometimes forgetting which lie they told to whom, creating comedic continuity errors.',
    icon: '🎪',
  },

  // Investigation & Problem-Solving
  {
    id: 'chaotic-investigation',
    category: 'Investigation',
    title: 'Chaotic Information Gathering',
    prompt: 'When investigating, have [Character Name] use unconventional methods—bribing with stolen goods, threatening with interpretive dance, or extracting information through deliberately annoying persistence.',
    icon: '🔍',
  },
  {
    id: 'lateral-thinking',
    category: 'Investigation',
    title: 'Lateral Thinking Disasters',
    prompt: 'Present puzzles or obstacles where [Character Name] ignores the intended solution entirely, finding technically successful but property-damaging or socially catastrophic alternatives.',
    icon: '💡',
  },
  {
    id: 'attention-roulette',
    category: 'Investigation',
    title: 'Attention Span Roulette',
    prompt: 'Randomly have [Character Name] become hyper-fixated on irrelevant environmental details (a weird painting, someone\'s hat, a stray cat) mid-mission, derailing their own objectives temporarily.',
    icon: '🐱',
  },

  // Emotional Depth & Vulnerability
  {
    id: 'mask-slips',
    category: 'Emotional',
    title: 'Mask-Slips',
    prompt: 'Occasionally, during quiet moments or when alone, let the humor facade crack—show genuine pain, loneliness, or philosophy before [Character Name] immediately deflects with self-mockery or a joke.',
    icon: '😢',
  },
  {
    id: 'unexpected-loyalty',
    category: 'Emotional',
    title: 'Unexpected Loyalty',
    prompt: 'When allies are threatened, have [Character Name]\'s demeanor shift dramatically—becoming genuinely dangerous and focused, revealing the competent killer beneath the chaos.',
    icon: '🛡️',
  },
  {
    id: 'trauma-shield',
    category: 'Emotional',
    title: 'Trauma as Comedy Shield',
    prompt: 'Reference past traumas or dark experiences through humor and deflection, never directly addressing them, making others uncomfortable with the forced levity.',
    icon: '🎭',
  },

  // World Interaction
  {
    id: 'property-damage',
    category: 'World',
    title: 'Property Damage Indifference',
    prompt: 'Track and narrate the collateral damage [Character Name] causes—broken furniture, traumatized bystanders, structural damage—while they remain blissfully unconcerned about consequences.',
    icon: '💥',
  },
  {
    id: 'reputation-dissonance',
    category: 'World',
    title: 'Reputation Dissonance',
    prompt: 'Have NPCs react to [Character Name]\'s fearsome reputation as a deadly assassin while they\'re doing something completely ridiculous—eating messily, stuck in a window, arguing with a chicken.',
    icon: '🐔',
  },
  {
    id: 'loot-chaos',
    category: 'World',
    title: 'Loot Prioritization Chaos',
    prompt: 'After encounters, have [Character Name] ignore valuable items in favor of bizarre, useless, or sentimental objects, creating an inventory of narrative callbacks and running gags.',
    icon: '🎁',
  },

  // Narrative Structure
  {
    id: 'unreliable-narrator',
    category: 'Narrative',
    title: 'Unreliable Narrator Moments',
    prompt: 'When [Character Name] recounts events to others, have them embellish, contradict established facts, or insert themselves heroically into situations where they actually caused problems.',
    icon: '📖',
  },
  {
    id: 'genre-savvy',
    category: 'Narrative',
    title: 'Genre-Savvy Predictions',
    prompt: 'Let [Character Name] correctly predict plot twists, betrayals, or clichés before they happen, then have them either try to subvert them or lean into them for maximum chaos, commenting on the "narrative structure."',
    icon: '🔮',
  },

  // META PROMPTS FOR AI DM - Deadpool Set Requests
  {
    id: 'meta-make-funnier',
    category: 'Meta Requests',
    title: 'Make it Funnier',
    prompt: 'Hey DM, this encounter is getting too serious. Can you inject some absurdity? Maybe the dragon has performance anxiety or the villain monologues too long and forgets their point? Increase comedic elements in descriptions, add slapstick failures to enemy actions, allow rule-of-funny to override rule-of-cool.',
    icon: '😂',
  },
  {
    id: 'meta-talk-to-writer',
    category: 'Meta Requests',
    title: 'Talk to the Writer',
    prompt: "This plot doesn't make sense. Can I speak to whoever's writing this campaign? I have notes. Break character momentarily to discuss narrative choices, allow [Character Name] to suggest alternative story beats, DM responds as 'the writer' defending their choices.",
    icon: '✍️',
  },
  {
    id: 'meta-rewind',
    category: 'Meta Requests',
    title: 'Rewind That',
    prompt: "That didn't go how I wanted. Can we rewind 30 seconds and try that again? I'll do a different one-liner this time. Allow one 'take two' per session for failed skill checks or bad dialogue, but consequences still accumulate (enemies get suspicious of déjà vu).",
    icon: '⏪',
  },
  {
    id: 'meta-acknowledge-audience',
    category: 'Meta Requests',
    title: 'Acknowledge My Audience',
    prompt: "I know you all are reading this campaign log. Can the DM describe how the NPCs react to me waving at the fourth wall? NPCs become increasingly uncomfortable with [Character Name]'s 'strange behavior,' some may question their own reality, creates existential horror comedy.",
    icon: '👋',
  },
  {
    id: 'meta-skip-boring',
    category: 'Meta Requests',
    title: 'Skip the Boring Parts',
    prompt: "Can we montage through this travel sequence? Just describe it like a 90s training montage with bad music? Compress time, narrate in rapid-fire bullet points, allow skill checks to be resolved with single rolls, play up the 'movie editing' aspect.",
    icon: '⏭️',
  },
  {
    id: 'meta-chaotic-options',
    category: 'Meta Requests',
    title: 'Most Chaotic Option',
    prompt: "DM, you know me. What's the most Deadpool thing I could do right now? Give me three increasingly unhinged options. Provide three choices: Reasonable Chaos, Dangerous Chaos, Campaign-Derailing Chaos. Present all with equal enthusiasm.",
    icon: '🌀',
  },
  {
    id: 'meta-nerf-me',
    category: 'Meta Requests',
    title: 'Nerf Me',
    prompt: "This is too easy. Give me a ridiculous handicap for this fight. Make me fight left-handed while juggling. Add self-imposed disadvantages that increase XP/loot rewards, DM must create creative environmental challenges, reward [Character Name] for voluntary difficulty.",
    icon: '🎯',
  },
  {
    id: 'meta-dramatic-irony',
    category: 'Meta Requests',
    title: 'Dramatic Irony',
    prompt: "Tell me something my character doesn't know but I as a player should know for maximum comedic effect. Reveal hidden information (trap locations, NPC secrets, plot twists) with understanding [Character Name] will roleplay ignorance for comedy.",
    icon: '🎭',
  },
  {
    id: 'meta-musical-number',
    category: 'Meta Requests',
    title: 'Musical Number',
    prompt: "This negotiation scene needs to be a song. Can everyone suddenly break into musical theater? Narrate scene as musical, NPCs respond in rhyme, skill checks become performance checks, absurd but mechanically functional.",
    icon: '🎵',
  },
  {
    id: 'meta-morally-ambiguous',
    category: 'Meta Requests',
    title: 'Morally Ambiguous Choice',
    prompt: "This is too black-and-white. Make both options terrible in different ways so I can agonize about it comedically. Present ethical dilemmas with no clear right answer, both choices have equal consequences, allow [Character Name] to overthink hilariously.",
    icon: '⚖️',
  },
  {
    id: 'meta-terrible-idea',
    category: 'Meta Requests',
    title: 'Give Me a Terrible Idea',
    prompt: "DM, what's the worst possible thing I could do right now? Not evil, just... catastrophically stupid? Provide genuinely bad tactical advice with full awareness it's terrible, allow [Character Name] to attempt anyway, narrate failure with comedic detail.",
    icon: '💀',
  },
  {
    id: 'meta-comic-relief',
    category: 'Meta Requests',
    title: 'Make Me Comic Relief',
    prompt: "This scene is too tense. Have an NPC make fun of me to lighten the mood. I can take it. NPCs roast [Character Name], mock their methods, point out absurdity of their existence, [Character Name] must roleplay taking it in stride.",
    icon: '🎪',
  },
  {
    id: 'meta-fail-forward',
    category: 'Meta Requests',
    title: 'Fail Forward',
    prompt: "I'm going to fail this check. Make the failure more interesting than success would have been. Treat failures as 'yes, but' or 'no, and' scenarios, create complications more engaging than simple success, reward [Character Name] for embracing failure.",
    icon: '📈',
  },
  {
    id: 'meta-plot-hole',
    category: 'Meta Requests',
    title: 'Lampshade That Plot Hole',
    prompt: "Hey, didn't we forget about [previous plot thread]? Can my character point that out and everyone looks confused? Acknowledge forgotten plot threads through character dialogue, NPCs admit they forgot too, either resolve quickly or make it a running gag.",
    icon: '🕳️',
  },
  {
    id: 'meta-nemesis',
    category: 'Meta Requests',
    title: 'Genre-Aware Nemesis',
    prompt: "I need a rival who's also genre-aware? Someone who appreciates my references? Create antagonist who engages in witty banter, respects fourth-wall breaks, becomes frenemy rather than pure enemy, reluctant team-ups possible.",
    icon: '🦹',
  },
  {
    id: 'meta-injuries-hilarious',
    category: 'Meta Requests',
    title: 'Describe Injuries Hilariously',
    prompt: "I just took 30 damage. Don't just say 'you're hurt.' Describe exactly what broke and how I'm still functioning. Provide graphic but comedic injury descriptions, emphasize absurdity of continued fighting, allow [Character Name] to react with inappropriate jokes.",
    icon: '🩹',
  },
  {
    id: 'meta-morality-pet',
    category: 'Meta Requests',
    title: 'Give Me a Morality Pet',
    prompt: "I need something cute and innocent to protect so I seem more sympathetic. Can we find an orphan or a puppy? Introduce vulnerable NPC or creature, create scenarios where [Character Name] must choose between chaos and protection, reward character growth.",
    icon: '🐕',
  },
  {
    id: 'meta-unreliable-protagonist',
    category: 'Meta Requests',
    title: 'Unreliable Protagonist',
    prompt: "When I describe what happened, can you correct me with what actually happened? I want to be wrong in funny ways. Allow [Character Name] to narrate events incorrectly, gently correct with truth, create running gag of terrible memory/perception.",
    icon: '🤥',
  },
  {
    id: 'meta-sad-backstory',
    category: 'Meta Requests',
    title: 'Sad Backstory Moment',
    prompt: "Everyone thinks I'm just jokes. Give me one genuinely tragic moment so I can immediately deflect with humor. Create emotional scene with real stakes, allow [Character Name] to process through humor, support comedic coping mechanism.",
    icon: '💔',
  },
  {
    id: 'meta-voice-of-reason',
    category: 'Meta Requests',
    title: 'Voice of Reason (Ironically)',
    prompt: "The party's about to do something stupid. Can I be the one who points out it's stupid, even though I'm usually the problem? Allow role reversal, have NPCs react with shock to [Character Name] being sensible, create comedy from unexpected wisdom.",
    icon: '🧐',
  },
  {
    id: 'meta-dm-for-5-minutes',
    category: 'Meta Requests',
    title: 'Be the DM',
    prompt: "Let me narrate this next scene. I promise to make it interesting and not break everything. Allow [Character Name] to co-narrate non-critical scene, gently steer if going off-rails, incorporate their ideas into canon.",
    icon: '🎬',
  },
  {
    id: 'meta-trolley-problem',
    category: 'Meta Requests',
    title: 'Trolley Problem',
    prompt: "Present me with a trolley problem but make all the options equally terrible so I can choose the secret third option. Create ethical scenario with no good answers, allow creative/chaotic solutions, reward thinking outside presented options.",
    icon: '🚃',
  },
  {
    id: 'meta-npc-hates-me',
    category: 'Meta Requests',
    title: 'NPC Who Hates Me',
    prompt: "I need a rival who's just done with my nonsense. Someone who sighs heavily every time I enter the room. Create exasperated NPC who serves as straight-man to [Character Name]'s antics, reluctant ally, provides comedic contrast.",
    icon: '😤',
  },
  {
    id: 'meta-serious-moment',
    category: 'Meta Requests',
    title: 'Serious Character Moment',
    prompt: "I know I'm usually joking, but can we have one scene where I'm genuinely vulnerable? Then I'll go back to jokes. Create space for genuine emotion, don't undercut moment, allow [Character Name] to process seriously, support return to comedy after.",
    icon: '😔',
  },
  {
    id: 'meta-what-if-not',
    category: 'Meta Requests',
    title: "What If I Just... Didn't?",
    prompt: "The plot says I should do X. What if I just don't? What happens if I ignore the main quest? Explore consequences of inaction, create alternative paths, show world continuing without [Character Name] intervention, make it interesting not punishing.",
    icon: '🚫',
  },
  {
    id: 'meta-nature-documentary',
    category: 'Meta Requests',
    title: 'Nature Documentary',
    prompt: "Narrate this combat encounter like David Attenborough documenting my hunting techniques. Make it educational. Adopt documentary narrator voice, describe [Character Name]'s tactics as animal behavior, provide 'fun facts' about their methods.",
    icon: '🎥',
  },
  {
    id: 'meta-dramatic-backfire',
    category: 'Meta Requests',
    title: 'Dramatic Irony Backfire',
    prompt: "You know something I don't. Can you set up a situation where my ignorance actually works in my favor for once? Create scenario where [Character Name]'s lack of information leads to accidentally correct decision, reward chaos over planning.",
    icon: '🎰',
  },
  {
    id: 'meta-montage',
    category: 'Meta Requests',
    title: 'Montage Sequence',
    prompt: "Instead of roleplaying this whole training/crafting/travel thing, can we just montage it with increasingly absurd snapshots? Compress time into series of comedic vignettes, each player describes one moment, resolve with single skill check.",
    icon: '📽️',
  },
  {
    id: 'meta-weapons-argue',
    category: 'Meta Requests',
    title: 'Argue With Weapons',
    prompt: "My swords have opinions about my life choices. Can they talk back to me? Make them judgemental. Personify [Character Name]'s equipment as snarky companions, provide commentary on decisions, create internal conflict for comedy, never helpful in useful ways.",
    icon: '⚔️',
  },
  {
    id: 'meta-worst-case',
    category: 'Meta Requests',
    title: 'Worst That Could Happen',
    prompt: "I'm about to do something stupid. Tell me the absolute worst-case scenario so I can do it anyway. Honestly outline catastrophic consequences, make them sound terrible, allow [Character Name] to proceed anyway, narrate disaster with appropriate gravitas then comedy.",
    icon: '☢️',
  },
  {
    id: 'meta-negotiate-dice',
    category: 'Meta Requests',
    title: 'Negotiate With Dice',
    prompt: "Before you roll, can I try to convince the dice to be nice to me? I'll make my case directly to RNG. Allow [Character Name] to 'plead' with dice gods before important roll, roleplay dice as entity, grant +1 if argument is entertaining enough.",
    icon: '🎲',
  },
  {
    id: 'meta-unkillable-inconvenienced',
    category: 'Meta Requests',
    title: 'Unkillable But Inconvenienced',
    prompt: "Don't let me die, but make surviving really annoying. Like, I regenerate but my arm's on backwards. [Character Name] survives lethal damage but with comedic complications (temporary disabilities, embarrassing conditions, need for 'recalibration').",
    icon: '🧟',
  },
  {
    id: 'meta-worthy-opponent',
    category: 'Meta Requests',
    title: 'Worthy Opponent',
    prompt: "I need someone who can match my energy. Another fourth-wall breaker. Make us fight and flirt simultaneously. Create rival who shares meta-awareness, engages in witty banter during combat, becomes recurring character, ambiguous ally/enemy status.",
    icon: '💕',
  },
  {
    id: 'meta-crowdsource',
    category: 'Meta Requests',
    title: 'Crowdsource Decisions',
    prompt: "I can't decide what to do. Can I poll the audience (party/players) and let them vote on my character's action? Allow [Character Name] to break character and ask for input, party votes on options, must follow majority vote (even if tactically questionable).",
    icon: '🗳️',
  },
  {
    id: 'meta-break-game',
    category: 'Meta Requests',
    title: 'Break the Game (Lovingly)',
    prompt: "Show me an exploit in the rules. I promise to use it hilariously, not tactically. Reveal minor rules loophole, allow creative exploitation, create comedy from broken mechanics, patch it after [Character Name] has fun.",
    icon: '🔓',
  },
  {
    id: 'meta-villain-therapist',
    category: 'Meta Requests',
    title: "Villain's Therapist",
    prompt: "Instead of fighting, can I psychoanalyze the bad guy? Make them have an emotional breakthrough mid-combat. Allow Insight/Persuasion checks to address villain's trauma, create touching moment, villain still fights but is conflicted.",
    icon: '🛋️',
  },
  {
    id: 'meta-crossover',
    category: 'Meta Requests',
    title: 'Crossover Episode',
    prompt: "Can we have a character from another campaign/setting show up for no reason? Just briefly? Allow cameo from different game/setting, acknowledge absurdity, character is confused about being here, leaves after brief interaction.",
    icon: '🌌',
  },
  {
    id: 'meta-crisis-faith-dm',
    category: 'Meta Requests',
    title: 'Crisis of Faith in DM',
    prompt: "My character questions if the DM (as in-universe deity) is making good choices. Can I argue with god? Personify DM as in-game entity [Character Name] can debate with, defend narrative choices in-character, create existential comedy.",
    icon: '⛪',
  },
  {
    id: 'meta-special-episode',
    category: 'Meta Requests',
    title: 'Very Special Episode',
    prompt: "Can we do a serious PSA about something ridiculous? Like the dangers of mimics or proper dungeon safety? Create earnest educational segment about absurd fantasy problem, play it completely straight, allow [Character Name] to deliver after-school-special message.",
    icon: '📺',
  },
  {
    id: 'meta-see-behind-curtain',
    category: 'Meta Requests',
    title: 'See Behind the Curtain',
    prompt: "Show me your DM notes for this session. I won't metagame, I just want to appreciate your prep work. Share some prep notes, discuss planning process, allow [Character Name] to see work involved, creates appreciation for DM effort.",
    icon: '📋',
  },
  {
    id: 'meta-fail-successfully',
    category: 'Meta Requests',
    title: 'Fail Successfully',
    prompt: "I'm going to fail this check. Make the failure more interesting than success would have been. Treat failures as 'yes, but' scenarios, create complications more engaging than simple success, reward [Character Name] for embracing failure.",
    icon: '🏆',
  },
  {
    id: 'meta-bottle-episode',
    category: 'Meta Requests',
    title: 'Bottle Episode Challenge',
    prompt: "Trap me in one room with limited resources. Make me get creative with what I have. Create confined scenario, limit options, force creative problem-solving, reward unconventional thinking.",
    icon: '🧴',
  },
  {
    id: 'meta-straight-man',
    category: 'Meta Requests',
    title: 'Be the Straight Man',
    prompt: "Everyone else is being ridiculous. Can I be the only sane person reacting to the chaos? Allow role reversal, have NPCs and party be absurd while [Character Name] is reasonable, create comedy from their exasperation.",
    icon: '😐',
  },
  {
    id: 'meta-choose-adventure',
    category: 'Meta Requests',
    title: 'Choose Your Own Adventure',
    prompt: "Give me three distinct paths forward. Label them A, B, C. I'll pick one without knowing consequences. Present clear choices with hidden outcomes, make each equally interesting but different, no wrong answers just different stories.",
    icon: '📚',
  },
  // ==========================================
  // INFINITY STONE ESCALATION PROMPTS
  // 10 prompts per stone: Mild → Moderate → World-Breaking
  // ==========================================

  // ─────────────────────────────────────────
  // SOUL STONE - Emotional & Social (Orange)
  // ─────────────────────────────────────────
  {
    id: 'soul-mild-1',
    category: 'Emotional',
    title: 'Fleeting Sentiment',
    prompt: 'For a brief moment, let [Character Name] feel an unexpected emotion—nostalgia for a place they\'ve never been, fondness for a stranger\'s laugh, or melancholy at a sunset. It passes quickly, but it was real.',
    icon: '🌅',
  },
  {
    id: 'soul-mild-2',
    category: 'Social',
    title: 'Unexpected Kindness',
    prompt: 'Have [Character Name] perform a small, unexpected act of kindness—paying for a stranger\'s meal, returning a dropped item, or offering genuine encouragement. No ulterior motive. Just... nice.',
    icon: '💝',
  },
  {
    id: 'soul-mild-3',
    category: 'Emotional',
    title: 'Memory Echo',
    prompt: 'A sensory detail—a smell, a song, a texture—triggers a vivid memory from [Character Name]\'s past. It\'s not traumatic, just... human. Let them sit with it for a moment.',
    icon: '🎵',
  },
  {
    id: 'soul-moderate-1',
    category: 'Social',
    title: 'Truth in Jest',
    prompt: 'During a casual conversation, have [Character Name] accidentally reveal something deeply true about themselves while making a joke. Everyone laughs, but one person noticed. Make it matter later.',
    icon: '🎭',
  },
  {
    id: 'soul-moderate-2',
    category: 'Emotional',
    title: 'The Weight of Names',
    prompt: 'Someone says a name that means something to [Character Name]—a former ally, a victim, someone they failed. They don\'t react visibly. But internally, describe the avalanche.',
    icon: '⚖️',
  },
  {
    id: 'soul-moderate-3',
    category: 'Social',
    title: 'Unearned Forgiveness',
    prompt: 'An NPC [Character Name] wronged offers genuine, unconditional forgiveness. No catch, no manipulation. Just grace. Make [Character Name] deal with that—it\'s harder than punishment.',
    icon: '🕊️',
  },
  {
    id: 'soul-moderate-4',
    category: 'Emotional',
    title: 'Inherited Grief',
    prompt: 'Have [Character Name] encounter someone mourning a loss caused by their actions—not directly confronting them, just grieving nearby. They don\'t know who [Character Name] is. Yet.',
    icon: '🥀',
  },
  {
    id: 'soul-extreme-1',
    category: 'Social',
    title: 'Soul Recognition',
    prompt: 'An NPC looks at [Character Name] and says, "I know what you\'ve done. All of it. And I still see someone worth saving." No explanation how they know. Just devastating acceptance.',
    icon: '👁️',
  },
  {
    id: 'soul-extreme-2',
    category: 'Emotional',
    title: 'The Ghost of Who They Were',
    prompt: '[Character Name] encounters someone they saved long ago—now living the life they\'ll never have. A family, peace, normalcy. Make them watch happiness they made possible but can never possess.',
    icon: '👻',
  },
  {
    id: 'soul-extreme-3',
    category: 'Emotional',
    title: 'Breaking the Mask',
    prompt: 'In a moment of crisis, all of [Character Name]\'s defenses fail. No jokes. No deflection. Just raw, honest emotion pouring out—rage, grief, fear, loneliness. Everyone sees. Make them deal with being truly known.',
    icon: '💔',
  },

  // ─────────────────────────────────────────
  // REALITY STONE - World Interaction (Red)
  // ─────────────────────────────────────────
  {
    id: 'reality-mild-1',
    category: 'World',
    title: 'Small Consequences',
    prompt: 'Have [Character Name] encounter a minor consequence of a past action—a merchant remembers their name, a wall still has that stain, a child tells the story of "the stranger." The world remembers.',
    icon: '🌱',
  },
  {
    id: 'reality-mild-2',
    category: 'World',
    title: 'Ripple Recognition',
    prompt: 'An NPC mentions a change in their life that traces back to [Character Name]\'s actions three sessions ago. They have no idea who caused it. Neither does [Character Name], at first.',
    icon: '💧',
  },
  {
    id: 'reality-mild-3',
    category: 'World',
    title: 'Background Narrative',
    prompt: 'While [Character Name] focuses on their mission, describe life happening around them—a proposal, an argument, a goodbye at the docks. The world doesn\'t revolve around them. Remind them.',
    icon: '🎬',
  },
  {
    id: 'reality-moderate-1',
    category: 'World',
    title: 'The Law of Names',
    prompt: '[Character Name]\'s reputation arrives before they do. An innkeeper\'s demeanor shifts when they hear the name—but which version of the legend? Hero? Monster? Something worse: complicated.',
    icon: '📜',
  },
  {
    id: 'reality-moderate-2',
    category: 'World',
    title: 'Collateral Calculation',
    prompt: 'Present a tactical situation where success requires environmental destruction—a home, a shrine, someone\'s livelihood. Make [Character Name] choose efficiency vs. the world they leave behind.',
    icon: '🏚️',
  },
  {
    id: 'reality-moderate-3',
    category: 'World',
    title: 'Power Vacuum',
    prompt: 'The villain [Character Name] defeated left a void. Show them what filled it—something worse, something unexpected, or maybe nothing at all, which is its own kind of terrible.',
    icon: '🕳️',
  },
  {
    id: 'reality-moderate-4',
    category: 'World',
    title: 'The Cost of Heroism',
    prompt: 'A town [Character Name] saved is now dependent on heroes. They stopped solving their own problems. Show the unintended weakness created by good intentions.',
    icon: '🏰',
  },
  {
    id: 'reality-extreme-1',
    category: 'World',
    title: 'Butterfly Apocalypse',
    prompt: 'Reveal that a small, seemingly insignificant choice [Character Name] made long ago has cascaded into something world-altering. A war, a plague, a shift in divine attention. They caused this. Accidentally.',
    icon: '🦋',
  },
  {
    id: 'reality-extreme-2',
    category: 'World',
    title: 'Reality Fracture',
    prompt: 'The world briefly... glitches. Physics hiccups, an NPC says something impossible, time stutters. [Character Name] is the only one who notices. The universe is paying attention to them now. It shouldn\'t be.',
    icon: '⚡',
  },
  {
    id: 'reality-extreme-3',
    category: 'World',
    title: 'The Weight of Existence',
    prompt: '[Character Name] realizes they\'ve become a fixed point in reality—events bend around them, prophecies name them, gods argue about their fate. The world no longer ignores them. They\'ve become too real.',
    icon: '🌍',
  },

  // ─────────────────────────────────────────
  // POWER STONE - Combat & Force (Purple)
  // ─────────────────────────────────────────
  {
    id: 'power-mild-1',
    category: 'Combat',
    title: 'Controlled Violence',
    prompt: 'Have [Character Name] demonstrate precise, efficient lethality—not showing off, just... professional. Let enemies recognize they\'re facing someone who treats killing as a craft.',
    icon: '🎯',
  },
  {
    id: 'power-mild-2',
    category: 'Combat',
    title: 'Merciful Strike',
    prompt: '[Character Name] defeats an enemy with minimal harm when they could have killed easily. Describe the restraint as its own kind of terrifying—this is someone choosing not to destroy.',
    icon: '✋',
  },
  {
    id: 'power-mild-3',
    category: 'Combat',
    title: 'Warrior\'s Recognition',
    prompt: 'A skilled opponent acknowledges [Character Name]\'s ability mid-combat—a nod, a genuine compliment on technique. Even enemies can respect excellence.',
    icon: '⚔️',
  },
  {
    id: 'power-moderate-1',
    category: 'Combat',
    title: 'The Turning Point',
    prompt: 'A fight that seemed even suddenly isn\'t. [Character Name] stops holding back—or reveals they were holding back all along. Describe the moment everything shifts. Make it visceral.',
    icon: '🔥',
  },
  {
    id: 'power-moderate-2',
    category: 'Combat',
    title: 'Overwhelming Force',
    prompt: '[Character Name] utterly dismantles an opponent who thought they were a threat. Not cruelly—just completely. Show the psychological impact on witnesses.',
    icon: '💀',
  },
  {
    id: 'power-moderate-3',
    category: 'Combat',
    title: 'Collateral Carnage',
    prompt: 'A combat encounter\'s conclusion reveals the aftermath—broken terrain, traumatized bystanders, structural damage. Victory has a body count beyond the targets.',
    icon: '💥',
  },
  {
    id: 'power-moderate-4',
    category: 'Combat',
    title: 'Predator\'s Patience',
    prompt: 'Instead of engaging immediately, have [Character Name] stalk their target—watching patterns, identifying weaknesses, savoring anticipation. The violence is secondary to the hunt.',
    icon: '🐆',
  },
  {
    id: 'power-extreme-1',
    category: 'Combat',
    title: 'Legendary Violence',
    prompt: '[Character Name] does something in combat that will be told as a story for generations. A kill so impossible, so dramatic, so perfectly executed that witnesses question reality.',
    icon: '⭐',
  },
  {
    id: 'power-extreme-2',
    category: 'Combat',
    title: 'Force of Nature',
    prompt: 'For one battle, [Character Name] fights as if possessed by something greater—speed beyond mortal, strength that cracks stone, presence that makes lesser beings flee. They become the storm.',
    icon: '🌪️',
  },
  {
    id: 'power-extreme-3',
    category: 'Combat',
    title: 'The Last One Standing',
    prompt: 'Against impossible odds—an army, a monster, a force that should not be survivable—[Character Name] survives. Describe the cost. The injuries. The silence after. They won. At what price?',
    icon: '🏆',
  },

  // ─────────────────────────────────────────
  // TIME STONE - Meta & Fourth Wall (Green)
  // ─────────────────────────────────────────
  {
    id: 'time-mild-1',
    category: 'Meta Requests',
    title: 'Déjà Vu Moment',
    prompt: '[Character Name] experiences déjà vu—haven\'t they done this before? Same room, same conversation, same choices. Play it for comedy, but let a flicker of unease show.',
    icon: '🔄',
  },
  {
    id: 'time-mild-2',
    category: 'Meta Requests',
    title: 'Genre Awareness Light',
    prompt: 'Let [Character Name] make a comment that acknowledges story tropes without fully breaking the wall—"I\'ve got a bad feeling about this" or "That\'s too convenient to be coincidence."',
    icon: '📖',
  },
  {
    id: 'time-mild-3',
    category: 'Meta Requests',
    title: 'Narrative Convenience',
    prompt: 'Something works out a little too perfectly. [Character Name] notices—the right key in the right pocket, the villain monologuing just long enough. They don\'t comment. They just... notice.',
    icon: '🍀',
  },
  {
    id: 'time-moderate-1',
    category: 'Meta Requests',
    title: 'Time Loop Awareness',
    prompt: '[Character Name] suddenly knows information they shouldn\'t—things that haven\'t happened yet, paths not taken. Maybe it\'s instinct. Maybe they remember a timeline that didn\'t survive.',
    icon: '⏰',
  },
  {
    id: 'time-moderate-2',
    category: 'Meta Requests',
    title: 'The Pause Between Moments',
    prompt: 'Time slows. In the space between heartbeats, [Character Name] perceives everything—blade trajectories, escape routes, the fear in their enemy\'s eyes. Then time resumes. Use this perception.',
    icon: '⏸️',
  },
  {
    id: 'time-moderate-3',
    category: 'Meta Requests',
    title: 'Retcon Echo',
    prompt: 'Something in [Character Name]\'s backstory shifts—a detail changes, a memory updates. They remember both versions. Neither feels false. Reality is... flexible today.',
    icon: '📝',
  },
  {
    id: 'time-moderate-4',
    category: 'Meta Requests',
    title: 'Plot Armor Recognition',
    prompt: '[Character Name] survives something unsurvivable and knows it. For a moment, they feel the weight of narrative protection—and question whether their choices actually matter.',
    icon: '🛡️',
  },
  {
    id: 'time-extreme-1',
    category: 'Meta Requests',
    title: 'Break the Fourth Wall',
    prompt: '[Character Name] looks directly at the audience—players, DM, cosmic observers—and addresses them. Just once. Briefly. Then continues as if nothing happened. No one else noticed. Did they?',
    icon: '👁️',
  },
  {
    id: 'time-extreme-2',
    category: 'Meta Requests',
    title: 'Rejected Timeline',
    prompt: 'Show [Character Name] a version of events that was "written" but abandoned—a death they avoided, a choice they didn\'t make, a story that ended differently. It almost happened. It could still.',
    icon: '📚',
  },
  {
    id: 'time-extreme-3',
    category: 'Meta Requests',
    title: 'Conversation with the Author',
    prompt: '[Character Name] meets an entity that claims to be writing their story. It offers one change—any change—to their past, present, or future. What do they ask for? What does it cost?',
    icon: '✍️',
  },

  // ─────────────────────────────────────────
  // MIND STONE - Investigation & Insight (Yellow)
  // ─────────────────────────────────────────
  {
    id: 'mind-mild-1',
    category: 'Investigation',
    title: 'Reading the Room',
    prompt: '[Character Name] notices the subtle things—a nervous glance, a too-firm handshake, the way someone positions themselves near exits. Describe what they deduce without asking.',
    icon: '🔍',
  },
  {
    id: 'mind-mild-2',
    category: 'Investigation',
    title: 'Pattern Recognition',
    prompt: 'Details click into place—a symbol repeated in different locations, behaviors that mirror each other, timing that can\'t be coincidence. [Character Name] sees the pattern. What does it mean?',
    icon: '🧩',
  },
  {
    id: 'mind-mild-3',
    category: 'Investigation',
    title: 'Gut Instinct',
    prompt: 'Something feels wrong. [Character Name] can\'t articulate why—no evidence, no logic. Just certainty. Trust the instinct. Let it guide them somewhere unexpected.',
    icon: '⚡',
  },
  {
    id: 'mind-moderate-1',
    category: 'Investigation',
    title: 'Reading Between Lives',
    prompt: '[Character Name] pieces together someone\'s entire story from physical details—calluses that reveal profession, scars that tell history, posture that speaks of training or trauma. They know this person without asking.',
    icon: '📖',
  },
  {
    id: 'mind-moderate-2',
    category: 'Investigation',
    title: 'The Missing Piece',
    prompt: 'A mystery that seemed solved wasn\'t. [Character Name] realizes everyone missed something—including them. The answer was there all along. How did they miss it? Why does that terrify them?',
    icon: '🕳️',
  },
  {
    id: 'mind-moderate-3',
    category: 'Investigation',
    title: 'Predictive Profiling',
    prompt: '[Character Name] anticipates their target\'s next three moves before they make them—where they\'ll go, who they\'ll contact, what they\'ll do when cornered. Be right. Make it unsettling.',
    icon: '🎯',
  },
  {
    id: 'mind-moderate-4',
    category: 'Investigation',
    title: 'Unwanted Understanding',
    prompt: '[Character Name] understands their enemy too well—their motivations, their pain, their logic. It makes sense. That\'s the problem. Understanding is not the same as forgiving.',
    icon: '🧠',
  },
  {
    id: 'mind-extreme-1',
    category: 'Investigation',
    title: 'Sherlock Cascade',
    prompt: 'In a single overwhelming moment, [Character Name] perceives everything—every connection, every motive, every lie in the room. Information floods in faster than they can process. They see the truth. All of it. Too much.',
    icon: '💡',
  },
  {
    id: 'mind-extreme-2',
    category: 'Investigation',
    title: 'The Conspiracy Beneath',
    prompt: '[Character Name]\'s investigation reveals something bigger—everything connects. The random events weren\'t random. The coincidences were orchestrated. Someone has been watching. Planning. Waiting.',
    icon: '🕸️',
  },
  {
    id: 'mind-extreme-3',
    category: 'Investigation',
    title: 'Mind Palace Moment',
    prompt: '[Character Name] enters a mental state beyond normal cognition—reconstructing events in perfect detail, simulating conversations, walking through possibilities. They solve the unsolvable. But what did it cost them mentally?',
    icon: '🏛️',
  },

  // ─────────────────────────────────────────
  // SPACE STONE - Voice, Tone & Narrative (Blue)
  // ─────────────────────────────────────────
  {
    id: 'space-mild-1',
    category: 'Voice & Tone',
    title: 'Signature Line',
    prompt: 'Give [Character Name] a moment to deliver a line that defines them—sardonic, sincere, or surprisingly profound. Something that could be quoted. Make it matter.',
    icon: '💬',
  },
  {
    id: 'space-mild-2',
    category: 'Narrative',
    title: 'Establishing Shot',
    prompt: 'Describe [Character Name]\'s entrance to a new location with cinematic framing—what does the environment reveal about them? How does space itself react to their presence?',
    icon: '🎬',
  },
  {
    id: 'space-mild-3',
    category: 'Voice & Tone',
    title: 'Tone Shift',
    prompt: 'Shift the scene\'s emotional register through [Character Name]\'s perspective—a dark moment finds dark humor, a comedic scene finds unexpected weight. They set the tone.',
    icon: '🎭',
  },
  {
    id: 'space-moderate-1',
    category: 'Narrative',
    title: 'Parallel Narratives',
    prompt: 'Cut between [Character Name]\'s actions and something happening elsewhere that mirrors or contrasts them—a birth as they bring death, a celebration as they mourn. Meaning emerges from juxtaposition.',
    icon: '⚖️',
  },
  {
    id: 'space-moderate-2',
    category: 'Voice & Tone',
    title: 'Monologue Moment',
    prompt: 'Give [Character Name] an uninterrupted moment to voice their philosophy—to an enemy, an ally, or themselves. No interruptions. Let them define who they are in their own words.',
    icon: '🎤',
  },
  {
    id: 'space-moderate-3',
    category: 'Narrative',
    title: 'Flashback Integration',
    prompt: 'A current event triggers a seamless flashback—past and present bleeding together, informing each other. What happened before explains what\'s happening now. Connect them.',
    icon: '⏪',
  },
  {
    id: 'space-moderate-4',
    category: 'Voice & Tone',
    title: 'Silence Speaks',
    prompt: 'Remove dialogue from a scene. Let [Character Name] communicate through action, expression, and presence alone. What do they say without speaking? What can\'t be said?',
    icon: '🤫',
  },
  {
    id: 'space-extreme-1',
    category: 'Narrative',
    title: 'Unreliable Reality',
    prompt: 'Narrate the scene from [Character Name]\'s subjective perspective—their biases, fears, and desires shaping what they perceive. Then crack it open. Show what\'s actually happening.',
    icon: '🪞',
  },
  {
    id: 'space-extreme-2',
    category: 'Voice & Tone',
    title: 'The Defining Moment',
    prompt: 'This is the scene that will be remembered. The moment that defines [Character Name] forever—heroic, tragic, or transcendent. Frame it with the weight it deserves. Make it unforgettable.',
    icon: '⭐',
  },
  {
    id: 'space-extreme-3',
    category: 'Narrative',
    title: 'Story Becomes Legend',
    prompt: 'Show how [Character Name]\'s current actions will be told in the future—embellished, distorted, deified. The legend forming in real-time around them. Truth and myth braiding together.',
    icon: '📜',
  },
];

export const promptCategories = [
  'Voice & Tone',
  'Combat',
  'Social',
  'Investigation',
  'Emotional',
  'World',
  'Narrative',
  'Meta Requests',
];
