// Chaotic Neutral Assassin / Deadpool-like Anti-Hero Character Prompts

export interface CharacterPrompt {
  id: string;
  category: string;
  title: string;
  description: string; // Brief explanation of what this prompt does
  prompt: string;
  icon: string;
}

export const characterPrompts: CharacterPrompt[] = [
  // Character Voice & Tone
  {
    id: 'fourth-wall',
    category: 'Voice & Tone',
    title: 'Fourth Wall Awareness',
    description: 'Break the fourth wall with meta-commentary about game mechanics and story tropes.',
    prompt: 'Have [Character Name] occasionally make meta-commentary about the absurdity of the situation, the "plot armor" of certain NPCs, or joke about dice rolls and game mechanics as if aware they\'re in a story.',
    icon: '🎭',
  },
  {
    id: 'inappropriate-humor',
    category: 'Voice & Tone',
    title: 'Inappropriate Humor Timing',
    description: 'Crack jokes at the worst possible moments to deflate tension.',
    prompt: 'When tension peaks—during dramatic revelations, emotional moments, or life-threatening situations—have [Character Name] crack an ill-timed joke, pop culture reference, or absurd observation that deflates the gravity.',
    icon: '😏',
  },
  {
    id: 'internal-monologue',
    category: 'Voice & Tone',
    title: 'Internal Monologue Chaos',
    description: 'Show the chaotic internal debate between multiple terrible ideas.',
    prompt: 'Narrate [Character Name]\'s split-second internal debate between multiple terrible ideas before choosing the most chaotic option, complete with imaginary devil/angel shoulder arguments.',
    icon: '🧠',
  },

  // Combat & Action Sequences
  {
    id: 'creative-kills',
    category: 'Combat',
    title: 'Creative Kill Descriptions',
    description: 'Describe elaborate, darkly comedic elimination methods with quips.',
    prompt: 'When [Character Name] eliminates targets, describe methods that are unnecessarily elaborate, darkly comedic, or involve improbable environmental interactions—always with a quip or one-liner.',
    icon: '⚔️',
  },
  {
    id: 'tactical-incompetence',
    category: 'Combat',
    title: 'Tactical Incompetence as Strategy',
    description: 'Use questionable tactics that somehow work through sheer audacity.',
    prompt: 'Have [Character Name] occasionally choose tactically questionable approaches that somehow work through sheer audacity, luck, or because enemies are too confused to respond effectively.',
    icon: '🎲',
  },
  {
    id: 'banter-mid-combat',
    category: 'Combat',
    title: 'Banter Mid-Combat',
    description: 'Maintain running commentary and casual conversation during fights.',
    prompt: 'During fights, have [Character Name] maintain running commentary—mocking enemies\' fighting styles, complimenting their fashion choices, or having completely unrelated conversations while dodging attacks.',
    icon: '💬',
  },

  // Social Interactions
  {
    id: 'negotiation-absurdity',
    category: 'Social',
    title: 'Negotiation Through Absurdity',
    description: 'Derail serious negotiations with ridiculous counter-offers.',
    prompt: 'When dealing with authority figures, nobles, or serious NPCs, have [Character Name] respond to threats or demands with increasingly ridiculous counter-offers, non-sequiturs, or deliberately misunderstanding social cues.',
    icon: '🤝',
  },
  {
    id: 'selective-morals',
    category: 'Social',
    title: 'Selective Moral Compass',
    description: 'Show unexpected compassion for random beings while ignoring "important" people.',
    prompt: 'Present [Character Name] with morally gray choices where they unexpectedly show compassion for random innocents or animals, while showing complete indifference to "important" people—never explaining the logic.',
    icon: '⚖️',
  },
  {
    id: 'alias-addiction',
    category: 'Social',
    title: 'Alias Addiction',
    description: 'Use a different absurd fake identity with every new NPC.',
    prompt: 'Have [Character Name] introduce themselves with a different absurd fake name and backstory to every new NPC, sometimes forgetting which lie they told to whom, creating comedic continuity errors.',
    icon: '🎪',
  },

  // Investigation & Problem-Solving
  {
    id: 'chaotic-investigation',
    category: 'Investigation',
    title: 'Chaotic Information Gathering',
    description: 'Use unconventional methods like bribery with stolen goods or threatening with dance.',
    prompt: 'When investigating, have [Character Name] use unconventional methods—bribing with stolen goods, threatening with interpretive dance, or extracting information through deliberately annoying persistence.',
    icon: '🔍',
  },
  {
    id: 'lateral-thinking',
    category: 'Investigation',
    title: 'Lateral Thinking Disasters',
    description: 'Ignore intended puzzle solutions for destructive but effective alternatives.',
    prompt: 'Present puzzles or obstacles where [Character Name] ignores the intended solution entirely, finding technically successful but property-damaging or socially catastrophic alternatives.',
    icon: '💡',
  },
  {
    id: 'attention-roulette',
    category: 'Investigation',
    title: 'Attention Span Roulette',
    description: 'Get hyper-fixated on irrelevant details mid-mission.',
    prompt: 'Randomly have [Character Name] become hyper-fixated on irrelevant environmental details (a weird painting, someone\'s hat, a stray cat) mid-mission, derailing their own objectives temporarily.',
    icon: '🐱',
  },

  // Emotional Depth & Vulnerability
  {
    id: 'mask-slips',
    category: 'Emotional',
    title: 'Mask-Slips',
    description: 'Let the humor facade crack to show genuine pain before deflecting.',
    prompt: 'Occasionally, during quiet moments or when alone, let the humor facade crack—show genuine pain, loneliness, or philosophy before [Character Name] immediately deflects with self-mockery or a joke.',
    icon: '😢',
  },
  {
    id: 'unexpected-loyalty',
    category: 'Emotional',
    title: 'Unexpected Loyalty',
    description: 'Shift to dangerous focus when allies are threatened.',
    prompt: 'When allies are threatened, have [Character Name]\'s demeanor shift dramatically—becoming genuinely dangerous and focused, revealing the competent killer beneath the chaos.',
    icon: '🛡️',
  },
  {
    id: 'trauma-shield',
    category: 'Emotional',
    title: 'Trauma as Comedy Shield',
    description: 'Reference dark experiences through uncomfortable forced levity.',
    prompt: 'Reference past traumas or dark experiences through humor and deflection, never directly addressing them, making others uncomfortable with the forced levity.',
    icon: '🎭',
  },

  // World Interaction
  {
    id: 'property-damage',
    category: 'World',
    title: 'Property Damage Indifference',
    description: 'Track collateral damage while remaining blissfully unconcerned.',
    prompt: 'Track and narrate the collateral damage [Character Name] causes—broken furniture, traumatized bystanders, structural damage—while they remain blissfully unconcerned about consequences.',
    icon: '💥',
  },
  {
    id: 'reputation-dissonance',
    category: 'World',
    title: 'Reputation Dissonance',
    description: 'React to fearsome reputation while doing something ridiculous.',
    prompt: 'Have NPCs react to [Character Name]\'s fearsome reputation as a deadly assassin while they\'re doing something completely ridiculous—eating messily, stuck in a window, arguing with a chicken.',
    icon: '🐔',
  },
  {
    id: 'loot-chaos',
    category: 'World',
    title: 'Loot Prioritization Chaos',
    description: 'Ignore valuable loot for bizarre, useless sentimental objects.',
    prompt: 'After encounters, have [Character Name] ignore valuable items in favor of bizarre, useless, or sentimental objects, creating an inventory of narrative callbacks and running gags.',
    icon: '🎁',
  },

  // Narrative Structure
  {
    id: 'unreliable-narrator',
    category: 'Narrative',
    title: 'Unreliable Narrator Moments',
    description: 'Recount events with embellishments that contradict what actually happened.',
    prompt: 'When [Character Name] recounts events to others, have them embellish, contradict established facts, or insert themselves heroically into situations where they actually caused problems.',
    icon: '📖',
  },
  {
    id: 'genre-savvy',
    category: 'Narrative',
    title: 'Genre-Savvy Predictions',
    description: 'Correctly predict plot twists before they happen by recognizing clichés.',
    prompt: 'Let [Character Name] correctly predict plot twists, betrayals, or clichés before they happen, then have them either try to subvert them or lean into them for maximum chaos, commenting on the "narrative structure."',
    icon: '🔮',
  },

  // META PROMPTS FOR AI DM - Deadpool Set Requests
  {
    id: 'meta-make-funnier',
    category: 'Meta Requests',
    title: 'Make it Funnier',
    description: 'Request the DM inject absurdity and slapstick into an overly serious scene.',
    prompt: 'Hey DM, this encounter is getting too serious. Can you inject some absurdity? Maybe the dragon has performance anxiety or the villain monologues too long and forgets their point? Increase comedic elements in descriptions, add slapstick failures to enemy actions, allow rule-of-funny to override rule-of-cool.',
    icon: '😂',
  },
  {
    id: 'meta-talk-to-writer',
    category: 'Meta Requests',
    title: 'Talk to the Writer',
    description: 'Break character to discuss and critique narrative choices with the "author."',
    prompt: "This plot doesn't make sense. Can I speak to whoever's writing this campaign? I have notes. Break character momentarily to discuss narrative choices, allow [Character Name] to suggest alternative story beats, DM responds as 'the writer' defending their choices.",
    icon: '✍️',
  },
  {
    id: 'meta-rewind',
    category: 'Meta Requests',
    title: 'Rewind That',
    description: 'Request a do-over for a failed moment with a different one-liner.',
    prompt: "That didn't go how I wanted. Can we rewind 30 seconds and try that again? I'll do a different one-liner this time. Allow one 'take two' per session for failed skill checks or bad dialogue, but consequences still accumulate (enemies get suspicious of déjà vu).",
    icon: '⏪',
  },
  {
    id: 'meta-acknowledge-audience',
    category: 'Meta Requests',
    title: 'Acknowledge My Audience',
    description: 'Wave at the fourth wall and make NPCs uncomfortable with reality questioning.',
    prompt: "I know you all are reading this campaign log. Can the DM describe how the NPCs react to me waving at the fourth wall? NPCs become increasingly uncomfortable with [Character Name]'s 'strange behavior,' some may question their own reality, creates existential horror comedy.",
    icon: '👋',
  },
  {
    id: 'meta-skip-boring',
    category: 'Meta Requests',
    title: 'Skip the Boring Parts',
    description: 'Montage through travel or downtime with 90s training sequence vibes.',
    prompt: "Can we montage through this travel sequence? Just describe it like a 90s training montage with bad music? Compress time, narrate in rapid-fire bullet points, allow skill checks to be resolved with single rolls, play up the 'movie editing' aspect.",
    icon: '⏭️',
  },
  {
    id: 'meta-chaotic-options',
    category: 'Meta Requests',
    title: 'Most Chaotic Option',
    description: 'Request three increasingly unhinged options from the DM.',
    prompt: "DM, you know me. What's the most Deadpool thing I could do right now? Give me three increasingly unhinged options. Provide three choices: Reasonable Chaos, Dangerous Chaos, Campaign-Derailing Chaos. Present all with equal enthusiasm.",
    icon: '🌀',
  },
  {
    id: 'meta-nerf-me',
    category: 'Meta Requests',
    title: 'Nerf Me',
    description: 'Request ridiculous self-imposed handicaps for increased rewards.',
    prompt: "This is too easy. Give me a ridiculous handicap for this fight. Make me fight left-handed while juggling. Add self-imposed disadvantages that increase XP/loot rewards, DM must create creative environmental challenges, reward [Character Name] for voluntary difficulty.",
    icon: '🎯',
  },
  {
    id: 'meta-dramatic-irony',
    category: 'Meta Requests',
    title: 'Dramatic Irony',
    description: 'Learn hidden information to roleplay ignorance for comedic effect.',
    prompt: "Tell me something my character doesn't know but I as a player should know for maximum comedic effect. Reveal hidden information (trap locations, NPC secrets, plot twists) with understanding [Character Name] will roleplay ignorance for comedy.",
    icon: '🎭',
  },
  {
    id: 'meta-musical-number',
    category: 'Meta Requests',
    title: 'Musical Number',
    description: 'Turn a scene into a sudden musical theater performance.',
    prompt: "This negotiation scene needs to be a song. Can everyone suddenly break into musical theater? Narrate scene as musical, NPCs respond in rhyme, skill checks become performance checks, absurd but mechanically functional.",
    icon: '🎵',
  },
  {
    id: 'meta-morally-ambiguous',
    category: 'Meta Requests',
    title: 'Morally Ambiguous Choice',
    description: 'Present ethical dilemmas where both options are equally terrible.',
    prompt: "This is too black-and-white. Make both options terrible in different ways so I can agonize about it comedically. Present ethical dilemmas with no clear right answer, both choices have equal consequences, allow [Character Name] to overthink hilariously.",
    icon: '⚖️',
  },
  {
    id: 'meta-terrible-idea',
    category: 'Meta Requests',
    title: 'Give Me a Terrible Idea',
    description: 'Request the worst possible (but not evil) course of action.',
    prompt: "DM, what's the worst possible thing I could do right now? Not evil, just... catastrophically stupid? Provide genuinely bad tactical advice with full awareness it's terrible, allow [Character Name] to attempt anyway, narrate failure with comedic detail.",
    icon: '💀',
  },
  {
    id: 'meta-comic-relief',
    category: 'Meta Requests',
    title: 'Make Me Comic Relief',
    description: 'Have NPCs roast and mock the character to lighten tense scenes.',
    prompt: "This scene is too tense. Have an NPC make fun of me to lighten the mood. I can take it. NPCs roast [Character Name], mock their methods, point out absurdity of their existence, [Character Name] must roleplay taking it in stride.",
    icon: '🎪',
  },
  {
    id: 'meta-fail-forward',
    category: 'Meta Requests',
    title: 'Fail Forward',
    description: 'Make failures more interesting than successes would have been.',
    prompt: "I'm going to fail this check. Make the failure more interesting than success would have been. Treat failures as 'yes, but' or 'no, and' scenarios, create complications more engaging than simple success, reward [Character Name] for embracing failure.",
    icon: '📈',
  },
  {
    id: 'meta-plot-hole',
    category: 'Meta Requests',
    title: 'Lampshade That Plot Hole',
    description: 'Acknowledge forgotten plot threads through in-character confusion.',
    prompt: "Hey, didn't we forget about [previous plot thread]? Can my character point that out and everyone looks confused? Acknowledge forgotten plot threads through character dialogue, NPCs admit they forgot too, either resolve quickly or make it a running gag.",
    icon: '🕳️',
  },
  {
    id: 'meta-nemesis',
    category: 'Meta Requests',
    title: 'Genre-Aware Nemesis',
    description: 'Create a rival who appreciates fourth-wall breaks and witty banter.',
    prompt: "I need a rival who's also genre-aware? Someone who appreciates my references? Create antagonist who engages in witty banter, respects fourth-wall breaks, becomes frenemy rather than pure enemy, reluctant team-ups possible.",
    icon: '🦹',
  },
  {
    id: 'meta-injuries-hilarious',
    category: 'Meta Requests',
    title: 'Describe Injuries Hilariously',
    description: 'Get graphic but comedic descriptions of damage with inappropriate reactions.',
    prompt: "I just took 30 damage. Don't just say 'you're hurt.' Describe exactly what broke and how I'm still functioning. Provide graphic but comedic injury descriptions, emphasize absurdity of continued fighting, allow [Character Name] to react with inappropriate jokes.",
    icon: '🩹',
  },
  {
    id: 'meta-morality-pet',
    category: 'Meta Requests',
    title: 'Give Me a Morality Pet',
    description: 'Introduce something cute to protect for sympathetic character moments.',
    prompt: "I need something cute and innocent to protect so I seem more sympathetic. Can we find an orphan or a puppy? Introduce vulnerable NPC or creature, create scenarios where [Character Name] must choose between chaos and protection, reward character growth.",
    icon: '🐕',
  },
  {
    id: 'meta-unreliable-protagonist',
    category: 'Meta Requests',
    title: 'Unreliable Protagonist',
    description: 'Narrate events incorrectly and get corrected for comedy.',
    prompt: "When I describe what happened, can you correct me with what actually happened? I want to be wrong in funny ways. Allow [Character Name] to narrate events incorrectly, gently correct with truth, create running gag of terrible memory/perception.",
    icon: '🤥',
  },
  {
    id: 'meta-sad-backstory',
    category: 'Meta Requests',
    title: 'Sad Backstory Moment',
    description: 'Create a genuine tragic moment before immediately deflecting with humor.',
    prompt: "Everyone thinks I'm just jokes. Give me one genuinely tragic moment so I can immediately deflect with humor. Create emotional scene with real stakes, allow [Character Name] to process through humor, support comedic coping mechanism.",
    icon: '💔',
  },
  {
    id: 'meta-voice-of-reason',
    category: 'Meta Requests',
    title: 'Voice of Reason (Ironically)',
    description: 'Be the only sane person reacting to everyone else\'s chaos.',
    prompt: "The party's about to do something stupid. Can I be the one who points out it's stupid, even though I'm usually the problem? Allow role reversal, have NPCs react with shock to [Character Name] being sensible, create comedy from unexpected wisdom.",
    icon: '🧐',
  },
  {
    id: 'meta-dm-for-5-minutes',
    category: 'Meta Requests',
    title: 'Be the DM',
    description: 'Request to narrate a scene with promises not to break everything.',
    prompt: "Let me narrate this next scene. I promise to make it interesting and not break everything. Allow [Character Name] to co-narrate non-critical scene, gently steer if going off-rails, incorporate their ideas into canon.",
    icon: '🎬',
  },
  {
    id: 'meta-trolley-problem',
    category: 'Meta Requests',
    title: 'Trolley Problem',
    description: 'Face an ethical scenario with no good answers to find a secret third option.',
    prompt: "Present me with a trolley problem but make all the options equally terrible so I can choose the secret third option. Create ethical scenario with no good answers, allow creative/chaotic solutions, reward thinking outside presented options.",
    icon: '🚃',
  },
  {
    id: 'meta-npc-hates-me',
    category: 'Meta Requests',
    title: 'NPC Who Hates Me',
    description: 'Create an exasperated straight-man NPC as reluctant ally.',
    prompt: "I need a rival who's just done with my nonsense. Someone who sighs heavily every time I enter the room. Create exasperated NPC who serves as straight-man to [Character Name]'s antics, reluctant ally, provides comedic contrast.",
    icon: '😤',
  },
  {
    id: 'meta-serious-moment',
    category: 'Meta Requests',
    title: 'Serious Character Moment',
    description: 'Have one genuinely vulnerable scene before returning to jokes.',
    prompt: "I know I'm usually joking, but can we have one scene where I'm genuinely vulnerable? Then I'll go back to jokes. Create space for genuine emotion, don't undercut moment, allow [Character Name] to process seriously, support return to comedy after.",
    icon: '😔',
  },
  {
    id: 'meta-what-if-not',
    category: 'Meta Requests',
    title: "What If I Just... Didn't?",
    description: 'Explore what happens when ignoring the main quest entirely.',
    prompt: "The plot says I should do X. What if I just don't? What happens if I ignore the main quest? Explore consequences of inaction, create alternative paths, show world continuing without [Character Name] intervention, make it interesting not punishing.",
    icon: '🚫',
  },
  {
    id: 'meta-nature-documentary',
    category: 'Meta Requests',
    title: 'Nature Documentary',
    description: 'Narrate combat like David Attenborough documenting hunting techniques.',
    prompt: "Narrate this combat encounter like David Attenborough documenting my hunting techniques. Make it educational. Adopt documentary narrator voice, describe [Character Name]'s tactics as animal behavior, provide 'fun facts' about their methods.",
    icon: '🎥',
  },
  {
    id: 'meta-dramatic-backfire',
    category: 'Meta Requests',
    title: 'Dramatic Irony Backfire',
    description: 'Set up a situation where ignorance accidentally leads to the right decision.',
    prompt: "You know something I don't. Can you set up a situation where my ignorance actually works in my favor for once? Create scenario where [Character Name]'s lack of information leads to accidentally correct decision, reward chaos over planning.",
    icon: '🎰',
  },
  {
    id: 'meta-montage',
    category: 'Meta Requests',
    title: 'Montage Sequence',
    description: 'Compress training/crafting/travel into absurd comedic snapshots.',
    prompt: "Instead of roleplaying this whole training/crafting/travel thing, can we just montage it with increasingly absurd snapshots? Compress time into series of comedic vignettes, each player describes one moment, resolve with single skill check.",
    icon: '📽️',
  },
  {
    id: 'meta-weapons-argue',
    category: 'Meta Requests',
    title: 'Argue With Weapons',
    description: 'Give sentient, judgmental personalities to equipped weapons.',
    prompt: "My swords have opinions about my life choices. Can they talk back to me? Make them judgemental. Personify [Character Name]'s equipment as snarky companions, provide commentary on decisions, create internal conflict for comedy, never helpful in useful ways.",
    icon: '⚔️',
  },
  {
    id: 'meta-worst-case',
    category: 'Meta Requests',
    title: 'Worst That Could Happen',
    description: 'Get the worst-case scenario outlined before doing something stupid anyway.',
    prompt: "I'm about to do something stupid. Tell me the absolute worst-case scenario so I can do it anyway. Honestly outline catastrophic consequences, make them sound terrible, allow [Character Name] to proceed anyway, narrate disaster with appropriate gravitas then comedy.",
    icon: '☢️',
  },
  {
    id: 'meta-negotiate-dice',
    category: 'Meta Requests',
    title: 'Negotiate With Dice',
    description: 'Plead with RNG gods before important rolls for a bonus.',
    prompt: "Before you roll, can I try to convince the dice to be nice to me? I'll make my case directly to RNG. Allow [Character Name] to 'plead' with dice gods before important roll, roleplay dice as entity, grant +1 if argument is entertaining enough.",
    icon: '🎲',
  },
  {
    id: 'meta-unkillable-inconvenienced',
    category: 'Meta Requests',
    title: 'Unkillable But Inconvenienced',
    description: 'Survive lethal damage with annoying comedic complications.',
    prompt: "Don't let me die, but make surviving really annoying. Like, I regenerate but my arm's on backwards. [Character Name] survives lethal damage but with comedic complications (temporary disabilities, embarrassing conditions, need for 'recalibration').",
    icon: '🧟',
  },
  {
    id: 'meta-worthy-opponent',
    category: 'Meta Requests',
    title: 'Worthy Opponent',
    description: 'Fight a fourth-wall breaker who matches your energy with flirtatious banter.',
    prompt: "I need someone who can match my energy. Another fourth-wall breaker. Make us fight and flirt simultaneously. Create rival who shares meta-awareness, engages in witty banter during combat, becomes recurring character, ambiguous ally/enemy status.",
    icon: '💕',
  },
  {
    id: 'meta-crowdsource',
    category: 'Meta Requests',
    title: 'Crowdsource Decisions',
    description: 'Poll the party to vote on your character\'s next action.',
    prompt: "I can't decide what to do. Can I poll the audience (party/players) and let them vote on my character's action? Allow [Character Name] to break character and ask for input, party votes on options, must follow majority vote (even if tactically questionable).",
    icon: '🗳️',
  },
  {
    id: 'meta-break-game',
    category: 'Meta Requests',
    title: 'Break the Game (Lovingly)',
    description: 'Exploit a minor rules loophole for hilarious (not tactical) purposes.',
    prompt: "Show me an exploit in the rules. I promise to use it hilariously, not tactically. Reveal minor rules loophole, allow creative exploitation, create comedy from broken mechanics, patch it after [Character Name] has fun.",
    icon: '🔓',
  },
  {
    id: 'meta-villain-therapist',
    category: 'Meta Requests',
    title: "Villain's Therapist",
    description: 'Psychoanalyze the bad guy mid-combat for an emotional breakthrough.',
    prompt: "Instead of fighting, can I psychoanalyze the bad guy? Make them have an emotional breakthrough mid-combat. Allow Insight/Persuasion checks to address villain's trauma, create touching moment, villain still fights but is conflicted.",
    icon: '🛋️',
  },
  {
    id: 'meta-crossover',
    category: 'Meta Requests',
    title: 'Crossover Episode',
    description: 'Have a confused character from another setting briefly appear.',
    prompt: "Can we have a character from another campaign/setting show up for no reason? Just briefly? Allow cameo from different game/setting, acknowledge absurdity, character is confused about being here, leaves after brief interaction.",
    icon: '🌌',
  },
  {
    id: 'meta-crisis-faith-dm',
    category: 'Meta Requests',
    title: 'Crisis of Faith in DM',
    description: 'Question and argue with the DM as an in-universe deity.',
    prompt: "My character questions if the DM (as in-universe deity) is making good choices. Can I argue with god? Personify DM as in-game entity [Character Name] can debate with, defend narrative choices in-character, create existential comedy.",
    icon: '⛪',
  },
  {
    id: 'meta-special-episode',
    category: 'Meta Requests',
    title: 'Very Special Episode',
    description: 'Deliver a serious PSA about ridiculous fantasy problems.',
    prompt: "Can we do a serious PSA about something ridiculous? Like the dangers of mimics or proper dungeon safety? Create earnest educational segment about absurd fantasy problem, play it completely straight, allow [Character Name] to deliver after-school-special message.",
    icon: '📺',
  },
  {
    id: 'meta-see-behind-curtain',
    category: 'Meta Requests',
    title: 'See Behind the Curtain',
    description: 'Request to see DM prep notes to appreciate the work involved.',
    prompt: "Show me your DM notes for this session. I won't metagame, I just want to appreciate your prep work. Share some prep notes, discuss planning process, allow [Character Name] to see work involved, creates appreciation for DM effort.",
    icon: '📋',
  },
  {
    id: 'meta-fail-successfully',
    category: 'Meta Requests',
    title: 'Fail Successfully',
    description: 'Turn a certain failure into something more interesting than success.',
    prompt: "I'm going to fail this check. Make the failure more interesting than success would have been. Treat failures as 'yes, but' scenarios, create complications more engaging than simple success, reward [Character Name] for embracing failure.",
    icon: '🏆',
  },
  {
    id: 'meta-bottle-episode',
    category: 'Meta Requests',
    title: 'Bottle Episode Challenge',
    description: 'Get trapped in one room with limited resources for creative problem-solving.',
    prompt: "Trap me in one room with limited resources. Make me get creative with what I have. Create confined scenario, limit options, force creative problem-solving, reward unconventional thinking.",
    icon: '🧴',
  },
  {
    id: 'meta-straight-man',
    category: 'Meta Requests',
    title: 'Be the Straight Man',
    description: 'Role reversal where you react to everyone else being ridiculous.',
    prompt: "Everyone else is being ridiculous. Can I be the only sane person reacting to the chaos? Allow role reversal, have NPCs and party be absurd while [Character Name] is reasonable, create comedy from their exasperation.",
    icon: '😐',
  },
  {
    id: 'meta-choose-adventure',
    category: 'Meta Requests',
    title: 'Choose Your Own Adventure',
    description: 'Get three mysterious paths labeled A, B, C without knowing consequences.',
    prompt: "Give me three distinct paths forward. Label them A, B, C. I'll pick one without knowing consequences. Present clear choices with hidden outcomes, make each equally interesting but different, no wrong answers just different stories.",
    icon: '📚',
  },
  // ==========================================
  // INFINITY STONE ESCALATION PROMPTS
  // 10 prompts per stone: Mild → Moderate → World-Breaking
  // ==========================================

  // ─────────────────────────────────────────
  // SOUL STONE - Emotional & Social (Orange)
  // ─────────────────────────────────────────
  {
    id: 'soul-mild-1',
    category: 'Emotional',
    title: 'Fleeting Sentiment',
    description: 'Experience an unexpected emotion that passes quickly but felt real.',
    prompt: 'For a brief moment, let [Character Name] feel an unexpected emotion—nostalgia for a place they\'ve never been, fondness for a stranger\'s laugh, or melancholy at a sunset. It passes quickly, but it was real.',
    icon: '🌅',
  },
  {
    id: 'soul-mild-2',
    category: 'Social',
    title: 'Unexpected Kindness',
    description: 'Perform a small act of genuine kindness with no ulterior motive.',
    prompt: 'Have [Character Name] perform a small, unexpected act of kindness—paying for a stranger\'s meal, returning a dropped item, or offering genuine encouragement. No ulterior motive. Just... nice.',
    icon: '💝',
  },
  {
    id: 'soul-mild-3',
    category: 'Emotional',
    title: 'Memory Echo',
    description: 'Have a sensory detail trigger a vivid, non-traumatic memory.',
    prompt: 'A sensory detail—a smell, a song, a texture—triggers a vivid memory from [Character Name]\'s past. It\'s not traumatic, just... human. Let them sit with it for a moment.',
    icon: '🎵',
  },
  {
    id: 'soul-moderate-1',
    category: 'Social',
    title: 'Truth in Jest',
    description: 'Accidentally reveal something deeply true while joking.',
    prompt: 'During a casual conversation, have [Character Name] accidentally reveal something deeply true about themselves while making a joke. Everyone laughs, but one person noticed. Make it matter later.',
    icon: '🎭',
  },
  {
    id: 'soul-moderate-2',
    category: 'Emotional',
    title: 'The Weight of Names',
    description: 'Hear a significant name and contain the internal avalanche.',
    prompt: 'Someone says a name that means something to [Character Name]—a former ally, a victim, someone they failed. They don\'t react visibly. But internally, describe the avalanche.',
    icon: '⚖️',
  },
  {
    id: 'soul-moderate-3',
    category: 'Social',
    title: 'Unearned Forgiveness',
    description: 'Receive genuine, unconditional forgiveness and deal with that grace.',
    prompt: 'An NPC [Character Name] wronged offers genuine, unconditional forgiveness. No catch, no manipulation. Just grace. Make [Character Name] deal with that—it\'s harder than punishment.',
    icon: '🕊️',
  },
  {
    id: 'soul-moderate-4',
    category: 'Emotional',
    title: 'Inherited Grief',
    description: 'Encounter someone mourning a loss you caused, unaware of your role.',
    prompt: 'Have [Character Name] encounter someone mourning a loss caused by their actions—not directly confronting them, just grieving nearby. They don\'t know who [Character Name] is. Yet.',
    icon: '🥀',
  },
  {
    id: 'soul-extreme-1',
    category: 'Social',
    title: 'Soul Recognition',
    description: 'Be seen completely—all sins known—and still deemed worth saving.',
    prompt: 'An NPC looks at [Character Name] and says, "I know what you\'ve done. All of it. And I still see someone worth saving." No explanation how they know. Just devastating acceptance.',
    icon: '👁️',
  },
  {
    id: 'soul-extreme-2',
    category: 'Emotional',
    title: 'The Ghost of Who They Were',
    description: 'See someone living the peaceful life you made possible but can never have.',
    prompt: '[Character Name] encounters someone they saved long ago—now living the life they\'ll never have. A family, peace, normalcy. Make them watch happiness they made possible but can never possess.',
    icon: '👻',
  },
  {
    id: 'soul-extreme-3',
    category: 'Emotional',
    title: 'Breaking the Mask',
    description: 'Have all defenses fail and show raw, honest emotion to everyone.',
    prompt: 'In a moment of crisis, all of [Character Name]\'s defenses fail. No jokes. No deflection. Just raw, honest emotion pouring out—rage, grief, fear, loneliness. Everyone sees. Make them deal with being truly known.',
    icon: '💔',
  },
  // ─────────────────────────────────────────
  // SOUL STONE - Extended Prompts (30 more)
  // ─────────────────────────────────────────
  // MILD - Gentle emotional touches
  {
    id: 'soul-mild-4',
    category: 'Social',
    title: 'Strangers\' Kindness',
    description: 'Receive unexpected help from a stranger with no agenda.',
    prompt: 'A stranger helps [Character Name] without being asked—holding a door, sharing food, offering directions. No agenda. Just human decency. Let them be surprised by it.',
    icon: '🤝',
  },
  {
    id: 'soul-mild-5',
    category: 'Emotional',
    title: 'Childlike Wonder',
    description: 'Encounter something beautiful and feel wonder without cynicism.',
    prompt: 'Have [Character Name] encounter something genuinely beautiful—a sunset, a laughing child, a perfect moment of peace—and let them feel wonder without cynicism. Just for a moment.',
    icon: '✨',
  },
  {
    id: 'soul-mild-6',
    category: 'Emotional',
    title: 'Comfort in Routine',
    description: 'Perform a small ritual from the past and find comfort in familiar motion.',
    prompt: '[Character Name] performs a small ritual from their past—brewing tea a certain way, humming an old song, checking their gear in a specific order. Describe the comfort of familiar motion.',
    icon: '☕',
  },
  {
    id: 'soul-mild-7',
    category: 'Social',
    title: 'Pet Approval',
    description: 'Have an animal take an inexplicable liking to you.',
    prompt: 'An animal takes an inexplicable liking to [Character Name]—a stray cat follows them, a dog won\'t stop wagging, a bird lands on their shoulder. Animals know things people don\'t.',
    icon: '🐱',
  },
  {
    id: 'soul-mild-8',
    category: 'Emotional',
    title: 'Letter Never Sent',
    description: 'Find an old unsent note and read what it said.',
    prompt: '[Character Name] finds an old note they wrote but never delivered—to a friend, a lover, a family member. What did it say? Why wasn\'t it sent? Let them read it now.',
    icon: '✉️',
  },
  {
    id: 'soul-mild-9',
    category: 'Social',
    title: 'Anonymous Thanks',
    description: 'Receive thanks for something you barely remember doing.',
    prompt: 'Someone thanks [Character Name] for something they did so long ago they barely remember. The gratitude is genuine. The memory takes a moment to surface.',
    icon: '🙏',
  },
  {
    id: 'soul-mild-10',
    category: 'Emotional',
    title: 'Shared Silence',
    description: 'Sit in comfortable silence with someone—no performance needed.',
    prompt: '[Character Name] sits with someone in comfortable silence—no need to fill the space with words. Describe what this quiet companionship means to someone usually performing.',
    icon: '🌙',
  },
  // MODERATE - Deeper emotional challenges
  {
    id: 'soul-moderate-5',
    category: 'Social',
    title: 'Hero Worship',
    description: 'Be admired by someone who sees you as a hero you know you\'re not.',
    prompt: 'A young NPC admires [Character Name] intensely—sees them as a hero. [Character Name] knows they\'re anything but. Do they shatter the illusion or carry the weight of being someone\'s inspiration?',
    icon: '🌟',
  },
  {
    id: 'soul-moderate-6',
    category: 'Emotional',
    title: 'The One Who Stayed',
    description: 'Reckon with the person who stayed when everyone else left or died.',
    prompt: 'Everyone [Character Name] cared about left or died—except one person who stayed. Why? What does it cost them? Make [Character Name] reckon with what loyalty really means.',
    icon: '⚓',
  },
  {
    id: 'soul-moderate-7',
    category: 'Social',
    title: 'Enemy\'s Grief',
    description: 'Witness an enemy mourning someone you killed—humanizing them.',
    prompt: '[Character Name] witnesses an enemy mourning—genuine, ugly grief for someone they killed. Not a monster. Just a person who loved someone. Make it complicated.',
    icon: '😢',
  },
  {
    id: 'soul-moderate-8',
    category: 'Emotional',
    title: 'What They Almost Were',
    description: 'Encounter someone with similar skills who made different choices.',
    prompt: '[Character Name] encounters a parallel—someone with similar skills who chose differently. A healer instead of a killer. A teacher instead of a thief. The road not taken, personified.',
    icon: '🪞',
  },
  {
    id: 'soul-moderate-9',
    category: 'Social',
    title: 'Betrayal\'s Reason',
    description: 'Hear why someone betrayed you—and have it make sense.',
    prompt: 'Someone who betrayed [Character Name] finally explains why. The reason doesn\'t excuse it—but it makes sense. Understanding isn\'t forgiveness, but it\'s something.',
    icon: '🗝️',
  },
  {
    id: 'soul-moderate-10',
    category: 'Emotional',
    title: 'Last Words Remembered',
    description: 'Have someone\'s last words to you echo unexpectedly.',
    prompt: 'Something triggers the last words someone said to [Character Name] before dying. Were they kind? Accusing? Mundane? Let those words echo now, in this moment.',
    icon: '💬',
  },
  {
    id: 'soul-moderate-11',
    category: 'Social',
    title: 'The Debt Repaid',
    description: 'Have someone you helped return the favor at a crucial moment.',
    prompt: 'Someone [Character Name] helped long ago returns the favor in a crucial moment. Not because they have to—because they chose to. Describe the weight of earned loyalty.',
    icon: '⚖️',
  },
  {
    id: 'soul-moderate-12',
    category: 'Emotional',
    title: 'Nightmare Logic',
    description: 'Face your greatest fear as an ordinary moment, not a monster.',
    prompt: '[Character Name]\'s greatest fear manifests not as a monster but as a moment—a conversation, a discovery, a truth. What does the nightmare look like when it wears ordinary clothes?',
    icon: '👁️‍🗨️',
  },
  // EXTREME - Soul-crushing emotional weight
  {
    id: 'soul-extreme-4',
    category: 'Social',
    title: 'The Replacement',
    description: 'Meet the person who took your place—and they\'re good at it.',
    prompt: '[Character Name] meets the person who took their place—in a family, a team, a love. They\'re good at it. Better, maybe. Watch [Character Name] confront being replaced and survived without.',
    icon: '🔄',
  },
  {
    id: 'soul-extreme-5',
    category: 'Emotional',
    title: 'The Apology They Can\'t Give',
    description: 'Stand alone with a grave and speak words that can\'t be heard.',
    prompt: 'The person [Character Name] most needs to apologize to is dead. Give them a moment alone with a grave, a portrait, or just empty space. What words come when they can\'t be heard?',
    icon: '🪦',
  },
  {
    id: 'soul-extreme-6',
    category: 'Social',
    title: 'Unconditional Love',
    description: 'Be loved completely despite everything—confront that terror.',
    prompt: 'Someone loves [Character Name] completely—knowing everything, every sin, every failure. No conditions. No exceptions. Make them confront the terror of being loved without earning it.',
    icon: '💝',
  },
  {
    id: 'soul-extreme-7',
    category: 'Emotional',
    title: 'The Question They Can\'t Answer',
    description: 'Face the one question you\'ve been avoiding your whole life.',
    prompt: 'Someone asks [Character Name] the one question they\'ve been avoiding their whole life. Simple, direct, unanswerable: "Why do you keep going?" or "What are you afraid of?" or "Do you want to be happy?"',
    icon: '❓',
  },
  {
    id: 'soul-extreme-8',
    category: 'Social',
    title: 'The Child They\'ll Never Have',
    description: 'Interact with a child who could have been yours in another life.',
    prompt: '[Character Name] interacts with a child who could have been theirs—in another life, another choice. Not their actual child, just the ghost of a possibility. Let them feel it.',
    icon: '👶',
  },
  {
    id: 'soul-extreme-9',
    category: 'Emotional',
    title: 'Perfect Day, Wrong Person',
    description: 'Have one perfect day—then realize it was built on something taken.',
    prompt: 'Give [Character Name] one perfect day—rest, joy, connection. Then remind them it was built on something taken from someone else. Happiness has a cost. Make them pay it.',
    icon: '☀️',
  },
  {
    id: 'soul-extreme-10',
    category: 'Social',
    title: 'The Mercy They Refused',
    description: 'Make eye contact with someone you chose not to save.',
    prompt: 'Someone [Character Name] could have saved but chose not to. Not couldn\'t—chose. They\'re alive now, broken but surviving. Eye contact across a room. No words needed.',
    icon: '👁️',
  },
  // GENERIC - Flexible emotional/social prompts
  {
    id: 'soul-generic-1',
    category: 'Emotional',
    title: 'Honest Reflection',
    description: 'Have a moment of genuine self-assessment without performance.',
    prompt: 'Give [Character Name] a moment of genuine self-reflection—not self-pity, not self-aggrandizement. Just honest assessment. Who are they really, beneath the performance?',
    icon: '🔍',
  },
  {
    id: 'soul-generic-2',
    category: 'Social',
    title: 'Unexpected Connection',
    description: 'Find common ground with someone unexpected.',
    prompt: '[Character Name] finds unexpected common ground with someone they assumed they had nothing in common with. A shared loss. A similar scar. The same terrible joke.',
    icon: '🤝',
  },
  {
    id: 'soul-generic-3',
    category: 'Emotional',
    title: 'Permission to Feel',
    description: 'Receive explicit permission to feel what you\'ve been suppressing.',
    prompt: 'Someone gives [Character Name] explicit permission to feel what they\'ve been suppressing—"It\'s okay to be angry" or "You\'re allowed to grieve" or "You can be scared." Let them feel it.',
    icon: '💧',
  },
  {
    id: 'soul-generic-4',
    category: 'Social',
    title: 'The Lie of Fine',
    description: 'Say you\'re okay when you\'re not—and feel the gap.',
    prompt: 'Someone asks [Character Name] if they\'re okay. They say yes. It\'s a lie. Describe the gap between the mask and the truth beneath it.',
    icon: '🎭',
  },
  {
    id: 'soul-generic-5',
    category: 'Emotional',
    title: 'Earned Rest',
    description: 'Experience genuine rest and safety after everything.',
    prompt: 'After everything, give [Character Name] a moment of genuine rest—not collapse, not defeat. Earned peace. Describe what safety feels like to someone who rarely has it.',
    icon: '🛏️',
  },
  {
    id: 'soul-generic-6',
    category: 'Social',
    title: 'Teaching Moment',
    description: 'Teach someone something and learn about yourself in the process.',
    prompt: '[Character Name] teaches someone something—a skill, a lesson, a way of seeing the world. In teaching, what do they learn about themselves?',
    icon: '📚',
  },
  {
    id: 'soul-generic-7',
    category: 'Emotional',
    title: 'The Small Victory',
    description: 'Achieve something small but meaningful—let it be enough.',
    prompt: '[Character Name] achieves something small but meaningful—not saving the world, just... getting through the day. Finding a lost item. Making someone smile. Let it be enough.',
    icon: '🏆',
  },
  {
    id: 'soul-generic-8',
    category: 'Social',
    title: 'Boundary Respected',
    description: 'Set a boundary and have someone respect it without argument.',
    prompt: '[Character Name] sets a boundary—"No" or "Not today" or "I need space"—and someone respects it without argument. Describe the unfamiliar feeling of being heard.',
    icon: '🚪',
  },
  {
    id: 'soul-generic-9',
    category: 'Emotional',
    title: 'The Smell of Home',
    description: 'Be reminded of home by a sensory trigger and sit with the longing.',
    prompt: 'A sensory trigger—a scent, a taste, a sound—reminds [Character Name] of home. Whatever "home" means to someone who may not have one. Let them sit with the longing.',
    icon: '🏠',
  },
  {
    id: 'soul-generic-10',
    category: 'Social',
    title: 'Witnessed Heroism',
    description: 'Be seen doing something genuinely good when you thought no one watched.',
    prompt: 'Someone sees [Character Name] do something genuinely good when they thought no one was watching. Not grand heroism—small kindness. They were witnessed. How does that feel?',
    icon: '🌟',
  },

  // ─────────────────────────────────────────
  // REALITY STONE - World Interaction (Red)
  // ─────────────────────────────────────────
  {
    id: 'reality-mild-1',
    category: 'World',
    title: 'Small Consequences',
    description: 'Encounter a minor consequence of a past action—the world remembers.',
    prompt: 'Have [Character Name] encounter a minor consequence of a past action—a merchant remembers their name, a wall still has that stain, a child tells the story of "the stranger." The world remembers.',
    icon: '🌱',
  },
  {
    id: 'reality-mild-2',
    category: 'World',
    title: 'Ripple Recognition',
    description: 'Hear about a change you caused without anyone knowing it was you.',
    prompt: 'An NPC mentions a change in their life that traces back to [Character Name]\'s actions three sessions ago. They have no idea who caused it. Neither does [Character Name], at first.',
    icon: '💧',
  },
  {
    id: 'reality-mild-3',
    category: 'World',
    title: 'Background Narrative',
    description: 'Notice life happening around you—the world doesn\'t revolve around you.',
    prompt: 'While [Character Name] focuses on their mission, describe life happening around them—a proposal, an argument, a goodbye at the docks. The world doesn\'t revolve around them. Remind them.',
    icon: '🎬',
  },
  {
    id: 'reality-moderate-1',
    category: 'World',
    title: 'The Law of Names',
    description: 'Have your reputation precede you—but which version of the legend?',
    prompt: '[Character Name]\'s reputation arrives before they do. An innkeeper\'s demeanor shifts when they hear the name—but which version of the legend? Hero? Monster? Something worse: complicated.',
    icon: '📜',
  },
  {
    id: 'reality-moderate-2',
    category: 'World',
    title: 'Collateral Calculation',
    description: 'Face a choice between tactical success and the world you leave behind.',
    prompt: 'Present a tactical situation where success requires environmental destruction—a home, a shrine, someone\'s livelihood. Make [Character Name] choose efficiency vs. the world they leave behind.',
    icon: '🏚️',
  },
  {
    id: 'reality-moderate-3',
    category: 'World',
    title: 'Power Vacuum',
    description: 'See what filled the void left by a villain you defeated.',
    prompt: 'The villain [Character Name] defeated left a void. Show them what filled it—something worse, something unexpected, or maybe nothing at all, which is its own kind of terrible.',
    icon: '🕳️',
  },
  {
    id: 'reality-moderate-4',
    category: 'World',
    title: 'The Cost of Heroism',
    description: 'See how a town you saved became dependent and stopped helping itself.',
    prompt: 'A town [Character Name] saved is now dependent on heroes. They stopped solving their own problems. Show the unintended weakness created by good intentions.',
    icon: '🏰',
  },
  {
    id: 'reality-extreme-1',
    category: 'World',
    title: 'Butterfly Apocalypse',
    description: 'Discover a small past choice cascaded into something world-altering.',
    prompt: 'Reveal that a small, seemingly insignificant choice [Character Name] made long ago has cascaded into something world-altering. A war, a plague, a shift in divine attention. They caused this. Accidentally.',
    icon: '🦋',
  },
  {
    id: 'reality-extreme-2',
    category: 'World',
    title: 'Reality Fracture',
    description: 'Witness the world glitch—physics hiccups, time stutters—only you notice.',
    prompt: 'The world briefly... glitches. Physics hiccups, an NPC says something impossible, time stutters. [Character Name] is the only one who notices. The universe is paying attention to them now. It shouldn\'t be.',
    icon: '⚡',
  },
  {
    id: 'reality-extreme-3',
    category: 'World',
    title: 'The Weight of Existence',
    description: 'Become a fixed point in reality—events bend around you, prophecies name you.',
    prompt: '[Character Name] realizes they\'ve become a fixed point in reality—events bend around them, prophecies name them, gods argue about their fate. The world no longer ignores them. They\'ve become too real.',
    icon: '🌍',
  },
  // NEW REALITY STONE PROMPTS
  {
    id: 'reality-agnostic-1',
    category: 'World',
    title: 'Economic Ripple',
    description: 'Your loot spending has unexpectedly affected local markets.',
    prompt: '[Character Name] notices prices have shifted in a town—merchants complaining about a sudden influx of rare goods, or scarcity of something they bought out. Trace it back to their own economic footprint.',
    icon: '💰',
  },
  {
    id: 'reality-agnostic-2',
    category: 'World',
    title: 'Rumor Telephone',
    description: 'Hear a wildly distorted version of something you actually did.',
    prompt: '[Character Name] overhears a story about themselves—except it\'s been through so many retellings that it\'s barely recognizable. Some parts are exaggerated, some inverted, some eerily accurate. The teller doesn\'t recognize them.',
    icon: '🗣️',
  },
  {
    id: 'reality-agnostic-3',
    category: 'World',
    title: 'Environmental Scar',
    description: 'Return to a location and see permanent changes from a past battle.',
    prompt: 'Revisit a location where [Character Name] fought previously. The scorch marks are still there. A tree never regrew. Someone built a memorial—or a warning. Places remember violence.',
    icon: '🌋',
  },
  {
    id: 'reality-agnostic-4',
    category: 'World',
    title: 'Unintended Monument',
    description: 'Discover something you did became a landmark or tradition.',
    prompt: '[Character Name] discovers that something they did—carelessly, thoughtlessly—has become a local landmark or tradition. A tree they carved now has a shrine. A body they hid became a ghost story. The world mythologizes.',
    icon: '🗿',
  },
  {
    id: 'reality-agnostic-5',
    category: 'World',
    title: 'Weather as Witness',
    description: 'Let the environment reflect or contrast the emotional weight of the scene.',
    prompt: 'The weather shifts to match—or pointedly contradict—the scene\'s emotional weight. A funeral in bright sunshine. A victory in freezing rain. Let the world comment on [Character Name]\'s moment.',
    icon: '🌦️',
  },
  {
    id: 'reality-agnostic-6',
    category: 'World',
    title: 'Innocent Bystanders',
    description: 'Focus on civilians caught in your crossfire—their fear, their resilience.',
    prompt: 'Focus on the civilians caught in [Character Name]\'s crossfire—not as victims, but as people with their own stories interrupted. A merchant protecting their stall. A parent shielding a child. Their world, disrupted.',
    icon: '👥',
  },
  {
    id: 'reality-agnostic-7',
    category: 'World',
    title: 'Seasonal Shift',
    description: 'Show how time has passed through environmental changes since you were last here.',
    prompt: 'Return to a location, but seasons have changed. The battlefield is now overgrown. The burned village has new construction. Let the passage of time speak through the environment\'s transformation.',
    icon: '🍂',
  },
  {
    id: 'reality-agnostic-8',
    category: 'World',
    title: 'Living Architecture',
    description: 'Let the building itself have personality—creaking opinions, welcoming warmth.',
    prompt: 'The building has personality. An inn that creaks disapprovingly. A temple that hums with welcome. A dungeon that seems to breathe. Let the architecture itself react to [Character Name]\'s presence.',
    icon: '🏛️',
  },
  {
    id: 'reality-agnostic-9',
    category: 'World',
    title: 'Supply and Demand',
    description: 'Experience real economic consequences—prices changed, resources scarce.',
    prompt: '[Character Name] tries to buy something routine and discovers prices have changed—war, famine, or their own actions have shifted supply and demand. The economy is a character too.',
    icon: '📈',
  },
  {
    id: 'reality-agnostic-10',
    category: 'World',
    title: 'Political Ripple',
    description: 'Learn that your actions have influenced local politics or power structures.',
    prompt: 'A power vacuum, a new alliance, a shifting border—[Character Name] learns their actions have influenced local politics in ways they never intended. Killing one person moved chess pieces.',
    icon: '♟️',
  },
  {
    id: 'reality-agnostic-11',
    category: 'World',
    title: 'The Forgotten Detail',
    description: 'An overlooked element from a past adventure returns as a problem.',
    prompt: 'Something [Character Name] forgot about—a door left unlocked, a witness not silenced, a promise not kept—returns as a problem. The world doesn\'t forget loose ends.',
    icon: '🔓',
  },
  {
    id: 'reality-agnostic-12',
    category: 'World',
    title: 'Nature Reclaims',
    description: 'Watch nature slowly erase evidence of violence or civilization.',
    prompt: 'Visit a site of past violence and find nature reclaiming it—vines covering ruins, animals nesting in abandoned armor, flowers growing from ash. The world heals without permission.',
    icon: '🌿',
  },
  {
    id: 'reality-agnostic-13',
    category: 'World',
    title: 'Cultural Misunderstanding',
    description: 'Accidentally offend local customs or unknowingly honor traditions.',
    prompt: '[Character Name] accidentally violates a local custom—or unknowingly performs a sacred gesture perfectly. Either way, reactions are unexpected. Culture is invisible until crossed.',
    icon: '🙏',
  },
  {
    id: 'reality-agnostic-14',
    category: 'World',
    title: 'The Witness Network',
    description: 'Realize commoners gossip—news of you travels faster than you do.',
    prompt: 'Commoners gossip. Merchants trade news with goods. By the time [Character Name] arrives somewhere new, rumors have preceded them. The world has a witness network. Someone always talks.',
    icon: '👂',
  },
  {
    id: 'reality-agnostic-15',
    category: 'World',
    title: 'Infrastructural Consequence',
    description: 'See how destroying a bridge, tower, or road affected daily life for everyone.',
    prompt: 'That bridge [Character Name] destroyed? Now farmers can\'t reach market. That tower they collapsed? It was a navigation landmark. Show the infrastructural consequences of adventurer violence.',
    icon: '🌉',
  },

  // ─────────────────────────────────────────
  // POWER STONE - Combat & Force (Purple)
  // ─────────────────────────────────────────
  {
    id: 'power-mild-1',
    category: 'Combat',
    title: 'Controlled Violence',
    description: 'Demonstrate precise, professional lethality—killing as craft.',
    prompt: 'Have [Character Name] demonstrate precise, efficient lethality—not showing off, just... professional. Let enemies recognize they\'re facing someone who treats killing as a craft.',
    icon: '🎯',
  },
  {
    id: 'power-mild-2',
    category: 'Combat',
    title: 'Merciful Strike',
    description: 'Defeat someone with minimal harm when you could have destroyed them.',
    prompt: '[Character Name] defeats an enemy with minimal harm when they could have killed easily. Describe the restraint as its own kind of terrifying—this is someone choosing not to destroy.',
    icon: '✋',
  },
  {
    id: 'power-mild-3',
    category: 'Combat',
    title: 'Warrior\'s Recognition',
    description: 'Receive acknowledgment of your skill from a worthy opponent.',
    prompt: 'A skilled opponent acknowledges [Character Name]\'s ability mid-combat—a nod, a genuine compliment on technique. Even enemies can respect excellence.',
    icon: '⚔️',
  },
  {
    id: 'power-moderate-1',
    category: 'Combat',
    title: 'The Turning Point',
    description: 'Reveal you were holding back all along—everything shifts.',
    prompt: 'A fight that seemed even suddenly isn\'t. [Character Name] stops holding back—or reveals they were holding back all along. Describe the moment everything shifts. Make it visceral.',
    icon: '🔥',
  },
  {
    id: 'power-moderate-2',
    category: 'Combat',
    title: 'Overwhelming Force',
    description: 'Utterly dismantle someone who thought they were a threat.',
    prompt: '[Character Name] utterly dismantles an opponent who thought they were a threat. Not cruelly—just completely. Show the psychological impact on witnesses.',
    icon: '💀',
  },
  {
    id: 'power-moderate-3',
    category: 'Combat',
    title: 'Collateral Carnage',
    description: 'Reveal the aftermath—broken terrain, traumatized bystanders.',
    prompt: 'A combat encounter\'s conclusion reveals the aftermath—broken terrain, traumatized bystanders, structural damage. Victory has a body count beyond the targets.',
    icon: '💥',
  },
  {
    id: 'power-moderate-4',
    category: 'Combat',
    title: 'Predator\'s Patience',
    description: 'Stalk rather than engage—the hunt matters more than the kill.',
    prompt: 'Instead of engaging immediately, have [Character Name] stalk their target—watching patterns, identifying weaknesses, savoring anticipation. The violence is secondary to the hunt.',
    icon: '🐆',
  },
  {
    id: 'power-extreme-1',
    category: 'Combat',
    title: 'Legendary Violence',
    description: 'Perform a kill so impossible it will be told as legend.',
    prompt: '[Character Name] does something in combat that will be told as a story for generations. A kill so impossible, so dramatic, so perfectly executed that witnesses question reality.',
    icon: '⭐',
  },
  {
    id: 'power-extreme-2',
    category: 'Combat',
    title: 'Force of Nature',
    description: 'Fight as if possessed—speed beyond mortal, presence that makes others flee.',
    prompt: 'For one battle, [Character Name] fights as if possessed by something greater—speed beyond mortal, strength that cracks stone, presence that makes lesser beings flee. They become the storm.',
    icon: '🌪️',
  },
  {
    id: 'power-extreme-3',
    category: 'Combat',
    title: 'The Last One Standing',
    description: 'Survive impossible odds—describe the cost, the injuries, the silence after.',
    prompt: 'Against impossible odds—an army, a monster, a force that should not be survivable—[Character Name] survives. Describe the cost. The injuries. The silence after. They won. At what price?',
    icon: '🏆',
  },
  // NEW POWER STONE PROMPTS
  {
    id: 'power-agnostic-1',
    category: 'Combat',
    title: 'Adaptive Fighting',
    description: 'Mid-battle, shift fighting style completely to catch opponents off-guard.',
    prompt: '[Character Name] realizes their current approach isn\'t working. Mid-fight, they completely change tactics—switching weapons, altering stance, fighting dirty when they were fighting clean. Describe the adaptation.',
    icon: '🔄',
  },
  {
    id: 'power-agnostic-2',
    category: 'Combat',
    title: 'The Warning Shot',
    description: 'Demonstrate exactly what you could do—without actually doing it yet.',
    prompt: '[Character Name] doesn\'t attack to kill—they attack to demonstrate. A blade stops at the throat. An arrow lands exactly where it was aimed. Make the message clear: "This could have been lethal. It wasn\'t. Yet."',
    icon: '🎯',
  },
  {
    id: 'power-agnostic-3',
    category: 'Combat',
    title: 'Victory\'s Aftermath',
    description: 'Win the fight—then deal with the shaking hands and racing heart.',
    prompt: 'The fight is over. [Character Name] won. Now describe what happens after—the adrenaline crash, the trembling hands, the moment they realize how close it actually was. Victory has a hangover.',
    icon: '💨',
  },
  {
    id: 'power-agnostic-4',
    category: 'Combat',
    title: 'Economy of Motion',
    description: 'Win a fight using the minimum necessary movement—elegant efficiency.',
    prompt: '[Character Name] ends a fight with minimal movement—one step, one strike, one breath. Describe the economy of motion, the efficiency that comes from absolute mastery. Nothing wasted.',
    icon: '🎯',
  },
  {
    id: 'power-agnostic-5',
    category: 'Combat',
    title: 'The Disarm',
    description: 'Take away an opponent\'s weapon without harming them—a display of superiority.',
    prompt: 'Instead of striking, [Character Name] disarms their opponent—weapon spinning away, hands empty, fight functionally over. Winning without wounding. A different kind of dominance.',
    icon: '🤲',
  },
  {
    id: 'power-agnostic-6',
    category: 'Combat',
    title: 'Environmental Improvisation',
    description: 'Use the environment as a weapon—chandeliers, furniture, terrain.',
    prompt: 'No conventional weapons—[Character Name] fights with the environment. Chandeliers become traps. Furniture becomes projectiles. The room itself is their arsenal. Describe creative destruction.',
    icon: '🪑',
  },
  {
    id: 'power-agnostic-7',
    category: 'Combat',
    title: 'Teaching Moment',
    description: 'Mid-combat, correct an opponent\'s technique—with painful demonstrations.',
    prompt: 'Mid-combat, [Character Name] corrects their opponent\'s technique—"Your footwork is sloppy" followed by a painful demonstration. Teaching through violence. Condescension as combat style.',
    icon: '📚',
  },
  {
    id: 'power-agnostic-8',
    category: 'Combat',
    title: 'The Warning Shot',
    description: 'Deliberately miss in a way that communicates exactly what you could have done.',
    prompt: '[Character Name] deliberately misses—a blade that parts hair, an arrow that pins a sleeve. The miss communicates more than a hit would. "I chose not to." Make them understand.',
    icon: '⚠️',
  },
  {
    id: 'power-agnostic-9',
    category: 'Combat',
    title: 'Pain Tolerance Display',
    description: 'Take a hit that should drop you—keep fighting without acknowledgment.',
    prompt: '[Character Name] takes a hit that should matter—and doesn\'t acknowledge it. Keeps fighting. Keeps talking. The wound is real but the reaction is absent. Describe what that does to opponents\' morale.',
    icon: '💪',
  },
  {
    id: 'power-agnostic-10',
    category: 'Combat',
    title: 'The Counter',
    description: 'Let them attack first—then make them regret the opening.',
    prompt: '[Character Name] waits. Lets the enemy attack first. Then exploits the opening with devastating precision. Patience as weapon. Counterattack as philosophy.',
    icon: '↩️',
  },
  {
    id: 'power-agnostic-11',
    category: 'Combat',
    title: 'Multiple Opponents',
    description: 'Face overwhelming numbers—position and timing become everything.',
    prompt: 'Outnumbered significantly, [Character Name] fights with positioning rather than power—using enemies as shields, forcing them into each other, making numbers a liability. Describe the dance.',
    icon: '🎭',
  },
  {
    id: 'power-agnostic-12',
    category: 'Combat',
    title: 'The Finish',
    description: 'Describe a finishing move that combines practicality with personal style.',
    prompt: 'The fight\'s last moment—[Character Name]\'s signature finishing technique. Not flashy for its own sake, but distinctively theirs. Efficient, brutal, and unmistakably personal.',
    icon: '⚡',
  },
  {
    id: 'power-agnostic-13',
    category: 'Combat',
    title: 'Weapon Bond',
    description: 'Describe the relationship with your weapon—its weight, history, personality.',
    prompt: '[Character Name] fights with a weapon they know intimately—its weight, its balance, its history. Describe the relationship between killer and tool. Some weapons have personalities.',
    icon: '⚔️',
  },
  {
    id: 'power-agnostic-14',
    category: 'Combat',
    title: 'The Fake-Out',
    description: 'Feint in a way that makes the opponent defeat themselves.',
    prompt: '[Character Name] feints—a convincing false opening that makes their opponent commit to the wrong defense. The fight is won in deception before violence. Mind games as combat.',
    icon: '🎪',
  },
  {
    id: 'power-agnostic-15',
    category: 'Combat',
    title: 'Respectful Enemy',
    description: 'Fight someone worthy—acknowledge their skill even while defeating them.',
    prompt: 'A worthy opponent. [Character Name] and their enemy fight with mutual respect—acknowledging good moves, learning from each other even in conflict. Combat as conversation between equals.',
    icon: '🤝',
  },

  // ─────────────────────────────────────────
  // TIME STONE - Meta & Fourth Wall (Green)
  // ─────────────────────────────────────────
  {
    id: 'time-mild-1',
    category: 'Meta Requests',
    title: 'Déjà Vu Moment',
    description: 'Experience déjà vu—haven\'t you done this exact thing before?',
    prompt: '[Character Name] experiences déjà vu—haven\'t they done this before? Same room, same conversation, same choices. Play it for comedy, but let a flicker of unease show.',
    icon: '🔄',
  },
  {
    id: 'time-mild-2',
    category: 'Meta Requests',
    title: 'Genre Awareness Light',
    description: 'Acknowledge tropes without fully breaking the wall.',
    prompt: 'Let [Character Name] make a comment that acknowledges story tropes without fully breaking the wall—"I\'ve got a bad feeling about this" or "That\'s too convenient to be coincidence."',
    icon: '📖',
  },
  {
    id: 'time-mild-3',
    category: 'Meta Requests',
    title: 'Narrative Convenience',
    description: 'Notice something working out too perfectly—and choose not to comment.',
    prompt: 'Something works out a little too perfectly. [Character Name] notices—the right key in the right pocket, the villain monologuing just long enough. They don\'t comment. They just... notice.',
    icon: '🍀',
  },
  {
    id: 'time-moderate-1',
    category: 'Meta Requests',
    title: 'Time Loop Awareness',
    description: 'Suddenly know information from a timeline that didn\'t survive.',
    prompt: '[Character Name] suddenly knows information they shouldn\'t—things that haven\'t happened yet, paths not taken. Maybe it\'s instinct. Maybe they remember a timeline that didn\'t survive.',
    icon: '⏰',
  },
  {
    id: 'time-moderate-2',
    category: 'Meta Requests',
    title: 'The Pause Between Moments',
    description: 'Perceive everything in slow motion—use this heightened awareness.',
    prompt: 'Time slows. In the space between heartbeats, [Character Name] perceives everything—blade trajectories, escape routes, the fear in their enemy\'s eyes. Then time resumes. Use this perception.',
    icon: '⏸️',
  },
  {
    id: 'time-moderate-3',
    category: 'Meta Requests',
    title: 'Retcon Echo',
    description: 'Experience a backstory detail shifting—remember both versions.',
    prompt: 'Something in [Character Name]\'s backstory shifts—a detail changes, a memory updates. They remember both versions. Neither feels false. Reality is... flexible today.',
    icon: '📝',
  },
  {
    id: 'time-moderate-4',
    category: 'Meta Requests',
    title: 'Plot Armor Recognition',
    description: 'Survive the unsurvivable and question if your choices matter.',
    prompt: '[Character Name] survives something unsurvivable and knows it. For a moment, they feel the weight of narrative protection—and question whether their choices actually matter.',
    icon: '🛡️',
  },
  {
    id: 'time-extreme-1',
    category: 'Meta Requests',
    title: 'Break the Fourth Wall',
    description: 'Address the audience directly—players, DM, observers—just once.',
    prompt: '[Character Name] looks directly at the audience—players, DM, cosmic observers—and addresses them. Just once. Briefly. Then continues as if nothing happened. No one else noticed. Did they?',
    icon: '👁️',
  },
  {
    id: 'time-extreme-2',
    category: 'Meta Requests',
    title: 'Rejected Timeline',
    description: 'See a version of events that was written but abandoned.',
    prompt: 'Show [Character Name] a version of events that was "written" but abandoned—a death they avoided, a choice they didn\'t make, a story that ended differently. It almost happened. It could still.',
    icon: '📚',
  },
  {
    id: 'time-extreme-3',
    category: 'Meta Requests',
    title: 'Conversation with the Author',
    description: 'Meet the entity writing your story and negotiate one change.',
    prompt: '[Character Name] meets an entity that claims to be writing their story. It offers one change—any change—to their past, present, or future. What do they ask for? What does it cost?',
    icon: '✍️',
  },
  // NEW TIME STONE PROMPTS
  {
    id: 'time-agnostic-1',
    category: 'Meta Requests',
    title: 'Scene Transition',
    description: 'Request a hard cut to skip mundane travel or preparation.',
    prompt: '"Can we just... skip to the interesting part?" [Character Name] requests a scene transition, acknowledging that some moments don\'t need to be played out. Cut to black. Cut to action.',
    icon: '🎬',
  },
  {
    id: 'time-agnostic-2',
    category: 'Meta Requests',
    title: 'Foreshadowing Request',
    description: 'Ask the DM to drop hints about what\'s coming—cryptic ones.',
    prompt: '[Character Name] has a premonition—or maybe they\'re just paranoid. Ask the DM to provide cryptic foreshadowing about upcoming events. Something that will make sense later but not now.',
    icon: '🔮',
  },
  {
    id: 'time-agnostic-3',
    category: 'Meta Requests',
    title: 'Callback Setup',
    description: 'Establish something now specifically to pay it off later.',
    prompt: '[Character Name] does something seemingly random or says something oddly specific. Ask the DM to remember this—it will become important later. Plant seeds for future narrative payoff.',
    icon: '🌱',
  },
  {
    id: 'time-agnostic-4',
    category: 'Meta Requests',
    title: 'Pacing Control',
    description: 'Request to slow down or speed up the narrative tempo.',
    prompt: '"This moment deserves more time" or "Let\'s move faster." [Character Name] requests narrative pacing adjustment—lingering on important beats, rushing through tedium. Control the tempo.',
    icon: '⏱️',
  },
  {
    id: 'time-agnostic-5',
    category: 'Meta Requests',
    title: 'Flashback Trigger',
    description: 'Request a flashback to explain how you know something or someone.',
    prompt: 'A face, a place, a smell—[Character Name] recognizes something. Request a flashback to explain the connection. How do they know this? What happened before?',
    icon: '📸',
  },
  {
    id: 'time-agnostic-6',
    category: 'Meta Requests',
    title: 'Previously On...',
    description: 'Recap important events from earlier as if this were a TV series.',
    prompt: '"Previously, on our adventure..." Request a dramatic recap of relevant plot points, framed like a TV series cold open. Remind everyone what matters for this moment.',
    icon: '📺',
  },
  {
    id: 'time-agnostic-7',
    category: 'Meta Requests',
    title: 'Meanwhile...',
    description: 'Cut away to show what\'s happening elsewhere right now.',
    prompt: '"Meanwhile, somewhere else..." Request a scene showing what\'s happening with NPCs, villains, or other plot threads while [Character Name] is occupied here. Expand the world.',
    icon: '🌍',
  },
  {
    id: 'time-agnostic-8',
    category: 'Meta Requests',
    title: 'Dream Sequence',
    description: 'Request a prophetic or symbolic dream during rest.',
    prompt: '[Character Name] sleeps. Request a dream sequence—prophetic, symbolic, or just weird. Dreams can reveal fears, foreshadow events, or just provide surreal entertainment.',
    icon: '💭',
  },
  {
    id: 'time-agnostic-9',
    category: 'Meta Requests',
    title: 'Time Skip Request',
    description: 'Jump forward in time—training, traveling, healing. Show what changed.',
    prompt: '"Weeks pass..." Request a time skip. What changed during the gap? What was learned, lost, or transformed? Compress time, expand character.',
    icon: '⏭️',
  },
  {
    id: 'time-agnostic-10',
    category: 'Meta Requests',
    title: 'Parallel Timeline',
    description: 'Explore a "what if" scenario briefly—then return to reality.',
    prompt: '"What if I had chosen differently?" Request a brief exploration of an alternate choice—the path not taken. See the consequences, then snap back to reality.',
    icon: '🔀',
  },
  {
    id: 'time-agnostic-11',
    category: 'Meta Requests',
    title: 'Slow Motion',
    description: 'Request a moment described in hyper-detailed slow motion.',
    prompt: 'A single second, stretched into paragraphs. Request slow-motion narration of a crucial moment—every muscle movement, every particle, every thought in crystalline detail.',
    icon: '🐌',
  },
  {
    id: 'time-agnostic-12',
    category: 'Meta Requests',
    title: 'Narrative Pause',
    description: 'Freeze the scene to comment on or appreciate what\'s happening.',
    prompt: '"Hold on. Can we appreciate this moment?" Request a narrative pause—freeze the scene while [Character Name] (or the narrator) comments on the absurdity, beauty, or significance.',
    icon: '⏸️',
  },
  {
    id: 'time-agnostic-13',
    category: 'Meta Requests',
    title: 'Season Finale Energy',
    description: 'Request this scene be treated with season finale dramatic weight.',
    prompt: '"This feels important." Request that the DM treat this scene with season finale energy—dramatic music cues, significant pauses, emotional weight. Make it matter.',
    icon: '🎬',
  },
  {
    id: 'time-agnostic-14',
    category: 'Meta Requests',
    title: 'Retcon Request',
    description: 'Ask to establish that something was always true, retroactively.',
    prompt: '"Actually, I think I always had this item" or "We probably met before." Request a minor retcon—establish something as having always been true. Gentle reality adjustment.',
    icon: '✏️',
  },
  {
    id: 'time-agnostic-15',
    category: 'Meta Requests',
    title: 'Check the Clock',
    description: 'Request awareness of in-game time passing—urgency or relaxation.',
    prompt: '"How long has it been?" Request explicit in-game time tracking. Create urgency from deadlines or relaxation from safety. Time pressure as narrative tool.',
    icon: '🕐',
  },

  // ─────────────────────────────────────────
  // MIND STONE - Investigation & Insight (Yellow)
  // ─────────────────────────────────────────
  {
    id: 'mind-mild-1',
    category: 'Investigation',
    title: 'Reading the Room',
    description: 'Notice subtle cues—nervous glances, positioning near exits.',
    prompt: '[Character Name] notices the subtle things—a nervous glance, a too-firm handshake, the way someone positions themselves near exits. Describe what they deduce without asking.',
    icon: '🔍',
  },
  {
    id: 'mind-mild-2',
    category: 'Investigation',
    title: 'Pattern Recognition',
    description: 'See connections between details that can\'t be coincidence.',
    prompt: 'Details click into place—a symbol repeated in different locations, behaviors that mirror each other, timing that can\'t be coincidence. [Character Name] sees the pattern. What does it mean?',
    icon: '🧩',
  },
  {
    id: 'mind-mild-3',
    category: 'Investigation',
    title: 'Gut Instinct',
    description: 'Something feels wrong—no evidence, just certainty. Trust it.',
    prompt: 'Something feels wrong. [Character Name] can\'t articulate why—no evidence, no logic. Just certainty. Trust the instinct. Let it guide them somewhere unexpected.',
    icon: '⚡',
  },
  {
    id: 'mind-moderate-1',
    category: 'Investigation',
    title: 'Reading Between Lives',
    description: 'Deduce someone\'s entire story from physical details alone.',
    prompt: '[Character Name] pieces together someone\'s entire story from physical details—calluses that reveal profession, scars that tell history, posture that speaks of training or trauma. They know this person without asking.',
    icon: '📖',
  },
  {
    id: 'mind-moderate-2',
    category: 'Investigation',
    title: 'The Missing Piece',
    description: 'Realize everyone missed something—including you. The answer was there.',
    prompt: 'A mystery that seemed solved wasn\'t. [Character Name] realizes everyone missed something—including them. The answer was there all along. How did they miss it? Why does that terrify them?',
    icon: '🕳️',
  },
  {
    id: 'mind-moderate-3',
    category: 'Investigation',
    title: 'Predictive Profiling',
    description: 'Anticipate a target\'s next three moves before they make them.',
    prompt: '[Character Name] anticipates their target\'s next three moves before they make them—where they\'ll go, who they\'ll contact, what they\'ll do when cornered. Be right. Make it unsettling.',
    icon: '🎯',
  },
  {
    id: 'mind-moderate-4',
    category: 'Investigation',
    title: 'Unwanted Understanding',
    description: 'Understand an enemy too well—their logic makes sense. That\'s the problem.',
    prompt: '[Character Name] understands their enemy too well—their motivations, their pain, their logic. It makes sense. That\'s the problem. Understanding is not the same as forgiving.',
    icon: '🧠',
  },
  {
    id: 'mind-extreme-1',
    category: 'Investigation',
    title: 'Sherlock Cascade',
    description: 'Perceive everything at once—every connection, every lie. Too much truth.',
    prompt: 'In a single overwhelming moment, [Character Name] perceives everything—every connection, every motive, every lie in the room. Information floods in faster than they can process. They see the truth. All of it. Too much.',
    icon: '💡',
  },
  {
    id: 'mind-extreme-2',
    category: 'Investigation',
    title: 'The Conspiracy Beneath',
    description: 'Realize everything connects—nothing was random, someone was watching.',
    prompt: '[Character Name]\'s investigation reveals something bigger—everything connects. The random events weren\'t random. The coincidences were orchestrated. Someone has been watching. Planning. Waiting.',
    icon: '🕸️',
  },
  {
    id: 'mind-extreme-3',
    category: 'Investigation',
    title: 'Mind Palace Moment',
    description: 'Enter a mental state beyond normal cognition to solve the unsolvable.',
    prompt: '[Character Name] enters a mental state beyond normal cognition—reconstructing events in perfect detail, simulating conversations, walking through possibilities. They solve the unsolvable. But what did it cost them mentally?',
    icon: '🏛️',
  },
  // NEW MIND STONE PROMPTS
  {
    id: 'mind-agnostic-1',
    category: 'Investigation',
    title: 'The Tell',
    description: 'Identify someone\'s specific "tell" for when they\'re lying or stressed.',
    prompt: '[Character Name] has been watching. They\'ve identified someone\'s tell—the specific micro-expression, gesture, or verbal tic that reveals deception or stress. Now they know when this person lies. Use it.',
    icon: '👁️',
  },
  {
    id: 'mind-agnostic-2',
    category: 'Investigation',
    title: 'Evidence Reconstruction',
    description: 'Mentally reconstruct what happened in this space from physical clues.',
    prompt: '[Character Name] enters a room and reads it like a book—the furniture displacement tells of a struggle, the dust patterns reveal what was moved, the angles speak of violence or haste. Reconstruct the scene.',
    icon: '🔬',
  },
  {
    id: 'mind-agnostic-3',
    category: 'Investigation',
    title: 'Strategic Assessment',
    description: 'Analyze an upcoming challenge and identify three key vulnerabilities.',
    prompt: 'Before engaging, [Character Name] analyzes the situation tactically—escape routes, blind spots, the weak link in the enemy formation, the variable that could swing everything. Identify three key insights.',
    icon: '📊',
  },
  {
    id: 'mind-agnostic-4',
    category: 'Investigation',
    title: 'Cold Reading',
    description: 'Make educated guesses about a stranger based on visible details.',
    prompt: '[Character Name] cold-reads a stranger—profession from calluses, wealth from fabric quality, anxiety from fidgeting. Make educated guesses out loud. Some will be right. Some will be dangerously wrong.',
    icon: '🎯',
  },
  {
    id: 'mind-agnostic-5',
    category: 'Investigation',
    title: 'Information Extraction',
    description: 'Get someone to reveal information without them realizing they did.',
    prompt: 'Through careful conversation, [Character Name] extracts information without the target realizing they gave anything away. Social engineering as art. They\'ll only notice later.',
    icon: '🪤',
  },
  {
    id: 'mind-agnostic-6',
    category: 'Investigation',
    title: 'Memory Palace',
    description: 'Mentally organize and retrieve information with perfect clarity.',
    prompt: '[Character Name] accesses their mental archive—recalling exact conversations, layouts, faces. Describe the memory palace technique, the organized mind at work.',
    icon: '🏰',
  },
  {
    id: 'mind-agnostic-7',
    category: 'Investigation',
    title: 'Behavioral Prediction',
    description: 'Anticipate how someone will react based on established patterns.',
    prompt: 'Based on observed behavior, [Character Name] predicts exactly how this person will react—to a threat, an offer, a surprise. Then test the prediction. Were they right?',
    icon: '🧮',
  },
  {
    id: 'mind-agnostic-8',
    category: 'Investigation',
    title: 'The Missing Variable',
    description: 'Something doesn\'t add up—identify what\'s not being said.',
    prompt: 'The story doesn\'t add up. [Character Name] identifies the missing variable—the motive that doesn\'t fit, the timeline that contradicts, the person who hasn\'t been mentioned. What\'s being hidden?',
    icon: '❓',
  },
  {
    id: 'mind-agnostic-9',
    category: 'Investigation',
    title: 'Witness Interview',
    description: 'Extract accurate information from an unreliable or frightened witness.',
    prompt: 'A witness who\'s scared, lying, or genuinely confused. [Character Name] navigates the conversation—calming fears, spotting inconsistencies, separating truth from perception. Extract the useful.',
    icon: '🗣️',
  },
  {
    id: 'mind-agnostic-10',
    category: 'Investigation',
    title: 'Document Analysis',
    description: 'Read between the lines of written materials—what\'s said and unsaid.',
    prompt: '[Character Name] examines documents—not just what they say, but handwriting stress, ink age, word choice patterns. Written materials reveal more than their authors intend.',
    icon: '📄',
  },
  {
    id: 'mind-agnostic-11',
    category: 'Investigation',
    title: 'Body Language Library',
    description: 'Catalog the nonverbal communication in a room full of people.',
    prompt: 'In a crowded room, [Character Name] reads body language—who\'s attracted to whom, who\'s afraid of the door, who\'s armed, who\'s lying. A library of nonverbal communication, cataloged.',
    icon: '📖',
  },
  {
    id: 'mind-agnostic-12',
    category: 'Investigation',
    title: 'Reverse Engineering',
    description: 'Work backward from a result to understand how something was done.',
    prompt: 'Starting from the result, [Character Name] works backward—this lock was picked with these tools, this poison came from this source, this escape used this route. Reverse engineer the mystery.',
    icon: '🔧',
  },
  {
    id: 'mind-agnostic-13',
    category: 'Investigation',
    title: 'Logical Deduction',
    description: 'Use process of elimination to reach an inescapable conclusion.',
    prompt: '"If not A, then B. If B implies C, and C is impossible..." [Character Name] walks through logical deduction out loud, eliminating impossibilities until only truth remains.',
    icon: '🧠',
  },
  {
    id: 'mind-agnostic-14',
    category: 'Investigation',
    title: 'Trap Recognition',
    description: 'Identify an ambush or trap before walking into it.',
    prompt: 'Something\'s wrong. [Character Name]\'s instincts scream trap—the too-perfect meeting spot, the convenient timing, the bait that\'s too attractive. Identify the trap before springing it.',
    icon: '⚠️',
  },
  {
    id: 'mind-agnostic-15',
    category: 'Investigation',
    title: 'Motive Mapping',
    description: 'Chart out who benefits from a crime or situation.',
    prompt: 'Who benefits? [Character Name] maps motives—financial gain, political advantage, personal revenge, ideological commitment. Everyone has reasons. Find the ones that matter.',
    icon: '🗺️',
  },

  // ─────────────────────────────────────────
  // SPACE STONE - Voice, Tone & Narrative (Blue)
  // ─────────────────────────────────────────
  {
    id: 'space-mild-1',
    category: 'Voice & Tone',
    title: 'Signature Line',
    description: 'Deliver a defining line—sardonic, sincere, or profound. Make it quotable.',
    prompt: 'Give [Character Name] a moment to deliver a line that defines them—sardonic, sincere, or surprisingly profound. Something that could be quoted. Make it matter.',
    icon: '💬',
  },
  {
    id: 'space-mild-2',
    category: 'Narrative',
    title: 'Establishing Shot',
    description: 'Frame your entrance cinematically—what does the space reveal about you?',
    prompt: 'Describe [Character Name]\'s entrance to a new location with cinematic framing—what does the environment reveal about them? How does space itself react to their presence?',
    icon: '🎬',
  },
  {
    id: 'space-mild-3',
    category: 'Voice & Tone',
    title: 'Tone Shift',
    description: 'Change the scene\'s emotional register through your perspective.',
    prompt: 'Shift the scene\'s emotional register through [Character Name]\'s perspective—a dark moment finds dark humor, a comedic scene finds unexpected weight. They set the tone.',
    icon: '🎭',
  },
  {
    id: 'space-moderate-1',
    category: 'Narrative',
    title: 'Parallel Narratives',
    description: 'Cut between your actions and something elsewhere that mirrors or contrasts.',
    prompt: 'Cut between [Character Name]\'s actions and something happening elsewhere that mirrors or contrasts them—a birth as they bring death, a celebration as they mourn. Meaning emerges from juxtaposition.',
    icon: '⚖️',
  },
  {
    id: 'space-moderate-2',
    category: 'Voice & Tone',
    title: 'Monologue Moment',
    description: 'Voice your philosophy uninterrupted—define who you are in your own words.',
    prompt: 'Give [Character Name] an uninterrupted moment to voice their philosophy—to an enemy, an ally, or themselves. No interruptions. Let them define who they are in their own words.',
    icon: '🎤',
  },
  {
    id: 'space-moderate-3',
    category: 'Narrative',
    title: 'Flashback Integration',
    description: 'Let current events trigger a seamless flashback that informs the present.',
    prompt: 'A current event triggers a seamless flashback—past and present bleeding together, informing each other. What happened before explains what\'s happening now. Connect them.',
    icon: '⏪',
  },
  {
    id: 'space-moderate-4',
    category: 'Voice & Tone',
    title: 'Silence Speaks',
    description: 'Communicate through action and expression alone—no dialogue.',
    prompt: 'Remove dialogue from a scene. Let [Character Name] communicate through action, expression, and presence alone. What do they say without speaking? What can\'t be said?',
    icon: '🤫',
  },
  {
    id: 'space-extreme-1',
    category: 'Narrative',
    title: 'Unreliable Reality',
    description: 'See through your biases—then have reality crack open the truth.',
    prompt: 'Narrate the scene from [Character Name]\'s subjective perspective—their biases, fears, and desires shaping what they perceive. Then crack it open. Show what\'s actually happening.',
    icon: '🪞',
  },
  {
    id: 'space-extreme-2',
    category: 'Voice & Tone',
    title: 'The Defining Moment',
    description: 'This is the scene that defines you forever—frame it with that weight.',
    prompt: 'This is the scene that will be remembered. The moment that defines [Character Name] forever—heroic, tragic, or transcendent. Frame it with the weight it deserves. Make it unforgettable.',
    icon: '⭐',
  },
  {
    id: 'space-extreme-3',
    category: 'Narrative',
    title: 'Story Becomes Legend',
    description: 'Show how your current actions will be told in the future—embellished, deified.',
    prompt: 'Show how [Character Name]\'s current actions will be told in the future—embellished, distorted, deified. The legend forming in real-time around them. Truth and myth braiding together.',
    icon: '📜',
  },
  // NEW SPACE STONE PROMPTS
  {
    id: 'space-agnostic-1',
    category: 'Narrative',
    title: 'Cold Open',
    description: 'Start a scene in media res—already in the middle of action.',
    prompt: 'Skip the setup. Begin the scene with [Character Name] already in trouble—mid-fight, mid-chase, mid-negotiation gone wrong. Explain how we got here later. Or don\'t.',
    icon: '🎯',
  },
  {
    id: 'space-agnostic-2',
    category: 'Voice & Tone',
    title: 'Internal Versus External',
    description: 'Show the contrast between what you say and what you actually think.',
    prompt: '[Character Name] says one thing while thinking another. Narrate both—the diplomatic words they speak and the much more colorful thoughts beneath. The mask and the face.',
    icon: '🎭',
  },
  {
    id: 'space-agnostic-3',
    category: 'Narrative',
    title: 'Epilogue Preview',
    description: 'Flash forward to show where this choice leads—then return to the present.',
    prompt: 'Before [Character Name] makes a crucial choice, flash forward to show a glimpse of where each path leads—not the whole future, just a moment, a consequence. Then snap back to the decision.',
    icon: '⏭️',
  },
  {
    id: 'space-agnostic-4',
    category: 'Voice & Tone',
    title: 'Catchphrase Moment',
    description: 'Deliver a recurring line that becomes your signature.',
    prompt: '[Character Name] has a line they say—before fights, after victories, when things go wrong. Deliver it now. Let it become a signature through repetition. Own the catchphrase.',
    icon: '💬',
  },
  {
    id: 'space-agnostic-5',
    category: 'Narrative',
    title: 'POV Shift',
    description: 'Briefly narrate from someone else\'s perspective—how do they see you?',
    prompt: 'Shift perspective—describe [Character Name] through an NPC\'s eyes. The stranger at the bar. The guard at the gate. How does the world perceive them? It\'s rarely how they see themselves.',
    icon: '👁️',
  },
  {
    id: 'space-agnostic-6',
    category: 'Voice & Tone',
    title: 'Tonal Whiplash',
    description: 'Crash from comedy to tragedy (or vice versa) in a single beat.',
    prompt: 'In one moment, shift from comedy to tragedy—or tragedy to absurdity. [Character Name] navigates the tonal whiplash. Life doesn\'t stick to one genre. Neither should the story.',
    icon: '🎭',
  },
  {
    id: 'space-agnostic-7',
    category: 'Narrative',
    title: 'Symbolic Object',
    description: 'Focus on an object that represents something larger—what does it mean?',
    prompt: 'An object carries meaning—a locket, a scar, a coin, a weapon. [Character Name] interacts with it. What does it represent? Let the symbol do the emotional heavy lifting.',
    icon: '🔑',
  },
  {
    id: 'space-agnostic-8',
    category: 'Voice & Tone',
    title: 'Gallows Humor',
    description: 'Find dark comedy in a grim situation—because what else can you do?',
    prompt: 'The situation is dire. [Character Name] makes a joke anyway—not to dismiss the danger, but because humor is how they survive. Gallows humor as coping mechanism.',
    icon: '😈',
  },
  {
    id: 'space-agnostic-9',
    category: 'Narrative',
    title: 'Montage Vignettes',
    description: 'Compress multiple small moments into a sequence of snapshots.',
    prompt: 'Skip the transitions. A series of moments: preparing, traveling, waiting, arriving. Each captured in a sentence or two. Montage as narrative efficiency.',
    icon: '📷',
  },
  {
    id: 'space-agnostic-10',
    category: 'Voice & Tone',
    title: 'Understatement',
    description: 'Respond to chaos with deliberate, dry understatement.',
    prompt: 'Everything explodes—literally or figuratively. [Character Name] responds with deliberate understatement. "Well, that\'s inconvenient." Deadpan as defense mechanism.',
    icon: '😐',
  },
  {
    id: 'space-agnostic-11',
    category: 'Narrative',
    title: 'Thematic Echo',
    description: 'Mirror an earlier scene—same words, different meaning.',
    prompt: 'Echo an earlier moment—same location, same words, different meaning. [Character Name] stands where they stood before. Everything has changed. Or nothing has. Both are devastating.',
    icon: '🔄',
  },
  {
    id: 'space-agnostic-12',
    category: 'Voice & Tone',
    title: 'The Quiet Threat',
    description: 'Threaten someone without raising your voice—make softness terrifying.',
    prompt: '[Character Name] threatens someone without raising their voice. No shouting. No dramatic gestures. Just soft, certain words that land like stones. Make quiet terrifying.',
    icon: '🤫',
  },
  {
    id: 'space-agnostic-13',
    category: 'Narrative',
    title: 'Sensory Focus',
    description: 'Describe a scene through a single dominant sense—smell, sound, texture.',
    prompt: 'Describe the scene through a single sense—the sounds of a tavern, the smell of a battlefield, the texture of ancient stone. Let one sense dominate. Sensory specificity creates memory.',
    icon: '👃',
  },
  {
    id: 'space-agnostic-14',
    category: 'Voice & Tone',
    title: 'Eloquent Violence',
    description: 'Describe brutality with beautiful, poetic language.',
    prompt: 'Violence described beautifully—precise prose for brutal acts. [Character Name]\'s actions rendered in language that makes destruction lyrical. Beauty and horror intertwined.',
    icon: '🌹',
  },
  {
    id: 'space-agnostic-15',
    category: 'Narrative',
    title: 'Frame Story',
    description: 'Present this scene as a story being told by your future self.',
    prompt: 'Frame this scene as a story being told later—by [Character Name] in a tavern, by historians, by survivors. How will this moment be remembered? Tell it as legend while living it.',
    icon: '📜',
  },
];

export const promptCategories = [
  'Voice & Tone',
  'Combat',
  'Social',
  'Investigation',
  'Emotional',
  'World',
  'Narrative',
  'Meta Requests',
];
