// Empyrean Series — 50 Prompt Templates for 3rd-party AI DMs
// Uses the same CharacterPrompt interface as characterPrompts.ts

import type { CharacterPrompt } from './characterPrompts';

export const empyreanPrompts: CharacterPrompt[] = [
  // ── Dragon Bond (8) ────────────────────────────────────────────────────────
  {
    id: 'emp-dragon-conscription',
    category: 'Dragon Bond',
    title: 'First Conscription Day',
    description: 'Arrive at Basgiath and face the parapet crossing.',
    prompt: '[Character Name] arrives at Basgiath War College for Conscription Day. Describe the journey to the fortress, the first sight of the Cliffs of Dralor, and the moment they must cross the parapet — a crumbling stone bridge with no railings over a lethal drop. Other conscripts are ahead and behind. Some fall. The wind is vicious. Describe the physical sensation, the fear, and what [Character Name] sees on the other side.',
    icon: '🏔️',
  },
  {
    id: 'emp-dragon-threshing',
    category: 'Dragon Bond',
    title: 'Dragon Presentation',
    description: 'Stand before unbonded dragons during Threshing.',
    prompt: '[Character Name] enters the Threshing field — a vast, open area where unbonded dragons wait. The air smells of sulfur and ozone. Dragons of varying sizes and breeds observe the candidates with ancient, appraising eyes. Describe the approach, the dragons\' reactions to [Character Name] specifically, and the moment a bond either forms or is rejected. Include the physical sensation of the telepathic connection igniting for the first time.',
    icon: '🐉',
  },
  {
    id: 'emp-dragon-bonding',
    category: 'Dragon Bond',
    title: 'Bond Deepening',
    description: 'A quiet moment strengthening the mental link with your dragon.',
    prompt: '[Character Name] finds a quiet moment with their bonded dragon — perhaps at dawn on the flight field, or in the dragon\'s den after a long day. The telepathic link is still new and developing. Describe the attempt to communicate more deeply: sharing a memory, trying to understand the dragon\'s emotions, or simply sitting in the warmth of the bond. Include what the dragon communicates back — not in human words, but in impressions, images, and ancient feeling.',
    icon: '💫',
  },
  {
    id: 'emp-dragon-flight',
    category: 'Dragon Bond',
    title: 'Aerial Combat Training',
    description: 'Practice formations and fire commands in flight.',
    prompt: '[Character Name] is in the air with their squad for aerial combat training. The instructor calls formations from the ground using signal flags. Describe the sensation of flight — the wind, the altitude, the dragon\'s muscles working beneath the saddle. Include a complex maneuver that tests [Character Name]\'s coordination with their dragon, a near-miss with another rider, and the instructor\'s assessment afterward.',
    icon: '🌤️',
  },
  {
    id: 'emp-dragon-injury',
    category: 'Dragon Bond',
    title: 'Dragon Injury',
    description: 'Your dragon is wounded; navigate the bond bleed-through.',
    prompt: '[Character Name]\'s dragon has been injured — during training, combat, or an accident. The bond bleed-through hits immediately: phantom pain in [Character Name]\'s body mirroring the dragon\'s wound. Describe the struggle to function through the shared agony, the rush to get the dragon to the healers, and the agonizing wait while the dragon is treated. Include the dragon\'s own reaction — pride, anger, or reassurance sent through the bond.',
    icon: '🩸',
  },
  {
    id: 'emp-dragon-second',
    category: 'Dragon Bond',
    title: 'Second Bond Manifestation',
    description: 'The rare second dragon bond manifests unexpectedly.',
    prompt: 'Something impossible happens: a second dragon approaches [Character Name] with bonding intent. The existing bond thrums with [the first dragon\'s reaction — jealousy? curiosity? rage?]. Describe the moment of contact with the second dragon, the disorienting sensation of two telepathic channels opening simultaneously, and the immediate social consequences as witnesses react with shock, fear, or suspicion. Second bonds are nearly unheard of — this will change everything.',
    icon: '⚡',
  },
  {
    id: 'emp-dragon-disagree',
    category: 'Dragon Bond',
    title: 'Dragon Disagreement',
    description: 'Your dragon refuses a direct order for reasons unknown.',
    prompt: '[Character Name] gives their dragon a direct command — fly to a location, engage a target, land in a specific spot — and the dragon flatly refuses. The telepathic channel fills with a wall of NO, tinged with an emotion [Character Name] can\'t immediately interpret. Describe [Character Name]\'s frustration, the attempt to understand the dragon\'s reasoning, and the eventual revelation of WHY the dragon refused. The dragon was right. They usually are.',
    icon: '🚫',
  },
  {
    id: 'emp-dragon-hatching',
    category: 'Dragon Bond',
    title: 'Hatching Witness',
    description: 'Witness a new clutch hatching and the chaos of first bonds.',
    prompt: '[Character Name] is present at a dragon hatching — a rare privilege. The eggs crack in the volcanic nesting grounds beneath Basgiath. Describe the emergence of hatchlings: wet, fierce, already dangerous. Some hatchlings immediately fixate on nearby riders, attempting to bond with beings who already have dragons. Others cry for parents. One hatchling does something unexpected that draws [Character Name]\'s attention. The scene is chaotic, beautiful, and primally moving.',
    icon: '🥚',
  },

  // ── Signet Abilities (7) ───────────────────────────────────────────────────
  {
    id: 'emp-signet-manifest',
    category: 'Signet Abilities',
    title: 'Signet Manifestation',
    description: 'Your signet power reveals itself for the first time under stress.',
    prompt: '[Character Name] is in extreme danger or emotional distress — describe the specific trigger. Something erupts from within: their signet manifests for the first time. The power is raw, uncontrolled, and terrifying. Describe what happens to [Character Name]\'s body (physical sensations, visual effects), what the signet actually DOES, and the aftermath — exhaustion, confusion, the reactions of witnesses, and the dragon\'s response through the bond. First manifestation is always overwhelming.',
    icon: '✨',
  },
  {
    id: 'emp-signet-overreach',
    category: 'Signet Abilities',
    title: 'Signet Overreach',
    description: 'Push your signet beyond safe limits and face burnout.',
    prompt: '[Character Name] pushes their signet past the safe limit — deliberately or out of necessity. Describe the heat building deep in the bones at the relic site, spreading outward as the body struggles to contain more energy than it was built to hold. The symptoms should reflect the nature of [Character Name]\'s specific signet. Describe the moment the dragon\'s presence through the bond sharpens — the dragon feels this and is pushing back, trying to reduce the flow. Present the choice: stop now and survive, or push further and risk permanent damage or death. Whatever they choose, describe the burnout consequences through the lens of their specific power. Recovery is not quick. The body remembers.',
    icon: '🔥',
  },
  {
    id: 'emp-signet-training',
    category: 'Signet Abilities',
    title: 'Signet Training',
    description: 'A professor tests your signet limits in a controlled exercise.',
    prompt: 'Professor [invent a name] specializes in signet development. They have designed an exercise specifically for [Character Name]\'s ability — describe the controlled environment, the escalating difficulty, and the professor\'s clinical observations. Include a moment where the professor pushes [Character Name] further than expected, the dragon\'s protective response through the bond, and the professor\'s assessment: what the signet can become, and what it will cost.',
    icon: '📚',
  },
  {
    id: 'emp-signet-combo',
    category: 'Signet Abilities',
    title: 'Signet Combo',
    description: 'Combine your signet with another rider\'s for an amplified effect.',
    prompt: '[Character Name] and a squadmate discover their signets can be combined for an amplified effect. Describe the first attempt: the synchronization challenge, the moment both powers lock together, and the result — something neither rider could achieve alone. Include the physical and emotional toll of channeling combined power, the squad\'s reaction, and the strategic implications. Also describe the risk: combined burnout could affect both riders simultaneously.',
    icon: '🤝',
  },
  {
    id: 'emp-signet-malfunction',
    category: 'Signet Abilities',
    title: 'Signet Malfunction',
    description: 'Your signet produces an unintended and unpredictable result.',
    prompt: '[Character Name] activates their signet for a routine purpose and something goes wrong — or very differently than expected. The power twists, amplifies, or redirects in a way that has never happened before. Describe the unintended effect, the immediate danger or consequence, and [Character Name]\'s scramble to regain control. Is this a malfunction, or is the signet evolving? The dragon offers an opinion through the bond.',
    icon: '⚠️',
  },
  {
    id: 'emp-signet-conceal',
    category: 'Signet Abilities',
    title: 'Signet Concealment',
    description: 'Hide the true nature of your signet from leadership.',
    prompt: '[Character Name]\'s signet is unusual, powerful, or politically dangerous — and they have decided to hide its true nature from Basgiath leadership. Describe a signet evaluation session where [Character Name] must demonstrate their ability while concealing its full scope. Include the evaluator\'s probing questions, a close call where the truth nearly slips, and the paranoid awareness that someone in the room might already suspect. The dragon\'s opinion on the deception adds tension.',
    icon: '🎭',
  },
  {
    id: 'emp-signet-evolve',
    category: 'Signet Abilities',
    title: 'Signet Evolution',
    description: 'Your power grows or changes in a way no codex has documented.',
    prompt: '[Character Name]\'s signet has changed — not just grown stronger, but fundamentally shifted in nature or capability. This is not documented in any codex. Describe the moment of realization: what the signet can now do that it couldn\'t before, the physical sensations of the change, and the implications. Does [Character Name] report this to the professors or keep it secret? The dragon\'s reaction suggests this has happened before, long ago, to other riders whose stories were erased.',
    icon: '🌀',
  },

  // ── Basgiath War College (8) ───────────────────────────────────────────────
  {
    id: 'emp-basgiath-gauntlet',
    category: 'Basgiath War College',
    title: 'Squad Challenge',
    description: 'Face an elimination-style gauntlet in the training grounds.',
    prompt: '[Character Name]\'s squad has been selected for a gauntlet challenge — a grueling series of combat, puzzle, and endurance tests in Basgiath\'s training grounds. The stakes: the losing squad faces punishment duty for a month. Describe the challenges, the moments where squad coordination saves them or fails them, and the interpersonal dynamics under pressure. Someone in the squad makes a costly mistake. Someone else performs beyond expectations.',
    icon: '⚔️',
  },
  {
    id: 'emp-basgiath-brief',
    category: 'Basgiath War College',
    title: 'Battle Brief Intelligence',
    description: 'A Battle Brief reveals disturbing news about the ward line.',
    prompt: 'During the weekly Battle Brief — where riders receive intelligence updates on the war — a piece of information slips through that is more alarming than usual. A wardstone failure closer to Basgiath than any before. Describe the briefing room, the instructor\'s carefully controlled delivery, the reactions of the other cadets, and [Character Name]\'s private assessment. What isn\'t being said is more frightening than what is. Afterward, in the corridor, someone pulls [Character Name] aside with additional information.',
    icon: '📋',
  },
  {
    id: 'emp-basgiath-mess',
    category: 'Basgiath War College',
    title: 'Mess Hall Confrontation',
    description: 'Tensions boil over between riders from different wings.',
    prompt: 'Dinner in the mess hall. A remark — possibly about rankings, a training incident, or a personal slight — escalates between riders from two different wings. [Character Name] is present and must choose: intervene, stay out of it, or take a side. Describe the mess hall atmosphere, the escalating argument, the moment it turns physical (or nearly does), and the consequences. Wing loyalty is powerful at Basgiath — this will be remembered.',
    icon: '🍽️',
  },
  {
    id: 'emp-basgiath-spar',
    category: 'Basgiath War College',
    title: 'Sparring Match',
    description: 'Hand-to-hand combat with a rival who fights dirty.',
    prompt: '[Character Name] is matched against a rival in the sparring ring. This opponent has a reputation for fighting dirty — technically legal moves that cause maximum pain. Describe the match blow by blow: the rival\'s dirty tactics, [Character Name]\'s response (adapt or retaliate?), the instructor\'s observations, and the crowd\'s reaction. Win or lose, this fight changes the dynamic between [Character Name] and their opponent.',
    icon: '🥊',
  },
  {
    id: 'emp-basgiath-wargames',
    category: 'Basgiath War College',
    title: 'War Games',
    description: 'Full-scale simulated battle with real stakes and injuries.',
    prompt: 'Basgiath conducts War Games — a full-scale simulated battle between wings, with real combat (blunted weapons, controlled signet use) and real consequences (injuries are common, death is rare but not unheard of). [Character Name]\'s wing faces a numerically superior opponent. Describe the strategy session, the aerial and ground phases of the battle, and the moment everything changes — a plan that works brilliantly or fails catastrophically. Include at least one genuine injury.',
    icon: '🏴',
  },
  {
    id: 'emp-basgiath-summons',
    category: 'Basgiath War College',
    title: 'Commandant\'s Summons',
    description: 'Called before leadership for an uncomfortable interrogation.',
    prompt: '[Character Name] receives a summons to the Commandant\'s office — or another senior leader. The walk through Basgiath\'s corridors feels longer than usual. Describe the office (what it reveals about the person in charge), the interrogation (what they want to know and why), and the undertones (what they\'re really asking). [Character Name] must decide how much truth to share. The leader knows more than they reveal, and the meeting ends with an implicit threat or an unexpected offer.',
    icon: '📜',
  },
  {
    id: 'emp-basgiath-archives',
    category: 'Basgiath War College',
    title: 'Archives Discovery',
    description: 'Uncover forbidden texts in the Scribe quadrant.',
    prompt: '[Character Name] gains access — legitimately or otherwise — to a restricted section of Basgiath\'s archives. Describe the descent into the lower stacks, the dust, the preservation wards on ancient texts, and the discovery of a document that challenges official history. What does it reveal? Who wrote it? Why was it hidden? [Character Name] must decide what to do with this knowledge — and they realize someone has been here before them recently. The dust has been disturbed.',
    icon: '📖',
  },
  {
    id: 'emp-basgiath-leadership',
    category: 'Basgiath War College',
    title: 'Wing Leadership',
    description: 'Earn or lose a leadership position within your wing.',
    prompt: '[Character Name] is either being considered for a leadership position (squad leader, wingleader) or is at risk of losing one. Describe the evaluation process: the tests, the politics, the competitors. Include a critical moment where [Character Name]\'s leadership style is tested — a crisis where they must make a call that not everyone will agree with. The outcome reshapes their position within the wing hierarchy and changes how others treat them.',
    icon: '👑',
  },

  // ── Venin and Dark Forces (7) ──────────────────────────────────────────────
  {
    id: 'emp-venin-first',
    category: 'Venin and Dark Forces',
    title: 'First Venin Encounter',
    description: 'Face a venin and realize the propaganda was wrong.',
    prompt: '[Character Name] encounters a venin for the first time — not in a briefing room, but in person. Everything they were taught said venin are mindless monsters. This one speaks. Describe the setting (a patrol beyond the wards, a ward failure zone, an attack on an outpost), the venin\'s appearance (the corruption visible on their body), and the shock of hearing them talk. What does the venin say? It should challenge something [Character Name] believed about the enemy.',
    icon: '👁️',
  },
  {
    id: 'emp-venin-wyvern',
    category: 'Venin and Dark Forces',
    title: 'Wyvern Assault',
    description: 'Wyverns attack during patrol, testing everything you\'ve learned.',
    prompt: 'During a routine patrol, wyverns attack — a swarm of them, coming from a direction nobody expected. Describe the initial moments: the screech, the dragon\'s instinctive response, the frantic scramble into combat formation. The fight is chaotic, terrifying, and nothing like training exercises. Include a squadmate in danger, a dragon-to-wyvern mid-air clash, and the aftermath — the cost counted in injuries, exhaustion, and the realization that this is the reality beyond Basgiath\'s walls.',
    icon: '🦇',
  },
  {
    id: 'emp-venin-ward',
    category: 'Venin and Dark Forces',
    title: 'Ward Line Failure',
    description: 'A section of the ward line goes dark and your squad investigates.',
    prompt: 'A section of the ward line has gone dark — the wardstone has failed or been destroyed. [Character Name]\'s squad is sent to investigate. Describe the approach: the moment they cross into unprotected territory, the change in the air and land (the grey, the silence, the wrongness), and what they find at the wardstone site. Was it natural degradation or deliberate sabotage? Something is still there, and it knows they\'ve arrived.',
    icon: '🌑',
  },
  {
    id: 'emp-venin-temptation',
    category: 'Venin and Dark Forces',
    title: 'Dark Wielding Temptation',
    description: 'Forbidden power presents itself in a desperate moment.',
    prompt: '[Character Name] is in a desperate situation — about to die, watching someone they care about in mortal danger, or facing impossible odds. In that moment, they feel it: the earth beneath them, pulsing with power that could be drawn. Dark wielding. Describe the sensation — the seductive pull, the promise of enough power to solve everything, the whisper that it would be just this once. What does [Character Name] do? And what does the dragon feel through the bond?',
    icon: '🖤',
  },
  {
    id: 'emp-venin-intel',
    category: 'Venin and Dark Forces',
    title: 'Venin Intelligence',
    description: 'Capture or interrogate a venin and learn something game-changing.',
    prompt: 'An early-stage venin has been captured alive — still coherent enough to communicate. [Character Name] is part of the interrogation, officially or unofficially. Describe the containment setup, the venin\'s appearance and demeanor (are they afraid? defiant? resigned?), and the information they reveal. What they say should change [Character Name]\'s understanding of the war, the enemy, or the Empyrean\'s secrets. The venin asks a question in return that [Character Name] cannot answer.',
    icon: '🔗',
  },
  {
    id: 'emp-venin-infected',
    category: 'Venin and Dark Forces',
    title: 'Infected Rider',
    description: 'A fellow rider shows signs of turning — and they\'re your friend.',
    prompt: 'Someone [Character Name] cares about — a squadmate, a friend, a romantic interest — is showing subtle signs of venin corruption. Darkening veins they try to hide. Mood changes. Unexplained power spikes. [Character Name] notices. Describe the dread, the denial, the moment of confirmation. What do you do when someone you love is becoming the enemy? Report them (and condemn them)? Hide it (and risk everyone)? Try to help (and risk yourself)?',
    icon: '💉',
  },
  {
    id: 'emp-venin-beyond',
    category: 'Venin and Dark Forces',
    title: 'Beyond the Wards',
    description: 'Cross into drained territory where the land is dead.',
    prompt: '[Character Name] crosses beyond the ward line into the Barrens — territory drained by venin over centuries. Describe the landscape: grey earth, petrified trees, silence where there should be life. The air tastes wrong. The dragon is uneasy, sending waves of discomfort through the bond. As they venture deeper, describe what they find — evidence of what this land was before it was drained, and evidence of what lives here now. The return to warded territory should feel like surfacing from underwater.',
    icon: '🏜️',
  },

  // ── Relationships and Politics (8) ─────────────────────────────────────────
  {
    id: 'emp-rel-alliance',
    category: 'Relationships and Politics',
    title: 'Forbidden Alliance',
    description: 'Form a secret pact with someone from a rival quadrant.',
    prompt: '[Character Name] makes contact with someone from a different quadrant — a scribe with forbidden knowledge, a healer with no allegiance to the Empyrean, or an infantry cadet who saw something they shouldn\'t have. Describe the clandestine meeting, the negotiation of trust, and the terms of their alliance. Both parties are risking their positions and possibly their lives. What do they each want? What do they each have to offer?',
    icon: '🤫',
  },
  {
    id: 'emp-rel-romantic',
    category: 'Relationships and Politics',
    title: 'Romantic Tension',
    description: 'A charged moment with someone you shouldn\'t trust but can\'t resist.',
    prompt: '[Character Name] is alone with someone they are drawn to — but shouldn\'t be. Chain of command, factional loyalty, or competing secrets make this dangerous. Describe the setting (a training room after hours, the library stacks, a quiet spot on the ramparts), the conversation that starts as one thing and becomes something else, and the physical awareness between them. The moment is interrupted before anything resolves — but something has shifted between them permanently.',
    icon: '💕',
  },
  {
    id: 'emp-rel-betrayal',
    category: 'Relationships and Politics',
    title: 'Betrayal Discovery',
    description: 'Someone close has been reporting to the Commandant.',
    prompt: '[Character Name] discovers that someone they trusted — a squadmate, a friend, a romantic interest — has been reporting information to the Commandant\'s office. Describe the discovery (overheard conversation, found documents, a warning from a third party), the confrontation (or the decision not to confront), and the emotional fallout. Was the betrayal driven by loyalty to the institution, coercion, or something else entirely? The relationship is irrevocably changed.',
    icon: '🗡️',
  },
  {
    id: 'emp-rel-legacy',
    category: 'Relationships and Politics',
    title: 'Family Legacy',
    description: 'Your family name carries weight that helps and hinders.',
    prompt: '[Character Name]\'s family name is recognized at Basgiath — for better or worse. Describe an incident where the legacy matters: a professor who served with a parent and has expectations, a rival who resents the family\'s reputation, or a senior officer who offers advantage based on bloodline. [Character Name] must navigate whether to leverage the legacy or reject it, knowing that either choice has consequences within Basgiath\'s political ecosystem.',
    icon: '🏛️',
  },
  {
    id: 'emp-rel-cross',
    category: 'Relationships and Politics',
    title: 'Cross-Quadrant Friendship',
    description: 'Bond with a scribe or healer despite social barriers.',
    prompt: '[Character Name] forms an unlikely friendship with someone from a different quadrant. Riders and scribes operate in different worlds; riders and healers have a relationship defined by dependency. Describe how the friendship forms (a shared incident, mutual curiosity, being assigned adjacent rooms), the social friction it creates (quadrant loyalty is strong), and a moment where the friendship is tested — and proven real.',
    icon: '🌉',
  },
  {
    id: 'emp-rel-loyalty',
    category: 'Relationships and Politics',
    title: 'Loyalty Test',
    description: 'Choose between following orders and protecting someone.',
    prompt: 'An order comes down from leadership — and obeying it means sacrificing someone [Character Name] cares about. Describe the order (a mission assignment, a disciplinary action, a strategic decision that treats people as expendable), the person at risk, and the impossible choice. If [Character Name] follows orders, describe the personal cost. If they defy orders, describe the institutional consequences. There is no clean outcome.',
    icon: '⚖️',
  },
  {
    id: 'emp-rel-powerplay',
    category: 'Relationships and Politics',
    title: 'Power Play',
    description: 'Navigate a conflict between senior riders with your squad caught in the middle.',
    prompt: 'Two senior riders — wingleaders, professors, or commanding officers — are in conflict, and [Character Name]\'s squad is caught in the middle. Each side applies pressure: favors, threats, assignments that are rewards or punishments depending on who you ask. Describe the political dynamics, the attempts to recruit [Character Name] to a side, and the squad\'s internal debate about which allegiance serves them best. Neutrality is not an option.',
    icon: '♟️',
  },
  {
    id: 'emp-rel-truth',
    category: 'Relationships and Politics',
    title: 'Truth or Treason',
    description: 'You have information that could save lives — or get you executed.',
    prompt: '[Character Name] possesses information that could change the war — the true state of the wards, a venin weakness, a political conspiracy. Sharing it would save lives but violate classification, expose the source, or challenge the Empyrean\'s authority. Describe the weight of the knowledge, the people who would benefit, and the calculation: is the truth worth your life? Who do you tell, and how do you ensure the information survives if you don\'t?',
    icon: '⚡',
  },

  // ── Combat and Survival (7) ────────────────────────────────────────────────
  {
    id: 'emp-combat-ambush',
    category: 'Combat and Survival',
    title: 'Ambush Response',
    description: 'Your patrol is ambushed beyond the ward line. Roll initiative.',
    prompt: '[Character Name]\'s patrol is ambushed beyond the ward line. Describe the first moments: the attack comes from an unexpected direction, the dragons react before the riders do, and training kicks in — or doesn\'t. Detail the combatants (venin, wyverns, or corrupted wildlife), the terrain (it favors the attackers), and the critical decisions in the first thirty seconds. Someone is down. The formation is broken. What does [Character Name] do?',
    icon: '⚔️',
  },
  {
    id: 'emp-combat-defense',
    category: 'Combat and Survival',
    title: 'Outpost Defense',
    description: 'Defend a fortified position against overwhelming venin forces.',
    prompt: '[Character Name]\'s squad is assigned to defend an outpost near the ward line. The outpost has walls, basic supplies, and a wardstone — but it\'s undermanned and the relief force is hours away. A venin assault begins. Describe the preparation, the first wave (testing defenses), the second wave (pressing weaknesses), and the moment when the wardstone begins to flicker. The squad must hold. Describe the cost of holding.',
    icon: '🏰',
  },
  {
    id: 'emp-combat-recon',
    category: 'Combat and Survival',
    title: 'Solo Reconnaissance',
    description: 'Sent alone beyond the wards on a critical intelligence mission.',
    prompt: '[Character Name] is sent on a solo reconnaissance mission beyond the ward line — just them and their dragon. The objective: confirm intelligence about a suspected venin gathering point. Describe the flight over unprotected territory (the dragon\'s unease, the desolation below), the approach to the target, and what [Character Name] finds. It\'s worse than intelligence suggested. Now they must get the information back — but they\'ve been spotted.',
    icon: '🔭',
  },
  {
    id: 'emp-combat-retreat',
    category: 'Combat and Survival',
    title: 'Wounded Retreat',
    description: 'Fight a rearguard action while dragging an injured squadmate to safety.',
    prompt: 'The mission has gone wrong. A squadmate is seriously injured — cannot walk, cannot fly their dragon. [Character Name] must get them to safety while the enemy closes in. Describe the terrain (hostile, beyond the wards), the injured rider\'s condition (deteriorating), and the rearguard fight — buying time in short, brutal engagements while falling back toward the ward line. The dragon carries both riders, but the weight slows them. Every minute is a calculation.',
    icon: '🩹',
  },
  {
    id: 'emp-combat-dogfight',
    category: 'Combat and Survival',
    title: 'Aerial Dogfight',
    description: 'One-on-one dragon combat against a mounted wyvern rider.',
    prompt: '[Character Name] is separated from their squad and faces a single opponent: a venin mounted on a wyvern. One-on-one, dragon against wyvern, rider against dark wielder. Describe the aerial combat in visceral detail: the diving attacks, the fire exchanges, the wyvern\'s venom spray, the venin\'s dark wielding, and the moment-by-moment coordination between [Character Name] and their dragon. This fight is personal. Only one combatant is landing.',
    icon: '🐲',
  },
  {
    id: 'emp-combat-grounded',
    category: 'Combat and Survival',
    title: 'Grounded Combat',
    description: 'Separated from your dragon, fight with blade and signet only.',
    prompt: '[Character Name] is separated from their dragon — knocked from the saddle, cut off by terrain, or deliberately targeted. On the ground, without the dragon\'s proximity to amplify their signet, they are diminished. Describe the fight with blade, training, and fading signet power against an opponent who knows they\'re weakened. Include the ache of the stretched bond, the dragon\'s frantic attempts to reach them, and the desperate improvisation required to survive.',
    icon: '🗡️',
  },
  {
    id: 'emp-combat-last',
    category: 'Combat and Survival',
    title: 'Last Stand',
    description: 'The situation is hopeless. How does your character face it?',
    prompt: 'It\'s over. [Character Name] is outnumbered, outmatched, out of options. The squad is scattered or down. The dragon is injured. The enemy is closing. There is no rescue coming. Describe how [Character Name] faces the end — with defiance, with calm, with one last desperate gamble, or with a message sent through the bond to someone who matters. This is the moment that defines who they are. What happens may surprise them.',
    icon: '🌅',
  },

  // ── Meta and Narrative (5) ─────────────────────────────────────────────────
  {
    id: 'emp-meta-dragon-pov',
    category: 'Meta and Narrative',
    title: 'Dragon Perspective',
    description: 'Tell the next scene from your bonded dragon\'s point of view.',
    prompt: 'Narrate the next scene entirely from the dragon\'s perspective. Describe how the dragon perceives the world differently: infrared vision, scent-mapping, the vibration of the earth, the taste of the wind. Show how the dragon thinks about their rider — the affection tinged with exasperation, the protective instinct, the things they notice that the rider misses. The dragon should have opinions about the current situation and express them in their own way: terse, ancient, and slightly amused.',
    icon: '🐉',
  },
  {
    id: 'emp-meta-history',
    category: 'Meta and Narrative',
    title: 'Unreliable History',
    description: 'Reveal that official history contradicts what actually happened.',
    prompt: '[Character Name] encounters evidence — a document, a witness, an ancient rune inscription — that directly contradicts official Navarre history. What the textbooks say happened during the Reunification, the founding of Basgiath, or the origin of the venin threat is wrong. Describe the evidence, its implications, and [Character Name]\'s reckoning with the fact that they\'ve been taught lies. Who benefits from the false history? What does the truth mean for the present war?',
    icon: '📜',
  },
  {
    id: 'emp-meta-dream',
    category: 'Meta and Narrative',
    title: 'Prophetic Dream',
    description: 'A symbolic dream tied to the current threat.',
    prompt: '[Character Name] has a dream that feels too real to be ordinary. The imagery is symbolic: fire, falling, a door that won\'t open, a voice speaking in a language they shouldn\'t understand. The dragon is present in the dream — or conspicuously absent. Describe the dream in vivid, surreal detail, then the waking: the lingering feeling, the attempt to interpret the symbols, and the moment later in the day when something in the dream echoes in reality.',
    icon: '🌙',
  },
  {
    id: 'emp-meta-montage',
    category: 'Meta and Narrative',
    title: 'Training Montage',
    description: 'Fast-forward through weeks, summarizing key growth moments.',
    prompt: 'Summarize the next several weeks of [Character Name]\'s life at Basgiath in a montage: key training milestones (the day they finally mastered a formation, the sparring match that changed something), relationship shifts (a friendship deepening, a rivalry cooling, a glance that lasted too long), physical changes (stronger, more scarred, more confident), and one small, perfect moment of happiness amid the grind. End the montage with the event that breaks the routine.',
    icon: '⏩',
  },
  {
    id: 'emp-meta-codex',
    category: 'Meta and Narrative',
    title: 'Codex Entry',
    description: 'Create an in-universe document: journal, report, or wingleader\'s orders.',
    prompt: 'Create an in-universe document written by or about [Character Name]. Choose the format: a personal journal entry processing a recent event, an official intelligence report documenting an encounter, a wingleader\'s orders for an upcoming mission, a healer\'s medical notes after treating [Character Name]\'s injuries, or a scribe\'s classified assessment of [Character Name]\'s signet. The document should reveal information, advance character development, and feel authentically written by someone in the Empyrean world.',
    icon: '📝',
  },

  // ── Meta and Narrative — NEW (+10) ─────────────────────────────────────────
  {
    id: 'emp-meta-villain-pov',
    category: 'Meta and Narrative',
    title: 'Villain\'s Perspective',
    description: 'Narrate a scene from the antagonist\'s point of view.',
    prompt: 'Replay a recent scene — but narrated entirely from the antagonist\'s perspective. Show their reasoning, their frustrations, their fear of [Character Name] or [Character Name]\'s dragon. Reveal what the antagonist noticed that [Character Name] missed, and what they plan to do next. The antagonist should feel like a fully realized person with their own logic, not a cartoon villain. End with their assessment of [Character Name] as a threat — and it should be uncomfortably accurate.',
    icon: '🎭',
  },
  {
    id: 'emp-meta-scribe-account',
    category: 'Meta and Narrative',
    title: 'The Scribe\'s Account',
    description: 'A scribe NPC documents an event involving the character.',
    prompt: 'A scribe stationed at Basgiath is tasked with documenting an event involving [Character Name]. Write the scribe\'s account: formal, biased by limited perspective, and revealing in what it omits or misinterprets. The scribe has opinions about riders — perhaps admiration, resentment, or clinical detachment. Their account gets key details wrong in ways that would frustrate [Character Name] if they ever read it. Include marginal notes where the scribe editorializes.',
    icon: '✒️',
  },
  {
    id: 'emp-meta-campfire',
    category: 'Meta and Narrative',
    title: 'Campfire Recap',
    description: 'Characters retell the session\'s events around a fire — disagreeing.',
    prompt: '[Character Name] and their squadmates sit around a fire after a harrowing event, retelling what happened. Each person remembers it differently: one exaggerates their own heroics, another downplays the danger, someone insists a detail everyone else forgot is the most important part. The disagreements are funny, then revealing, then briefly tense when they touch on something real. End with the one thing everyone agrees on — and the one thing nobody says out loud.',
    icon: '🔥',
  },
  {
    id: 'emp-meta-what-if',
    category: 'Meta and Narrative',
    title: 'What If? Divergence',
    description: 'Replay a past decision with the opposite choice.',
    prompt: 'Take a significant decision [Character Name] made earlier in the campaign and replay it — but this time, they choose the opposite. Narrate the alternate outcome in full: who lives, who dies, what alliances form or shatter, how the ripple effects change everything. Then snap back to reality. [Character Name] sits with the knowledge of what could have been. Does the road they chose feel better or worse now? The dragon offers no comfort — just the steady hum of the bond.',
    icon: '🔀',
  },
  {
    id: 'emp-meta-bystander',
    category: 'Meta and Narrative',
    title: 'The Bystander',
    description: 'A civilian describes what they saw when riders clashed.',
    prompt: 'Tell the story of a recent event from the perspective of a bystander: a servant in the fortress, a groundskeeper on the flight field, a merchant in a nearby town, or a child watching from a window. They don\'t understand rider politics, signet powers, or dragon bonds. They see fire, hear shouting, feel the ground shake. Describe what [Character Name] looks like to someone who has no idea who they are — terrifying, magnificent, or just another soldier in a war they didn\'t choose.',
    icon: '👤',
  },
  {
    id: 'emp-meta-fourth-wall',
    category: 'Meta and Narrative',
    title: 'Fourth Wall Crack',
    description: 'The character briefly senses the player behind them.',
    prompt: '[Character Name] experiences a brief, uncanny moment of meta-awareness. Perhaps mid-conversation they pause, struck by the sensation of being observed — not by anyone in the room, but from somewhere outside the world entirely. The dragon feels it too: a ripple in the bond that has no source. The moment passes in seconds, leaving [Character Name] unsettled. They describe it to someone, who dismisses it. But the reader — the player — knows exactly what they felt.',
    icon: '👁️‍🗨️',
  },
  {
    id: 'emp-meta-post-credits',
    category: 'Meta and Narrative',
    title: 'Post-Credits Scene',
    description: 'A short epilogue from the future hinting at consequences.',
    prompt: 'Flash forward — weeks, months, or years from the current moment. Show a brief scene from [Character Name]\'s future: a scar they haven\'t earned yet, a title they don\'t yet hold, a person standing beside them who they haven\'t met. The scene is vivid but context-free — the player must piece together what it means. End on a single line of dialogue that recontextualizes something happening in the present. Then snap back to now. The future is earned, not given.',
    icon: '🎬',
  },
  {
    id: 'emp-meta-narrator-lies',
    category: 'Meta and Narrative',
    title: 'The Narrator Lies',
    description: 'The DM narrates a scene, then reveals a key detail was wrong.',
    prompt: 'Narrate a scene for [Character Name] as normal — a conversation, an arrival at a location, a quiet moment. Make it feel real and grounded. Then, partway through or at the end, reveal that one key detail was wrong. The person they were talking to wasn\'t who they appeared to be. The room had a door they didn\'t notice. The letter said something different than what was read aloud. Rewind and replay the scene with the true detail — watch how everything changes.',
    icon: '🃏',
  },
  {
    id: 'emp-meta-enemy-debrief',
    category: 'Meta and Narrative',
    title: 'Enemy Debrief',
    description: 'Venin commanders discuss the character as a tactical threat.',
    prompt: 'Scene: a venin war council, deep beyond the wards. Commanders — some still recognizably human, others far gone — discuss [Character Name] by name. They have intelligence: the signet type, the dragon breed, the squad composition, the psychological profile. They debate how to neutralize [Character Name]. Their assessment is clinical, respectful, and frightening in its accuracy. One commander proposes a plan. Another disagrees. The decision they reach should make the player deeply uncomfortable.',
    icon: '🗺️',
  },
  {
    id: 'emp-meta-parallel',
    category: 'Meta and Narrative',
    title: 'Parallel Lives',
    description: 'The same hour from two characters\' perspectives — paths almost crossing.',
    prompt: 'Show the same one-hour window from two perspectives: [Character Name] and someone else (a rival, a love interest, an unknown figure). Their paths almost cross — they\'re in the same building, on the same road, separated by a single wall or a few minutes. Each is dealing with their own crisis. The parallel structure reveals connections neither character sees: a shared enemy, a mutual ally acting as intermediary, or a decision one makes that unknowingly affects the other. They never meet in this scene.',
    icon: '⏳',
  },

  // ── Dragon Bond — NEW (+7) ─────────────────────────────────────────────────
  {
    id: 'emp-dragon-council',
    category: 'Dragon Bond',
    title: 'Dragon Council',
    description: 'Dragons gather without riders — a hierarchy negotiation.',
    prompt: '[Character Name]\'s dragon leaves without explanation. Through the bond, [Character Name] catches fragments: many dragons gathered, a heated exchange of impressions and dominance displays. The dragons are holding a council — no riders invited. [Character Name] experiences it secondhand: the hierarchy negotiations, the ancient protocols, the disputes between breeds. Their dragon\'s position in this hierarchy is tested. The bond transmits tension, pride, and something that feels like dragon politics. When the dragon returns, something has changed.',
    icon: '👑',
  },
  {
    id: 'emp-dragon-grooming',
    category: 'Dragon Bond',
    title: 'Grooming Ritual',
    description: 'Scale care, talon sharpening — the domesticity of dragon partnership.',
    prompt: 'A quiet afternoon: [Character Name] tends to their dragon. Describe the ritual — inspecting scales for damage, applying oil to dry patches, filing talon edges, checking wing membranes for tears. The dragon has preferences and opinions about the process: a ticklish spot behind the jaw, irritation when the tail is handled wrong, a rumbling purr when the neck ridge is scratched just right. This is the mundane reality of dragon partnership — intimate, physical, and strangely peaceful. The bond hums with contentment.',
    icon: '🪮',
  },
  {
    id: 'emp-dragon-ancient-memory',
    category: 'Dragon Bond',
    title: 'Ancient Memory',
    description: 'The dragon shares a memory from before Basgiath existed.',
    prompt: 'During a deep bond-meditation, the dragon opens a channel [Character Name] has never accessed before: ancestral memory. Not the dragon\'s own experience, but a memory passed down through bloodlines — from before Basgiath, before Navarre, before humans rode dragons at all. The vision is primordial: vast forests, erupting volcanoes, dragons hunting in packs across an unrecognizable landscape. Something in the memory is relevant to the present — a location, a creature, a warning. The dragon chose to share this now for a reason.',
    icon: '🏔️',
  },
  {
    id: 'emp-dragon-rivalry',
    category: 'Dragon Bond',
    title: 'Dragon Rivalry',
    description: 'Two bonded dragons despise each other — their riders must cooperate.',
    prompt: '[Character Name] is assigned to work closely with another rider whose dragon despises [Character Name]\'s dragon. The hatred is mutual, ancient, and breed-deep. Through the bond, [Character Name] feels their dragon\'s hostility as a constant low burn. The riders must cooperate on a mission while their dragons snarl, posture, and sabotage each other\'s positioning in the air. Describe the challenge of maintaining professionalism while your soul-bonded partner is radiating contempt at your colleague\'s soul-bonded partner.',
    icon: '😤',
  },
  {
    id: 'emp-dragon-feeding',
    category: 'Dragon Bond',
    title: 'Feeding Day',
    description: 'Accompany your dragon on a hunt — witness the predator within.',
    prompt: '[Character Name] accompanies their dragon on a hunt — not the sanitized feeding pens at Basgiath, but a real hunt in the wild. Through the bond, [Character Name] experiences the dragon\'s predator instincts: the tracking, the patience, the explosive violence of the kill. The dragon is something other than a partner in this moment — ancient, alien, and terrifyingly efficient. [Character Name] sees their gentle companion tear apart prey with casual precision. The bond carries the dragon\'s satisfaction. It tastes like iron.',
    icon: '🦌',
  },
  {
    id: 'emp-dragon-humor',
    category: 'Dragon Bond',
    title: 'Dragon Humor',
    description: 'The dragon does something deliberately funny — alien but unmistakable.',
    prompt: '[Character Name]\'s dragon does something unexpected: something deliberately, unmistakably funny. Dragon humor is alien — it might be perfectly timed physical comedy (a tail-sweep at an annoying person), a sardonic impression sent through the bond, or an elaborate prank involving fire and someone\'s laundry. The dragon\'s amusement radiates through the bond: a deep, rumbling satisfaction. [Character Name] is caught between mortification and helpless laughter. Other riders stare. The dragon is pleased with itself.',
    icon: '😏',
  },
  {
    id: 'emp-dragon-den',
    category: 'Dragon Bond',
    title: 'Den Visit',
    description: 'Enter the dragon\'s private den — what it reveals about their inner world.',
    prompt: '[Character Name]\'s dragon invites them into their private den for the first time. This is significant — dragons are territorial about their sleeping spaces. Describe what [Character Name] finds inside: the arrangement of the space, objects the dragon has collected (shiny things, trophies from hunts, something stolen from a rider they dislike), the temperature, the smell, the way the dragon watches [Character Name] explore their space. The den reveals something about the dragon\'s personality that the bond never communicated directly. It\'s unexpectedly moving.',
    icon: '🏠',
  },

  // ── Signet Abilities — NEW (+7) ────────────────────────────────────────────
  {
    id: 'emp-signet-resonance',
    category: 'Signet Abilities',
    title: 'Signet Resonance',
    description: 'Two signets react to proximity — harmonic amplification.',
    prompt: '[Character Name] stands near another rider and both signets activate spontaneously — not in conflict, but in resonance. The combined effect is something neither rider can produce alone: a harmonic amplification that warps the air, shifts the light, or briefly touches something beyond normal signet reach. Describe the sensation (it\'s intoxicating and dangerous), the other rider\'s reaction, and the aftermath. Professors will want to study this. Someone else will want to weaponize it. The dragon has an opinion.',
    icon: '🔊',
  },
  {
    id: 'emp-signet-oath',
    category: 'Signet Abilities',
    title: 'Signet Under Oath',
    description: 'Forced to use your signet for an official tribunal.',
    prompt: '[Character Name] is ordered to demonstrate their signet before a tribunal — either as evidence in a disciplinary hearing, a loyalty assessment, or a capability evaluation for a sensitive mission. Using power under observation, on command, feels different than using it in combat. Describe the formality of the setting, the evaluators\' clinical attention, and the vulnerability of being examined. The signet responds to [Character Name]\'s emotional state — and right now, that state is complicated. What the tribunal sees may not be the whole truth.',
    icon: '⚖️',
  },
  {
    id: 'emp-signet-null',
    category: 'Signet Abilities',
    title: 'Null Zone',
    description: 'Enter an area where signets don\'t work — sudden powerlessness.',
    prompt: '[Character Name] enters an area where signets simply stop working. No warning, no gradual fade — just sudden, absolute absence. Describe the disorientation: the phantom reach for power that isn\'t there, the vulnerability, the way it changes [Character Name]\'s body language and confidence. The dragon\'s bond is muted too — still present, but whisper-thin. In this zone, [Character Name] must rely on blade, wits, and training alone. Describe what happens when a signet-dependent rider is stripped to baseline — and what it reveals about who they are without power.',
    icon: '🚫',
  },
  {
    id: 'emp-signet-inheritance',
    category: 'Signet Abilities',
    title: 'Signet Inheritance',
    description: 'Your signet matches a dead relative\'s — the weight of repetition.',
    prompt: '[Character Name] learns that their signet is identical — not similar, identical — to a relative who died. A parent, a grandparent, an ancestor whose story ended badly. The professors exchange glances. The family records are pulled. Describe the weight of inheriting a power that killed someone before, the comparisons that begin immediately, and the question nobody asks out loud: will the same fate apply? The dead relative\'s dragon is still alive. It visits [Character Name]\'s dragon. The bond carries a secondhand grief that isn\'t [Character Name]\'s own.',
    icon: '🪦',
  },
  {
    id: 'emp-signet-weaponize',
    category: 'Signet Abilities',
    title: 'Signet Weaponization',
    description: 'Command orders creative weaponization — moral discomfort.',
    prompt: 'A commanding officer pulls [Character Name] aside with a "creative application" for their signet — something the textbooks don\'t cover and the ethics lectures would prohibit. The application is militarily brilliant and morally uncomfortable. Describe the order, [Character Name]\'s internal conflict, the execution (or refusal), and the consequences. If they comply, the results are effective and haunting. If they refuse, the political fallout is immediate. The dragon\'s opinion through the bond is clear but unhelpful.',
    icon: '🎯',
  },
  {
    id: 'emp-signet-bleed',
    category: 'Signet Abilities',
    title: 'Signet Bleed',
    description: 'The signet activates during sleep — unconscious power.',
    prompt: '[Character Name] wakes to discover their signet activated while they slept. The evidence is around them: scorched sheets, frozen air, objects moved or transformed, a terrified roommate, or wards triggered in the night. The dragon felt it happen and couldn\'t stop it. Describe the disorientation of waking to the aftermath, the struggle to reconstruct what the unconscious mind was doing with the power, and the unsettling realization: the signet has a will of its own when the conscious mind lets go. This will happen again.',
    icon: '😴',
  },
  {
    id: 'emp-signet-duel',
    category: 'Signet Abilities',
    title: 'Signet Duel',
    description: 'Formal signet-only combat — no blades, no dragons, pure power.',
    prompt: '[Character Name] is challenged to — or challenges someone to — a formal signet duel. The rules are ancient: no physical weapons, no dragon assistance, pure signet against signet in a warded arena. Describe the preparation (studying the opponent\'s signet type, planning counters), the opening exchange, the mid-duel adaptation when the opponent reveals a capability [Character Name] didn\'t expect, and the decisive moment. Win or lose, both riders walk away changed. The watching crowd includes someone who is taking very careful notes.',
    icon: '💥',
  },

  // ── Basgiath War College — NEW (+7) ────────────────────────────────────────
  {
    id: 'emp-basgiath-night-exam',
    category: 'Basgiath War College',
    title: 'Night Exam',
    description: 'A surprise midnight test — evaluated half-asleep.',
    prompt: 'Three sharp knocks on the door at midnight. An instructor stands in the corridor with a lantern and a clipboard. [Character Name] has sixty seconds to dress and report. The exam is designed to test performance under exhaustion: tactical decisions made half-awake, combat reflexes at their lowest, and the ability to function when the mind screams for sleep. Describe the stumbling start, the gradual sharpening of focus, and the moment [Character Name] either rises to the challenge or makes a mistake that will follow them for weeks.',
    icon: '🌙',
  },
  {
    id: 'emp-basgiath-transfer',
    category: 'Basgiath War College',
    title: 'New Transfer',
    description: 'A transfer rider arrives mid-year — disrupts squad dynamics.',
    prompt: 'A new rider transfers into [Character Name]\'s squad mid-year — unprecedented and suspicious. They come from another wing, another posting, or a program nobody talks about. Their skills are sharp but their social integration is nonexistent. The squad must absorb this newcomer while wondering: are they a spy, a punishment, a replacement for someone, or genuinely displaced? Describe the first training session together, the mess hall interrogation, and the moment the transfer reveals — deliberately or accidentally — why they\'re really here.',
    icon: '🆕',
  },
  {
    id: 'emp-basgiath-instructor-secret',
    category: 'Basgiath War College',
    title: 'Instructor\'s Secret',
    description: 'A professor reveals something personal that reframes everything.',
    prompt: 'A professor whom [Character Name] has known only as an authority figure lets something slip — after a late training session, in an unguarded moment, or during a crisis where rank formalities dissolve. What they reveal is personal: a past failure, a lost bond, a secret about the war, or a reason they teach instead of fight. It reframes every interaction [Character Name] has had with them. Describe the moment of revelation, [Character Name]\'s reaction, and the unspoken agreement about whether this knowledge is shared or kept.',
    icon: '🤐',
  },
  {
    id: 'emp-basgiath-infirmary',
    category: 'Basgiath War College',
    title: 'Infirmary Recovery',
    description: 'Extended stay in the healers\' ward — vulnerability and overheard secrets.',
    prompt: '[Character Name] is confined to the infirmary for extended recovery — injured enough that the healers won\'t release them. Describe the frustration of immobility, the bond stretched thin with the dragon outside, and the unexpected advantage: the infirmary is where secrets travel. Healers talk, injured riders mutter in drugged sleep, and visitors reveal things in the assumed privacy of a sickbed. [Character Name] overhears something they shouldn\'t. Meanwhile, someone visits who [Character Name] didn\'t expect — and the visit matters more than the information.',
    icon: '🏥',
  },
  {
    id: 'emp-basgiath-graduation',
    category: 'Basgiath War College',
    title: 'Graduation Pressure',
    description: 'Final evaluations loom — everything rides on performance.',
    prompt: 'Final evaluations are approaching. The weight of every choice, every training score, every political ally and enemy made at Basgiath now converges on a series of tests that will determine [Character Name]\'s posting, rank, and future. Describe the preparation: the late-night studying, the last sparring sessions, the quiet conversations with squadmates about what comes after. Include the moment of doubt — the fear that all of it wasn\'t enough. The dragon sends steady confidence through the bond. Whether it\'s earned confidence or comforting lies is unclear.',
    icon: '🎓',
  },
  {
    id: 'emp-basgiath-black-market',
    category: 'Basgiath War College',
    title: 'Underground Economy',
    description: 'Discover the cadet black market — contraband, favors, debts.',
    prompt: '[Character Name] is introduced to Basgiath\'s unofficial economy: a network of cadets who trade contraband (restricted texts, smuggled food, weapons modifications, signet-dampening herbs), favors (test answers, patrol swaps, introduction to useful people), and debts (the currency that really runs the college). Describe the hidden market, the broker who runs it, and the price of entry. What does [Character Name] need badly enough to deal? And what do they have that the market wants? The first transaction is free. The second never is.',
    icon: '💰',
  },
  {
    id: 'emp-basgiath-riot',
    category: 'Basgiath War College',
    title: 'Quadrant Riot',
    description: 'Tensions between quadrants erupt into campus-wide unrest.',
    prompt: 'It starts with a single incident — an insult, a death, a policy announcement — and within hours, Basgiath is in chaos. Riders against scribes, infantry against everyone, healers barricading their wing. Describe the escalation from tension to violence, [Character Name]\'s position in the middle of it, and the impossible choices: protect your quadrant or protect your cross-quadrant friends? Fight or mediate? The dragons are agitated — their riders\' fury bleeds through dozens of bonds simultaneously. Describe how order is — or isn\'t — restored.',
    icon: '🔥',
  },

  // ── Venin and Dark Forces — NEW (+7) ───────────────────────────────────────
  {
    id: 'emp-venin-trap',
    category: 'Venin and Dark Forces',
    title: 'Venin Trap',
    description: 'An ambush designed specifically for your signet type.',
    prompt: 'The venin have been studying [Character Name]. The ambush isn\'t random — it\'s engineered to counter [Character Name]\'s specific signet. Describe the moment of realization: the terrain that neutralizes their power, the positioning that isolates them from the squad, the venin who demonstrates knowledge of [Character Name]\'s fighting patterns. Someone has been feeding them intelligence. The trap is elegant, personal, and nearly lethal. Escaping requires [Character Name] to fight in a way they\'ve never been trained for — improvisation against preparation.',
    icon: '🕸️',
  },
  {
    id: 'emp-venin-turned-friend',
    category: 'Venin and Dark Forces',
    title: 'The Turned Friend',
    description: 'A rider who turned venin tries to recruit you with memories.',
    prompt: '[Character Name] comes face to face with someone they knew — a former classmate, a graduated rider, someone who was reported killed in action. They\'re venin now. But they\'re lucid, articulate, and they remember everything: shared jokes, training sessions, the name of [Character Name]\'s dragon. They don\'t attack. They talk. They explain why they turned, what they\'ve seen, what the venin really are. Their pitch is terrifyingly reasonable. The corruption is visible but the person inside is still recognizable. That makes it so much worse.',
    icon: '💔',
  },
  {
    id: 'emp-venin-corruption-creep',
    category: 'Venin and Dark Forces',
    title: 'Corruption Creep',
    description: 'Strange dreams, darkening veins — is it the environment or worse?',
    prompt: '[Character Name] has been having strange dreams — grey landscapes, whispered invitations, the taste of power that isn\'t theirs. They notice a darkening in the veins of their forearm, faint enough to be a shadow in the wrong light. Their signet feels different — stronger, but with a resonance that wasn\'t there before. Describe the mounting paranoia: is this corruption from too much time beyond the wards, a signet evolution, or the first signs of turning? The dragon monitors the bond obsessively. [Character Name] doesn\'t tell anyone. Not yet.',
    icon: '🩸',
  },
  {
    id: 'emp-venin-nest',
    category: 'Venin and Dark Forces',
    title: 'Venin Nest',
    description: 'Discover a breeding ground — the scale of the enemy revealed.',
    prompt: '[Character Name]\'s squad discovers something that isn\'t in any intelligence briefing: a venin nest. Not a camp, not a gathering point — a place where venin are made, where the corruption is cultivated and spread deliberately. The scale is staggering: dozens of victims in various stages of turning, wyvern eggs incubating in dark-wielded heat, and infrastructure that suggests this has been operating for years. Describe the horror, the strategic implications, and the impossible question: destroy it now with the resources at hand, or withdraw and report, knowing it might move?',
    icon: '🕳️',
  },
  {
    id: 'emp-venin-dark-witness',
    category: 'Venin and Dark Forces',
    title: 'Dark Wielding Witness',
    description: 'Watch an ally secretly use dark wielding "for the right reasons."',
    prompt: '[Character Name] witnesses something they were never meant to see: an ally — someone trusted, someone respected — drawing on dark wielding. Not in desperation, but deliberately, with practiced control. They\'re using it for a purpose that seems righteous: healing someone beyond normal means, strengthening a failing wardstone, killing a venin that conventional power couldn\'t touch. The result is effective. The cost is visible in the dark veins that fade slowly afterward. The ally sees [Character Name] watching. The silence between them is the loudest sound in the world.',
    icon: '🌑',
  },
  {
    id: 'emp-venin-wyvern-taming',
    category: 'Venin and Dark Forces',
    title: 'Wyvern Taming',
    description: 'Someone claims wyverns can be turned — and wants help proving it.',
    prompt: 'A researcher — either a rogue scribe or a rider with too much curiosity — approaches [Character Name] with a theory: wyverns aren\'t inherently corrupted. They can be turned back. The evidence is thin but compelling: a captured wyvern that responds to kindness, historical texts suggesting wyverns existed before venin did, and a method that\'s untested and potentially suicidal. The researcher needs [Character Name]\'s dragon to attempt communication. Describe the experiment, the wyvern\'s response, and the implications if the theory is even partially right. Everything Basgiath teaches about wyverns would be wrong.',
    icon: '🦅',
  },
  {
    id: 'emp-venin-sage',
    category: 'Venin and Dark Forces',
    title: 'The Sage Venin',
    description: 'Encounter an ancient venin who remembers being human — and grieves.',
    prompt: '[Character Name] encounters a venin unlike any other: ancient, powerful, and sane. This venin remembers their name, their dragon\'s name, the year they graduated from Basgiath — centuries ago. They remember being human, and they grieve it with a lucidity that makes the corruption seem even more horrifying. They don\'t attack. They want to talk — about what it\'s like to live this long as something wrong, about the others who\'ve lost their minds, about a secret they\'ve carried since before the current war began. What they reveal could change everything. Their only request: remember my name.',
    icon: '🧓',
  },

  // ── Relationships and Politics — NEW (+7) ──────────────────────────────────
  {
    id: 'emp-rel-ex',
    category: 'Relationships and Politics',
    title: 'The Ex',
    description: 'Someone from before Basgiath shows up — old feelings, new complications.',
    prompt: 'Someone from [Character Name]\'s life before Basgiath appears — a former partner, a childhood sweetheart, a friend who became something more. They\'re here now: as a new conscript, a visiting dignitary, a scribe transfer, or a prisoner. The old feelings collide with the new reality. [Character Name] is different now — bonded, powerful, changed by what they\'ve survived. The person from before knew who [Character Name] used to be, and they\'re not sure they like who [Character Name] has become. The conversation they need to have keeps getting interrupted.',
    icon: '💫',
  },
  {
    id: 'emp-rel-marriage',
    category: 'Relationships and Politics',
    title: 'Political Marriage',
    description: 'A strategic alliance proposal through marriage — love vs. duty.',
    prompt: 'A proposal arrives — not romantic, but political. A marriage that would cement an alliance between families, wings, or factions within the Empyrean. The intended partner may be a stranger, an acquaintance, or someone [Character Name] has complicated feelings about. Describe the proposal (who benefits, what\'s at stake), [Character Name]\'s reaction, the pressure from family or command to accept, and the person they\'d have to give up or set aside. The dragon\'s opinion is characteristically blunt. Love and duty stand on opposite sides of the room.',
    icon: '💍',
  },
  {
    id: 'emp-rel-squad-fracture',
    category: 'Relationships and Politics',
    title: 'Squad Fracture',
    description: 'Your squad splits over an ideological disagreement — pick a side.',
    prompt: '[Character Name]\'s squad fractures over something fundamental: how to treat captured venin, whether to follow orders they believe are wrong, loyalty to a disgraced leader, or a secret that divides them into those who know and those who don\'t. The split isn\'t clean — friends end up on opposite sides. Describe the argument that breaks them, the aftermath (cold shoulders, separate mess hall tables, training exercises charged with resentment), and [Character Name]\'s attempt to bridge or widen the gap. Some fractures heal stronger. Some don\'t heal at all.',
    icon: '💔',
  },
  {
    id: 'emp-rel-mentor-fall',
    category: 'Relationships and Politics',
    title: 'Mentor\'s Fall',
    description: 'A trusted mentor is disgraced — stand by them or distance yourself.',
    prompt: 'A person [Character Name] trusted and admired — a professor, a senior rider, a wingleader — is publicly disgraced. The accusation may be true, false, or complicated. Basgiath\'s hierarchy moves quickly: the mentor\'s allies scatter, their enemies circle, and everyone watches to see who stands by them. [Character Name] must decide: public loyalty (and share the taint of association), quiet distance (and live with the cowardice), or investigation (and risk discovering a truth worse than the accusation). The mentor sends a message through unofficial channels. It says one word.',
    icon: '📉',
  },
  {
    id: 'emp-rel-enemy-respect',
    category: 'Relationships and Politics',
    title: 'Enemy Respect',
    description: 'A rival earns genuine respect through an act of courage.',
    prompt: '[Character Name]\'s rival — someone they\'ve clashed with, despised, or deliberately avoided — does something undeniably brave. It might save [Character Name]\'s life, protect someone vulnerable, or cost the rival dearly with no personal gain. The act is witnessed. Denying its courage would be dishonest. Describe the event, [Character Name]\'s reluctant admiration, and the awkward interaction that follows. The rivalry doesn\'t end — but it changes shape. It\'s harder to hate someone you respect. The rival seems equally uncomfortable with the new dynamic.',
    icon: '🤝',
  },
  {
    id: 'emp-rel-correspondence',
    category: 'Relationships and Politics',
    title: 'Secret Correspondence',
    description: 'Intercepted letters reveal a conspiracy — who do you warn?',
    prompt: '[Character Name] intercepts — or is given — a series of letters that reveal a conspiracy within Basgiath. The correspondents are people with power, and the conspiracy could be anything: suppressing ward failure reports, arranging "accidents" for inconvenient riders, negotiating with the enemy, or covering up signet experiments. The letters don\'t name everyone involved — some are referenced by codename. [Character Name] recognizes one of them. Describe the decision: who to trust with this information, how to verify it, and the danger of being discovered holding evidence that powerful people want destroyed.',
    icon: '✉️',
  },
  {
    id: 'emp-rel-favor',
    category: 'Relationships and Politics',
    title: 'The Favor Owed',
    description: 'Someone powerful calls in a debt — the price is higher than expected.',
    prompt: 'A debt comes due. Someone powerful — a wingleader, a political figure, a shadowy ally — once did [Character Name] a significant favor. Now they want payment, and the price is higher than expected. It might be information, a betrayal of trust, a dangerous mission presented as "a small thing," or silence about something [Character Name] witnessed. Describe the meeting where the debt is called, the negotiation (is there room to bargain?), and [Character Name]\'s calculation: pay the price, refuse and face consequences, or find a third option that satisfies no one but preserves their integrity.',
    icon: '📜',
  },

  // ── Combat and Survival — NEW (+7) ─────────────────────────────────────────
  {
    id: 'emp-combat-night-raid',
    category: 'Combat and Survival',
    title: 'Night Raid',
    description: 'Black-ops sabotage behind enemy lines — stealth, no dragons.',
    prompt: '[Character Name] volunteers or is selected for a night raid: a small team, no dragons (too visible), deep behind enemy lines. The objective is sabotage — destroy a supply cache, collapse a tunnel, assassinate a venin commander, or plant false intelligence. Describe the insertion (how they get there without dragons), the approach (silence, darkness, the fear of discovery), the execution (something goes wrong — it always does), and the extraction. Include the disorienting experience of operating without the dragon bond\'s safety net. The walk back is the longest walk of their life.',
    icon: '🌑',
  },
  {
    id: 'emp-combat-siege',
    category: 'Combat and Survival',
    title: 'Siege Warfare',
    description: 'Multi-day siege of a warded fortress — attrition and morale.',
    prompt: '[Character Name] is part of a force besieging a fortified position — or defending one. The siege lasts days. Describe the grinding attrition: rationed food, sleep in shifts, the wardstones flickering as they\'re tested by sustained assault. Morale erodes. Injuries accumulate. The dragons are exhausted from repeated sorties. On the third day, describe the breaking point: a wall falls, a wardstone fails, a betrayal from within, or a relief force that arrives too late or just in time. Siege warfare is not glorious — it\'s endurance, and the victory tastes like ash.',
    icon: '🏰',
  },
  {
    id: 'emp-combat-honor-duel',
    category: 'Combat and Survival',
    title: 'Honor Duel',
    description: 'Formal challenge with witnesses — reputation and rank on the line.',
    prompt: 'A formal challenge is issued — by [Character Name] or against them. The duel follows ancient rider protocol: witnesses from both wings, seconds who verify the terms, and a combat space cleared and warded. The stakes are specific: rank, a disputed command decision, an insult to a dragon, or a personal grievance too serious for the mess hall. Describe the preparation (choosing weapons, consulting the dragon, studying the opponent), the duel itself (three exchanges that tell a story), and the aftermath. The winner gains more than rank. The loser learns something they needed to know.',
    icon: '⚔️',
  },
  {
    id: 'emp-combat-false-flag',
    category: 'Combat and Survival',
    title: 'False Flag',
    description: 'Ordered to stage an attack disguised as the enemy — ethical combat.',
    prompt: '[Character Name] receives orders for a false flag operation: attack a target while appearing to be the enemy. The tactical rationale is sound — provoke a response, shift blame, create a pretext for escalation. The ethical reality is nauseating. Describe the briefing (clinical, efficient, devoid of moral language), the mission preparation (disguises, altered tactics, the wrongness of it), and the execution. Include the moment [Character Name] sees the faces of the people who believe the false flag — and the drive back in silence. The dragon\'s opinion is a wall of cold disapproval.',
    icon: '🏴‍☠️',
  },
  {
    id: 'emp-combat-multi-wing',
    category: 'Combat and Survival',
    title: 'Multi-Wing Assault',
    description: 'Coordinated attack across three wings — large-scale aerial chaos.',
    prompt: 'The largest operation [Character Name] has ever been part of: three wings, dozens of dragons, a coordinated assault on a major venin position. The scale is overwhelming — the sky is full of fire, the ground shakes with impacts, and the communication system is overloaded. Describe [Character Name]\'s assigned role in the larger battle, the moment their section of the plan goes sideways, the improvised coordination with riders they\'ve never met, and the aerial view of the battle from above — beautiful and horrifying in equal measure. War at scale is not personal. It\'s industrial.',
    icon: '🦅',
  },
  {
    id: 'emp-combat-assassination',
    category: 'Combat and Survival',
    title: 'Assassination Attempt',
    description: 'Someone tries to kill the character — not in battle, but in their sleep.',
    prompt: '[Character Name] wakes to danger. Not an alarm, not a battle — someone is in their room, and they are not friendly. The assassination attempt is professional: timed to avoid patrols, designed to look like natural death or an accident, and executed by someone who knows [Character Name]\'s habits. Describe the first seconds of awareness, the fight in darkness and confined space, and the pursuit or aftermath. The assassin escapes — or doesn\'t — but either way leaves evidence of who sent them. The dragon felt the spike of terror through the bond and is destroying the outer wall to reach them.',
    icon: '🗡️',
  },
  {
    id: 'emp-combat-no-magic',
    category: 'Combat and Survival',
    title: 'No-Magic Zone',
    description: 'Combat in a signet-dead zone — pure blade and tactics.',
    prompt: '[Character Name] fights in a zone where signets are completely nullified — whether by ancient wards, environmental interference, or deliberate enemy action. No signet, no dragon amplification, no power shortcuts. Just steel, footwork, and everything the combat instructors drilled into them during first year. Describe the adjustment: the instinctive reach for power that isn\'t there, the rediscovery of physical combat fundamentals, and the opponent who chose this ground because they excel without magic. Victory here is earned with muscle and blade — the oldest way.',
    icon: '🛡️',
  },

  // ── Forbidden Lore (9) ────────────────────────────────────────────────────
  {
    id: 'emp-lore-cipher',
    category: 'Forbidden Lore',
    title: 'Cipher Text',
    description: 'Coded journal describing signet abilities the college claims don\'t exist.',
    prompt: '[Character Name] finds a coded journal hidden in an unlikely place — behind a loose stone, inside a dragon saddle, or tucked into a book of mundane regulations. The cipher is complex but partially cracked by a previous reader who left margin notes. As [Character Name] decodes the text, it describes signet abilities the college explicitly denies exist — abilities that sound disturbingly similar to venin powers. The journal\'s author was a rider. The last entry is unfinished, mid-sentence, as if they were interrupted. The margin notes are in a different hand and say only: "They know you have this."',
    icon: '🔐',
  },
  {
    id: 'emp-lore-burned',
    category: 'Forbidden Lore',
    title: 'The Burned History',
    description: 'Dragon reveals riders destroyed a civilization and erased the records.',
    prompt: '[Character Name]\'s dragon shares something unbidden through the bond — not words, but a cascade of ancient images. Cities burning. Riders on dragonback raining fire on a civilization that is clearly not venin. People screaming in a language [Character Name] doesn\'t recognize. The dragon\'s ancestral memory is clear: riders destroyed this civilization, then erased every record of its existence. The college teaches that dragons have always fought venin. This memory says otherwise. The dragon offers no judgment — only the truth, and the question of what [Character Name] will do with it.',
    icon: '🔥',
  },
  {
    id: 'emp-lore-thesis',
    category: 'Forbidden Lore',
    title: 'Forbidden Thesis',
    description: 'Dead scholar\'s research proves signet-venin connection — suppressed by the college.',
    prompt: '[Character Name] obtains a thesis written by a scholar who died under suspicious circumstances. The research is meticulous, spanning decades: signets and venin powers share the same magical origin. The difference is not the source but the method of channeling. The implications are staggering — every rider carries the potential to become venin, and the college knows it. The thesis was submitted for review and immediately classified. The scholar died two weeks later. "Natural causes." [Character Name] must decide: share this, hide it, or investigate the scholar\'s death.',
    icon: '📄',
  },
  {
    id: 'emp-lore-memory-stone',
    category: 'Forbidden Lore',
    title: 'Memory Stone',
    description: 'Artifact plays back a centuries-old scene that contradicts official history.',
    prompt: '[Character Name] touches an ancient stone — a wardstone fragment, a relic in a forgotten chamber, or an artifact given by a dying rider — and is pulled into a vision. The scene is centuries old: a meeting of the original Empyrean founders. They are arguing. One faction wants to tell the truth about the wards\' limitations. The other insists on secrecy "for the good of Navarre." The vote is close. Secrecy wins by a single voice. The face of the dissenter is familiar — an ancestor, perhaps, or a figure from a portrait in Basgiath\'s halls. The stone cracks after showing its truth, as if it was waiting for the right person.',
    icon: '💎',
  },
  {
    id: 'emp-lore-heretic-map',
    category: 'Forbidden Lore',
    title: 'The Heretic\'s Map',
    description: 'Map showing locations beyond the wards the college insists are uninhabitable.',
    prompt: '[Character Name] discovers a hand-drawn map that shouldn\'t exist. It shows locations beyond the ward line — not the grey wasteland the college describes, but settlements, trade routes, and landmarks. Annotations in faded ink describe people living beyond the wards: communities that adapted, formed alliances, developed their own defenses. The college teaches that nothing survives beyond the wards. This map says entire cultures thrive there. One location is circled repeatedly with a note: "They have answers we\'ve been afraid to ask." Getting there would mean going AWOL.',
    icon: '🗺️',
  },
  {
    id: 'emp-lore-living-doc',
    category: 'Forbidden Lore',
    title: 'Living Document',
    description: 'Text rewrites itself based on reader\'s signet — personalized truths.',
    prompt: '[Character Name] opens an ancient text and watches the ink move. The words rearrange themselves as they read, responding to [Character Name]\'s signet — the document is alive in some magical sense, calibrated to reveal different truths to different wielders. What it shows [Character Name] is personal and disturbing: details about their specific signet that no one has ever explained, a warning about a path they\'re already walking, and a prediction about what they\'ll become if they don\'t change course. When another person looks at the same page, they see entirely different text. The document cannot be copied — ink slides off any attempt to transcribe it.',
    icon: '📝',
  },
  {
    id: 'emp-lore-price',
    category: 'Forbidden Lore',
    title: 'The Price of Knowing',
    description: 'Learn something so dangerous that knowing it makes you a target.',
    prompt: 'Someone — a dying rider, a captured venin, a rogue scribe — tells [Character Name] something they cannot unhear. A single piece of information so dangerous that everyone who has ever learned it has been silenced. Describe what the information is (it should fundamentally challenge the power structure of Navarre), the moment [Character Name] realizes the weight of what they now know, and the immediate consequences: the teller dies or disappears, someone was watching, and [Character Name] notices they are being followed within hours. The knowledge cannot be unlearned. The only question is what to do with it before someone ensures their silence.',
    icon: '⚠️',
  },
  {
    id: 'emp-lore-oral',
    category: 'Forbidden Lore',
    title: 'Oral Tradition',
    description: 'Gryphon rider shares knowledge never written down — on purpose.',
    prompt: 'A gryphon rider from Poromiel — encountered during a joint operation, a diplomatic meeting, or a chance encounter — offers to share something with [Character Name]. Not a document, not a book. A story, passed mouth to mouth for generations, never written down because written things can be found and burned. The story describes events that both Navarre and Poromiel have erased from their histories: a time when dragon riders and gryphon riders worked together against a threat that was neither venin nor human. The gryphon rider finishes and says: "Now you carry it too. Choose the next person carefully."',
    icon: '🦅',
  },
  {
    id: 'emp-lore-redacted',
    category: 'Forbidden Lore',
    title: 'The Redacted Name',
    description: 'Every record of a specific rider erased — find out why.',
    prompt: '[Character Name] notices an absence. In the records of a particular graduating class, one name has been removed from every document — class rolls, training records, achievement lists, even group photographs have been physically altered. The erasure is thorough but not perfect: a signature on a shared project, an initial carved into a desk, a reference in someone else\'s personal journal. Piecing together the fragments reveals a rider who was exceptional — perhaps the most powerful of their generation — and then simply ceased to exist in the official record. What did they do? What did they discover? And why is someone still actively maintaining the erasure, decades later?',
    icon: '✂️',
  },
];

export const empyreanPromptCategories = [
  'Dragon Bond',
  'Signet Abilities',
  'Basgiath War College',
  'Venin and Dark Forces',
  'Relationships and Politics',
  'Combat and Survival',
  'Meta and Narrative',
  'Forbidden Lore',
] as const;

export type EmpyreanPromptCategory = typeof empyreanPromptCategories[number];
