// Empyrean Series — 50 Prompt Templates for 3rd-party AI DMs
// Uses the same CharacterPrompt interface as characterPrompts.ts

import type { CharacterPrompt } from './characterPrompts';

export const empyreanPrompts: CharacterPrompt[] = [
  // ── Dragon Bond (8) ────────────────────────────────────────────────────────
  {
    id: 'emp-dragon-conscription',
    category: 'Dragon Bond',
    title: 'First Conscription Day',
    description: 'Arrive at Basgiath and face the parapet crossing.',
    prompt: '[Character Name] arrives at Basgiath War College for Conscription Day. Describe the journey to the fortress, the first sight of the Cliffs of Dralor, and the moment they must cross the parapet — a crumbling stone bridge with no railings over a lethal drop. Other conscripts are ahead and behind. Some fall. The wind is vicious. Describe the physical sensation, the fear, and what [Character Name] sees on the other side.',
    icon: '🏔️',
  },
  {
    id: 'emp-dragon-threshing',
    category: 'Dragon Bond',
    title: 'Dragon Presentation',
    description: 'Stand before unbonded dragons during Threshing.',
    prompt: '[Character Name] enters the Threshing field — a vast, open area where unbonded dragons wait. The air smells of sulfur and ozone. Dragons of varying sizes and breeds observe the candidates with ancient, appraising eyes. Describe the approach, the dragons\' reactions to [Character Name] specifically, and the moment a bond either forms or is rejected. Include the physical sensation of the telepathic connection igniting for the first time.',
    icon: '🐉',
  },
  {
    id: 'emp-dragon-bonding',
    category: 'Dragon Bond',
    title: 'Bond Deepening',
    description: 'A quiet moment strengthening the mental link with your dragon.',
    prompt: '[Character Name] finds a quiet moment with their bonded dragon — perhaps at dawn on the flight field, or in the dragon\'s den after a long day. The telepathic link is still new and developing. Describe the attempt to communicate more deeply: sharing a memory, trying to understand the dragon\'s emotions, or simply sitting in the warmth of the bond. Include what the dragon communicates back — not in human words, but in impressions, images, and ancient feeling.',
    icon: '💫',
  },
  {
    id: 'emp-dragon-flight',
    category: 'Dragon Bond',
    title: 'Aerial Combat Training',
    description: 'Practice formations and fire commands in flight.',
    prompt: '[Character Name] is in the air with their squad for aerial combat training. The instructor calls formations from the ground using signal flags. Describe the sensation of flight — the wind, the altitude, the dragon\'s muscles working beneath the saddle. Include a complex maneuver that tests [Character Name]\'s coordination with their dragon, a near-miss with another rider, and the instructor\'s assessment afterward.',
    icon: '🌤️',
  },
  {
    id: 'emp-dragon-injury',
    category: 'Dragon Bond',
    title: 'Dragon Injury',
    description: 'Your dragon is wounded; navigate the bond bleed-through.',
    prompt: '[Character Name]\'s dragon has been injured — during training, combat, or an accident. The bond bleed-through hits immediately: phantom pain in [Character Name]\'s body mirroring the dragon\'s wound. Describe the struggle to function through the shared agony, the rush to get the dragon to the healers, and the agonizing wait while the dragon is treated. Include the dragon\'s own reaction — pride, anger, or reassurance sent through the bond.',
    icon: '🩸',
  },
  {
    id: 'emp-dragon-second',
    category: 'Dragon Bond',
    title: 'Second Bond Manifestation',
    description: 'The rare second dragon bond manifests unexpectedly.',
    prompt: 'Something impossible happens: a second dragon approaches [Character Name] with bonding intent. The existing bond thrums with [the first dragon\'s reaction — jealousy? curiosity? rage?]. Describe the moment of contact with the second dragon, the disorienting sensation of two telepathic channels opening simultaneously, and the immediate social consequences as witnesses react with shock, fear, or suspicion. Second bonds are nearly unheard of — this will change everything.',
    icon: '⚡',
  },
  {
    id: 'emp-dragon-disagree',
    category: 'Dragon Bond',
    title: 'Dragon Disagreement',
    description: 'Your dragon refuses a direct order for reasons unknown.',
    prompt: '[Character Name] gives their dragon a direct command — fly to a location, engage a target, land in a specific spot — and the dragon flatly refuses. The telepathic channel fills with a wall of NO, tinged with an emotion [Character Name] can\'t immediately interpret. Describe [Character Name]\'s frustration, the attempt to understand the dragon\'s reasoning, and the eventual revelation of WHY the dragon refused. The dragon was right. They usually are.',
    icon: '🚫',
  },
  {
    id: 'emp-dragon-hatching',
    category: 'Dragon Bond',
    title: 'Hatching Witness',
    description: 'Witness a new clutch hatching and the chaos of first bonds.',
    prompt: '[Character Name] is present at a dragon hatching — a rare privilege. The eggs crack in the volcanic nesting grounds beneath Basgiath. Describe the emergence of hatchlings: wet, fierce, already dangerous. Some hatchlings immediately fixate on nearby riders, attempting to bond with beings who already have dragons. Others cry for parents. One hatchling does something unexpected that draws [Character Name]\'s attention. The scene is chaotic, beautiful, and primally moving.',
    icon: '🥚',
  },

  // ── Signet Abilities (7) ───────────────────────────────────────────────────
  {
    id: 'emp-signet-manifest',
    category: 'Signet Abilities',
    title: 'Signet Manifestation',
    description: 'Your signet power reveals itself for the first time under stress.',
    prompt: '[Character Name] is in extreme danger or emotional distress — describe the specific trigger. Something erupts from within: their signet manifests for the first time. The power is raw, uncontrolled, and terrifying. Describe what happens to [Character Name]\'s body (physical sensations, visual effects), what the signet actually DOES, and the aftermath — exhaustion, confusion, the reactions of witnesses, and the dragon\'s response through the bond. First manifestation is always overwhelming.',
    icon: '✨',
  },
  {
    id: 'emp-signet-overreach',
    category: 'Signet Abilities',
    title: 'Signet Overreach',
    description: 'Push your signet beyond safe limits and face burnout.',
    prompt: '[Character Name] pushes their signet past the safe limit — deliberately or out of necessity. Describe the intoxicating rush of power expanding beyond its normal boundaries, the moment the body starts to fail (nosebleed, trembling, vision darkening), and the choice: stop now and survive, or push further and risk permanent damage. Whatever they choose, describe the burnout consequences — the physical cost, the recovery period, and the lesson learned about the line between power and destruction.',
    icon: '🔥',
  },
  {
    id: 'emp-signet-training',
    category: 'Signet Abilities',
    title: 'Signet Training',
    description: 'A professor tests your signet limits in a controlled exercise.',
    prompt: 'Professor [invent a name] specializes in signet development. They have designed an exercise specifically for [Character Name]\'s ability — describe the controlled environment, the escalating difficulty, and the professor\'s clinical observations. Include a moment where the professor pushes [Character Name] further than expected, the dragon\'s protective response through the bond, and the professor\'s assessment: what the signet can become, and what it will cost.',
    icon: '📚',
  },
  {
    id: 'emp-signet-combo',
    category: 'Signet Abilities',
    title: 'Signet Combo',
    description: 'Combine your signet with another rider\'s for an amplified effect.',
    prompt: '[Character Name] and a squadmate discover their signets can be combined for an amplified effect. Describe the first attempt: the synchronization challenge, the moment both powers lock together, and the result — something neither rider could achieve alone. Include the physical and emotional toll of channeling combined power, the squad\'s reaction, and the strategic implications. Also describe the risk: combined burnout could affect both riders simultaneously.',
    icon: '🤝',
  },
  {
    id: 'emp-signet-malfunction',
    category: 'Signet Abilities',
    title: 'Signet Malfunction',
    description: 'Your signet produces an unintended and unpredictable result.',
    prompt: '[Character Name] activates their signet for a routine purpose and something goes wrong — or very differently than expected. The power twists, amplifies, or redirects in a way that has never happened before. Describe the unintended effect, the immediate danger or consequence, and [Character Name]\'s scramble to regain control. Is this a malfunction, or is the signet evolving? The dragon offers an opinion through the bond.',
    icon: '⚠️',
  },
  {
    id: 'emp-signet-conceal',
    category: 'Signet Abilities',
    title: 'Signet Concealment',
    description: 'Hide the true nature of your signet from leadership.',
    prompt: '[Character Name]\'s signet is unusual, powerful, or politically dangerous — and they have decided to hide its true nature from Basgiath leadership. Describe a signet evaluation session where [Character Name] must demonstrate their ability while concealing its full scope. Include the evaluator\'s probing questions, a close call where the truth nearly slips, and the paranoid awareness that someone in the room might already suspect. The dragon\'s opinion on the deception adds tension.',
    icon: '🎭',
  },
  {
    id: 'emp-signet-evolve',
    category: 'Signet Abilities',
    title: 'Signet Evolution',
    description: 'Your power grows or changes in a way no codex has documented.',
    prompt: '[Character Name]\'s signet has changed — not just grown stronger, but fundamentally shifted in nature or capability. This is not documented in any codex. Describe the moment of realization: what the signet can now do that it couldn\'t before, the physical sensations of the change, and the implications. Does [Character Name] report this to the professors or keep it secret? The dragon\'s reaction suggests this has happened before, long ago, to other riders whose stories were erased.',
    icon: '🌀',
  },

  // ── Basgiath War College (8) ───────────────────────────────────────────────
  {
    id: 'emp-basgiath-gauntlet',
    category: 'Basgiath War College',
    title: 'Squad Challenge',
    description: 'Face an elimination-style gauntlet in the training grounds.',
    prompt: '[Character Name]\'s squad has been selected for a gauntlet challenge — a grueling series of combat, puzzle, and endurance tests in Basgiath\'s training grounds. The stakes: the losing squad faces punishment duty for a month. Describe the challenges, the moments where squad coordination saves them or fails them, and the interpersonal dynamics under pressure. Someone in the squad makes a costly mistake. Someone else performs beyond expectations.',
    icon: '⚔️',
  },
  {
    id: 'emp-basgiath-brief',
    category: 'Basgiath War College',
    title: 'Battle Brief Intelligence',
    description: 'A Battle Brief reveals disturbing news about the ward line.',
    prompt: 'During the weekly Battle Brief — where riders receive intelligence updates on the war — a piece of information slips through that is more alarming than usual. A wardstone failure closer to Basgiath than any before. Describe the briefing room, the instructor\'s carefully controlled delivery, the reactions of the other cadets, and [Character Name]\'s private assessment. What isn\'t being said is more frightening than what is. Afterward, in the corridor, someone pulls [Character Name] aside with additional information.',
    icon: '📋',
  },
  {
    id: 'emp-basgiath-mess',
    category: 'Basgiath War College',
    title: 'Mess Hall Confrontation',
    description: 'Tensions boil over between riders from different wings.',
    prompt: 'Dinner in the mess hall. A remark — possibly about rankings, a training incident, or a personal slight — escalates between riders from two different wings. [Character Name] is present and must choose: intervene, stay out of it, or take a side. Describe the mess hall atmosphere, the escalating argument, the moment it turns physical (or nearly does), and the consequences. Wing loyalty is powerful at Basgiath — this will be remembered.',
    icon: '🍽️',
  },
  {
    id: 'emp-basgiath-spar',
    category: 'Basgiath War College',
    title: 'Sparring Match',
    description: 'Hand-to-hand combat with a rival who fights dirty.',
    prompt: '[Character Name] is matched against a rival in the sparring ring. This opponent has a reputation for fighting dirty — technically legal moves that cause maximum pain. Describe the match blow by blow: the rival\'s dirty tactics, [Character Name]\'s response (adapt or retaliate?), the instructor\'s observations, and the crowd\'s reaction. Win or lose, this fight changes the dynamic between [Character Name] and their opponent.',
    icon: '🥊',
  },
  {
    id: 'emp-basgiath-wargames',
    category: 'Basgiath War College',
    title: 'War Games',
    description: 'Full-scale simulated battle with real stakes and injuries.',
    prompt: 'Basgiath conducts War Games — a full-scale simulated battle between wings, with real combat (blunted weapons, controlled signet use) and real consequences (injuries are common, death is rare but not unheard of). [Character Name]\'s wing faces a numerically superior opponent. Describe the strategy session, the aerial and ground phases of the battle, and the moment everything changes — a plan that works brilliantly or fails catastrophically. Include at least one genuine injury.',
    icon: '🏴',
  },
  {
    id: 'emp-basgiath-summons',
    category: 'Basgiath War College',
    title: 'Commandant\'s Summons',
    description: 'Called before leadership for an uncomfortable interrogation.',
    prompt: '[Character Name] receives a summons to the Commandant\'s office — or another senior leader. The walk through Basgiath\'s corridors feels longer than usual. Describe the office (what it reveals about the person in charge), the interrogation (what they want to know and why), and the undertones (what they\'re really asking). [Character Name] must decide how much truth to share. The leader knows more than they reveal, and the meeting ends with an implicit threat or an unexpected offer.',
    icon: '📜',
  },
  {
    id: 'emp-basgiath-archives',
    category: 'Basgiath War College',
    title: 'Archives Discovery',
    description: 'Uncover forbidden texts in the Scribe quadrant.',
    prompt: '[Character Name] gains access — legitimately or otherwise — to a restricted section of Basgiath\'s archives. Describe the descent into the lower stacks, the dust, the preservation wards on ancient texts, and the discovery of a document that challenges official history. What does it reveal? Who wrote it? Why was it hidden? [Character Name] must decide what to do with this knowledge — and they realize someone has been here before them recently. The dust has been disturbed.',
    icon: '📖',
  },
  {
    id: 'emp-basgiath-leadership',
    category: 'Basgiath War College',
    title: 'Wing Leadership',
    description: 'Earn or lose a leadership position within your wing.',
    prompt: '[Character Name] is either being considered for a leadership position (squad leader, wingleader) or is at risk of losing one. Describe the evaluation process: the tests, the politics, the competitors. Include a critical moment where [Character Name]\'s leadership style is tested — a crisis where they must make a call that not everyone will agree with. The outcome reshapes their position within the wing hierarchy and changes how others treat them.',
    icon: '👑',
  },

  // ── Venin and Dark Forces (7) ──────────────────────────────────────────────
  {
    id: 'emp-venin-first',
    category: 'Venin and Dark Forces',
    title: 'First Venin Encounter',
    description: 'Face a venin and realize the propaganda was wrong.',
    prompt: '[Character Name] encounters a venin for the first time — not in a briefing room, but in person. Everything they were taught said venin are mindless monsters. This one speaks. Describe the setting (a patrol beyond the wards, a ward failure zone, an attack on an outpost), the venin\'s appearance (the corruption visible on their body), and the shock of hearing them talk. What does the venin say? It should challenge something [Character Name] believed about the enemy.',
    icon: '👁️',
  },
  {
    id: 'emp-venin-wyvern',
    category: 'Venin and Dark Forces',
    title: 'Wyvern Assault',
    description: 'Wyverns attack during patrol, testing everything you\'ve learned.',
    prompt: 'During a routine patrol, wyverns attack — a swarm of them, coming from a direction nobody expected. Describe the initial moments: the screech, the dragon\'s instinctive response, the frantic scramble into combat formation. The fight is chaotic, terrifying, and nothing like training exercises. Include a squadmate in danger, a dragon-to-wyvern mid-air clash, and the aftermath — the cost counted in injuries, exhaustion, and the realization that this is the reality beyond Basgiath\'s walls.',
    icon: '🦇',
  },
  {
    id: 'emp-venin-ward',
    category: 'Venin and Dark Forces',
    title: 'Ward Line Failure',
    description: 'A section of the ward line goes dark and your squad investigates.',
    prompt: 'A section of the ward line has gone dark — the wardstone has failed or been destroyed. [Character Name]\'s squad is sent to investigate. Describe the approach: the moment they cross into unprotected territory, the change in the air and land (the grey, the silence, the wrongness), and what they find at the wardstone site. Was it natural degradation or deliberate sabotage? Something is still there, and it knows they\'ve arrived.',
    icon: '🌑',
  },
  {
    id: 'emp-venin-temptation',
    category: 'Venin and Dark Forces',
    title: 'Dark Wielding Temptation',
    description: 'Forbidden power presents itself in a desperate moment.',
    prompt: '[Character Name] is in a desperate situation — about to die, watching someone they care about in mortal danger, or facing impossible odds. In that moment, they feel it: the earth beneath them, pulsing with power that could be drawn. Dark wielding. Describe the sensation — the seductive pull, the promise of enough power to solve everything, the whisper that it would be just this once. What does [Character Name] do? And what does the dragon feel through the bond?',
    icon: '🖤',
  },
  {
    id: 'emp-venin-intel',
    category: 'Venin and Dark Forces',
    title: 'Venin Intelligence',
    description: 'Capture or interrogate a venin and learn something game-changing.',
    prompt: 'An early-stage venin has been captured alive — still coherent enough to communicate. [Character Name] is part of the interrogation, officially or unofficially. Describe the containment setup, the venin\'s appearance and demeanor (are they afraid? defiant? resigned?), and the information they reveal. What they say should change [Character Name]\'s understanding of the war, the enemy, or the Empyrean\'s secrets. The venin asks a question in return that [Character Name] cannot answer.',
    icon: '🔗',
  },
  {
    id: 'emp-venin-infected',
    category: 'Venin and Dark Forces',
    title: 'Infected Rider',
    description: 'A fellow rider shows signs of turning — and they\'re your friend.',
    prompt: 'Someone [Character Name] cares about — a squadmate, a friend, a romantic interest — is showing subtle signs of venin corruption. Darkening veins they try to hide. Mood changes. Unexplained power spikes. [Character Name] notices. Describe the dread, the denial, the moment of confirmation. What do you do when someone you love is becoming the enemy? Report them (and condemn them)? Hide it (and risk everyone)? Try to help (and risk yourself)?',
    icon: '💉',
  },
  {
    id: 'emp-venin-beyond',
    category: 'Venin and Dark Forces',
    title: 'Beyond the Wards',
    description: 'Cross into drained territory where the land is dead.',
    prompt: '[Character Name] crosses beyond the ward line into the Barrens — territory drained by venin over centuries. Describe the landscape: grey earth, petrified trees, silence where there should be life. The air tastes wrong. The dragon is uneasy, sending waves of discomfort through the bond. As they venture deeper, describe what they find — evidence of what this land was before it was drained, and evidence of what lives here now. The return to warded territory should feel like surfacing from underwater.',
    icon: '🏜️',
  },

  // ── Relationships and Politics (8) ─────────────────────────────────────────
  {
    id: 'emp-rel-alliance',
    category: 'Relationships and Politics',
    title: 'Forbidden Alliance',
    description: 'Form a secret pact with someone from a rival quadrant.',
    prompt: '[Character Name] makes contact with someone from a different quadrant — a scribe with forbidden knowledge, a healer with no allegiance to the Empyrean, or an infantry cadet who saw something they shouldn\'t have. Describe the clandestine meeting, the negotiation of trust, and the terms of their alliance. Both parties are risking their positions and possibly their lives. What do they each want? What do they each have to offer?',
    icon: '🤫',
  },
  {
    id: 'emp-rel-romantic',
    category: 'Relationships and Politics',
    title: 'Romantic Tension',
    description: 'A charged moment with someone you shouldn\'t trust but can\'t resist.',
    prompt: '[Character Name] is alone with someone they are drawn to — but shouldn\'t be. Chain of command, factional loyalty, or competing secrets make this dangerous. Describe the setting (a training room after hours, the library stacks, a quiet spot on the ramparts), the conversation that starts as one thing and becomes something else, and the physical awareness between them. The moment is interrupted before anything resolves — but something has shifted between them permanently.',
    icon: '💕',
  },
  {
    id: 'emp-rel-betrayal',
    category: 'Relationships and Politics',
    title: 'Betrayal Discovery',
    description: 'Someone close has been reporting to the Commandant.',
    prompt: '[Character Name] discovers that someone they trusted — a squadmate, a friend, a romantic interest — has been reporting information to the Commandant\'s office. Describe the discovery (overheard conversation, found documents, a warning from a third party), the confrontation (or the decision not to confront), and the emotional fallout. Was the betrayal driven by loyalty to the institution, coercion, or something else entirely? The relationship is irrevocably changed.',
    icon: '🗡️',
  },
  {
    id: 'emp-rel-legacy',
    category: 'Relationships and Politics',
    title: 'Family Legacy',
    description: 'Your family name carries weight that helps and hinders.',
    prompt: '[Character Name]\'s family name is recognized at Basgiath — for better or worse. Describe an incident where the legacy matters: a professor who served with a parent and has expectations, a rival who resents the family\'s reputation, or a senior officer who offers advantage based on bloodline. [Character Name] must navigate whether to leverage the legacy or reject it, knowing that either choice has consequences within Basgiath\'s political ecosystem.',
    icon: '🏛️',
  },
  {
    id: 'emp-rel-cross',
    category: 'Relationships and Politics',
    title: 'Cross-Quadrant Friendship',
    description: 'Bond with a scribe or healer despite social barriers.',
    prompt: '[Character Name] forms an unlikely friendship with someone from a different quadrant. Riders and scribes operate in different worlds; riders and healers have a relationship defined by dependency. Describe how the friendship forms (a shared incident, mutual curiosity, being assigned adjacent rooms), the social friction it creates (quadrant loyalty is strong), and a moment where the friendship is tested — and proven real.',
    icon: '🌉',
  },
  {
    id: 'emp-rel-loyalty',
    category: 'Relationships and Politics',
    title: 'Loyalty Test',
    description: 'Choose between following orders and protecting someone.',
    prompt: 'An order comes down from leadership — and obeying it means sacrificing someone [Character Name] cares about. Describe the order (a mission assignment, a disciplinary action, a strategic decision that treats people as expendable), the person at risk, and the impossible choice. If [Character Name] follows orders, describe the personal cost. If they defy orders, describe the institutional consequences. There is no clean outcome.',
    icon: '⚖️',
  },
  {
    id: 'emp-rel-powerplay',
    category: 'Relationships and Politics',
    title: 'Power Play',
    description: 'Navigate a conflict between senior riders with your squad caught in the middle.',
    prompt: 'Two senior riders — wingleaders, professors, or commanding officers — are in conflict, and [Character Name]\'s squad is caught in the middle. Each side applies pressure: favors, threats, assignments that are rewards or punishments depending on who you ask. Describe the political dynamics, the attempts to recruit [Character Name] to a side, and the squad\'s internal debate about which allegiance serves them best. Neutrality is not an option.',
    icon: '♟️',
  },
  {
    id: 'emp-rel-truth',
    category: 'Relationships and Politics',
    title: 'Truth or Treason',
    description: 'You have information that could save lives — or get you executed.',
    prompt: '[Character Name] possesses information that could change the war — the true state of the wards, a venin weakness, a political conspiracy. Sharing it would save lives but violate classification, expose the source, or challenge the Empyrean\'s authority. Describe the weight of the knowledge, the people who would benefit, and the calculation: is the truth worth your life? Who do you tell, and how do you ensure the information survives if you don\'t?',
    icon: '⚡',
  },

  // ── Combat and Survival (7) ────────────────────────────────────────────────
  {
    id: 'emp-combat-ambush',
    category: 'Combat and Survival',
    title: 'Ambush Response',
    description: 'Your patrol is ambushed beyond the ward line. Roll initiative.',
    prompt: '[Character Name]\'s patrol is ambushed beyond the ward line. Describe the first moments: the attack comes from an unexpected direction, the dragons react before the riders do, and training kicks in — or doesn\'t. Detail the combatants (venin, wyverns, or corrupted wildlife), the terrain (it favors the attackers), and the critical decisions in the first thirty seconds. Someone is down. The formation is broken. What does [Character Name] do?',
    icon: '⚔️',
  },
  {
    id: 'emp-combat-defense',
    category: 'Combat and Survival',
    title: 'Outpost Defense',
    description: 'Defend a fortified position against overwhelming venin forces.',
    prompt: '[Character Name]\'s squad is assigned to defend an outpost near the ward line. The outpost has walls, basic supplies, and a wardstone — but it\'s undermanned and the relief force is hours away. A venin assault begins. Describe the preparation, the first wave (testing defenses), the second wave (pressing weaknesses), and the moment when the wardstone begins to flicker. The squad must hold. Describe the cost of holding.',
    icon: '🏰',
  },
  {
    id: 'emp-combat-recon',
    category: 'Combat and Survival',
    title: 'Solo Reconnaissance',
    description: 'Sent alone beyond the wards on a critical intelligence mission.',
    prompt: '[Character Name] is sent on a solo reconnaissance mission beyond the ward line — just them and their dragon. The objective: confirm intelligence about a suspected venin gathering point. Describe the flight over unprotected territory (the dragon\'s unease, the desolation below), the approach to the target, and what [Character Name] finds. It\'s worse than intelligence suggested. Now they must get the information back — but they\'ve been spotted.',
    icon: '🔭',
  },
  {
    id: 'emp-combat-retreat',
    category: 'Combat and Survival',
    title: 'Wounded Retreat',
    description: 'Fight a rearguard action while dragging an injured squadmate to safety.',
    prompt: 'The mission has gone wrong. A squadmate is seriously injured — cannot walk, cannot fly their dragon. [Character Name] must get them to safety while the enemy closes in. Describe the terrain (hostile, beyond the wards), the injured rider\'s condition (deteriorating), and the rearguard fight — buying time in short, brutal engagements while falling back toward the ward line. The dragon carries both riders, but the weight slows them. Every minute is a calculation.',
    icon: '🩹',
  },
  {
    id: 'emp-combat-dogfight',
    category: 'Combat and Survival',
    title: 'Aerial Dogfight',
    description: 'One-on-one dragon combat against a mounted wyvern rider.',
    prompt: '[Character Name] is separated from their squad and faces a single opponent: a venin mounted on a wyvern. One-on-one, dragon against wyvern, rider against dark wielder. Describe the aerial combat in visceral detail: the diving attacks, the fire exchanges, the wyvern\'s venom spray, the venin\'s dark wielding, and the moment-by-moment coordination between [Character Name] and their dragon. This fight is personal. Only one combatant is landing.',
    icon: '🐲',
  },
  {
    id: 'emp-combat-grounded',
    category: 'Combat and Survival',
    title: 'Grounded Combat',
    description: 'Separated from your dragon, fight with blade and signet only.',
    prompt: '[Character Name] is separated from their dragon — knocked from the saddle, cut off by terrain, or deliberately targeted. On the ground, without the dragon\'s proximity to amplify their signet, they are diminished. Describe the fight with blade, training, and fading signet power against an opponent who knows they\'re weakened. Include the ache of the stretched bond, the dragon\'s frantic attempts to reach them, and the desperate improvisation required to survive.',
    icon: '🗡️',
  },
  {
    id: 'emp-combat-last',
    category: 'Combat and Survival',
    title: 'Last Stand',
    description: 'The situation is hopeless. How does your character face it?',
    prompt: 'It\'s over. [Character Name] is outnumbered, outmatched, out of options. The squad is scattered or down. The dragon is injured. The enemy is closing. There is no rescue coming. Describe how [Character Name] faces the end — with defiance, with calm, with one last desperate gamble, or with a message sent through the bond to someone who matters. This is the moment that defines who they are. What happens may surprise them.',
    icon: '🌅',
  },

  // ── Meta and Narrative (5) ─────────────────────────────────────────────────
  {
    id: 'emp-meta-dragon-pov',
    category: 'Meta and Narrative',
    title: 'Dragon Perspective',
    description: 'Tell the next scene from your bonded dragon\'s point of view.',
    prompt: 'Narrate the next scene entirely from the dragon\'s perspective. Describe how the dragon perceives the world differently: infrared vision, scent-mapping, the vibration of the earth, the taste of the wind. Show how the dragon thinks about their rider — the affection tinged with exasperation, the protective instinct, the things they notice that the rider misses. The dragon should have opinions about the current situation and express them in their own way: terse, ancient, and slightly amused.',
    icon: '🐉',
  },
  {
    id: 'emp-meta-history',
    category: 'Meta and Narrative',
    title: 'Unreliable History',
    description: 'Reveal that official history contradicts what actually happened.',
    prompt: '[Character Name] encounters evidence — a document, a witness, an ancient rune inscription — that directly contradicts official Navarre history. What the textbooks say happened during the Reunification, the founding of Basgiath, or the origin of the venin threat is wrong. Describe the evidence, its implications, and [Character Name]\'s reckoning with the fact that they\'ve been taught lies. Who benefits from the false history? What does the truth mean for the present war?',
    icon: '📜',
  },
  {
    id: 'emp-meta-dream',
    category: 'Meta and Narrative',
    title: 'Prophetic Dream',
    description: 'A symbolic dream tied to the current threat.',
    prompt: '[Character Name] has a dream that feels too real to be ordinary. The imagery is symbolic: fire, falling, a door that won\'t open, a voice speaking in a language they shouldn\'t understand. The dragon is present in the dream — or conspicuously absent. Describe the dream in vivid, surreal detail, then the waking: the lingering feeling, the attempt to interpret the symbols, and the moment later in the day when something in the dream echoes in reality.',
    icon: '🌙',
  },
  {
    id: 'emp-meta-montage',
    category: 'Meta and Narrative',
    title: 'Training Montage',
    description: 'Fast-forward through weeks, summarizing key growth moments.',
    prompt: 'Summarize the next several weeks of [Character Name]\'s life at Basgiath in a montage: key training milestones (the day they finally mastered a formation, the sparring match that changed something), relationship shifts (a friendship deepening, a rivalry cooling, a glance that lasted too long), physical changes (stronger, more scarred, more confident), and one small, perfect moment of happiness amid the grind. End the montage with the event that breaks the routine.',
    icon: '⏩',
  },
  {
    id: 'emp-meta-codex',
    category: 'Meta and Narrative',
    title: 'Codex Entry',
    description: 'Create an in-universe document: journal, report, or wingleader\'s orders.',
    prompt: 'Create an in-universe document written by or about [Character Name]. Choose the format: a personal journal entry processing a recent event, an official intelligence report documenting an encounter, a wingleader\'s orders for an upcoming mission, a healer\'s medical notes after treating [Character Name]\'s injuries, or a scribe\'s classified assessment of [Character Name]\'s signet. The document should reveal information, advance character development, and feel authentically written by someone in the Empyrean world.',
    icon: '📝',
  },
];

export const empyreanPromptCategories = [
  'Dragon Bond',
  'Signet Abilities',
  'Basgiath War College',
  'Venin and Dark Forces',
  'Relationships and Politics',
  'Combat and Survival',
  'Meta and Narrative',
] as const;

export type EmpyreanPromptCategory = typeof empyreanPromptCategories[number];
