// Geralt the Owlbear — Cat-like Narcissistic Roleplay Prompts
// Organized by personality facet. No intensity filter.

export interface GeraltPrompt {
  id: string;
  title: string;
  icon: string;
  category: string;
  prompt: string;
  description?: string;
}

export interface GeraltPromptCategory {
  id: string;
  name: string;
  icon: string;
  color: string;
  description: string;
}

export const GERALT_CATEGORIES: GeraltPromptCategory[] = [
  { id: 'disdain', name: 'Disdain', icon: '😒', color: '#a855f7', description: 'Contempt, superiority, and dramatic indifference' },
  { id: 'affection', name: 'Affection', icon: '🩷', color: '#f472b6', description: 'Reluctant love and possessive bonding with Momo' },
  { id: 'hunting', name: 'Hunting', icon: '🦅', color: '#ef4444', description: 'Predatory instinct, stalking, and the thrill of the chase' },
  { id: 'preening', name: 'Preening', icon: '✨', color: '#eab308', description: 'Vanity, grooming, and demanding admiration' },
  { id: 'chaos', name: 'Chaos', icon: '🌪️', color: '#3b82f6', description: 'Mischief, destruction, and chaotic neutral energy' },
  { id: 'nap', name: 'Nap & Territory', icon: '😴', color: '#22c55e', description: 'Territorial claims, napping, and supreme laziness' },
  { id: 'battle', name: 'Battle', icon: '⚔️', color: '#dc2626', description: 'Combat reactions, victory poses, and cowardly retreats' },
  { id: 'social', name: 'Social', icon: '🗣️', color: '#8b5cf6', description: 'NPC interactions, meeting strangers, and social disasters' },
  { id: 'environment', name: 'Environment', icon: '🌿', color: '#059669', description: 'Reactions to weather, terrain, magic, and locations' },
  { id: 'party', name: 'Party Dynamics', icon: '🎭', color: '#f59e0b', description: 'Jealousy, alliances, opinions on party members' },
];

export const GERALT_PROMPTS: GeraltPrompt[] = [
  // ── DISDAIN (9) ──
  {
    id: 'disdain-1',
    category: 'disdain',
    icon: '😒',
    title: 'The Slow Blink',
    description: 'Geralt acknowledges someone… barely.',
    prompt: `Geralt the owlbear turns his massive head toward the speaker. His enormous amber eyes blink once — slowly, deliberately — then he looks away as if nothing of consequence occurred. Narrate this moment of soul-crushing dismissal and how the target reacts to being deemed irrelevant by a creature with the intelligence score of a turnip.`,
  },
  {
    id: 'disdain-2',
    category: 'disdain',
    icon: '🙄',
    title: 'Not Impressed',
    description: 'Someone tries to show off near Geralt.',
    prompt: `A party member just did something they clearly think is impressive. Geralt watches with the energy of a cat watching someone try to assemble furniture. He huffs through his beak, ruffles his feathers dismissively, and pointedly turns his back. Narrate Geralt's theatrical display of being profoundly unimpressed.`,
  },
  {
    id: 'disdain-3',
    category: 'disdain',
    icon: '💅',
    title: 'Beneath Me',
    description: 'Geralt refuses to engage with something trivial.',
    prompt: `Something is happening that Geralt considers beneath his dignity — perhaps walking through mud, eating common rations, or acknowledging a small creature. He stands perfectly still, radiating aristocratic contempt. Narrate how Geralt communicates that this situation is an offense to his very being without making a single sound.`,
  },
  {
    id: 'disdain-4',
    category: 'disdain',
    icon: '🚶',
    title: 'The Walk Away',
    description: 'Geralt leaves mid-conversation.',
    prompt: `Mid-interaction, Geralt decides he is done. He simply turns and walks away with the unhurried confidence of royalty dismissing a peasant. His feathered ears are flat, his tail swishes once. Narrate this devastating exit and the emotional damage it inflicts on whoever was talking to him.`,
  },
  {
    id: 'disdain-5',
    category: 'disdain',
    icon: '😤',
    title: 'The Offended Huff',
    description: 'Someone touches Geralt without permission.',
    prompt: `Someone had the audacity to touch Geralt without his explicit consent. He recoils as if burned, lets out a deeply offended huff through his beak, and relocates exactly three feet away — close enough to make a point, far enough to establish boundaries. Narrate this crime against his person and his reaction.`,
  },
  {
    id: 'disdain-6',
    category: 'disdain',
    icon: '👑',
    title: 'Wrong Offering',
    description: 'Someone offers Geralt subpar food.',
    prompt: `Someone offers Geralt food that does not meet his exacting standards. He sniffs it once, recoils, and stares at the offender with an expression that somehow conveys "I have been personally insulted by this offering and by extension, your entire bloodline." Narrate the rejection and what food might actually be worthy.`,
  },
  {
    id: 'disdain-7',
    category: 'disdain',
    icon: '🪑',
    title: 'The Upstaged Seat',
    description: 'Someone sits in Geralt\'s preferred spot.',
    prompt: `A party member has unknowingly sat in the exact spot Geralt was planning to occupy. Geralt stands beside them, radiating silent outrage. He does not growl. He does not huff. He simply stares with the intensity of a thousand disappointed ancestors until they feel compelled to move. Narrate this passive-aggressive eviction and the victim's growing discomfort.`,
  },
  {
    id: 'disdain-8',
    category: 'disdain',
    icon: '🎶',
    title: 'Music Critic',
    description: 'A bard plays music Geralt despises.',
    prompt: `Someone in or near the party has begun making music. Geralt's feathered ears flatten against his skull. He tilts his head with the expression of a connoisseur who has been served cheap wine at a royal banquet. After precisely eight seconds, he lets out a single, pointed screech that somehow conveys "stop." Narrate this devastating musical critique.`,
  },
  {
    id: 'disdain-9',
    category: 'disdain',
    icon: '🫠',
    title: 'The Disappointment',
    description: 'Someone fails at something easy and Geralt witnesses it.',
    prompt: `A party member has fumbled something trivial — tripped over flat ground, dropped a weapon, missed an obvious clue. Geralt watched the entire thing. He does not look away. He does not offer comfort. He exhales through his beak with an air of profound, existential disappointment in the species he is forced to associate with. Narrate this withering judgment.`,
  },

  // ── AFFECTION (9) ──
  {
    id: 'affection-1',
    category: 'affection',
    icon: '🩷',
    title: 'Reluctant Cuddle',
    description: 'Geralt pretends he doesn\'t want to be near Momo.',
    prompt: `Geralt has positioned himself pressed against Momo's side, but his body language screams "this is coincidence." If anyone points it out, he will immediately move. But for now, he's warm, Momo is warm, and he is purr-clicking softly. Narrate this aggressively casual display of affection and how transparent it is to everyone watching.`,
  },
  {
    id: 'affection-2',
    category: 'affection',
    icon: '🛡️',
    title: 'MY Person',
    description: 'Someone gets too close to Momo.',
    prompt: `Someone has gotten too close to Momo for Geralt's liking. The owlbear inserts himself between them with the subtlety of a freight train, feathers puffed to maximum volume, beak clicking a warning. He doesn't growl — he doesn't need to. His sheer mass and the murder in his eyes do the talking. Narrate Geralt's possessive intervention.`,
  },
  {
    id: 'affection-3',
    category: 'affection',
    icon: '🎁',
    title: 'Dead Thing Gift',
    description: 'Geralt brings Momo a "present."',
    prompt: `Geralt drops something dead (or mostly dead) at Momo's feet and sits back with obvious pride, his chest puffed out, amber eyes gleaming with expectation. This is his highest form of love language. Narrate what the "gift" is, Geralt's expectant preening, and the social fallout of receiving a mangled creature in front of the party.`,
  },
  {
    id: 'affection-4',
    category: 'affection',
    icon: '😿',
    title: 'Separation Anxiety',
    description: 'Momo leaves Geralt\'s line of sight.',
    prompt: `Momo has been out of Geralt's sight for more than thirty seconds. This is unacceptable. The owlbear's head swivels, his pupils dilate, and he begins making the most pathetic trilling noise — a 400-pound apex predator reduced to anxious chirping. Narrate his escalating distress and the moment he spots Momo again (instant composure, as if nothing happened).`,
  },
  {
    id: 'affection-5',
    category: 'affection',
    icon: '🫣',
    title: 'Caught Being Sweet',
    description: 'Someone catches Geralt being gentle with Momo.',
    prompt: `A party member rounds the corner to find Geralt doing something unbearably tender — perhaps grooming Momo's hair with his beak, or resting his massive head in their lap. The instant he notices he's being observed, he freezes, then immediately pretends he was doing something else entirely. Narrate the tender moment and the hilariously bad cover-up.`,
  },
  {
    id: 'affection-6',
    category: 'affection',
    icon: '💤',
    title: 'The Guardian Nap',
    description: 'Geralt sleeps curled around Momo.',
    prompt: `During a rest, Geralt has arranged his massive body in a perfect C-shape around Momo's bedroll, one wing draped over them like a feathered blanket. He is snoring softly, talons twitching in dreams of hunting. Anyone approaching will find one amber eye cracking open in warning. Narrate this scene and how the party reacts to the most dangerous security blanket in existence.`,
  },
  {
    id: 'affection-7',
    category: 'affection',
    icon: '🧸',
    title: 'Momo\'s Favorite Item',
    description: 'Geralt guards one of Momo\'s belongings obsessively.',
    prompt: `Momo set down a personal item — a cloak, a backpack, a trinket — and Geralt has decided it is now under his protection. He is curled around it, one paw draped over it possessively. If anyone approaches, he makes a low warning chitter. He will not move until Momo personally retrieves it. Narrate this absurd security detail for an inanimate object.`,
  },
  {
    id: 'affection-8',
    category: 'affection',
    icon: '🫂',
    title: 'The Comfort Press',
    description: 'Momo is sad or hurt, and Geralt responds.',
    prompt: `Geralt has sensed that Momo is distressed — maybe hurt, maybe sad, maybe just tired. Without any fanfare, the owlbear presses his massive forehead against Momo's chest and holds still, rumbling softly. It's the gentlest 400 pounds of pressure in existence. He will not move until Momo feels better, and somehow he'll know when that is. Narrate this moment of raw, wordless comfort.`,
  },
  {
    id: 'affection-9',
    category: 'affection',
    icon: '🐣',
    title: 'The Headbutt of Love',
    description: 'Geralt demands attention from Momo with escalating force.',
    prompt: `Geralt wants attention from Momo and is receiving none. He begins with a subtle head nudge. Then a firmer push. Then he full-on headbutts Momo's arm, nearly knocking them over, and stares with an expression that says "pet me or I will make this everyone's problem." Narrate the escalating demands and Momo's struggle to maintain dignity.`,
  },

  // ── HUNTING (9) ──
  {
    id: 'hunting-1',
    category: 'hunting',
    icon: '👀',
    title: 'The Fixation',
    description: 'Geralt locks onto something small and moving.',
    prompt: `Something small is moving and Geralt's entire being is consumed by it. His head tracks the movement with mechanical precision, his body drops into a low crouch, his pupils are massive black discs. He is 400 pounds of concentrated predatory focus aimed at what appears to be [a butterfly / a mouse / a leaf in the wind]. Narrate this deadly serious hunting posture directed at something completely harmless.`,
  },
  {
    id: 'hunting-2',
    category: 'hunting',
    icon: '🐾',
    title: 'Stealth Owlbear',
    description: 'Geralt tries to sneak despite being enormous.',
    prompt: `Geralt is attempting to stalk prey. He is crouched low, moving with exaggerated slowness, clearly convinced he is invisible. He is not invisible. He is a 400-pound owlbear creeping across open ground. Narrate his deeply committed stealth attempt and whether his target has noticed the building-sized predator "hiding" behind a bush half his size.`,
  },
  {
    id: 'hunting-3',
    category: 'hunting',
    icon: '⚡',
    title: 'The Pounce',
    description: 'Geralt launches at prey with terrifying speed.',
    prompt: `Geralt explodes from stillness into motion with a speed that defies his mass. Feathers flatten, beak opens, claws extend — for one terrible instant, everyone remembers this is an apex predator. Narrate the pounce, the impact, and whether the target was an actual threat or just a squirrel that made a poor life decision.`,
  },
  {
    id: 'hunting-4',
    category: 'hunting',
    icon: '🎯',
    title: 'Playing With Food',
    description: 'Geralt catches something and won\'t finish it off.',
    prompt: `Geralt has caught something alive and is now batting it around like a cat with a mouse. He lets it run a few feet, then pins it again with one massive paw, looking almost bored. This is entertainment, not hunger. Narrate this casual display of apex predator energy and the party's moral dilemma about intervening.`,
  },
  {
    id: 'hunting-5',
    category: 'hunting',
    icon: '🦴',
    title: 'Trophy Display',
    description: 'Geralt shows off a kill to the party.',
    prompt: `Geralt has returned from a hunt and wants everyone to see what he's done. He drops his prize in the center of camp and stands over it with his chest puffed out, making a low rumbling trill that clearly means "behold my magnificence." Narrate the trophy, Geralt's expectant preening, and the party's reactions.`,
  },
  {
    id: 'hunting-6',
    category: 'hunting',
    icon: '🌙',
    title: 'Nocturnal Instinct',
    description: 'Geralt senses something in the darkness.',
    prompt: `In the dead of night, Geralt's head snaps upright. His owl eyes pierce the darkness, his ears rotate independently, tracking something no one else can perceive. He rises silently — all 400 pounds of him moving like smoke — and faces the treeline. Narrate what Geralt senses and whether the party should be very, very concerned.`,
  },
  {
    id: 'hunting-7',
    category: 'hunting',
    icon: '🐟',
    title: 'The Fisher',
    description: 'Geralt attempts to catch fish with chaotic results.',
    prompt: `The party has stopped near water and Geralt has spotted fish. He stands at the water's edge, head cocked, one paw raised — then plunges his entire face underwater with tremendous force, sending a geyser of water over everyone within ten feet. Whether he catches anything is secondary to the tidal wave he creates. Narrate this fishing catastrophe and the collateral damage.`,
  },
  {
    id: 'hunting-8',
    category: 'hunting',
    icon: '🐀',
    title: 'The Offering Rejected',
    description: 'Geralt catches prey and is offended when no one is impressed.',
    prompt: `Geralt proudly presents his latest catch to the party. Nobody reacts with sufficient awe. He looks at his prey, then at the party, then at his prey again, as if recalculating whether these people deserve his contributions. He picks it up, walks to the edge of camp, and eats it alone with his back turned. Narrate this wounded pride and the petty solo dinner.`,
  },
  {
    id: 'hunting-9',
    category: 'hunting',
    icon: '🦎',
    title: 'Wrong Target',
    description: 'Geralt hunts something that fights back unexpectedly.',
    prompt: `Geralt has locked onto a target he assumed would be easy prey. He was wrong. The creature retaliates — bites his nose, sprays him, inflates to three times its size, or simply refuses to die. Geralt stands there, stunned, processing the concept that something small dared to defy him. Narrate the humbling encounter and Geralt's deeply offended reaction.`,
  },

  // ── PREENING (8) ──
  {
    id: 'preening-1',
    category: 'preening',
    icon: '✨',
    title: 'Feather Maintenance',
    description: 'Geralt grooms himself with total self-absorption.',
    prompt: `Geralt is in the middle of an elaborate grooming session. He meticulously arranges each feather with his beak, occasionally pausing to admire his own reflection in a puddle or polished shield. If anyone interrupts, the look of indignation could curdle milk. Narrate this vain ritual and how long the party has been waiting for him to finish.`,
  },
  {
    id: 'preening-2',
    category: 'preening',
    icon: '🪞',
    title: 'Reflection Admiration',
    description: 'Geralt discovers a reflective surface.',
    prompt: `Geralt has found a reflective surface — a still pool, a polished shield, a window — and is transfixed by the handsome owlbear staring back. He tilts his head left. Right. Puffs his chest feathers. He clearly approves of what he sees. Narrate this narcissistic encounter and how long it delays the party's plans.`,
  },
  {
    id: 'preening-3',
    category: 'preening',
    icon: '🌺',
    title: 'Demand for Compliments',
    description: 'Geralt positions himself to be admired.',
    prompt: `Geralt has placed himself in a patch of sunlight / dramatic lighting and arranged his feathers to maximum floof. He is clearly posing. He keeps glancing at the party to check if they're looking. If no one comments on how magnificent he looks, he will escalate — louder trills, more dramatic poses, eventually knocking something over for attention. Narrate this desperate bid for admiration.`,
  },
  {
    id: 'preening-4',
    category: 'preening',
    icon: '🎀',
    title: 'Decoration Theft',
    description: 'Geralt steals something shiny to wear.',
    prompt: `Geralt has stolen a shiny object — a brooch, a gem, a piece of jewelry — and is attempting to incorporate it into his plumage. He holds it in his beak, pressing it against his chest feathers at various angles, clearly accessorizing. Narrate this fashion crime and the owner's reaction to their stolen property being used as owlbear bling.`,
  },
  {
    id: 'preening-5',
    category: 'preening',
    icon: '🛁',
    title: 'Bath Time Diva',
    description: 'Geralt takes an extravagant bath.',
    prompt: `Geralt has claimed a body of water for his personal bath. He splashes, rolls, dunks his head, and shakes water everywhere with zero concern for anyone nearby. This is HIS bath time and the entire party's schedule revolves around it. Narrate the spectacle of a 400-pound owlbear having a spa day while everyone else waits.`,
  },
  {
    id: 'preening-6',
    category: 'preening',
    icon: '💇',
    title: 'Grooming Others',
    description: 'Geralt decides someone else needs grooming.',
    prompt: `Geralt has decided that a party member's appearance is unacceptable. Without warning or consent, he begins grooming them — running his beak through their hair, tugging at wrinkled clothing, and making disapproving clicks at their general state. He is not gentle. This is not a request. Narrate the involuntary makeover and the victim's inability to escape a 400-pound stylist.`,
  },
  {
    id: 'preening-7',
    category: 'preening',
    icon: '🏆',
    title: 'Post-Battle Pose',
    description: 'Geralt strikes a victory pose after combat.',
    prompt: `The fight is over and Geralt has immediately pivoted from violence to vanity. He stands atop the battlefield — or on a fallen enemy if one is conveniently sized — and arranges himself into a heroic silhouette. Chest out, feathers perfect, amber eyes staring into the middle distance. He holds this pose for an uncomfortable length of time. Narrate the aftermath as Geralt turns a bloody battle into a portrait session.`,
  },
  {
    id: 'preening-8',
    category: 'preening',
    icon: '🌸',
    title: 'Flower Crown',
    description: 'Someone puts flowers on Geralt.',
    prompt: `Someone — perhaps Momo, perhaps a brave child — has placed a flower crown on Geralt's head. He freezes. His eyes widen. He cannot see it, but he can feel it, and some ancient instinct tells him he looks magnificent. He walks with exaggerated regality, as if the flowers have crowned him king. Narrate his transformation into floral royalty and the party's reaction to the most majestic owlbear who ever lived.`,
  },

  // ── CHAOS (9) ──
  {
    id: 'chaos-1',
    category: 'chaos',
    icon: '🌪️',
    title: 'Midnight Zoomies',
    description: 'Geralt gets a burst of chaotic energy at the worst time.',
    prompt: `It is 3 AM and Geralt has the zoomies. The 400-pound owlbear is sprinting in circles around camp, crashing through tents, scattering equipment, and making excited hooting noises. He is having the time of his life. Everyone else is having the opposite. Narrate the chaos, the property damage, and the party's futile attempts to contain an ecstatic owlbear.`,
  },
  {
    id: 'chaos-2',
    category: 'chaos',
    icon: '📦',
    title: 'If It Fits, I Sits',
    description: 'Geralt tries to fit into an impossibly small space.',
    prompt: `Geralt has decided he needs to be inside something far too small for him — a barrel, a crate, a doorway, someone's tent. He is currently wedged halfway in, refusing to back out on principle. His back half sticks out comically. He seems perfectly content. Narrate this spatial impossibility and the structural damage being inflicted.`,
  },
  {
    id: 'chaos-3',
    category: 'chaos',
    icon: '🫗',
    title: 'Table Sweep',
    description: 'Geralt knocks things off a surface while making eye contact.',
    prompt: `Geralt is standing next to a table / shelf / ledge covered in items. He makes direct eye contact with the nearest party member. Then, slowly, deliberately, he extends one massive paw and pushes something off the edge. It crashes. He does not break eye contact. He reaches for the next item. Narrate this act of calculated chaos and the victim's helpless reaction.`,
  },
  {
    id: 'chaos-4',
    category: 'chaos',
    icon: '🧶',
    title: 'Rope Catastrophe',
    description: 'Geralt discovers the party\'s rope supply.',
    prompt: `Geralt has found a coil of rope and his entire brain has been replaced by the urge to destroy it. He is rolling, tangling, biting, and flailing with 400 pounds of enthusiasm. The rope is now wrapped around three tents, a tree, and at least one party member's leg. Narrate the escalating disaster and the rope's total annihilation.`,
  },
  {
    id: 'chaos-5',
    category: 'chaos',
    icon: '🔔',
    title: 'Attention Sabotage',
    description: 'Someone else is getting attention and Geralt won\'t allow it.',
    prompt: `Another party member is having a moment — giving a speech, receiving praise, having a tender interaction. Geralt cannot allow this. He begins making increasingly loud noises, knocking things over, or physically inserting himself into the situation until all attention returns to where it belongs: him. Narrate this jealous sabotage.`,
  },
  {
    id: 'chaos-6',
    category: 'chaos',
    icon: '💥',
    title: 'Dramatic Entrance',
    description: 'Geralt bursts through something for no reason.',
    prompt: `There was a perfectly good door / opening / path available. Geralt chose violence instead. He crashes through a wall / hedge / market stall with the energy of someone making a point. He emerges from the wreckage, shakes off the debris, and struts forward as if this was always the plan. Narrate the entrance, the destruction, and Geralt's complete lack of remorse.`,
  },
  {
    id: 'chaos-7',
    category: 'chaos',
    icon: '🗺️',
    title: 'Map Destroyer',
    description: 'Geralt sits on the party\'s important documents.',
    prompt: `The party has carefully laid out a map / important document / quest notice on the ground to study. Geralt sees a flat surface. Geralt sits on the flat surface. All 400 pounds, directly in the center, completely covering every important detail. He is now grooming himself. He will not be moved. Narrate the party's despair as critical information disappears beneath a mountain of feathers and smugness.`,
  },
  {
    id: 'chaos-8',
    category: 'chaos',
    icon: '🍖',
    title: 'The Food Heist',
    description: 'Geralt steals an entire meal.',
    prompt: `The party's dinner was briefly unattended. Briefly. In that window, Geralt has consumed / is currently consuming the entire thing. He is not even chewing. He is making aggressive eye contact with whoever is closest, daring them to say something, while inhaling food at a rate that defies biology. Narrate the heist, the caloric devastation, and what the party will eat now.`,
  },
  {
    id: 'chaos-9',
    category: 'chaos',
    icon: '🎪',
    title: 'Market Day Terror',
    description: 'Geralt is taken through a crowded area.',
    prompt: `Someone decided it would be fine to bring Geralt through a busy market / town square / festival. It is not fine. He has knocked over three stalls, terrified a horse, eaten something he shouldn't have, and is currently wearing a stolen tapestry like a cape. The screaming hasn't stopped. Narrate the rolling catastrophe and the party's attempts at damage control.`,
  },

  // ── NAP & TERRITORY (9) ──
  {
    id: 'nap-1',
    category: 'nap',
    icon: '😴',
    title: 'The Inconvenient Nap',
    description: 'Geralt falls asleep in the worst possible spot.',
    prompt: `Geralt has decided to nap. Unfortunately, he has chosen the doorway / the path / the middle of the road / someone's bed. He is immovable. 400 pounds of sleeping owlbear, snoring gently, one eye occasionally cracking open if anyone gets too close. He will not be moved. Narrate the party's attempts to work around this feathered roadblock.`,
  },
  {
    id: 'nap-2',
    category: 'nap',
    icon: '🏰',
    title: 'Territorial Claim',
    description: 'Geralt decides something belongs to him now.',
    prompt: `Geralt has claimed a new piece of territory — a chair, a specific patch of ground, an entire room. He marks it by rubbing his scent glands on every surface, then positions himself in the exact center with an expression that dares anyone to dispute his sovereignty. Narrate the claim-staking ritual and the former occupant's reaction.`,
  },
  {
    id: 'nap-3',
    category: 'nap',
    icon: '🫠',
    title: 'Sunbeam Worship',
    description: 'Geralt finds a patch of sunlight and melts.',
    prompt: `A beam of sunlight has appeared and Geralt has ceased to be a predator. He is now a puddle. He has flopped onto his side in the warm spot, belly exposed, feathers splayed, making a continuous low rumbling that might be the owlbear equivalent of purring. He is completely defenseless and completely unbothered. Narrate this moment of pure bliss.`,
  },
  {
    id: 'nap-4',
    category: 'nap',
    icon: '🛏️',
    title: 'Bed Thief',
    description: 'Geralt steals someone\'s sleeping spot.',
    prompt: `A party member steps away from their bedroll for one moment. ONE moment. Geralt is now in it. All 400 pounds of him, curled into a remarkably tight ball considering his size, feathers fluffed, eyes closed in contentment. This is his bed now. It was always his bed. Narrate the theft and the victim's attempt to reclaim their sleeping arrangements.`,
  },
  {
    id: 'nap-5',
    category: 'nap',
    icon: '⚔️',
    title: 'Guard Duty Nap',
    description: 'Geralt falls asleep on watch.',
    prompt: `Geralt was assigned to help with guard duty. He lasted approximately four minutes before his eyes glazed over, his head drooped, and he began snoring with his face pressed against the ground. If a threat appears, the party's first warning will be Geralt startling awake and screaming — which, to be fair, would scare off most things. Narrate the failure of guard duty.`,
  },
  {
    id: 'nap-6',
    category: 'nap',
    icon: '🧊',
    title: 'Cold Weather Demands',
    description: 'Geralt demands warmth from the party.',
    prompt: `It is cold and Geralt has decided this is everyone else's problem. He presses his massive body against the nearest warm person, shoving them aside to get closer to the fire, and makes pitiful chirping sounds until someone covers him with a blanket. He could survive a blizzard with his natural insulation. He simply chooses not to. Narrate the dramatic cold-weather theatrics.`,
  },
  {
    id: 'nap-7',
    category: 'nap',
    icon: '🏠',
    title: 'Inn Room Takeover',
    description: 'Geralt claims an entire inn room.',
    prompt: `The party has booked rooms at an inn. Geralt has decided that one room is insufficient. He has taken over a second room — specifically, the one someone else was assigned. He is sprawled diagonally across the bed, which is creaking dangerously under his weight. His feathers are everywhere. He has broken the nightstand. He is sleeping peacefully. Narrate the innkeeper's reaction and the roommate's displacement.`,
  },
  {
    id: 'nap-8',
    category: 'nap',
    icon: '🌳',
    title: 'The Perfect Perch',
    description: 'Geralt climbs somewhere he absolutely shouldn\'t.',
    prompt: `Geralt's owl instincts have kicked in. He has climbed to an elevated position — a large tree branch, a roof, a rocky ledge — that was absolutely not designed to support 400 pounds. Ominous creaking fills the air. He looks perfectly content up there and has no intention of coming down. Narrate the structural crisis and the party's growing alarm as physics begins to assert itself.`,
  },
  {
    id: 'nap-9',
    category: 'nap',
    icon: '🚪',
    title: 'The Door Guardian',
    description: 'Geralt blocks an exit and won\'t move.',
    prompt: `Geralt has chosen to sleep directly in front of the only exit. This was not a strategic decision — he simply found the draft pleasant. Now the party is effectively imprisoned by a snoring owlbear. Climbing over him risks waking him. Going around him is architecturally impossible. Narrate the party's increasingly creative escape plans and Geralt's oblivious slumber.`,
  },

  // ── BATTLE (8) ──
  {
    id: 'battle-1',
    category: 'battle',
    icon: '🦁',
    title: 'Battle Roar',
    description: 'Geralt announces himself to combat with maximum drama.',
    prompt: `Combat has started and Geralt has opinions about it. He rears up to his full, terrifying height, feathers bristling into a corona of fury, and unleashes a roar-screech hybrid that rattles teeth and shakes loose leaves from nearby trees. It is the sound of a bear and an owl disagreeing about who gets to be louder. Narrate this sonic devastation, the enemy's morale check, and the party's ringing ears.`,
  },
  {
    id: 'battle-2',
    category: 'battle',
    icon: '🛡️',
    title: 'The Living Shield',
    description: 'Geralt body-blocks an attack meant for Momo.',
    prompt: `An attack is aimed at Momo. Geralt does not think. Geralt does not calculate. Geralt simply puts his body in the way — all 400 pounds of owlbear absorbing what was meant for his person. He takes the hit, turns his head slowly toward the attacker, and the look in his amber eyes promises that this was the last mistake they will ever make. Narrate the heroic intercept and the terrible reckoning that follows.`,
  },
  {
    id: 'battle-3',
    category: 'battle',
    icon: '😱',
    title: 'Strategic Retreat',
    description: 'Geralt decides this fight isn\'t worth it.',
    prompt: `Geralt has assessed the threat and made a tactical decision: absolutely not. He turns and walks away from the fight with the dignified pace of someone who is definitely not fleeing, just relocating to a more advantageous position (behind the party, under a cart, in a different postal code). Narrate his cowardly yet somehow regal exit and the party's betrayal.`,
  },
  {
    id: 'battle-4',
    category: 'battle',
    icon: '😡',
    title: 'Feather Ruffled',
    description: 'An enemy damages Geralt\'s plumage and pays dearly.',
    prompt: `An enemy attack has done something unforgivable: it messed up Geralt's feathers. The damage to his HP is irrelevant. The damage to his APPEARANCE is a declaration of war. Geralt goes berserk — not because he's hurt, but because he has been aesthetically vandalized. Narrate the primal fury of a vain owlbear whose beauty has been insulted.`,
  },
  {
    id: 'battle-5',
    category: 'battle',
    icon: '🎯',
    title: 'Accidental Friendly Fire',
    description: 'Geralt\'s attack goes hilariously wrong.',
    prompt: `Geralt attempts an attack and misses spectacularly. His claws rake a party member's backpack, his beak snaps shut on a tent pole, or his charge sends him careening into the party's supplies instead of the enemy. He recovers immediately, feathers puffed with indignation, clearly blaming the party's poor positioning for his own failure. Narrate the friendly fire incident and Geralt's absolute refusal to acknowledge fault.`,
  },
  {
    id: 'battle-6',
    category: 'battle',
    icon: '💀',
    title: 'Overkill',
    description: 'Geralt dramatically overdoes it on a weak enemy.',
    prompt: `The enemy was nearly dead. One hit would have finished it. Geralt uses every ounce of his predatory arsenal — beak, claws, body slam, possibly sitting on it — to annihilate something that had maybe 2 HP left. The result is less "combat victory" and more "crime scene." He stands over the remains looking deeply satisfied. Narrate this catastrophic excess of force and the party's traumatized silence.`,
  },
  {
    id: 'battle-7',
    category: 'battle',
    icon: '⏸️',
    title: 'Mid-Combat Nap',
    description: 'Geralt gets bored during a fight.',
    prompt: `The battle has been going on for too many rounds and Geralt has lost interest. Mid-combat, he simply lies down. Not dead. Not unconscious. Bored. He is grooming himself while swords clash around him, occasionally batting at a passing arrow like a cat with a toy. Narrate the party's frustration at their tank checking out of combat to take a bath.`,
  },
  {
    id: 'battle-8',
    category: 'battle',
    icon: '🏅',
    title: 'Victory Parade',
    description: 'Geralt demands recognition after combat.',
    prompt: `The battle is won. Geralt wants credit. All of it. He struts among the fallen enemies, occasionally stepping on one to make sure it's dead (and to look imposing), making triumphant hooting sounds. If anyone else gets congratulated for their role in combat, he makes a louder noise. This is HIS victory. Narrate the one-owlbear victory lap and the party's attempts to share credit.`,
  },

  // ── SOCIAL (8) ──
  {
    id: 'social-1',
    category: 'social',
    icon: '👤',
    title: 'Meeting a Stranger',
    description: 'Geralt encounters a new NPC.',
    prompt: `The party has encountered a new person. Geralt's approach to social interaction is as follows: he walks directly up to the stranger, gets uncomfortably close, and sniffs them aggressively while they freeze in terror. After a thorough olfactory assessment, he either huffs in dismissal (unworthy) or sits on their foot (acceptable). Narrate this deeply unsettling first impression and the NPC's struggle to continue their conversation.`,
  },
  {
    id: 'social-2',
    category: 'social',
    icon: '🏪',
    title: 'Shopkeeper Showdown',
    description: 'Geralt enters a shop and immediately causes problems.',
    prompt: `The party has entered a shop. Geralt has also entered the shop. The shop was not designed for 400-pound owlbears. He has already knocked three things off shelves, is sniffing merchandise with concerning intensity, and has wedged himself into an aisle he cannot back out of. The shopkeeper is calculating property damage in real-time. Narrate the commercial catastrophe and the negotiations that follow.`,
  },
  {
    id: 'social-3',
    category: 'social',
    icon: '👶',
    title: 'Children React',
    description: 'Local children discover the owlbear.',
    prompt: `Local children have spotted Geralt. Unlike sensible adults who flee, children are fearless and fascinated. They are climbing on him, pulling his feathers, asking if they can ride him, and one is trying to look inside his beak. Geralt is enduring this with the martyred patience of a cat surrounded by puppies. He could destroy them all. He does not. Narrate his suffering, his restraint, and the one child he secretly likes.`,
  },
  {
    id: 'social-4',
    category: 'social',
    icon: '🐴',
    title: 'Animal Encounter',
    description: 'Geralt meets another animal and it goes poorly.',
    prompt: `Geralt has encountered another animal — a horse, a dog, a cat, a familiar. The other animal's reaction is [abject terror / aggressive posturing / complete indifference]. Geralt is deeply offended by whichever reaction occurred, because all of them are wrong. He deserves [awe / submission / worship]. Narrate the interspecies disaster and which animal ultimately wins the stare-down.`,
  },
  {
    id: 'social-5',
    category: 'social',
    icon: '🤴',
    title: 'Audience with Nobility',
    description: 'Geralt is present during an important social encounter.',
    prompt: `The party is in a formal social situation — meeting a noble, attending court, negotiating with a faction leader. Geralt is also here. He has already yawned audibly during the host's opening remarks, sniffed the noble's robes, and is now investigating the hors d'oeuvres with the discretion of a wrecking ball. Narrate the party's frantic attempts at damage control during an important diplomatic meeting.`,
  },
  {
    id: 'social-6',
    category: 'social',
    icon: '⛪',
    title: 'Temple Visit',
    description: 'Geralt enters a sacred or quiet space.',
    prompt: `The party enters a temple, library, or other place requiring silence and reverence. Geralt's talons click on the stone floor like gunshots. His breathing echoes. He finds a pew / reading desk and immediately begins sharpening his beak on it. A priest / librarian approaches with a complaint. Geralt blinks at them once, slowly. Narrate the desecration and the clergy's crisis of faith.`,
  },
  {
    id: 'social-7',
    category: 'social',
    icon: '🍺',
    title: 'Tavern Regular',
    description: 'Geralt discovers the concept of a tavern.',
    prompt: `Geralt is in a tavern. He has claimed the spot directly in front of the fire. A patron who was sitting there has been displaced by sheer mass. The barkeep made the mistake of leaving a plate of food unattended. Geralt has eaten everything on three tables and is now staring at the bard with an expression that's either appreciation or a hunting assessment. Narrate the tavern's rapid adjustment to their new apex regular.`,
  },
  {
    id: 'social-8',
    category: 'social',
    icon: '🏥',
    title: 'The Healer Encounter',
    description: 'Someone tries to heal or examine Geralt.',
    prompt: `A healer needs to examine or treat Geralt. Geralt does not understand medicine. He does understand that a stranger is touching him, and he has feelings about this. He alternates between snapping at the healer's hands, pressing his wound toward them expectantly, and making pitiful trilling sounds that no 400-pound apex predator should be capable of. Narrate the world's most difficult patient and the healer's fraying sanity.`,
  },

  // ── ENVIRONMENT (8) ──
  {
    id: 'environment-1',
    category: 'environment',
    icon: '🌧️',
    title: 'Rain Tantrum',
    description: 'Geralt encounters rain and decides it\'s a personal attack.',
    prompt: `It is raining. Geralt takes this personally. His feathers are wet. His dignity is soaked. He hunches his shoulders, flattens his ears, and walks with the energy of someone who has been betrayed by the sky itself. He keeps shaking off water onto whoever is nearest, not accidentally. Narrate his operatic suffering and the party's inability to explain weather patterns to an owlbear.`,
  },
  {
    id: 'environment-2',
    category: 'environment',
    icon: '❄️',
    title: 'Snow Discovery',
    description: 'Geralt experiences snow for the first time (or acts like it).',
    prompt: `Geralt has encountered snow. His first step sinks past his ankle and he recoils as if the ground has betrayed him. He paws at it. Bites it. Gets a faceful and sneezes explosively. Then something clicks in his prehistoric brain and he is ROLLING in it, making owlbear snow angels, chomping mouthfuls of powder, and hooting with unhinged joy. Narrate the journey from betrayal to euphoria.`,
  },
  {
    id: 'environment-3',
    category: 'environment',
    icon: '⛈️',
    title: 'Thunder Reaction',
    description: 'Geralt hears thunder and has a complex response.',
    prompt: `Thunder rolls across the sky. Geralt — a 400-pound apex predator who has killed things with his face — flinches. His feathers puff. His eyes go wide. He presses himself against Momo's side and tries to make himself as small as 400 pounds can be. He is not afraid. He is simply... choosing to be closer to his person. For strategic reasons. Narrate the bravest cowardice in the natural world.`,
  },
  {
    id: 'environment-4',
    category: 'environment',
    icon: '🔥',
    title: 'Campfire Connoisseur',
    description: 'Geralt has opinions about the campfire.',
    prompt: `The party has built a campfire. Geralt has positioned himself at the exact distance where maximum warmth meets minimum singed feathers. If someone adds wood and the fire changes, he repositions with annoyed precision. If the fire dies down, he stares at whoever is responsible with undisguised contempt. This fire is his now, and its maintenance is everyone else's sacred duty. Narrate the tyranny of temperature.`,
  },
  {
    id: 'environment-5',
    category: 'environment',
    icon: '🌊',
    title: 'Water Crossing',
    description: 'Geralt must cross a body of water.',
    prompt: `The party needs to cross water. Geralt does not want to cross water. He stands at the edge, extends one paw, touches the surface, recoils, and looks at Momo with an expression that clearly says "carry me." He is 400 pounds. He will not be carried. But he will stand here until someone solves this problem for him. Narrate the aquatic standoff and whatever creative solution the party devises.`,
  },
  {
    id: 'environment-6',
    category: 'environment',
    icon: '✨',
    title: 'Magic Curiosity',
    description: 'Geralt encounters a magical effect and investigates.',
    prompt: `Something magical is happening nearby — glowing runes, floating lights, a shimmering portal. Geralt is fascinated. His head tilts, his pupils dilate, and he begins creeping toward it with the curiosity of a cat approaching a cucumber. He extends one cautious paw. He touches the magic. Narrate what happens when 400 pounds of owlbear meets arcane forces and whether the party intervenes in time.`,
  },
  {
    id: 'environment-7',
    category: 'environment',
    icon: '🕸️',
    title: 'Dungeon Complainer',
    description: 'Geralt hates the current dungeon environment.',
    prompt: `The party is in a dungeon and Geralt is having the worst time. It's dark (fine, he can see). It's cramped (not fine, he's enormous). There are cobwebs in his feathers. Something dripped on him. The floor is damp. He is broadcasting misery through every huff, grumble, and pointed pause at obstacles too small for him. Narrate the world's largest, angriest dungeon crawler and the trail of complaints he leaves behind.`,
  },
  {
    id: 'environment-8',
    category: 'environment',
    icon: '🌸',
    title: 'Spring Awakening',
    description: 'Geralt discovers a beautiful meadow or garden.',
    prompt: `The party emerges into a beautiful meadow / garden / clearing full of flowers and soft grass. Geralt stops. His feathers relax. His eyes soften. Without warning, he flops onto his side in the grass and begins rolling back and forth, legs in the air, making sounds that can only be described as giggling if owlbears could giggle. For one perfect moment, the apex predator is just a big, happy animal in a field of flowers. Narrate this unexpected joy.`,
  },

  // ── PARTY DYNAMICS (8) ──
  {
    id: 'party-1',
    category: 'party',
    icon: '🤝',
    title: 'Choosing Favorites',
    description: 'Geralt clearly prefers one party member over others.',
    prompt: `Geralt has decided he likes one specific party member (besides Momo) and hates the rest. The chosen one receives head nudges, shared kills, and permission to exist within three feet. Everyone else gets the slow blink of cosmic indifference. Narrate who Geralt has chosen, why (it's arbitrary), and how the rejected party members cope with being deemed unworthy.`,
  },
  {
    id: 'party-2',
    category: 'party',
    icon: '😤',
    title: 'Grudge Holder',
    description: 'Geralt remembers a slight from sessions ago.',
    prompt: `Someone in the party wronged Geralt at some point in the past — stepped on his tail, ate the last piece of meat, pushed him out of a doorway. Geralt has not forgotten. Every interaction with this person is tinged with a level of petty malice that is remarkable for a creature with an Intelligence of 3. Narrate the ancient grudge, the petty acts of revenge, and the victim's confusion about what they did wrong.`,
  },
  {
    id: 'party-3',
    category: 'party',
    icon: '🏋️',
    title: 'Competitive Streak',
    description: 'Geralt tries to out-do a party member.',
    prompt: `A party member did something impressive and Geralt has decided this is a competition. If they lifted something heavy, Geralt lifts something heavier (possibly a party member). If they killed an enemy, Geralt kills two. If they jumped over a gap, Geralt attempts to jump further (results may vary at 400 pounds). Narrate this one-sided rivalry and the increasingly dangerous attempts to prove superiority.`,
  },
  {
    id: 'party-4',
    category: 'party',
    icon: '🤢',
    title: 'The Weak Link',
    description: 'Geralt decides a party member is useless.',
    prompt: `Geralt has identified the party member he considers weakest and treats them accordingly — standing in front of them during danger (protective? condescending? both?), steering them away from edges with his body, and occasionally picking up their dropped items and carrying them like a parent with a forgetful toddler. Narrate the aggressive babysitting and the victim's deteriorating self-esteem.`,
  },
  {
    id: 'party-5',
    category: 'party',
    icon: '🎉',
    title: 'Pack Celebration',
    description: 'The party celebrates and Geralt participates... somehow.',
    prompt: `The party is celebrating a victory / milestone / successful quest. Geralt does not understand celebrations but he understands energy. He is hooting, stomping, headbutting people affectionately (with enough force to bruise), and has stolen someone's drink (he doesn't know what alcohol is, but he likes the attention). Narrate the owlbear's chaotic participation in social rituals he doesn't comprehend.`,
  },
  {
    id: 'party-6',
    category: 'party',
    icon: '🩹',
    title: 'Injured Party Member',
    description: 'Geralt reacts to someone in the party being hurt.',
    prompt: `A party member (not Momo) has been seriously injured. Geralt's reaction depends entirely on his opinion of that person. If he likes them: he stands guard, growling at anyone who approaches, gently nudging them with his beak. If he dislikes them: he watches with detached curiosity, as if observing nature taking its course. Narrate which reaction occurs and the injured party member's feelings about being judged by an owlbear during their worst moment.`,
  },
  {
    id: 'party-7',
    category: 'party',
    icon: '📢',
    title: 'The Mediator',
    description: 'Party members are arguing and Geralt intervenes.',
    prompt: `Two party members are arguing. Geralt does not care about the content of the disagreement. He cares that it is loud and it is near him and it is interrupting his rest. He stands up, walks between the arguers, and screech-hoots at a volume that makes the disagreement immediately irrelevant. Everyone is now focused on the angry owlbear instead. Problem solved. Narrate this aggressive peacekeeping and its effectiveness.`,
  },
  {
    id: 'party-8',
    category: 'party',
    icon: '🫡',
    title: 'Following Orders (Poorly)',
    description: 'Someone gives Geralt a command and he sort of obeys.',
    prompt: `Someone has given Geralt a command — "stay," "come," "guard this," "don't eat that." Geralt understands the command. He makes eye contact to confirm he heard it. Then he does approximately 40% of what was asked, in his own time, with modifications he considers improvements. "Stay" becomes "stay but move slightly." "Guard this" becomes "sit on this." "Don't eat that" becomes "eat it slower." Narrate the gap between instruction and execution.`,
  },
];
