project_id = "rkkgmonjfvncpvlzsojw"

[functions.narrative-forge]
verify_jwt = false

[functions.chronicle-sync]
verify_jwt = false

[functions.oracle-assistant]
verify_jwt = false

[functions.combat-log-synthesize]
verify_jwt = false

[functions.homebrew-assistant]
verify_jwt = false

[functions.party-link]
verify_jwt = false

[functions.ai-dm]
verify_jwt = false

[functions.ai-dm-summarize]
verify_jwt = false
