// Base Equipment Items (Greek Heroes Set)
import { EquipmentItem, SetInfo } from './types';

export const sampleEquipment: EquipmentItem[] = [
  {
    id: 'spartan-war-helm',
    name: 'Spartan War Helm',
    slotType: 'head',
    rarity: 'rare',
    level: 15,
    icon: 'Crown',
    stats: { ac: 2 },
    weight: 4,
    value: 250,
    description: 'A battle-worn helm bearing the marks of countless Spartan victories.',
    lore: 'Forged in the fires of Sparta, this helm has witnessed the fall of empires.',
    setId: 'greek-heroes',
    setName: 'Greek Heroes Set',
  },
  {
    id: 'greek-heroes-cuirass',
    name: 'Greek Heroes Cuirass',
    slotType: 'chest',
    rarity: 'epic',
    level: 18,
    icon: 'Shield',
    stats: { ac: 5 },
    properties: ['Heavy Armor'],
    weight: 25,
    value: 500,
    description: 'Legendary armor said to have been worn by the heroes of old.',
    setId: 'greek-heroes',
    setName: 'Greek Heroes Set',
  },
  {
    id: 'mercenary-gauntlets',
    name: 'Mercenary Gauntlets',
    slotType: 'arms',
    rarity: 'rare',
    level: 12,
    icon: 'Hand',
    stats: { ac: 1, attackBonus: 1 },
    weight: 2,
    value: 150,
    description: 'Reinforced gauntlets favored by hired blades across Greece.',
    setId: 'greek-heroes',
    setName: 'Greek Heroes Set',
  },
  {
    id: 'belt-of-immortal',
    name: 'Belt of the Immortal',
    slotType: 'waist',
    rarity: 'epic',
    level: 16,
    icon: 'CircleDot',
    stats: { ac: 2, constitution: 1 },
    enchantments: [
      { name: 'Undying Fortitude', description: 'Once per long rest, drop to 1 HP instead of 0' },
    ],
    weight: 1,
    value: 400,
    description: 'A belt woven with threads said to be from the Fates themselves.',
    setId: 'greek-heroes',
    setName: 'Greek Heroes Set',
  },
  {
    id: 'spartan-war-greaves',
    name: 'Spartan War Greaves',
    slotType: 'legs',
    rarity: 'rare',
    level: 15,
    icon: 'Footprints',
    stats: { ac: 3, movement: 5 },
    weight: 4,
    value: 200,
    description: 'Bronze greaves that have marched across countless battlefields.',
    setId: 'greek-heroes',
    setName: 'Greek Heroes Set',
  },
  {
    id: 'sword-of-damokles',
    name: 'Sword of Damokles',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Sword',
    stats: { damage: '2d6+3', attackBonus: 2 },
    properties: ['Magical', 'Versatile'],
    enchantments: [
      { name: 'Impending Doom', description: '+1d6 damage on critical hits' },
      { name: 'Favor of Fortune', description: 'Advantage on death saving throws' },
    ],
    weight: 3,
    value: 2500,
    description: 'A blade that hangs by a thread over the heads of tyrants.',
    lore: 'Legend says this sword was gifted by the gods to remind mortals of the fragility of power.',
  },
  {
    id: 'spear-of-leonidas',
    name: 'Spear of Leonidas',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Axe',
    stats: { damage: '1d8+2', attackBonus: 3 },
    properties: ['Magical', 'Reach', 'Thrown'],
    enchantments: [
      { name: 'Spartan Legacy', description: 'Advantage on attacks when outnumbered' },
      { name: "Thermopylae's Stand", description: '+2 AC when at half HP or lower' },
    ],
    weight: 4,
    value: 3000,
    description: 'The legendary spear wielded by King Leonidas at Thermopylae.',
    lore: 'This spear has tasted the blood of immortals and mortals alike.',
  },
  {
    id: 'hades-bow',
    name: "Hades's Bow",
    slotType: 'ranged_weapon',
    rarity: 'legendary',
    level: 18,
    icon: 'Target',
    stats: { damage: '1d8+1d6🔥' },
    properties: ['Magical', 'Ammunition'],
    enchantments: [
      { name: 'Hellfire Arrows', description: 'Arrows deal an additional 1d6 fire damage' },
      { name: 'Soul Sight', description: 'Can see invisible creatures within 60 feet' },
    ],
    weight: 2,
    value: 2000,
    description: 'A bow forged in the depths of the Underworld.',
  },
  {
    id: 'eye-of-horus',
    name: 'Eye of Horus',
    slotType: 'amulet',
    rarity: 'epic',
    level: 14,
    icon: 'Gem',
    stats: { perception: 2, wisdom: 1 },
    enchantments: [
      { name: 'Divine Sight', description: 'Advantage on Perception checks' },
    ],
    weight: 0.1,
    value: 350,
    description: 'An ancient amulet bearing the all-seeing eye.',
  },
  {
    id: 'ring-of-protection',
    name: 'Ring of Protection',
    slotType: 'ring1',
    rarity: 'epic',
    level: 10,
    icon: 'Circle',
    stats: { ac: 1, saves: 1 },
    weight: 0,
    value: 300,
    description: 'A simple silver band that provides an aura of protection.',
  },
];

// Base set definitions
export const baseSetDefinitions: SetInfo[] = [
  {
    id: 'greek-heroes',
    name: 'Greek Heroes Set',
    pieces: ['spartan-war-helm', 'greek-heroes-cuirass', 'belt-of-immortal', 'spartan-war-greaves', 'mercenary-gauntlets'],
    bonuses: [
      { setId: 'greek-heroes', setName: 'Greek Heroes Set', piecesRequired: 2, bonus: '+10 movement speed' },
      { setId: 'greek-heroes', setName: 'Greek Heroes Set', piecesRequired: 3, bonus: 'Advantage on Athletics checks' },
      { setId: 'greek-heroes', setName: 'Greek Heroes Set', piecesRequired: 4, bonus: '+2 Strength' },
      { setId: 'greek-heroes', setName: 'Greek Heroes Set', piecesRequired: 5, bonus: 'Heroic Strike: Once per day, deal maximum damage' },
    ],
  },
];
