// Custom Armor Sets - 12 Complete Sets
import { EquipmentItem, SetInfo } from './types';

// =============================================================================
// COMMON ARMOR SETS (3 Sets)
// =============================================================================

// Set 1: Novice's Shadow Ensemble
export const noviceShadowSet: EquipmentItem[] = [
  {
    id: 'novice_shadow_hood',
    name: "Novice's Shadow Hood",
    slotType: 'head',
    rarity: 'common',
    level: 1,
    icon: '🎭',
    description: 'Simple dark hood that conceals the face in shadows.',
    stats: { stealthBonus: 1 },
    weight: 0.5,
    value: 10,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
  {
    id: 'novice_shadow_wraps',
    name: "Novice's Shadow Wraps",
    slotType: 'chest',
    rarity: 'common',
    level: 1,
    icon: '🥋',
    description: 'Simple dark cloth wraps favored by initiates. Lightweight and silent, but offers minimal protection.',
    stats: { ac: 1, stealthBonus: 1 },
    weight: 3,
    value: 25,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
  {
    id: 'novice_shadow_bracers',
    name: "Novice's Shadow Bracers",
    slotType: 'arms',
    rarity: 'common',
    level: 1,
    icon: '🤜',
    description: 'Cloth wraps reinforced with thin leather strips.',
    stats: { unarmedDamageBonus: 1 },
    weight: 0.5,
    value: 8,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
  {
    id: 'novice_utility_belt',
    name: "Novice's Utility Belt",
    slotType: 'waist',
    rarity: 'common',
    level: 1,
    icon: '🎒',
    description: 'Basic leather belt with pouches for tools and poisons.',
    stats: { carryCapacity: 5, toolSlots: 3 },
    weight: 1,
    value: 12,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
  {
    id: 'novice_shadow_pants',
    name: "Novice's Shadow Pants",
    slotType: 'legs',
    rarity: 'common',
    level: 1,
    icon: '👖',
    description: 'Dark, flexible pants designed for silent movement.',
    stats: { movement: 5 },
    weight: 1,
    value: 15,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
  {
    id: 'initiate_guild_token',
    name: "Initiate's Guild Token",
    slotType: 'amulet',
    rarity: 'common',
    level: 1,
    icon: '🪙',
    description: 'A simple bronze medallion marking guild membership.',
    stats: { guildReputation: 1 },
    weight: 0.1,
    value: 5,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
  {
    id: 'ring_of_silent_steps',
    name: 'Ring of Silent Steps',
    slotType: 'ring1',
    rarity: 'common',
    level: 1,
    icon: '💍',
    description: 'A plain iron ring that muffles footsteps slightly.',
    stats: { stealthBonus: 1 },
    weight: 0,
    value: 20,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
  {
    id: 'ring_of_steady_hands',
    name: 'Ring of Steady Hands',
    slotType: 'ring2',
    rarity: 'common',
    level: 1,
    icon: '💍',
    description: 'Helps steady the hands for precise work.',
    stats: { sleightOfHandBonus: 1 },
    weight: 0,
    value: 20,
    setId: 'novice-shadow',
    setName: "Novice's Shadow Ensemble",
  },
];

// Set 2: Street Runner's Kit
export const streetRunnerSet: EquipmentItem[] = [
  {
    id: 'street_runner_cap',
    name: "Street Runner's Cap",
    slotType: 'head',
    rarity: 'common',
    level: 2,
    icon: '🧢',
    description: 'Worn leather cap that helps blend into urban crowds.',
    stats: { disguiseBonus: 1 },
    weight: 0.3,
    value: 8,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
  {
    id: 'street_runner_leathers',
    name: "Street Runner's Leathers",
    slotType: 'chest',
    rarity: 'common',
    level: 2,
    icon: '🧥',
    description: 'Worn leather armor designed for urban navigation. Reinforced at the elbows and knees for climbing.',
    stats: { ac: 2, dexterity: 1 },
    weight: 5,
    value: 35,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
  {
    id: 'street_runner_gloves',
    name: "Street Runner's Gloves",
    slotType: 'arms',
    rarity: 'common',
    level: 2,
    icon: '🧤',
    description: 'Fingerless gloves with reinforced palms for climbing.',
    stats: { athleticsBonus: 1 },
    weight: 0.2,
    value: 10,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
  {
    id: 'street_runner_sash',
    name: "Street Runner's Sash",
    slotType: 'waist',
    rarity: 'common',
    level: 2,
    icon: '🎗️',
    description: 'Colorful sash that helps blend into market crowds.',
    stats: { disguiseBonus: 1 },
    weight: 0.2,
    value: 5,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
  {
    id: 'street_runner_boots',
    name: "Street Runner's Boots",
    slotType: 'legs',
    rarity: 'common',
    level: 2,
    icon: '👢',
    description: 'Soft-soled boots perfect for rooftop running.',
    stats: { acrobaticsBonus: 1, movement: 5 },
    weight: 1,
    value: 18,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
  {
    id: 'lucky_street_charm',
    name: 'Lucky Street Charm',
    slotType: 'amulet',
    rarity: 'common',
    level: 2,
    icon: '🍀',
    description: 'A small trinket believed to bring good fortune.',
    stats: { luckBonus: 1 },
    weight: 0.1,
    value: 10,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
  {
    id: 'ring_of_quick_fingers',
    name: 'Ring of Quick Fingers',
    slotType: 'ring1',
    rarity: 'common',
    level: 2,
    icon: '💍',
    description: 'Enhances manual dexterity for pickpocketing.',
    stats: { sleightOfHandBonus: 2 },
    weight: 0,
    value: 25,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
  {
    id: 'ring_of_the_fence',
    name: 'Ring of the Fence',
    slotType: 'ring2',
    rarity: 'common',
    level: 2,
    icon: '💍',
    description: 'Grants better prices when selling stolen goods.',
    stats: { persuasionBonus: 1, merchantDiscount: 5 },
    weight: 0,
    value: 15,
    setId: 'street-runner',
    setName: "Street Runner's Kit",
  },
];

// Set 3: Apprentice's Concealment Garb
export const apprenticeConcealmentSet: EquipmentItem[] = [
  {
    id: 'apprentice_deep_hood',
    name: "Apprentice's Deep Hood",
    slotType: 'head',
    rarity: 'common',
    level: 3,
    icon: '🧣',
    description: 'A deep hood that shadows the face completely.',
    stats: { disguiseBonus: 2 },
    weight: 0.4,
    value: 12,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
  {
    id: 'apprentice_hooded_cloak',
    name: "Apprentice's Hooded Cloak",
    slotType: 'chest',
    rarity: 'common',
    level: 3,
    icon: '🧥',
    description: 'A simple hooded cloak in muted colors. Helps blend into crowds but provides little physical protection.',
    stats: { disguiseBonus: 2 },
    weight: 2,
    value: 20,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
  {
    id: 'apprentice_hidden_blade_bracer',
    name: "Apprentice's Hidden Blade Bracer",
    slotType: 'arms',
    rarity: 'common',
    level: 3,
    icon: '🔪',
    description: 'Leather bracer with a concealed spring-loaded blade.',
    stats: { hiddenWeaponDamage: '1d4' },
    weight: 1,
    value: 30,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
  {
    id: 'apprentice_tool_belt',
    name: "Apprentice's Tool Belt",
    slotType: 'waist',
    rarity: 'common',
    level: 3,
    icon: '🔧',
    description: 'Well-organized belt with compartments for lockpicks and tools.',
    stats: { thievesToolsBonus: 1, toolSlots: 4 },
    weight: 1,
    value: 15,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
  {
    id: 'apprentice_soft_boots',
    name: "Apprentice's Soft Boots",
    slotType: 'legs',
    rarity: 'common',
    level: 3,
    icon: '👞',
    description: 'Extremely soft-soled boots that make almost no sound.',
    stats: { stealthBonus: 2 },
    weight: 0.8,
    value: 20,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
  {
    id: 'amulet_of_whispers',
    name: 'Amulet of Whispers',
    slotType: 'amulet',
    rarity: 'common',
    level: 3,
    icon: '🗣️',
    description: 'Allows the wearer to speak in barely audible whispers that only intended targets can hear.',
    stats: { communicationRange: 30 },
    weight: 0.1,
    value: 25,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
  {
    id: 'ring_of_lockpicking',
    name: 'Ring of Lockpicking',
    slotType: 'ring1',
    rarity: 'common',
    level: 3,
    icon: '🔑',
    description: "The ring's edge can be used as an improvised lockpick.",
    stats: { thievesToolsBonus: 1 },
    weight: 0,
    value: 30,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
  {
    id: 'ring_of_blend',
    name: 'Ring of Blending',
    slotType: 'ring2',
    rarity: 'common',
    level: 3,
    icon: '💍',
    description: 'Helps the wearer blend into any social situation.',
    stats: { deceptionBonus: 1 },
    weight: 0,
    value: 20,
    setId: 'apprentice-concealment',
    setName: "Apprentice's Concealment Garb",
  },
];

// =============================================================================
// UNCOMMON ARMOR SETS (3 Sets)
// =============================================================================

// Set 4: Wetboy's Professional Kit
export const wetboyProfessionalSet: EquipmentItem[] = [
  {
    id: 'wetboy_shadow_mask',
    name: "Wetboy's Shadow Mask",
    slotType: 'head',
    rarity: 'uncommon',
    level: 5,
    icon: '😶',
    description: 'A featureless black mask that obscures identity and grants darkvision.',
    stats: { ac: 1, darkvision: 30 },
    enchantments: [{ name: 'Darkvision', description: 'See 30ft in complete darkness' }],
    weight: 0.3,
    value: 100,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
  {
    id: 'wetboy_reinforced_leathers',
    name: "Wetboy's Reinforced Leathers",
    slotType: 'chest',
    rarity: 'uncommon',
    level: 5,
    icon: '🦺',
    description: 'Dark leather armor with strategic metal plates hidden beneath. Designed for those who work in the shadows.',
    stats: { ac: 4, stealthBonus: 2, initiativeBonus: 1 },
    enchantments: [{ name: 'Silent Movement', description: 'No disadvantage on Stealth' }],
    weight: 8,
    value: 150,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
  {
    id: 'wetboy_poison_delivery_gauntlets',
    name: "Wetboy's Poison Delivery Gauntlets",
    slotType: 'arms',
    rarity: 'uncommon',
    level: 5,
    icon: '🧪',
    description: 'Sleek gloves with hollow fingertips for poison injection.',
    stats: { ac: 1, poisonDamageBonus: '1d4', poisonApplications: 3 },
    enchantments: [{ name: 'Touch Poison Delivery', description: 'Apply poison via touch' }],
    weight: 0.5,
    value: 120,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
  {
    id: 'wetboy_assassin_belt',
    name: "Wetboy's Assassin Belt",
    slotType: 'waist',
    rarity: 'uncommon',
    level: 5,
    icon: '⚫',
    description: 'Black leather belt with hidden compartments for vials and blades.',
    stats: { poisonVialSlots: 6, throwingKnifeSlots: 4, carryCapacity: 10 },
    enchantments: [{ name: 'Quick Draw', description: 'Draw items as free action' }],
    weight: 1,
    value: 80,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
  {
    id: 'wetboy_silent_stride_boots',
    name: "Wetboy's Silent Stride Boots",
    slotType: 'legs',
    rarity: 'uncommon',
    level: 5,
    icon: '🥾',
    description: 'Boots enchanted to make absolutely no sound when walking.',
    stats: { ac: 1, stealthBonus: 3, movement: 10 },
    enchantments: [{ name: 'Silence', description: 'Footsteps make no sound' }],
    weight: 1.5,
    value: 140,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
  {
    id: 'amulet_of_the_wetboy',
    name: 'Amulet of the Wetboy',
    slotType: 'amulet',
    rarity: 'uncommon',
    level: 5,
    icon: '💀',
    description: 'Guild symbol that grants resistance to poison and disease.',
    stats: { poisonResistance: 1 },
    enchantments: [{ name: 'Poison Resistance', description: 'Advantage on poison saves' }],
    weight: 0.1,
    value: 200,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
  {
    id: 'ring_of_the_shadow',
    name: 'Ring of the Shadow',
    slotType: 'ring1',
    rarity: 'uncommon',
    level: 5,
    icon: '💍',
    description: 'Grants the ability to hide in plain sight in dim light.',
    stats: { stealthBonus: 2 },
    enchantments: [{ name: 'Hide in Shadows', description: 'Hide in dim light' }],
    weight: 0,
    value: 150,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
  {
    id: 'ring_of_poison_mastery',
    name: 'Ring of Poison Mastery',
    slotType: 'ring2',
    rarity: 'uncommon',
    level: 5,
    icon: '☠️',
    description: 'Enhances the potency of all poisons applied by the wearer.',
    stats: { poisonDC: 2, poisonDamage: '1d4' },
    enchantments: [{ name: 'Poison Enhancement', description: '+2 poison DC, +1d4 damage' }],
    weight: 0,
    value: 180,
    setId: 'wetboy-professional',
    setName: "Wetboy's Professional Kit",
  },
];

// Set 5: Guild Operative's Formal Attire
export const guildOperativeSet: EquipmentItem[] = [
  {
    id: 'operative_elegant_mask',
    name: "Operative's Elegant Mask",
    slotType: 'head',
    rarity: 'uncommon',
    level: 6,
    icon: '🎭',
    description: 'A beautiful masquerade mask that changes appearance subtly.',
    stats: { charisma: 1, disguiseBonus: 3 },
    enchantments: [{ name: 'Minor Illusion', description: 'Appearance shifts subtly' }],
    weight: 0.2,
    value: 110,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
  {
    id: 'operative_vestments',
    name: "Guild Operative's Vestments",
    slotType: 'chest',
    rarity: 'uncommon',
    level: 6,
    icon: '👔',
    description: 'Elegant clothing with concealed armor plating. Allows the wearer to move freely in high society while staying protected.',
    stats: { ac: 3, charisma: 1, persuasionBonus: 2 },
    enchantments: [{ name: 'Social Camouflage', description: 'Blend into high society' }],
    weight: 4,
    value: 180,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
  {
    id: 'operative_silk_gloves',
    name: "Operative's Silk Gloves",
    slotType: 'arms',
    rarity: 'uncommon',
    level: 6,
    icon: '🧤',
    description: 'Fine silk gloves that leave no fingerprints and enhance dexterity.',
    stats: { sleightOfHandBonus: 3 },
    enchantments: [{ name: 'Traceless Touch', description: 'Leave no fingerprints' }],
    weight: 0.1,
    value: 90,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
  {
    id: 'operative_concealed_sash',
    name: "Operative's Concealed Sash",
    slotType: 'waist',
    rarity: 'uncommon',
    level: 6,
    icon: '🎀',
    description: 'Decorative sash with hidden pockets woven into the fabric.',
    stats: { hiddenItemSlots: 5 },
    enchantments: [{ name: 'Arcane Concealment', description: 'DC 18 to find hidden items' }],
    weight: 0.3,
    value: 70,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
  {
    id: 'operative_dancing_shoes',
    name: "Operative's Dancing Shoes",
    slotType: 'legs',
    rarity: 'uncommon',
    level: 6,
    icon: '👞',
    description: 'Elegant footwear that enhances grace and balance.',
    stats: { acrobaticsBonus: 2, performanceBonus: 2, movement: 5 },
    enchantments: [{ name: 'Feather Fall', description: 'Feather Fall 1/day' }],
    weight: 0.5,
    value: 100,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
  {
    id: 'amulet_of_silver_tongue',
    name: 'Amulet of the Silver Tongue',
    slotType: 'amulet',
    rarity: 'uncommon',
    level: 6,
    icon: '🗨️',
    description: 'Grants eloquence and persuasive power in conversation.',
    stats: { charisma: 1, persuasionBonus: 2, deceptionBonus: 2 },
    enchantments: [{ name: 'Charm Person', description: 'Charm Person 2/day' }],
    weight: 0.1,
    value: 220,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
  {
    id: 'ring_of_noble_bearing',
    name: 'Ring of Noble Bearing',
    slotType: 'ring1',
    rarity: 'uncommon',
    level: 6,
    icon: '👑',
    description: 'Makes the wearer appear of high social standing.',
    stats: { charisma: 1, intimidationBonus: 2 },
    enchantments: [{ name: 'Prestidigitation', description: 'Prestidigitation at will' }],
    weight: 0,
    value: 130,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
  {
    id: 'ring_of_detect_lies',
    name: 'Ring of Detect Lies',
    slotType: 'ring2',
    rarity: 'uncommon',
    level: 6,
    icon: '👁️',
    description: 'Tingles when someone nearby is lying.',
    stats: { insightBonus: 3 },
    enchantments: [{ name: 'Detect Thoughts', description: 'Limited to detecting lies' }],
    weight: 0,
    value: 160,
    setId: 'guild-operative',
    setName: "Guild Operative's Formal Attire",
  },
];

// Set 6: Rooftop Stalker's Climbing Gear
export const rooftopStalkerSet: EquipmentItem[] = [
  {
    id: 'stalker_vision_goggles',
    name: "Stalker's Vision Goggles",
    slotType: 'head',
    rarity: 'uncommon',
    level: 7,
    icon: '🥽',
    description: 'Specialized goggles that enhance vision in darkness and at distance.',
    stats: { darkvision: 60, perceptionBonus: 2 },
    enchantments: [{ name: 'Darkvision', description: '60ft darkvision' }, { name: 'Eagle Vision', description: 'See great distances' }],
    weight: 0.3,
    value: 150,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
  {
    id: 'stalker_garb',
    name: "Rooftop Stalker's Garb",
    slotType: 'chest',
    rarity: 'uncommon',
    level: 7,
    icon: '🎽',
    description: 'Fitted armor designed for vertical movement. Features reinforced grip pads and flexible joints.',
    stats: { ac: 3, athleticsBonus: 2, climbingSpeed: 10 },
    enchantments: [{ name: 'Spider Climb', description: 'Limited spider climbing ability' }],
    weight: 6,
    value: 160,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
  {
    id: 'stalker_climbing_gauntlets',
    name: "Stalker's Climbing Gauntlets",
    slotType: 'arms',
    rarity: 'uncommon',
    level: 7,
    icon: '🧗',
    description: 'Gauntlets with retractable climbing claws and gecko-grip palms.',
    stats: { ac: 1, athleticsBonus: 3, climbingSpeed: 15 },
    enchantments: [{ name: 'Spider Climb', description: 'Hands only spider climb' }],
    weight: 1,
    value: 140,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
  {
    id: 'stalker_grappling_harness',
    name: "Stalker's Grappling Harness",
    slotType: 'waist',
    rarity: 'uncommon',
    level: 7,
    icon: '🪢',
    description: 'Reinforced harness with built-in grappling hook launcher.',
    stats: { grapplingHookRange: 50, ropeLength: 100 },
    enchantments: [{ name: 'Rope Trick', description: 'Rope Trick 1/day' }],
    weight: 3,
    value: 120,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
  {
    id: 'stalker_parkour_boots',
    name: "Stalker's Parkour Boots",
    slotType: 'legs',
    rarity: 'uncommon',
    level: 7,
    icon: '🥾',
    description: 'Boots with shock-absorbing soles that reduce fall damage.',
    stats: { ac: 1, acrobaticsBonus: 3, fallDamageReduction: '2d6', jumpDistance: 10 },
    enchantments: [{ name: 'Jump', description: 'Jump spell 2/day' }],
    weight: 1.5,
    value: 170,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
  {
    id: 'amulet_of_the_eagle',
    name: 'Amulet of the Eagle',
    slotType: 'amulet',
    rarity: 'uncommon',
    level: 7,
    icon: '🦅',
    description: 'Grants eagle-like vision and awareness of surroundings.',
    stats: { perceptionBonus: 3 },
    enchantments: [{ name: 'Eagle Vision', description: 'See from above, advantage on Perception' }],
    weight: 0.1,
    value: 190,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
  {
    id: 'ring_of_sure_grip',
    name: 'Ring of Sure Grip',
    slotType: 'ring1',
    rarity: 'uncommon',
    level: 7,
    icon: '💪',
    description: 'Prevents the wearer from losing grip or being disarmed.',
    stats: { athleticsBonus: 2 },
    enchantments: [{ name: 'Immovable Grip', description: 'Cannot be disarmed' }],
    weight: 0,
    value: 140,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
  {
    id: 'ring_of_feather_falling',
    name: 'Ring of Feather Falling',
    slotType: 'ring2',
    rarity: 'uncommon',
    level: 7,
    icon: '🪶',
    description: 'Automatically activates feather fall when falling.',
    stats: { fallDamageImmunity: 1 },
    enchantments: [{ name: 'Feather Fall', description: 'Automatic feather fall' }],
    weight: 0,
    value: 200,
    setId: 'rooftop-stalker',
    setName: "Rooftop Stalker's Climbing Gear",
  },
];

// =============================================================================
// RARE ARMOR SETS (3 Sets)
// =============================================================================

// Set 7: Master Assassin's Complete Arsenal
export const masterAssassinSet: EquipmentItem[] = [
  {
    id: 'master_eagle_vision_cowl',
    name: "Master's Eagle Vision Cowl",
    slotType: 'head',
    rarity: 'rare',
    level: 10,
    icon: '🦅',
    description: 'Legendary hood that grants supernatural perception, allowing the wearer to see through walls and detect enemies.',
    stats: { ac: 2, perceptionBonus: 4, darkvision: 120 },
    enchantments: [{ name: 'True Seeing', description: 'Limited true seeing' }, { name: 'Detect Evil/Good', description: 'Sense alignment' }],
    weight: 0.5,
    value: 600,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
  {
    id: 'master_assassin_cuirass',
    name: "Master Assassin's Cuirass",
    slotType: 'chest',
    rarity: 'rare',
    level: 10,
    icon: '🛡️',
    description: 'Masterwork armor crafted from shadow-treated leather and mithril threading. Whispers say it was worn by a legendary blade.',
    stats: { ac: 6, stealthBonus: 3, criticalHitBonus: 1 },
    properties: ['Poison Resistance'],
    enchantments: [{ name: 'Blur', description: 'Blur 1/day' }, { name: 'Advantage on Stealth', description: 'Always have advantage on Stealth checks' }],
    weight: 10,
    value: 800,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
  {
    id: 'master_hidden_blade_assembly',
    name: "Master's Hidden Blade Assembly",
    slotType: 'arms',
    rarity: 'rare',
    level: 10,
    icon: '🗡️',
    description: 'Dual hidden blades that extend instantly for assassination. Can be poisoned.',
    stats: { ac: 2, hiddenWeaponDamage: '2d6', sneakAttackDamage: '2d6', poisonApplications: 5 },
    enchantments: [{ name: 'Instant Deploy', description: 'Deploy as free action' }, { name: 'Assassination Critical', description: 'Auto-crit on surprise' }],
    weight: 2,
    value: 700,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
  {
    id: 'master_tool_harness',
    name: "Master's Tool Harness",
    slotType: 'waist',
    rarity: 'rare',
    level: 10,
    icon: '🎒',
    description: 'Masterwork harness with compartments for every tool of the trade.',
    stats: { poisonVialSlots: 10, throwingWeaponSlots: 8, toolSlots: 6, carryCapacity: 20 },
    enchantments: [{ name: 'Bag of Holding', description: 'Limited extra-dimensional storage' }, { name: 'Quick Draw', description: 'Draw any item as free action' }],
    weight: 2,
    value: 500,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
  {
    id: 'master_boots_of_speed',
    name: "Master's Boots of Speed",
    slotType: 'legs',
    rarity: 'rare',
    level: 10,
    icon: '⚡',
    description: 'Enchanted boots that grant supernatural speed and agility.',
    stats: { ac: 2, movement: 20, acrobaticsBonus: 4, stealthBonus: 2 },
    enchantments: [{ name: 'Haste', description: 'Haste 1/day' }, { name: 'Freedom of Movement', description: 'Cannot be restrained' }],
    weight: 1,
    value: 650,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
  {
    id: 'amulet_of_the_creed',
    name: 'Amulet of the Creed',
    slotType: 'amulet',
    rarity: 'rare',
    level: 10,
    icon: '🔺',
    description: 'The sacred symbol of the Brotherhood. Grants protection and marks you as a master.',
    stats: { ac: 1, saves: 2 },
    enchantments: [{ name: 'Protection from Evil/Good', description: 'Constant protection' }, { name: 'Death Ward', description: 'Death Ward 1/week' }],
    weight: 0.2,
    value: 900,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
  {
    id: 'ring_of_invisibility',
    name: 'Ring of Invisibility',
    slotType: 'ring1',
    rarity: 'rare',
    level: 10,
    icon: '👻',
    description: 'Grants true invisibility for short periods.',
    stats: { stealthBonus: 5 },
    enchantments: [{ name: 'Invisibility', description: 'Invisibility 3/day, 1 minute each' }],
    weight: 0,
    value: 800,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
  {
    id: 'ring_of_critical_strikes',
    name: 'Ring of Critical Strikes',
    slotType: 'ring2',
    rarity: 'rare',
    level: 10,
    icon: '💥',
    description: 'Expands critical hit range and damage.',
    stats: { criticalRange: '18-20', criticalDamage: '2d6' },
    enchantments: [{ name: 'Keen Edge', description: 'Crit on 18-20' }, { name: 'Vorpal', description: 'Vorpal on natural 20' }],
    weight: 0,
    value: 850,
    setId: 'master-assassin',
    setName: "Master Assassin's Complete Arsenal",
  },
];

// Set 8: Nightshroud Complete Set
export const nightshroudSet: EquipmentItem[] = [
  {
    id: 'nightshroud_helm',
    name: 'Nightshroud Helm',
    slotType: 'head',
    rarity: 'rare',
    level: 11,
    icon: '🌑',
    description: 'A helm carved from solid shadow. Grants supernatural senses in darkness.',
    stats: { ac: 2, darkvision: 120, blindsight: 30, perceptionBonus: 3 },
    enchantments: [{ name: 'See Invisibility', description: 'See invisible creatures' }, { name: "Devil's Sight", description: 'See in magical darkness' }],
    weight: 1,
    value: 650,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
  {
    id: 'nightshroud_armor',
    name: 'Nightshroud Armor',
    slotType: 'chest',
    rarity: 'rare',
    level: 11,
    icon: '🌑',
    description: 'Black armor that seems to absorb light itself. Grants the wearer supernatural stealth in darkness.',
    stats: { ac: 5, stealthBonus: 4, darkvision: 60 },
    enchantments: [{ name: 'Invisibility in Dim Light', description: 'Invisible in dim light' }, { name: 'Shadow Step', description: 'Shadow Step 2/day' }],
    weight: 12,
    value: 950,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
  {
    id: 'nightshroud_shadow_gauntlets',
    name: 'Nightshroud Shadow Gauntlets',
    slotType: 'arms',
    rarity: 'rare',
    level: 11,
    icon: '👤',
    description: 'Gauntlets that allow the wearer to manipulate shadows as weapons.',
    stats: { ac: 2, necroticDamage: '1d8' },
    enchantments: [{ name: 'Shadow Blade', description: 'Create shadow blade at will' }, { name: 'Darkness', description: 'Darkness 2/day' }],
    weight: 1.5,
    value: 700,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
  {
    id: 'nightshroud_void_sash',
    name: 'Nightshroud Void Sash',
    slotType: 'waist',
    rarity: 'rare',
    level: 11,
    icon: '⚫',
    description: 'A sash woven from the fabric of the Shadowfell itself.',
    stats: { dimensionalStorage: 50, shadowStepRange: 60 },
    enchantments: [{ name: 'Portable Hole', description: 'Shadow dimension storage' }, { name: 'Misty Step', description: 'Misty Step at will in darkness' }],
    weight: 0.5,
    value: 550,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
  {
    id: 'nightshroud_shadow_stride_boots',
    name: 'Nightshroud Shadow Stride Boots',
    slotType: 'legs',
    rarity: 'rare',
    level: 11,
    icon: '👣',
    description: 'Boots that allow the wearer to walk through shadows.',
    stats: { ac: 2, movement: 15, stealthBonus: 4 },
    enchantments: [{ name: 'Pass Without Trace', description: 'Constant pass without trace' }, { name: 'Shadow Walk', description: 'Travel via shadows' }],
    weight: 1,
    value: 720,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
  {
    id: 'amulet_of_shadow_mastery',
    name: 'Amulet of Shadow Mastery',
    slotType: 'amulet',
    rarity: 'rare',
    level: 11,
    icon: '🕳️',
    description: 'Grants complete mastery over shadow magic and darkness.',
    stats: { shadowSpellDC: 3 },
    enchantments: [{ name: 'Control Shadows', description: 'Manipulate shadows at will' }, { name: 'Summon Shadow', description: 'Summon Shadow 1/day' }],
    weight: 0.2,
    value: 1000,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
  {
    id: 'ring_of_the_void',
    name: 'Ring of the Void',
    slotType: 'ring1',
    rarity: 'rare',
    level: 11,
    icon: '⚫',
    description: 'A ring that contains a fragment of pure void.',
    stats: { necroticDamage: '2d6' },
    enchantments: [{ name: 'Disintegrate', description: 'Disintegrate 1/day' }, { name: 'Banishment', description: 'Banish to shadow realm' }],
    weight: 0,
    value: 750,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
  {
    id: 'ring_of_shadow_form',
    name: 'Ring of Shadow Form',
    slotType: 'ring2',
    rarity: 'rare',
    level: 11,
    icon: '👻',
    description: 'Allows the wearer to become a living shadow.',
    stats: { incorporealForm: 3 },
    enchantments: [{ name: 'Gaseous Form', description: 'Shadow gaseous form' }, { name: 'Etherealness', description: 'Limited etherealness' }],
    weight: 0,
    value: 880,
    setId: 'nightshroud',
    setName: 'Nightshroud Complete Set',
  },
];

// Set 9: Phantom's Complete Regalia
export const phantomRegaliaSet: EquipmentItem[] = [
  {
    id: 'phantom_spectral_mask',
    name: "Phantom's Spectral Mask",
    slotType: 'head',
    rarity: 'rare',
    level: 12,
    icon: '👻',
    description: 'A mask that phases between material and ethereal planes.',
    stats: { ac: 2, perceptionBonus: 3 },
    enchantments: [{ name: 'See Ethereal', description: 'See into Ethereal Plane' }, { name: 'Alter Self', description: 'Change face at will' }],
    weight: 0.3,
    value: 680,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
  {
    id: 'phantom_regalia',
    name: "Phantom's Regalia",
    slotType: 'chest',
    rarity: 'rare',
    level: 12,
    icon: '👻',
    description: "Ethereal armor that shifts between corporeal and incorporeal states. Said to have been forged from the essence of a wraith.",
    stats: { ac: 5, stealthBonus: 3, evasionBonus: 2 },
    enchantments: [{ name: 'Misty Step', description: 'Misty Step 3/day' }, { name: 'Pass Without Trace', description: 'Pass Without Trace 1/day' }],
    weight: 8,
    value: 1100,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
  {
    id: 'phantom_phase_gloves',
    name: "Phantom's Phase Gloves",
    slotType: 'arms',
    rarity: 'rare',
    level: 12,
    icon: '🤚',
    description: 'Gloves that allow hands to pass through solid matter.',
    stats: { ac: 2, sleightOfHandBonus: 4 },
    enchantments: [{ name: 'Pass Through Walls', description: 'Hands pass through walls' }, { name: 'Ethereal Pickpocket', description: 'Steal from pockets ethereally' }],
    weight: 0.2,
    value: 650,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
  {
    id: 'phantom_ethereal_sash',
    name: "Phantom's Ethereal Sash",
    slotType: 'waist',
    rarity: 'rare',
    level: 12,
    icon: '💨',
    description: 'A sash that exists partially on the Ethereal Plane.',
    stats: { etherealStorage: 30, phaseSpeed: 10 },
    enchantments: [{ name: 'Blink', description: 'Blink 2/day' }, { name: 'Ethereal Storage', description: 'Store items in Ethereal Plane' }],
    weight: 0.2,
    value: 580,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
  {
    id: 'phantom_ghost_step_boots',
    name: "Phantom's Ghost Step Boots",
    slotType: 'legs',
    rarity: 'rare',
    level: 12,
    icon: '👟',
    description: 'Boots that allow the wearer to walk through walls and float.',
    stats: { ac: 2, movement: 15, levitation: 10 },
    enchantments: [{ name: 'Levitate', description: 'Levitate at will' }, { name: 'Passwall', description: 'Passwall 1/day' }],
    weight: 0.8,
    value: 750,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
  {
    id: 'amulet_of_etherealness',
    name: 'Amulet of Etherealness',
    slotType: 'amulet',
    rarity: 'rare',
    level: 12,
    icon: '🌫️',
    description: 'Grants the ability to shift into the Ethereal Plane.',
    stats: { ghostlyDefense: 2 },
    enchantments: [{ name: 'Etherealness', description: 'Etherealness 2/day (10 min)' }, { name: 'Blink', description: 'Blink at will' }],
    weight: 0.1,
    value: 1050,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
  {
    id: 'ring_of_phasing',
    name: 'Ring of Phasing',
    slotType: 'ring1',
    rarity: 'rare',
    level: 12,
    icon: '💍',
    description: 'Allows the wearer to phase through attacks and obstacles.',
    stats: { evasionBonus: 3 },
    enchantments: [{ name: 'Uncanny Dodge', description: 'Halve damage as reaction' }, { name: 'Phase', description: 'Phase through attacks as reaction' }],
    weight: 0,
    value: 820,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
  {
    id: 'ring_of_the_wraith',
    name: 'Ring of the Wraith',
    slotType: 'ring2',
    rarity: 'rare',
    level: 12,
    icon: '☠️',
    description: 'Grants wraith-like abilities and immunities.',
    stats: { lifeDrain: '1d6' },
    enchantments: [{ name: 'Life Drain', description: 'Drain 1d6 HP per hit' }, { name: 'Incorporeal Movement', description: 'Move through creatures 1/day' }],
    weight: 0,
    value: 900,
    setId: 'phantom-regalia',
    setName: "Phantom's Complete Regalia",
  },
];

// =============================================================================
// EPIC/VERY RARE ARMOR SETS (3 Sets)
// =============================================================================

// Set 10: Ka'kari Bonded Complete Set
export const kakariSet: EquipmentItem[] = [
  {
    id: 'kakari_living_cowl',
    name: "Ka'kari Living Cowl",
    slotType: 'head',
    rarity: 'epic',
    level: 15,
    icon: '⚫',
    description: "The Ka'kari extends to form a perfect hood that enhances all senses.",
    stats: { ac: 3, perceptionBonus: 5, darkvision: 120 },
    enchantments: [{ name: 'True Seeing', description: 'True Seeing always active' }, { name: 'Detect Magic', description: 'Detect Magic at will' }, { name: 'Mind Blank', description: 'Immune to mental intrusion' }],
    weight: 0,
    value: 3000,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
  {
    id: 'kakari_bonded_armor',
    name: "Ka'kari Bonded Armor",
    slotType: 'chest',
    rarity: 'epic',
    level: 15,
    icon: '⚫',
    description: "Living armor that bonds with its wearer, shifting and adapting to threats. Absorbs magical energy and can devour enchantments.",
    stats: { ac: 8, stealthBonus: 5 },
    properties: ['Magic Resistance', 'Adaptive Defense'],
    enchantments: [{ name: 'Devour Magic', description: 'Absorb spell effects' }, { name: 'Perfect Invisibility', description: 'Invisibility at will' }, { name: 'Regeneration', description: '1d6 HP per turn' }, { name: 'Shape-shifting', description: 'Cosmetic transformation' }],
    weight: 0,
    value: 5000,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
  {
    id: 'kakari_devouring_gauntlets',
    name: "Ka'kari Devouring Gauntlets",
    slotType: 'arms',
    rarity: 'epic',
    level: 15,
    icon: '🖤',
    description: 'Gauntlets that can consume and nullify any magic they touch.',
    stats: { ac: 3, unarmedDamage: '2d8' },
    enchantments: [{ name: 'Dispel Magic', description: 'Dispel Magic at will on touch' }, { name: 'Counterspell', description: 'Counterspell as reaction' }, { name: 'Absorb Elements', description: 'Absorb elemental damage' }],
    weight: 0,
    value: 2800,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
  {
    id: 'kakari_void_belt',
    name: "Ka'kari Void Belt",
    slotType: 'waist',
    rarity: 'epic',
    level: 15,
    icon: '⬛',
    description: 'A belt that opens into a pocket dimension, storing unlimited equipment.',
    stats: { storage: 999 },
    enchantments: [{ name: 'Bag of Holding', description: 'Unlimited storage' }, { name: 'Instant Summon', description: 'Summon any stored item instantly' }],
    weight: 0,
    value: 2500,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
  {
    id: 'kakari_shadow_striders',
    name: "Ka'kari Shadow Striders",
    slotType: 'legs',
    rarity: 'epic',
    level: 15,
    icon: '🦶',
    description: 'Boots formed from living darkness that grant impossible speed and mobility.',
    stats: { ac: 3, movement: 40, teleportRange: 120 },
    enchantments: [{ name: 'Haste', description: 'Haste at will' }, { name: 'Dimension Door', description: 'Dimension Door at will' }, { name: 'Air Walk', description: 'Walk on air' }],
    weight: 0,
    value: 3200,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
  {
    id: 'kakari_heart',
    name: "Ka'kari Heart",
    slotType: 'amulet',
    rarity: 'epic',
    level: 15,
    icon: '🖤',
    description: "The core of the Ka'kari bonds with the wearer's heart, granting immortality and power.",
    stats: { constitution: 4, regeneration: '2d6' },
    enchantments: [{ name: 'Regeneration', description: 'Constant regeneration' }, { name: 'Death Ward', description: 'Automatic death ward' }, { name: 'Clone', description: 'Revive after 1 hour if killed' }],
    weight: 0,
    value: 8000,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
  {
    id: 'ring_of_the_night_angel',
    name: 'Ring of the Night Angel',
    slotType: 'ring1',
    rarity: 'epic',
    level: 15,
    icon: '😇',
    description: 'Marks the wearer as the legendary Night Angel, granting divine assassination powers.',
    stats: { assassinateDC: 5 },
    enchantments: [{ name: 'Divine Smite', description: '+4d8 radiant damage' }, { name: 'Assassinate', description: 'Instant kill on crit (DC 20 CON)' }, { name: 'Judgment', description: 'Mark targets for death' }],
    weight: 0,
    value: 4500,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
  {
    id: 'ring_of_devouring',
    name: 'Ring of Devouring',
    slotType: 'ring2',
    rarity: 'epic',
    level: 15,
    icon: '🕳️',
    description: 'Absorbs the essence of slain enemies, growing stronger with each kill.',
    stats: { soulAbsorption: 1 },
    enchantments: [{ name: 'Soul Trap', description: 'Trap souls of slain enemies' }, { name: 'Essence Drain', description: 'Drain life on kill' }, { name: 'Power Absorption', description: '+1 to all stats per 10 kills' }],
    weight: 0,
    value: 5000,
    setId: 'kakari-bonded',
    setName: "Ka'kari Bonded Complete Set",
  },
];

// Set 11: Entreri's Legendary Arsenal
export const entreriSet: EquipmentItem[] = [
  {
    id: 'entreri_assassin_mask',
    name: "Entreri's Assassin Mask",
    slotType: 'head',
    rarity: 'epic',
    level: 16,
    icon: '😈',
    description: 'The feared mask of Artemis Entreri. Strikes terror into the hearts of enemies.',
    stats: { ac: 3, intimidationBonus: 5, perceptionBonus: 4 },
    enchantments: [{ name: 'Fear', description: 'Fear aura at will' }, { name: 'Intimidating Presence', description: '30ft fear aura' }, { name: 'Deathly Glare', description: 'Frighten with a look' }],
    weight: 0.3,
    value: 2800,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
  {
    id: 'entreri_masterwork_leathers',
    name: "Entreri's Masterwork Leathers",
    slotType: 'chest',
    rarity: 'epic',
    level: 16,
    icon: '🗡️',
    description: "Legendary armor worn by the most feared assassin of the Realms. Enhances the wearer's deadly precision and grants preternatural reflexes.",
    stats: { ac: 7, dexterity: 2, initiativeBonus: 3 },
    properties: ['Immune to Surprise'],
    enchantments: [{ name: 'Haste', description: 'Haste 1/day' }, { name: 'Uncanny Dodge', description: 'Halve damage as reaction' }, { name: 'Advantage on Dexterity Saves', description: 'Always have advantage' }],
    weight: 8,
    value: 6500,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
  {
    id: 'entreri_jeweled_dagger_bracer',
    name: "Entreri's Jeweled Dagger Bracer",
    slotType: 'arms',
    rarity: 'epic',
    level: 16,
    icon: '💎',
    description: 'Houses the legendary jeweled dagger, capable of draining life force.',
    stats: { ac: 3, lifeDrain: '2d8', vampiricHealing: 1 },
    enchantments: [{ name: 'Vampiric Touch', description: 'Heal for damage dealt' }, { name: 'Life Steal', description: 'Constant life steal' }, { name: 'Soul Trap', description: 'Trap souls on kill' }],
    weight: 1,
    value: 3500,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
  {
    id: 'entreri_assassin_belt',
    name: "Entreri's Assassin Belt",
    slotType: 'waist',
    rarity: 'epic',
    level: 16,
    icon: '⚫',
    description: 'Contains hidden compartments for every tool of assassination.',
    stats: { poisonVialSlots: 15, weaponSlots: 10, toolSlots: 8, carryCapacity: 30 },
    enchantments: [{ name: 'Instant Access', description: 'Draw any item instantly' }, { name: 'Dimensional Storage', description: 'Extra-dimensional space' }, { name: 'Quick Draw', description: 'Draw weapons as bonus action' }],
    weight: 1,
    value: 2200,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
  {
    id: 'entreri_speed_boots',
    name: "Entreri's Boots of Blinding Speed",
    slotType: 'legs',
    rarity: 'epic',
    level: 16,
    icon: '⚡',
    description: 'Boots that grant superhuman speed and agility, making the wearer a blur.',
    stats: { ac: 3, movement: 30, extraAttacks: 1, acrobaticsBonus: 5 },
    enchantments: [{ name: 'Haste', description: 'Haste at will' }, { name: 'Blur', description: 'Constant blur' }, { name: 'Freedom of Movement', description: 'Cannot be restrained' }],
    weight: 0.8,
    value: 3800,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
  {
    id: 'amulet_of_the_master_assassin',
    name: 'Amulet of the Master Assassin',
    slotType: 'amulet',
    rarity: 'epic',
    level: 16,
    icon: '💀',
    description: 'Symbol of the greatest assassin to ever live. Grants unparalleled killing power.',
    stats: { criticalDamage: '4d6', assassinateDC: 4, sneakAttackDice: '3d6' },
    enchantments: [{ name: 'Assassinate', description: 'Auto-crit on surprise' }, { name: 'Death Strike', description: 'Double damage on crit' }, { name: 'Executioner', description: '+4d6 sneak attack' }],
    weight: 0.2,
    value: 7000,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
  {
    id: 'charon_claw_ring',
    name: "Charon's Claw Ring",
    slotType: 'ring1',
    rarity: 'epic',
    level: 16,
    icon: '🔥',
    description: "Contains a fragment of the legendary sword Charon's Claw.",
    stats: { fireDamage: '3d6' },
    enchantments: [{ name: 'Dispel Magic', description: 'Dispel Magic at will' }, { name: 'Antimagic Blade', description: '10ft antimagic field' }, { name: 'Flame Strike', description: 'Wreath weapons in flame' }],
    weight: 0,
    value: 4200,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
  {
    id: 'ring_of_perfect_precision',
    name: 'Ring of Perfect Precision',
    slotType: 'ring2',
    rarity: 'epic',
    level: 16,
    icon: '🎯',
    description: 'Grants supernatural accuracy and deadly precision.',
    stats: { attackBonus: 3 },
    enchantments: [{ name: 'True Strike', description: 'Constant true strike' }, { name: 'Sharpshooter', description: 'No disadvantage at range' }, { name: 'Never Miss', description: 'Reroll any miss once per turn' }],
    weight: 0,
    value: 5500,
    setId: 'entreri-arsenal',
    setName: "Entreri's Legendary Arsenal",
  },
];

// Set 12: Grandmaster's Legendary Vestments
export const grandmasterSet: EquipmentItem[] = [
  {
    id: 'grandmaster_crown_of_shadows',
    name: "Grandmaster's Crown of Shadows",
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: '👑',
    description: 'A crown forged from crystallized shadows. Grants absolute mastery over darkness and stealth.',
    stats: { ac: 4, intelligence: 3, wisdom: 3, charisma: 3, darkvision: 120 },
    enchantments: [{ name: 'Wish', description: 'Wish 1/week' }, { name: 'True Seeing', description: 'Constant true seeing' }, { name: 'Mind Blank', description: 'Constant mind blank' }, { name: 'Foresight', description: 'Cannot be surprised' }],
    weight: 0.5,
    value: 10000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
  {
    id: 'grandmaster_ceremonial_robes',
    name: "Grandmaster's Ceremonial Robes",
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: '👘',
    description: 'Ancient robes passed down through generations of masters. Woven with threads of pure shadow and moonlight, granting the wearer mastery over darkness.',
    stats: { ac: 9, stealthBonus: 6, strength: 2, dexterity: 2, constitution: 2, intelligence: 2, wisdom: 2, charisma: 2 },
    properties: ['Legendary'],
    enchantments: [{ name: 'True Invisibility', description: 'Invisibility at will' }, { name: 'Teleportation', description: 'Teleport unlimited' }, { name: 'Shadow Clone', description: 'Create duplicates' }, { name: 'Death Ward', description: 'Automatic death ward' }, { name: 'Legendary Resistance', description: '3/day' }],
    weight: 2,
    value: 15000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
  {
    id: 'grandmaster_gloves_of_mastery',
    name: "Grandmaster's Gloves of Mastery",
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: '🥋',
    description: 'Gloves that grant perfect mastery of all weapons and tools.',
    stats: { ac: 4, attackBonus: 4, damage: '4', unarmedDamage: '3d10' },
    enchantments: [{ name: 'Weapon Mastery', description: 'Proficient with all weapons' }, { name: 'Disarm Immunity', description: 'Cannot be disarmed' }, { name: 'Flurry of Blows', description: 'Monk flurry ability' }],
    weight: 0.3,
    value: 8000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
  {
    id: 'grandmaster_sash_of_infinity',
    name: "Grandmaster's Sash of Infinity",
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: '∞',
    description: 'A sash that contains an infinite pocket dimension.',
    stats: { storage: 9999 },
    enchantments: [{ name: 'Infinite Storage', description: 'Unlimited storage space' }, { name: 'Time Stop', description: 'Items never decay' }, { name: 'Teleport Objects', description: 'Summon any item anywhere' }],
    weight: 0.1,
    value: 12000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
  {
    id: 'grandmaster_boots_of_eternity',
    name: "Grandmaster's Boots of Eternity",
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: '🌟',
    description: 'Boots that transcend the limitations of time and space.',
    stats: { ac: 4, movement: 60 },
    enchantments: [{ name: 'Time Stop', description: 'Time Stop 1/day' }, { name: 'Teleport', description: 'Teleport at will, unlimited range' }, { name: 'Plane Shift', description: 'Travel between planes' }, { name: 'Haste', description: 'Constant haste' }],
    weight: 0.5,
    value: 14000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
  {
    id: 'amulet_of_the_immortal',
    name: 'Amulet of the Immortal',
    slotType: 'amulet',
    rarity: 'legendary',
    level: 20,
    icon: '♾️',
    description: 'Grants true immortality. The wearer cannot permanently die.',
    stats: { regeneration: '3d10' },
    enchantments: [{ name: 'True Resurrection', description: 'Auto-resurrect after 24 hours' }, { name: 'Regeneration', description: 'Constant 3d10 regeneration' }, { name: 'Clone', description: 'Infinite clones' }],
    weight: 0.1,
    value: 20000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
  {
    id: 'ring_of_three_wishes',
    name: 'Ring of Three Wishes',
    slotType: 'ring1',
    rarity: 'legendary',
    level: 20,
    icon: '✨',
    description: 'Grants three wishes per day.',
    stats: { wishes: 3 },
    enchantments: [{ name: 'Wish', description: 'Wish 3/day' }, { name: 'Miracle', description: 'Divine intervention' }, { name: 'Alter Reality', description: 'Reshape reality' }],
    weight: 0,
    value: 18000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
  {
    id: 'ring_of_ultimate_power',
    name: 'Ring of Ultimate Power',
    slotType: 'ring2',
    rarity: 'legendary',
    level: 20,
    icon: '💪',
    description: 'The pinnacle of magical craftsmanship. Grants godlike power.',
    stats: { strength: 5, dexterity: 5, constitution: 5, intelligence: 5, wisdom: 5, charisma: 5, saves: 5, attackBonus: 5 },
    enchantments: [{ name: 'Omnipotence', description: 'Limited omnipotence' }, { name: 'Divine Intervention', description: 'Call upon divine power' }, { name: 'Legendary Actions', description: '3 legendary actions per round' }],
    weight: 0,
    value: 25000,
    setId: 'grandmaster-vestments',
    setName: "Grandmaster's Legendary Vestments",
  },
];

// Combine all armor items
export const allCustomArmor: EquipmentItem[] = [
  ...noviceShadowSet,
  ...streetRunnerSet,
  ...apprenticeConcealmentSet,
  ...wetboyProfessionalSet,
  ...guildOperativeSet,
  ...rooftopStalkerSet,
  ...masterAssassinSet,
  ...nightshroudSet,
  ...phantomRegaliaSet,
  ...kakariSet,
  ...entreriSet,
  ...grandmasterSet,
];

// Set definitions for bonuses
export const customArmorSetDefinitions: SetInfo[] = [
  {
    id: 'novice-shadow',
    name: "Novice's Shadow Ensemble",
    pieces: noviceShadowSet.map(i => i.id),
    bonuses: [
      { setId: 'novice-shadow', setName: "Novice's Shadow Ensemble", piecesRequired: 2, bonus: '+1 Stealth' },
      { setId: 'novice-shadow', setName: "Novice's Shadow Ensemble", piecesRequired: 4, bonus: '+5ft movement in dim light' },
      { setId: 'novice-shadow', setName: "Novice's Shadow Ensemble", piecesRequired: 6, bonus: 'Advantage on hiding in shadows' },
      { setId: 'novice-shadow', setName: "Novice's Shadow Ensemble", piecesRequired: 8, bonus: 'Pass Without Trace 1/day' },
    ],
  },
  {
    id: 'street-runner',
    name: "Street Runner's Kit",
    pieces: streetRunnerSet.map(i => i.id),
    bonuses: [
      { setId: 'street-runner', setName: "Street Runner's Kit", piecesRequired: 2, bonus: '+1 Acrobatics' },
      { setId: 'street-runner', setName: "Street Runner's Kit", piecesRequired: 4, bonus: '+10ft climbing speed' },
      { setId: 'street-runner', setName: "Street Runner's Kit", piecesRequired: 6, bonus: 'Advantage on Sleight of Hand' },
      { setId: 'street-runner', setName: "Street Runner's Kit", piecesRequired: 8, bonus: 'Dash as bonus action' },
    ],
  },
  {
    id: 'apprentice-concealment',
    name: "Apprentice's Concealment Garb",
    pieces: apprenticeConcealmentSet.map(i => i.id),
    bonuses: [
      { setId: 'apprentice-concealment', setName: "Apprentice's Concealment Garb", piecesRequired: 2, bonus: '+1 Disguise' },
      { setId: 'apprentice-concealment', setName: "Apprentice's Concealment Garb", piecesRequired: 4, bonus: '+2 to Deception checks' },
      { setId: 'apprentice-concealment', setName: "Apprentice's Concealment Garb", piecesRequired: 6, bonus: 'Disguise Self 1/day' },
      { setId: 'apprentice-concealment', setName: "Apprentice's Concealment Garb", piecesRequired: 8, bonus: 'Invisibility 1/day (1 minute)' },
    ],
  },
  {
    id: 'wetboy-professional',
    name: "Wetboy's Professional Kit",
    pieces: wetboyProfessionalSet.map(i => i.id),
    bonuses: [
      { setId: 'wetboy-professional', setName: "Wetboy's Professional Kit", piecesRequired: 2, bonus: '+2 Poison DC' },
      { setId: 'wetboy-professional', setName: "Wetboy's Professional Kit", piecesRequired: 4, bonus: 'Advantage on Stealth in darkness' },
      { setId: 'wetboy-professional', setName: "Wetboy's Professional Kit", piecesRequired: 6, bonus: '+1d6 Sneak Attack damage' },
      { setId: 'wetboy-professional', setName: "Wetboy's Professional Kit", piecesRequired: 8, bonus: 'Assassinate: Auto-crit on surprised enemies' },
    ],
  },
  {
    id: 'guild-operative',
    name: "Guild Operative's Formal Attire",
    pieces: guildOperativeSet.map(i => i.id),
    bonuses: [
      { setId: 'guild-operative', setName: "Guild Operative's Formal Attire", piecesRequired: 2, bonus: '+1 Charisma' },
      { setId: 'guild-operative', setName: "Guild Operative's Formal Attire", piecesRequired: 4, bonus: 'Advantage on Persuasion with nobles' },
      { setId: 'guild-operative', setName: "Guild Operative's Formal Attire", piecesRequired: 6, bonus: 'Charm Person 2/day' },
      { setId: 'guild-operative', setName: "Guild Operative's Formal Attire", piecesRequired: 8, bonus: 'Suggestion 1/day' },
    ],
  },
  {
    id: 'rooftop-stalker',
    name: "Rooftop Stalker's Climbing Gear",
    pieces: rooftopStalkerSet.map(i => i.id),
    bonuses: [
      { setId: 'rooftop-stalker', setName: "Rooftop Stalker's Climbing Gear", piecesRequired: 2, bonus: '+15ft climbing speed' },
      { setId: 'rooftop-stalker', setName: "Rooftop Stalker's Climbing Gear", piecesRequired: 4, bonus: 'No fall damage from 30ft or less' },
      { setId: 'rooftop-stalker', setName: "Rooftop Stalker's Climbing Gear", piecesRequired: 6, bonus: 'Spider Climb 2/day' },
      { setId: 'rooftop-stalker', setName: "Rooftop Stalker's Climbing Gear", piecesRequired: 8, bonus: 'Fly 1/day (1 minute)' },
    ],
  },
  {
    id: 'master-assassin',
    name: "Master Assassin's Complete Arsenal",
    pieces: masterAssassinSet.map(i => i.id),
    bonuses: [
      { setId: 'master-assassin', setName: "Master Assassin's Complete Arsenal", piecesRequired: 2, bonus: '+2 Initiative' },
      { setId: 'master-assassin', setName: "Master Assassin's Complete Arsenal", piecesRequired: 4, bonus: 'Critical hits on 19-20' },
      { setId: 'master-assassin', setName: "Master Assassin's Complete Arsenal", piecesRequired: 6, bonus: '+2d6 Sneak Attack damage' },
      { setId: 'master-assassin', setName: "Master Assassin's Complete Arsenal", piecesRequired: 8, bonus: 'Death Strike: Double damage on crits vs surprised' },
    ],
  },
  {
    id: 'nightshroud',
    name: 'Nightshroud Complete Set',
    pieces: nightshroudSet.map(i => i.id),
    bonuses: [
      { setId: 'nightshroud', setName: 'Nightshroud Complete Set', piecesRequired: 2, bonus: 'Darkvision 60ft' },
      { setId: 'nightshroud', setName: 'Nightshroud Complete Set', piecesRequired: 4, bonus: 'Invisible in dim light' },
      { setId: 'nightshroud', setName: 'Nightshroud Complete Set', piecesRequired: 6, bonus: 'Shadow Step at will' },
      { setId: 'nightshroud', setName: 'Nightshroud Complete Set', piecesRequired: 8, bonus: 'Shadow Form 1/day (incorporeal)' },
    ],
  },
  {
    id: 'phantom-regalia',
    name: "Phantom's Complete Regalia",
    pieces: phantomRegaliaSet.map(i => i.id),
    bonuses: [
      { setId: 'phantom-regalia', setName: "Phantom's Complete Regalia", piecesRequired: 2, bonus: 'Misty Step 1/day' },
      { setId: 'phantom-regalia', setName: "Phantom's Complete Regalia", piecesRequired: 4, bonus: 'Phase through walls (hands only)' },
      { setId: 'phantom-regalia', setName: "Phantom's Complete Regalia", piecesRequired: 6, bonus: 'Blink 2/day' },
      { setId: 'phantom-regalia', setName: "Phantom's Complete Regalia", piecesRequired: 8, bonus: 'Etherealness 1/day' },
    ],
  },
  {
    id: 'kakari-bonded',
    name: "Ka'kari Bonded Complete Set",
    pieces: kakariSet.map(i => i.id),
    bonuses: [
      { setId: 'kakari-bonded', setName: "Ka'kari Bonded Complete Set", piecesRequired: 2, bonus: 'Devour Magic (touch dispel)' },
      { setId: 'kakari-bonded', setName: "Ka'kari Bonded Complete Set", piecesRequired: 4, bonus: 'Perfect Invisibility at will' },
      { setId: 'kakari-bonded', setName: "Ka'kari Bonded Complete Set", piecesRequired: 6, bonus: 'Regeneration 2d6/turn' },
      { setId: 'kakari-bonded', setName: "Ka'kari Bonded Complete Set", piecesRequired: 8, bonus: 'Immortality (revive after 1 hour)' },
    ],
  },
  {
    id: 'entreri-arsenal',
    name: "Entreri's Legendary Arsenal",
    pieces: entreriSet.map(i => i.id),
    bonuses: [
      { setId: 'entreri-arsenal', setName: "Entreri's Legendary Arsenal", piecesRequired: 2, bonus: '+3 Initiative' },
      { setId: 'entreri-arsenal', setName: "Entreri's Legendary Arsenal", piecesRequired: 4, bonus: 'Critical hits on 18-20' },
      { setId: 'entreri-arsenal', setName: "Entreri's Legendary Arsenal", piecesRequired: 6, bonus: 'Life Drain (heal for damage dealt)' },
      { setId: 'entreri-arsenal', setName: "Entreri's Legendary Arsenal", piecesRequired: 8, bonus: 'Blinding Speed (extra attack per turn)' },
    ],
  },
  {
    id: 'grandmaster-vestments',
    name: "Grandmaster's Legendary Vestments",
    pieces: grandmasterSet.map(i => i.id),
    bonuses: [
      { setId: 'grandmaster-vestments', setName: "Grandmaster's Legendary Vestments", piecesRequired: 2, bonus: '+2 to all ability scores' },
      { setId: 'grandmaster-vestments', setName: "Grandmaster's Legendary Vestments", piecesRequired: 4, bonus: 'Legendary Resistance 1/day' },
      { setId: 'grandmaster-vestments', setName: "Grandmaster's Legendary Vestments", piecesRequired: 6, bonus: 'Teleport at will' },
      { setId: 'grandmaster-vestments', setName: "Grandmaster's Legendary Vestments", piecesRequired: 8, bonus: 'Wish 1/week' },
    ],
  },
];
