// Legendary Deadpool-Themed Equipment Sets
import { EquipmentItem } from './types';

// SET 1: THE MERC WITH A MOUTH'S REGALIA
export const mercWithMouthSet: EquipmentItem[] = [
  {
    id: 'mask-perpetual-commentary',
    name: 'Mask of Perpetual Commentary',
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: 'Drama',
    stats: { ac: 3 },
    properties: ['Advantage on Intimidation', 'Advantage on Performance'],
    enchantments: [
      { name: 'Unfiltered Thoughts', description: 'Your internal monologue becomes audible to enemies within 30ft, forcing Wisdom saves or disadvantage on attacks' },
      { name: 'Fourth Wall Crack', description: 'Once per session, ask the DM what an enemy\'s HP is. They must answer truthfully while you wink at an imaginary audience' },
    ],
    weight: 2,
    value: 5000,
    description: 'A mask that speaks your mind whether you want it to or not.',
    lore: 'Forged by a bored deity who thought silence was overrated.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
  {
    id: 'cuirass-regenerative-nonsense',
    name: 'Cuirass of Regenerative Nonsense',
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: 'Heart',
    stats: { ac: 5 },
    properties: ['Regenerate 1d6 HP per round'],
    enchantments: [
      { name: 'Unkillable Absurdity', description: 'When reduced to 0 HP, make a DC 15 Constitution save. On success, return with 1 HP and a witty one-liner' },
      { name: 'Healing Factor Timeout', description: 'Declare a "commercial break" during combat. Freeze time for 6 seconds while you regenerate and eat a chimichanga (restore 2d8 HP)' },
    ],
    weight: 20,
    value: 8000,
    description: 'Armor that heals you through sheer narrative convenience.',
    lore: 'The enchantment was originally a bug, but the artificer decided it was a feature.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
  {
    id: 'gauntlets-gratuitous-violence',
    name: 'Gauntlets of Gratuitous Violence',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'Swords',
    stats: { attackBonus: 2 },
    properties: ['+1d6 slashing damage'],
    enchantments: [
      { name: 'Overkill Protocol', description: 'Critical hits trigger excessive blood effects that distract enemies (they lose next action)' },
      { name: 'Unnecessary Flourish', description: 'After killing an enemy, perform a 10-second victory dance. All allies gain inspiration, all enemies gain confusion' },
    ],
    weight: 4,
    value: 4500,
    description: 'These gauntlets believe subtlety is for cowards.',
    lore: 'Originally designed for theatrical productions. The blood effects are not supposed to be real.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
  {
    id: 'belt-infinite-pouches',
    name: 'Belt of Infinite Pouches (But What\'s In Them?)',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'Package',
    stats: { ac: 2 },
    properties: ['Unlimited small item storage'],
    enchantments: [
      { name: 'Random Item Generator', description: 'Once per short rest, pull out a completely random item (DM rolls on wild magic table for items)' },
      { name: 'Deus Ex Machina Pocket', description: 'Ask the DM "wouldn\'t it be convenient if I had [specific item]?" DM must allow it once per session, but it\'s broken/cursed/wrong color' },
    ],
    weight: 1,
    value: 6000,
    description: 'Nobody knows what\'s in here. Not even you.',
    lore: 'The pouches are connected to a pocket dimension maintained by a very confused imp.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
  {
    id: 'greaves-inexplicable-acrobatics',
    name: 'Greaves of Inexplicable Acrobatics',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'Footprints',
    stats: { ac: 3, movement: 15 },
    properties: ['Advantage on Acrobatics'],
    enchantments: [
      { name: 'Physics? What Physics?', description: 'Can wall-run, double-jump, and defy gravity for style points' },
      { name: 'Cartoon Logic', description: 'Once per combat, declare an action that makes no physical sense. DM must allow it if it\'s funny enough (group vote)' },
    ],
    weight: 5,
    value: 5500,
    description: 'Newton died so you could look cool.',
    lore: 'Created by an artificer who failed physics but aced drama.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
  {
    id: 'katana-meta-awareness',
    name: 'Katana of Meta-Awareness',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Sword',
    stats: { damage: '2d8+3', attackBonus: 2 },
    properties: ['Finesse', 'Versatile'],
    enchantments: [
      { name: 'Narrative Blade', description: 'Deals extra 1d10 damage to "main story NPCs" and "obvious plot devices"' },
      { name: 'Script Peek', description: 'Ask the DM "is this enemy important to the plot?" They must answer with a percentage (0-100% plot relevance)' },
    ],
    weight: 3,
    value: 7500,
    description: 'This blade knows which enemies matter to the story.',
    lore: 'Forged by a smith who could see the threads of fate... and thought they were tacky.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
  {
    id: 'pistol-anachronistic-mayhem',
    name: 'Pistol of Anachronistic Mayhem',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Zap',
    stats: { damage: '2d6+2' },
    properties: ['Range 60/180', 'Reload (6 shots)'],
    enchantments: [
      { name: 'Wrong Genre', description: 'Enemies hit must make Intelligence save or spend next turn questioning why guns exist in this setting' },
      { name: 'Budget Concerns', description: 'Complain about "expensive CGI" when firing. DM must describe bullet effects in increasingly absurd detail' },
    ],
    weight: 2,
    value: 6000,
    description: 'A weapon that shouldn\'t exist here. Everyone knows it.',
    lore: 'Fell through a portal from a dimension where explosions are cheaper than sword fights.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
  {
    id: 'bow-self-aware-arrows',
    name: 'Bow of Self-Aware Arrows',
    slotType: 'ranged_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Target',
    stats: { damage: '1d8+1d6🔥' },
    properties: ['Range 150/600'],
    enchantments: [
      { name: 'Guided by Plot Armor', description: 'Arrows can curve around corners if it would be "cinematically cool"' },
      { name: 'Director\'s Cut', description: 'Before releasing arrow, ask for a "slow-motion sequence." DM must narrate your shot in excessive dramatic detail (grants advantage)' },
    ],
    weight: 2,
    value: 5500,
    description: 'The arrows know where they need to go for maximum drama.',
    lore: 'Each arrow contains a tiny critic who rates the shot\'s artistic merit.',
    setId: 'merc-with-mouth',
    setName: "The Merc with a Mouth's Regalia",
  },
];

// SET 2: ARSENAL OF CHAOTIC CONTRACTS
export const chaoticContractsSet: EquipmentItem[] = [
  {
    id: 'cowl-constant-quipping',
    name: 'Cowl of Constant Quipping',
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: 'MessageCircle',
    stats: { ac: 2, charisma: 3 },
    properties: ['Immunity to Charm'],
    enchantments: [
      { name: 'Verbal Parry', description: 'When enemy monologues, interrupt with sarcasm. They must make Wisdom save or lose concentration' },
      { name: 'Subtitle Glitch', description: 'Speak in another language. DM must provide "subtitles" in increasingly incorrect translations' },
    ],
    weight: 2,
    value: 5000,
    description: 'You physically cannot shut up while wearing this.',
    lore: 'Cursed by a bard who was tired of being interrupted.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
  {
    id: 'armor-questionable-sponsorships',
    name: 'Armor of Questionable Sponsorships',
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: 'BadgeDollarSign',
    stats: { ac: 4 },
    properties: ['Resistance to piercing damage'],
    enchantments: [
      { name: 'Product Placement', description: 'Armor displays logos of random brands. Gain 1d20 gold per combat for "advertising"' },
      { name: 'Sponsor Break', description: 'Mid-combat, give a 30-second advertisement for a fake product. Heal 1d8 HP per party member who laughs' },
    ],
    weight: 25,
    value: 7000,
    description: 'This armor brought to you by... someone.',
    lore: 'The original owner sold ad space to fund their adventuring career.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
  {
    id: 'bracers-excessive-reloading',
    name: 'Bracers of Excessive Reloading',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'RefreshCw',
    stats: { attackBonus: 2 },
    properties: ['Reload as bonus action'],
    enchantments: [
      { name: 'Akimbo Absurdity', description: 'Can dual-wield ranged weapons with no penalty' },
      { name: 'Infinite Ammo Cheat', description: 'Once per session, ask DM "did I remember to buy ammo?" DM must say yes regardless of truth' },
    ],
    weight: 3,
    value: 4500,
    description: 'Ammunition is more of a suggestion than a requirement.',
    lore: 'Made by a fletcher who was tired of counting arrows.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
  {
    id: 'sash-taco-trucks',
    name: 'Sash of Taco Trucks',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'UtensilsCrossed',
    stats: { ac: 1 },
    properties: ['Summon food as bonus action'],
    enchantments: [
      { name: 'Chimichanga Healing', description: 'Eating food heals 2d6 HP and grants temp HP equal to Charisma modifier' },
      { name: 'Food Fight', description: 'Throw food at enemies. They must save or waste action cleaning themselves while you laugh' },
    ],
    weight: 1,
    value: 4000,
    description: 'It always smells faintly of delicious street food.',
    lore: 'Blessed by the god of questionable food hygiene.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
  {
    id: 'boots-inappropriate-timing',
    name: 'Boots of Inappropriate Timing',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'Clock',
    stats: { ac: 2, movement: 20 },
    properties: ['Dash as bonus action'],
    enchantments: [
      { name: 'Entrance Dramatic', description: 'When entering combat, make Performance check. High roll grants surprise round' },
      { name: 'Late to the Party', description: 'Arrive after combat starts. Ask DM "what did I miss?" Get free surprise attack because enemies weren\'t expecting you' },
    ],
    weight: 4,
    value: 5000,
    description: 'Always arrive at the most awkward moment.',
    lore: 'These boots have a mind of their own about when you should show up.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
  {
    id: 'dual-swords-self-referential',
    name: 'Dual Swords of Self-Referential Humor',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Swords',
    stats: { damage: '2d6+2 each', attackBonus: 2 },
    properties: ['Light', 'Finesse'],
    enchantments: [
      { name: 'Recursive Damage', description: 'Each hit references previous hit in increasingly meta ways, stacking +1 damage per reference' },
      { name: 'Callback Combo', description: 'Reference a joke from 3+ sessions ago. If party remembers, auto-crit' },
    ],
    weight: 4,
    value: 7000,
    description: 'These swords have inside jokes with themselves.',
    lore: 'Forged from the physical manifestation of a pun that was so bad it became good.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
  {
    id: 'grenade-questionable-legality',
    name: 'Grenade of Questionable Legality',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Bomb',
    stats: { damage: '4d6 fire' },
    properties: ['20ft radius', '3 uses per long rest'],
    enchantments: [
      { name: 'Collateral Damage', description: 'Destroys environment dramatically. DM must describe property damage in detail' },
      { name: 'Oops', description: 'If you hit allies, they take no damage but must roleplay being annoyed with you for 5 minutes' },
    ],
    weight: 1,
    value: 3000,
    description: 'Probably illegal in most jurisdictions.',
    lore: 'The serial numbers have been filed off. All of them. Including ones that weren\'t there.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
  {
    id: 'crossbow-improbable-trick-shots',
    name: 'Crossbow of Improbable Trick Shots',
    slotType: 'ranged_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Crosshair',
    stats: { damage: '1d10+2' },
    properties: ['Range 100/400'],
    enchantments: [
      { name: 'Ricochet Ridiculousness', description: 'Can bounce shots off surfaces. Each bounce adds +1d4 damage but -2 to hit' },
      { name: 'Calculated Chaos', description: 'Describe an impossible trick shot. Roll Performance vs DM\'s chosen DC. Success = it works exactly as described' },
    ],
    weight: 5,
    value: 5500,
    description: 'Geometry is more of a guideline for these bolts.',
    lore: 'The original owner spent more time on trick shots than actual combat.',
    setId: 'chaotic-contracts',
    setName: 'Arsenal of Chaotic Contracts',
  },
];

// SET 3: REGALIA OF REGENERATIVE RIDICULOUSNESS
export const regenerativeRidiculousnessSet: EquipmentItem[] = [
  {
    id: 'helmet-scarred-memories',
    name: 'Helmet of Scarred Memories',
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: 'Brain',
    stats: { ac: 3 },
    properties: ['Advantage on Wisdom saves'],
    enchantments: [
      { name: 'Trauma Humor', description: 'Convert emotional damage into jokes. Heal 1d4 HP per self-deprecating quip' },
      { name: 'Flashback Sequence', description: 'Trigger random flashback mid-combat. DM narrates absurd origin story moment (gain inspiration)' },
    ],
    weight: 3,
    value: 5500,
    description: 'Every dent tells a story. Most of them are funny.',
    lore: 'This helmet has been through so much it developed a sense of humor as a coping mechanism.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
  {
    id: 'plate-persistent-healing',
    name: 'Plate of Persistent Healing',
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: 'HeartPulse',
    stats: { ac: 6 },
    properties: ['Regenerate 1d8 HP per round'],
    enchantments: [
      { name: 'Unkillable', description: 'Death saves automatically succeed on 8 or higher' },
      { name: 'Respawn Timer', description: 'If killed, ask DM "how long until I respawn?" Return in 1d4 rounds with full HP and new outfit' },
    ],
    weight: 30,
    value: 10000,
    description: 'Death is more of an inconvenience than a destination.',
    lore: 'Made from the shed skin of an immortal troll who found the whole process tedious.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
  {
    id: 'gauntlets-gratuitous-gestures',
    name: 'Gauntlets of Gratuitous Gestures',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'Hand',
    stats: { attackBonus: 3 },
    properties: ['Grapple as bonus action'],
    enchantments: [
      { name: 'Finger Guns', description: 'Point at enemy and say "bang." They take 1d6 psychic damage from sheer audacity' },
      { name: 'Thumbs Up/Down', description: 'After killing enemy, ask party to vote thumbs up or down on execution style. Majority approval grants temp HP' },
    ],
    weight: 3,
    value: 5000,
    description: 'Your hands become instruments of judgment.',
    lore: 'Originally worn by a gladiator who valued showmanship over survival.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
  {
    id: 'belt-holsters',
    name: 'Belt of Holsters (So Many Holsters)',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'Layers',
    stats: { ac: 2 },
    properties: ['Draw/stow weapons as free action'],
    enchantments: [
      { name: 'Quick Draw', description: 'Always act first in initiative if you make gun-slinging motion' },
      { name: 'Where Did That Come From?', description: 'Pull out weapon you definitely don\'t own. DM must allow it but it disappears after use' },
    ],
    weight: 2,
    value: 4500,
    description: 'How many holsters? All of them. All the holsters.',
    lore: 'Made by an armorer with a strap and buckle addiction.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
  {
    id: 'greaves-unstoppable-momentum',
    name: 'Greaves of Unstoppable Momentum',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'TrendingUp',
    stats: { ac: 3, movement: 10 },
    properties: ['Cannot be knocked prone'],
    enchantments: [
      { name: 'Parkour!', description: 'Shout "parkour!" when climbing or jumping. Automatically succeed on Athletics checks under DC 15' },
      { name: 'Action Roll', description: 'Declare you\'re doing an action roll. DM must describe your movement in slow-motion with dramatic music (advantage on Acrobatics)' },
    ],
    weight: 5,
    value: 5500,
    description: 'An object in motion stays in motion, especially you.',
    lore: 'The enchantment was inspired by watching cats land on their feet.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
  {
    id: 'katanas-slice-dice',
    name: 'Katanas of Slice and Dice (Matched Pair)',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Scissors',
    stats: { damage: '2d6+3 each', attackBonus: 3 },
    properties: ['Finesse', 'Light'],
    enchantments: [
      { name: 'Surgical Precision', description: 'Can target specific body parts. Called shots don\'t have disadvantage' },
      { name: 'Dramatic Decapitation', description: 'On killing blow, ask DM "does the head come off?" If yes, describe in excessive detail (intimidate nearby enemies)' },
    ],
    weight: 4,
    value: 8000,
    description: 'Two blades, infinite ways to cut things.',
    lore: 'These blades argue about who gets the killing blow.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
  {
    id: 'pistols-punchline-delivery',
    name: 'Pistols of Punchline Delivery',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Zap',
    stats: { damage: '2d8+2 each' },
    properties: ['Range 40/120', 'Reload (12 shots each)'],
    enchantments: [
      { name: 'One-Liner Ammunition', description: 'Each shot must be accompanied by quip. Good quip = +1d4 damage' },
      { name: 'Bullet Time', description: 'Ask DM for bullet-time sequence. They must narrate your shots in Matrix-style slow motion (advantage on attacks)' },
    ],
    weight: 4,
    value: 7000,
    description: 'Every bullet delivers a punchline.',
    lore: 'Crafted by a comedian who switched careers to assassination.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
  {
    id: 'rocket-launcher-reasonable',
    name: 'Rocket Launcher of Reasonable Escalation',
    slotType: 'ranged_weapon',
    rarity: 'artifact',
    level: 20,
    icon: 'Rocket',
    stats: { damage: '6d6 fire' },
    properties: ['30ft radius', 'Range 150/600', '1 use per long rest'],
    enchantments: [
      { name: 'Disproportionate Response', description: 'Can be used against single target for comedic overkill' },
      { name: 'Where Did You Get That?', description: 'NPCs must question how you\'re carrying this. Respond with increasingly absurd explanations (Performance check for believability)' },
    ],
    weight: 15,
    value: 12000,
    description: 'For when swords just aren\'t enough.',
    lore: 'Nobody knows where this came from. Including you.',
    setId: 'regenerative-ridiculousness',
    setName: 'Regalia of Regenerative Ridiculousness',
  },
];

// SET 4: THE MERCENARY'S SELF-AWARE ARSENAL
export const selfAwareArsenalSet: EquipmentItem[] = [
  {
    id: 'mask-medium-awareness',
    name: 'Mask of Medium Awareness',
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: 'Eye',
    stats: { ac: 2, perception: 4 },
    properties: ['Detect Thoughts at will'],
    enchantments: [
      { name: 'Read the Room', description: 'Instantly know if scene is comedy, drama, or action. Adjust behavior for genre appropriateness (or inappropriateness)' },
      { name: 'Spoiler Alert', description: 'Ask DM if current quest is "filler" or "main story." They must answer with episode number format ("This is Episode 7, so...")' },
    ],
    weight: 2,
    value: 6000,
    description: 'Sees more than just the physical world.',
    lore: 'Worn by a seer who got bored of regular prophecies.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
  {
    id: 'breastplate-breaking-tension',
    name: 'Breastplate of Breaking Tension',
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: 'Laugh',
    stats: { ac: 5 },
    properties: ['Advantage on saves vs fear'],
    enchantments: [
      { name: 'Inappropriate Timing', description: 'When allies are having serious moment, interject with nonsense. Enemies lose concentration' },
      { name: 'Mood Whiplash', description: 'After tragic scene, immediately shift to comedy. DM must follow your tonal lead for next 5 minutes' },
    ],
    weight: 25,
    value: 7500,
    description: 'No mood is too serious to break.',
    lore: 'Originally worn by a court jester who survived seven kings.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
  {
    id: 'vambraces-violence-escalation',
    name: 'Vambraces of Violence Escalation',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'TrendingUp',
    stats: { ac: 2 },
    properties: ['+2 to all damage rolls'],
    enchantments: [
      { name: 'Go Big or Go Home', description: 'Each successive attack must be more dramatic than the last or take disadvantage' },
      { name: 'Stunt Coordinator', description: 'Describe elaborate attack choreography. Roll Performance. High roll = DM must narrate exactly as described with bonuses' },
    ],
    weight: 3,
    value: 5000,
    description: 'Always escalate. Never de-escalate.',
    lore: 'Made for someone who believed moderation was for quitters.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
  {
    id: 'belt-budget-constraints',
    name: 'Belt of Budget Constraints',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'Coins',
    stats: { ac: 1 },
    properties: ['Carry capacity doubled'],
    enchantments: [
      { name: 'Practical Effects', description: 'Magic appears as "low-budget" versions (fireball is clearly a thrown prop, etc.)' },
      { name: 'CGI Complaint', description: 'Criticize quality of magical effects. Caster must make Concentration check or lose spell' },
    ],
    weight: 1,
    value: 3500,
    description: 'Makes everything look suspiciously affordable.',
    lore: 'Created by an illusionist who ran out of money.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
  {
    id: 'boots-sequel-hooks',
    name: 'Boots of Sequel Hooks',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'Link',
    stats: { ac: 3, movement: 15 },
    properties: ['Leave no tracks'],
    enchantments: [
      { name: 'Unresolved Plot Threads', description: 'Wherever you go, minor mysteries appear that never get solved' },
      { name: 'Cliffhanger Escape', description: 'When escaping, declare "To be continued!" Automatically succeed on one Escape action per session' },
    ],
    weight: 4,
    value: 5500,
    description: 'Every step sets up something that may never pay off.',
    lore: 'Worn by an adventurer who never finished a single quest.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
  {
    id: 'blade-borrowed-references',
    name: 'Blade of Borrowed References',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Sword',
    stats: { damage: '2d8+3', attackBonus: 2 },
    properties: ['Finesse'],
    enchantments: [
      { name: 'Copyright Infringement', description: 'Attacks mimic famous movie/game moves. Each reference deals +1d6 damage if party recognizes it' },
      { name: 'Homage or Ripoff?', description: 'Perfectly recreate iconic weapon technique from other media. DM must allow it even if mechanically nonsensical' },
    ],
    weight: 3,
    value: 7000,
    description: 'Every swing is a tribute to something.',
    lore: 'This blade has watched a lot of action movies.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
  {
    id: 'gun-genre-confusion',
    name: 'Gun of Genre Confusion',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'HelpCircle',
    stats: { damage: '2d6+2' },
    properties: ['Range 60/180'],
    enchantments: [
      { name: 'Wrong Setting', description: 'Enemies question why firearms exist in fantasy world, giving you advantage' },
      { name: 'Realism Toggle', description: 'Ask DM to switch between "realistic gun mechanics" and "action movie gun mechanics" mid-combat' },
    ],
    weight: 2,
    value: 5500,
    description: 'Doesn\'t belong here. Doesn\'t care.',
    lore: 'Arrived in this world by narrative accident.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
  {
    id: 'explosive-uncertain-origin',
    name: 'Explosive Devices of Uncertain Origin',
    slotType: 'ranged_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Flame',
    stats: { damage: '3d8 fire' },
    properties: ['15ft radius', '5 uses per long rest'],
    enchantments: [
      { name: 'Boom Mic', description: 'Explosions are always louder than expected, affecting wider area' },
      { name: 'Michael Bay Mode', description: 'Request explosion be described in excessive detail with slow-motion. Gain inspiration if DM commits to the bit' },
    ],
    weight: 5,
    value: 6000,
    description: 'Nobody knows where these come from.',
    lore: 'They just... appear when you need them.',
    setId: 'self-aware-arsenal',
    setName: "The Mercenary's Self-Aware Arsenal",
  },
];

// SET 5: VESTMENTS OF VIOLENT COMEDY
export const violentComedySet: EquipmentItem[] = [
  {
    id: 'crown-conscious-incompetence',
    name: 'Crown of Conscious Incompetence',
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: 'Crown',
    stats: { ac: 2, wisdom: 3 },
    properties: ['Immunity to Confusion'],
    enchantments: [
      { name: 'Aware of Stupidity', description: 'Know when you\'re making bad decision but do it anyway for comedy' },
      { name: 'Hindsight Commentary', description: 'After failing, narrate what you should have done. Gain advantage on retry' },
    ],
    weight: 2,
    value: 5500,
    description: 'You know it\'s a bad idea. You do it anyway.',
    lore: 'Worn by a fool who was wiser than they let on.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
  {
    id: 'armor-acceptable-losses',
    name: 'Armor of Acceptable Losses',
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: 'Shield',
    stats: { ac: 4 },
    properties: ['Resistance to all damage', 'Always slightly injured'],
    enchantments: [
      { name: 'Flesh Wound', description: 'All injuries are "just scratches" until you hit 0 HP, then it\'s dramatic' },
      { name: 'Damage Report', description: 'After taking hit, give medical assessment of injuries in technical terms (player makes Medicine check, high roll = temp HP from humor)' },
    ],
    weight: 20,
    value: 7000,
    description: 'Pain is just comedy waiting to happen.',
    lore: 'Made from the armor of someone who refused to admit they were hurt.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
  {
    id: 'gloves-gratuitous-gestures',
    name: 'Gloves of Gratuitous Gestures',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'Sparkles',
    stats: { ac: 2, attackBonus: 1 },
    enchantments: [
      { name: 'Expressive Violence', description: 'Attacks include unnecessary flourishes that deal +1d4 damage but look ridiculous' },
      { name: 'Jazz Hands', description: 'Mid-combat, do jazz hands at enemy. They must make Wisdom save or lose action from confusion' },
    ],
    weight: 1,
    value: 4500,
    description: 'Every gesture is unnecessarily dramatic.',
    lore: 'Previously owned by a mime who turned to violence.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
  {
    id: 'sash-snack-storage',
    name: 'Sash of Snack Storage',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'Cookie',
    stats: { ac: 1 },
    properties: ['Unlimited food storage'],
    enchantments: [
      { name: 'Combat Munchies', description: 'Eat snacks during battle as bonus action, heal 1d6 HP, enemies are disturbed' },
      { name: 'Sharing is Caring', description: 'Offer enemy a snack mid-fight. If they accept (Persuasion check), gain temporary truce' },
    ],
    weight: 2,
    value: 4000,
    description: 'Always has a snack ready. Always.',
    lore: 'The snacks are always fresh. Don\'t ask how.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
  {
    id: 'pants-improbable-pockets',
    name: 'Pants of Improbable Pockets',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'Box',
    stats: { ac: 2, movement: 10 },
    enchantments: [
      { name: 'Hammer Space', description: 'Can pull out items that definitely don\'t fit in pockets' },
      { name: 'Inventory Tetris', description: 'When asked how you\'re carrying something, describe impossible storage method. DM must accept it' },
    ],
    weight: 2,
    value: 5000,
    description: 'The pockets are bigger on the inside. Much bigger.',
    lore: 'Tailored by a wizard who hated carrying bags.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
  {
    id: 'swords-surgical-sarcasm',
    name: 'Swords of Surgical Strikes (and Sarcasm)',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Swords',
    stats: { damage: '2d6+2 each', attackBonus: 2 },
    properties: ['Finesse', 'Light'],
    enchantments: [
      { name: 'Witty Riposte', description: 'When enemy misses you, make Charisma check. Success = they take 1d6 psychic damage from your comeback' },
      { name: 'Sword Commentary', description: 'Narrate your sword fight like sports announcer. Allies gain +1 to hit from entertainment value' },
    ],
    weight: 4,
    value: 7500,
    description: 'Cuts with blades and words.',
    lore: 'The previous owner was a fencing instructor with a sharp tongue.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
  {
    id: 'firearms-flexible-legality',
    name: 'Firearms of Flexible Legality',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Target',
    stats: { damage: '2d8+2' },
    properties: ['Range 50/150', 'Reload (variable)'],
    enchantments: [
      { name: 'Ammo Ambiguity', description: 'Never quite clear how many bullets you have left (DM rolls secretly)' },
      { name: 'Reload Montage', description: 'When reloading, describe it dramatically. High Performance check = reload as free action' },
    ],
    weight: 3,
    value: 6000,
    description: 'Technically legal. Technically.',
    lore: 'The paperwork for this weapon is suspiciously vague.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
  {
    id: 'throwing-whatever-handy',
    name: "Throwing Weapons of Whatever's Handy",
    slotType: 'ranged_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Grab',
    stats: { damage: '1d6+2' },
    properties: ['Range 30/90', 'Improvised'],
    enchantments: [
      { name: 'Environmental Hazard', description: 'Can throw anything in environment as weapon with same stats' },
      { name: 'Is That a [Object]?', description: 'Throw completely inappropriate item. DM must determine damage based on absurdity (funnier = more damage)' },
    ],
    weight: 0,
    value: 4500,
    description: 'Everything is a weapon if you throw it hard enough.',
    lore: 'Based on the philosophy that anything can hurt if applied correctly.',
    setId: 'violent-comedy',
    setName: 'Vestments of Violent Comedy',
  },
];

// SET 6: THE UNKILLABLE MERC'S LOADOUT
export const unkillableMercSet: EquipmentItem[] = [
  {
    id: 'helm-helpful-hallucinations',
    name: 'Helm of Helpful Hallucinations',
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: 'Sparkles',
    stats: { ac: 3 },
    properties: ['Advantage on Perception'],
    enchantments: [
      { name: 'Imaginary Friends', description: 'See helpful (?) hallucinations that give terrible advice' },
      { name: 'Consensus Reality', description: 'When hallucinations disagree with real NPCs, ask party to vote on who\'s actually there' },
    ],
    weight: 3,
    value: 5500,
    description: 'Shows you things that may or may not exist.',
    lore: 'The previous owner insisted the helmet was perfectly normal. The helmet disagreed.',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
  {
    id: 'cuirass-continuous-carnage',
    name: 'Cuirass of Continuous Carnage',
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: 'Flame',
    stats: { ac: 6 },
    properties: ['Regenerate 2d6 HP per round'],
    enchantments: [
      { name: "Can't Stop Won't Stop", description: 'While above 50% HP, gain extra attack. While below 50% HP, gain advantage on all rolls (always dangerous)' },
      { name: 'Bloody But Unbowed', description: 'The more injured you are, the more one-liners you get. DM must allow extra quips per wound level' },
    ],
    weight: 25,
    value: 10000,
    description: 'The carnage never stops, and neither do you.',
    lore: 'This armor feeds on violence and returns it as vitality.',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
  {
    id: 'bracers-boundary-breaking',
    name: 'Bracers of Boundary Breaking',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'Maximize',
    stats: { ac: 3, attackBonus: 2 },
    enchantments: [
      { name: 'Fourth Wall Fists', description: 'Unarmed strikes can hit "narrative constructs" (break down plot walls, punch through scene transitions)' },
      { name: 'Reach Through the Screen', description: 'Once per session, "reach out" to the players/DM and ask for something. They must negotiate with you in-character' },
    ],
    weight: 3,
    value: 6000,
    description: 'These bracers recognize no boundaries.',
    lore: 'Made from material that exists between stories.',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
  {
    id: 'belt-unnecessary-buckles',
    name: 'Belt of Unnecessary Buckles',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'Link',
    stats: { ac: 2, saves: 1 },
    enchantments: [
      { name: 'Tactical Fashion', description: 'So many buckles enemies get distracted counting them (disadvantage on opportunity attacks against you)' },
      { name: 'Costume Change', description: 'Declare a quick-change into new outfit mid-scene. DM must describe transformation sequence, gain +2 Charisma for rest of scene' },
    ],
    weight: 2,
    value: 4500,
    description: 'You stopped counting the buckles at thirty.',
    lore: 'Designed by someone who thought "enough buckles" was a myth.',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
  {
    id: 'greaves-gravity-defiance',
    name: 'Greaves of Gravity Defiance',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'ArrowUp',
    stats: { ac: 3 },
    properties: ['Walk on walls/ceilings (1 min per short rest)'],
    enchantments: [
      { name: 'Physics Denial', description: "When you should fall, make Charisma check. Success = you don't fall until you look down (Coyote Rule)" },
      { name: 'Stunt Double', description: 'When attempting dangerous acrobatics, claim your "stunt double" is doing it. Automatically succeed but DM describes it as obviously fake' },
    ],
    weight: 4,
    value: 5500,
    description: 'Gravity is more of a suggestion.',
    lore: 'These greaves have a very casual relationship with physics.',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
  {
    id: 'katanas-killing-jokes',
    name: 'Katanas of Killing Jokes',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Swords',
    stats: { damage: '3d6+3 each', attackBonus: 3 },
    properties: ['Finesse', 'Light'],
    enchantments: [
      { name: 'Punchline Blade', description: 'Setup joke with first attack, deliver punchline with second. If joke lands (Performance check), second attack auto-crits' },
      { name: 'Sword Names', description: 'Your swords have names. Introduce them to enemies before fighting. Enemies must make Wisdom save or be confused by this behavior' },
    ],
    weight: 4,
    value: 9000,
    description: 'Comedy is tragedy plus timing. These provide the timing.',
    lore: 'Named "Setup" and "Punchline" by their creator.',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
  {
    id: 'guns-gratuitous-firepower',
    name: 'Guns of Gratuitous Firepower',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Zap',
    stats: { damage: '3d8+3 each' },
    properties: ['Range 60/180', 'Reload (ambiguous)'],
    enchantments: [
      { name: 'Bullet Ballet', description: 'Each shot can ricochet once. Describe trajectory dramatically for +1d6 damage' },
      { name: 'Akimbo Aesthetic', description: 'When dual-wielding guns, make Performance check. Success = look so cool enemies pause to watch (lose their reactions)' },
    ],
    weight: 4,
    value: 8000,
    description: 'More gun than anyone needs. Exactly enough for you.',
    lore: 'Made for someone who believed subtlety was a character flaw.',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
  {
    id: 'launcher-disproportionate-response',
    name: 'Launcher of Disproportionate Response',
    slotType: 'ranged_weapon',
    rarity: 'artifact',
    level: 20,
    icon: 'Rocket',
    stats: { damage: '8d6 fire' },
    properties: ['40ft radius', 'Range 200/800', '1 use per long rest'],
    enchantments: [
      { name: 'Overkill Ordinance', description: 'Can be used on single target. They must make Dexterity save or be completely vaporized (no death saves, just gone)' },
      { name: "Where'd You Get That?", description: 'Pull out progressively larger weapons from nowhere. Each weapon is one size category larger than previous. DM must allow until it gets ridiculous (then allow one more)' },
    ],
    weight: 20,
    value: 15000,
    description: 'For problems that require a very large solution.',
    lore: 'The definition of "bringing a gun to a knife fight."',
    setId: 'unkillable-merc',
    setName: "The Unkillable Merc's Loadout",
  },
];

// SET 7: ARSENAL OF ABSOLUTE ABSURDITY
export const absoluteAbsurditySet: EquipmentItem[] = [
  {
    id: 'mask-mixed-messages',
    name: 'Mask of Mixed Messages',
    slotType: 'head',
    rarity: 'legendary',
    level: 20,
    icon: 'Shuffle',
    stats: { ac: 2, charisma: 4 },
    properties: ['Advantage on Deception'],
    enchantments: [
      { name: 'Unreliable Narrator', description: 'Your version of events conflicts with reality. Enemies must make Intelligence save or believe your version' },
      { name: 'Retcon Ray', description: 'Point at something and declare "that didn\'t happen." DM must provide alternative explanation for minor events' },
    ],
    weight: 2,
    value: 6000,
    description: 'The truth is whatever you say it is.',
    lore: 'This mask was created by a historian with a very creative memory.',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
  {
    id: 'breastplate-borrowed-time',
    name: 'Breastplate of Borrowed Time',
    slotType: 'chest',
    rarity: 'legendary',
    level: 20,
    icon: 'Clock',
    stats: { ac: 5 },
    properties: ['On 15+ roll, attacks "missed" retroactively'],
    enchantments: [
      { name: 'Temporal Shenanigans', description: 'Once per combat, declare "wait, let me try that again" and rewind 6 seconds' },
      { name: "Director's Cut", description: 'After scene ends, describe "deleted scenes" that didn\'t happen but could have. DM must acknowledge alternate timeline' },
    ],
    weight: 20,
    value: 8000,
    description: 'Time is negotiable while wearing this.',
    lore: 'Made by a chronomancer who was always running late.',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
  {
    id: 'gauntlets-gratuitous-gore',
    name: 'Gauntlets of Gratuitous Gore',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'Droplet',
    stats: { ac: 3 },
    properties: ['Critical hits on 18-20'],
    enchantments: [
      { name: 'Excessive Violence', description: 'Critical hits trigger elaborate kill animations that take 30 seconds to describe' },
      { name: 'Rated R', description: 'Before attack, declare rating (PG, PG-13, R). Higher ratings deal more damage but disturb party members' },
    ],
    weight: 4,
    value: 5500,
    description: 'Every hit is excessively described.',
    lore: 'The enchanter was a frustrated novelist.',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
  {
    id: 'belt-bottomless-pouches',
    name: 'Belt of Bottomless Pouches',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'Package',
    stats: { ac: 2 },
    properties: ['Infinite storage for small items'],
    enchantments: [
      { name: 'Hammerspace Access', description: 'Pull out items that shouldn\'t exist in setting (modern tech, anachronistic objects)' },
      { name: 'Prop Department', description: 'Need specific item for joke? Ask DM if you "happen to have" it. 50% chance yes, regardless of logic' },
    ],
    weight: 1,
    value: 5000,
    description: 'The bottom is a lie.',
    lore: 'Connected to a dimension where genre consistency doesn\'t exist.',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
  {
    id: 'boots-bizarre-locomotion',
    name: 'Boots of Bizarre Locomotion',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'Footprints',
    stats: { ac: 3, movement: 20 },
    properties: ['Can move in impossible ways'],
    enchantments: [
      { name: 'Cartoon Physics', description: 'Can run on air briefly, spin legs like wheels, leave dust clouds' },
      { name: 'Looney Tunes Logic', description: 'When falling, don\'t fall until you look down and realize. Gain one free action before gravity remembers you' },
    ],
    weight: 3,
    value: 5500,
    description: 'Physics takes the day off when you wear these.',
    lore: 'Enchanted by a wizard who watched too many animated plays.',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
  {
    id: 'blades-bloody-banter',
    name: 'Blades of Bloody Banter',
    slotType: 'primary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Swords',
    stats: { damage: '2d10+3 each', attackBonus: 3 },
    properties: ['Finesse', 'Light'],
    enchantments: [
      { name: 'Conversation Starter', description: 'Each hit allows free Intimidation or Persuasion check as part of attack' },
      { name: 'Sword Fight Dialogue', description: 'During melee, engage in witty repartee. Each good comeback heals 1d4 HP' },
    ],
    weight: 4,
    value: 8500,
    description: 'The conversation never stops, even during violence.',
    lore: 'Preferred weapon of a diplomat who was also an assassin.',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
  {
    id: 'pistols-probability-violation',
    name: 'Pistols of Probability Violation',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Dice5',
    stats: { damage: '2d10+3 each' },
    properties: ['Range 80/240'],
    enchantments: [
      { name: 'Impossible Shots', description: 'Can shoot around corners, through small gaps, ricocheting off multiple surfaces' },
      { name: 'Bullet Time Selfie', description: 'In middle of shooting, take selfie with bullet in frame. Make Performance check, success = automatic hit and inspiration' },
    ],
    weight: 4,
    value: 8000,
    description: 'Probability is merely a suggestion.',
    lore: 'These guns don\'t believe in "impossible."',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
  {
    id: 'explosives-escalating-mayhem',
    name: 'Explosives of Escalating Mayhem',
    slotType: 'ranged_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Bomb',
    stats: { damage: 'Variable (2d6-10d6)' },
    properties: ['Radius scales with damage'],
    enchantments: [
      { name: 'Boom Slider', description: 'Declare how big explosion should be. Bigger = more damage but more collateral damage' },
      { name: 'Walk Away Slowly', description: 'After throwing explosive, walk away without looking. Make Charisma check. Success = explosion perfectly timed behind you, look incredibly cool' },
    ],
    weight: 5,
    value: 7000,
    description: 'The explosion is always exactly as big as you want it to be.',
    lore: 'Calibrated by a pyromaniac with very specific aesthetic preferences.',
    setId: 'absolute-absurdity',
    setName: 'Arsenal of Absolute Absurdity',
  },
];

// SET 8: THE SELF-AWARE SLAYER'S KIT
export const selfAwareSlayerSet: EquipmentItem[] = [
  {
    id: 'cowl-cosmic-awareness',
    name: 'Cowl of Cosmic Awareness',
    slotType: 'head',
    rarity: 'artifact',
    level: 20,
    icon: 'Eye',
    stats: { ac: 3, wisdom: 5 },
    properties: ['Truesight 60ft'],
    enchantments: [
      { name: 'See the Strings', description: 'Perceive "fate" as literal strings DM is pulling. Can attempt to cut them (make Dexterity check to avoid predetermined outcomes)' },
      { name: 'Read the Module', description: 'Ask DM what page of the adventure they\'re on. They must show you (but you can\'t read it, just see page number)' },
    ],
    weight: 2,
    value: 12000,
    description: 'Sees the narrative itself.',
    lore: 'Woven from the threads of broken fourth walls.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
  {
    id: 'armor-authorial-intent',
    name: 'Armor of Authorial Intent',
    slotType: 'chest',
    rarity: 'artifact',
    level: 20,
    icon: 'BookOpen',
    stats: { ac: 6 },
    properties: ['Resistance to "plot-mandated" damage'],
    enchantments: [
      { name: 'Narrative Armor', description: 'If DM says "you\'re supposed to lose this fight," gain advantage on all rolls out of spite' },
      { name: "Writer's Block", description: 'Once per session, declare "the writer doesn\'t know what happens next." Force 5-minute improv session where DM and players collaborate on next scene' },
    ],
    weight: 30,
    value: 15000,
    description: 'Protects against authorial decisions.',
    lore: 'Made from rejected manuscript pages given physical form.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
  {
    id: 'gloves-genre-savviness',
    name: 'Gloves of Genre Savviness',
    slotType: 'arms',
    rarity: 'legendary',
    level: 20,
    icon: 'Lightbulb',
    stats: { ac: 3, attackBonus: 3 },
    enchantments: [
      { name: 'Trope Awareness', description: 'Recognize narrative patterns. When DM uses common trope, call it out for advantage' },
      { name: 'Subvert Expectations', description: 'When DM sets up obvious twist, declare "I see where this is going" and suggest alternative. DM must incorporate if it\'s better' },
    ],
    weight: 2,
    value: 6500,
    description: 'You\'ve seen this story before.',
    lore: 'Made for someone who read too many adventure novels.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
  {
    id: 'sash-script-flipping',
    name: 'Sash of Script Flipping',
    slotType: 'waist',
    rarity: 'legendary',
    level: 20,
    icon: 'FileText',
    stats: { ac: 2, saves: 2 },
    enchantments: [
      { name: 'Reverse Psychology', description: 'When told "you can\'t do that," gain +5 bonus to attempt anyway' },
      { name: 'Yes And', description: 'After DM describes scene, add one detail. DM must accept it as canon unless it breaks everything' },
    ],
    weight: 1,
    value: 5000,
    description: 'The script is just a suggestion.',
    lore: 'Worn by an actor who was terrible at following directions.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
  {
    id: 'boots-boundary-crossing',
    name: 'Boots of Boundary Crossing',
    slotType: 'legs',
    rarity: 'legendary',
    level: 20,
    icon: 'FastForward',
    stats: { ac: 3, movement: 25 },
    properties: ['Can phase through "scene transitions"'],
    enchantments: [
      { name: 'Skip Ahead', description: 'Once per session, declare you\'re "fast-forwarding" through boring part. DM must summarize next 10 minutes in 30 seconds' },
      { name: 'Cut to the Chase', description: 'When investigation/puzzle is taking too long, ask "can we just get to the good part?" DM must provide one major clue' },
    ],
    weight: 3,
    value: 6000,
    description: 'Moves between scenes as easily as within them.',
    lore: 'These boots understand that some scenes drag on.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
  {
    id: 'swords-surgical-storytelling',
    name: 'Swords of Surgical Storytelling',
    slotType: 'primary_weapon',
    rarity: 'artifact',
    level: 20,
    icon: 'Swords',
    stats: { damage: '3d8+4 each', attackBonus: 4 },
    properties: ['Finesse', 'Light'],
    enchantments: [
      { name: 'Narrative Edge', description: 'Deal extra damage to "narratively important" enemies (DM must identify them)' },
      { name: "Chekhov's Blades", description: 'If swords are mentioned in description but not used, they must be used before scene ends (guaranteed opportunity)' },
    ],
    weight: 4,
    value: 12000,
    description: 'Every cut advances the plot.',
    lore: 'These blades were made to kill story beats as much as enemies.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
  {
    id: 'guns-guaranteed-payoff',
    name: 'Guns of Guaranteed Payoff',
    slotType: 'secondary_weapon',
    rarity: 'legendary',
    level: 20,
    icon: 'Crosshair',
    stats: { damage: '3d8+4 each' },
    properties: ['Range 100/300'],
    enchantments: [
      { name: 'Setup and Punchline', description: 'If you describe loading guns dramatically, next shot automatically hits' },
      { name: 'Slow-Mo Money Shot', description: 'Declare "slow motion" before shooting. DM must describe in excessive detail, attack has advantage, looks incredible' },
    ],
    weight: 4,
    value: 10000,
    description: 'Every shot matters. Narratively.',
    lore: 'These guns understand dramatic timing.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
  {
    id: 'device-deus-ex-machina',
    name: 'Device of Deus Ex Machina',
    slotType: 'ranged_weapon',
    rarity: 'artifact',
    level: 20,
    icon: 'Wand2',
    stats: { damage: '10d6' },
    properties: ['50ft radius', '1 use per campaign arc'],
    enchantments: [
      { name: 'Convenient Solution', description: 'Solves current problem perfectly but creates new problem for later' },
      { name: 'Ass Pull', description: 'When situation seems impossible, pull out this device. DM must accept you "always had it" despite never mentioning it before' },
    ],
    weight: 5,
    value: 25000,
    description: 'The solution to all problems. Once.',
    lore: 'This device exists because the story demands it.',
    setId: 'self-aware-slayer',
    setName: "The Self-Aware Slayer's Kit",
  },
];

// Combine all legendary items
export const allLegendaryItems: EquipmentItem[] = [
  ...mercWithMouthSet,
  ...chaoticContractsSet,
  ...regenerativeRidiculousnessSet,
  ...selfAwareArsenalSet,
  ...violentComedySet,
  ...unkillableMercSet,
  ...absoluteAbsurditySet,
  ...selfAwareSlayerSet,
];
