// Legendary Set Bonus Definitions
import { SetInfo } from './types';

export const legendarySetDefinitions: SetInfo[] = [
  {
    id: 'merc-with-mouth',
    name: "The Merc with a Mouth's Regalia",
    pieces: [
      'mask-perpetual-commentary',
      'cuirass-regenerative-nonsense',
      'gauntlets-gratuitous-violence',
      'belt-infinite-pouches',
      'greaves-inexplicable-acrobatics',
      'katana-meta-awareness',
      'pistol-anachronistic-mayhem',
      'bow-self-aware-arrows',
    ],
    bonuses: [
      { setId: 'merc-with-mouth', setName: "The Merc with a Mouth's Regalia", piecesRequired: 2, bonus: 'Breaking the Fourth Wall: Can directly address the players once per session' },
      { setId: 'merc-with-mouth', setName: "The Merc with a Mouth's Regalia", piecesRequired: 3, bonus: 'Metagaming Mastery: Advantage on all rolls when you reference game mechanics out loud' },
      { setId: 'merc-with-mouth', setName: "The Merc with a Mouth's Regalia", piecesRequired: 5, bonus: 'Maximum Effort: Once per long rest, double all damage, advantage on all rolls, regenerate 10 HP/round for 1 minute' },
      { setId: 'merc-with-mouth', setName: "The Merc with a Mouth's Regalia", piecesRequired: 8, bonus: "Deadpool's Narrative Control: Once per campaign arc, ask DM to retcon one event from the last session" },
    ],
  },
  {
    id: 'chaotic-contracts',
    name: 'Arsenal of Chaotic Contracts',
    pieces: [
      'cowl-constant-quipping',
      'armor-questionable-sponsorships',
      'bracers-excessive-reloading',
      'sash-taco-trucks',
      'boots-inappropriate-timing',
      'dual-swords-self-referential',
      'grenade-questionable-legality',
      'crossbow-improbable-trick-shots',
    ],
    bonuses: [
      { setId: 'chaotic-contracts', setName: 'Arsenal of Chaotic Contracts', piecesRequired: 2, bonus: 'No Plan Survives Contact: Gain advantage on first action when you ignore the party\'s plan' },
      { setId: 'chaotic-contracts', setName: 'Arsenal of Chaotic Contracts', piecesRequired: 3, bonus: 'Chaotic Neutral Alignment Lock: Cannot be shifted to Lawful or Evil, immune to "boring" mind control' },
      { setId: 'chaotic-contracts', setName: 'Arsenal of Chaotic Contracts', piecesRequired: 5, bonus: 'Luck of the Absurd: Once per session, turn any roll into Natural 20 for something ridiculous' },
      { setId: 'chaotic-contracts', setName: 'Arsenal of Chaotic Contracts', piecesRequired: 8, bonus: 'Master of Mayhem: Random encounters 50% more likely but 100% more interesting, immune to chaos you didn\'t cause' },
    ],
  },
  {
    id: 'regenerative-ridiculousness',
    name: 'Regalia of Regenerative Ridiculousness',
    pieces: [
      'helmet-scarred-memories',
      'plate-persistent-healing',
      'gauntlets-gratuitous-gestures',
      'belt-holsters',
      'greaves-unstoppable-momentum',
      'katanas-slice-dice',
      'pistols-punchline-delivery',
      'rocket-launcher-reasonable',
    ],
    bonuses: [
      { setId: 'regenerative-ridiculousness', setName: 'Regalia of Regenerative Ridiculousness', piecesRequired: 2, bonus: 'Healing Factor Hijinks: Regeneration can\'t be stopped, dismembered parts crawl back together' },
      { setId: 'regenerative-ridiculousness', setName: 'Regalia of Regenerative Ridiculousness', piecesRequired: 3, bonus: 'Too Dumb to Die: Immunity to intelligence-based attacks, mindless undead ignore you' },
      { setId: 'regenerative-ridiculousness', setName: 'Regalia of Regenerative Ridiculousness', piecesRequired: 5, bonus: 'Narrative Immortality: Can\'t permanently die as long as you\'re entertaining' },
      { setId: 'regenerative-ridiculousness', setName: 'Regalia of Regenerative Ridiculousness', piecesRequired: 8, bonus: "Deadpool's Blessing: Aware you're in a game, can reference dice rolls and DM fiat, gain advantage when breaking immersion" },
    ],
  },
  {
    id: 'self-aware-arsenal',
    name: "The Mercenary's Self-Aware Arsenal",
    pieces: [
      'mask-medium-awareness',
      'breastplate-breaking-tension',
      'vambraces-violence-escalation',
      'belt-budget-constraints',
      'boots-sequel-hooks',
      'blade-borrowed-references',
      'gun-genre-confusion',
      'explosive-uncertain-origin',
    ],
    bonuses: [
      { setId: 'self-aware-arsenal', setName: "The Mercenary's Self-Aware Arsenal", piecesRequired: 2, bonus: 'Audience Surrogate: Can ask questions players want answered but characters shouldn\'t know' },
      { setId: 'self-aware-arsenal', setName: "The Mercenary's Self-Aware Arsenal", piecesRequired: 3, bonus: 'Comic Book Physics: Fall damage capped at 20, survive anything that looks cool' },
      { setId: 'self-aware-arsenal', setName: "The Mercenary's Self-Aware Arsenal", piecesRequired: 5, bonus: 'Retroactive Continuity: Once per arc, add new skill proficiency as "I always knew that"' },
      { setId: 'self-aware-arsenal', setName: "The Mercenary's Self-Aware Arsenal", piecesRequired: 8, bonus: "Deadpool's Domain: Reality bends to your comedic timing, improbable coincidences favor you" },
    ],
  },
  {
    id: 'violent-comedy',
    name: 'Vestments of Violent Comedy',
    pieces: [
      'crown-conscious-incompetence',
      'armor-acceptable-losses',
      'gloves-gratuitous-gestures',
      'sash-snack-storage',
      'pants-improbable-pockets',
      'swords-surgical-sarcasm',
      'firearms-flexible-legality',
      'throwing-whatever-handy',
    ],
    bonuses: [
      { setId: 'violent-comedy', setName: 'Vestments of Violent Comedy', piecesRequired: 2, bonus: 'Tonal Dissonance: Advantage on Charisma checks when mood is inappropriate to situation' },
      { setId: 'violent-comedy', setName: 'Vestments of Violent Comedy', piecesRequired: 3, bonus: 'Collateral Damage Immunity: Allies in your area attacks take half damage (they\'re used to it)' },
      { setId: 'violent-comedy', setName: 'Vestments of Violent Comedy', piecesRequired: 5, bonus: 'Recursive Humor Loop: Jokes referencing previous jokes deal stacking +5d6 damage max' },
      { setId: 'violent-comedy', setName: 'Vestments of Violent Comedy', piecesRequired: 8, bonus: 'Living Cartoon Logic: Physics are suggestions, survive lethal damage if death would be "off-brand"' },
    ],
  },
  {
    id: 'unkillable-merc',
    name: "The Unkillable Merc's Loadout",
    pieces: [
      'helm-helpful-hallucinations',
      'cuirass-continuous-carnage',
      'bracers-boundary-breaking',
      'belt-unnecessary-buckles',
      'greaves-gravity-defiance',
      'katanas-killing-jokes',
      'guns-gratuitous-firepower',
      'launcher-disproportionate-response',
    ],
    bonuses: [
      { setId: 'unkillable-merc', setName: "The Unkillable Merc's Loadout", piecesRequired: 2, bonus: 'Regenerative Monologue: Heal 1d6 HP per round while talking' },
      { setId: 'unkillable-merc', setName: "The Unkillable Merc's Loadout", piecesRequired: 3, bonus: 'Immortality Clause: Cannot be permanently killed by normal means, death saves with advantage' },
      { setId: 'unkillable-merc', setName: "The Unkillable Merc's Loadout", piecesRequired: 5, bonus: 'Narrative Immunity: DM must provide resurrection method if killed, no matter how implausible' },
      { setId: 'unkillable-merc', setName: "The Unkillable Merc's Loadout", piecesRequired: 8, bonus: "Deadpool's Dominion: Exist slightly outside normal reality, perceive game mechanics as physical objects" },
    ],
  },
  {
    id: 'absolute-absurdity',
    name: 'Arsenal of Absolute Absurdity',
    pieces: [
      'mask-mixed-messages',
      'breastplate-borrowed-time',
      'gauntlets-gratuitous-gore',
      'belt-bottomless-pouches',
      'boots-bizarre-locomotion',
      'blades-bloody-banter',
      'pistols-probability-violation',
      'explosives-escalating-mayhem',
    ],
    bonuses: [
      { setId: 'absolute-absurdity', setName: 'Arsenal of Absolute Absurdity', piecesRequired: 2, bonus: 'Meta-Textual Awareness: See game mechanics floating in air, gain +1 when predicting DM strategy' },
      { setId: 'absolute-absurdity', setName: 'Arsenal of Absolute Absurdity', piecesRequired: 3, bonus: 'Protagonist Privilege: Find exactly what you need in random loot, NPCs remember you' },
      { setId: 'absolute-absurdity', setName: 'Arsenal of Absolute Absurdity', piecesRequired: 5, bonus: "Deadpool's Playground: Reality bends for jokes, DM must say 'yes, and...' once per session" },
      { setId: 'absolute-absurdity', setName: 'Arsenal of Absolute Absurdity', piecesRequired: 8, bonus: 'Master of the Meta: Control narrative flow, suggest scene transitions, once per arc declare "bottle episode"' },
    ],
  },
  {
    id: 'self-aware-slayer',
    name: "The Self-Aware Slayer's Kit",
    pieces: [
      'cowl-cosmic-awareness',
      'armor-authorial-intent',
      'gloves-genre-savviness',
      'sash-script-flipping',
      'boots-boundary-crossing',
      'swords-surgical-storytelling',
      'guns-guaranteed-payoff',
      'device-deus-ex-machina',
    ],
    bonuses: [
      { setId: 'self-aware-slayer', setName: "The Self-Aware Slayer's Kit", piecesRequired: 2, bonus: 'Audience Participation: Directly address players, ask for suggestions, must follow majority vote' },
      { setId: 'self-aware-slayer', setName: "The Self-Aware Slayer's Kit", piecesRequired: 3, bonus: 'Dramatic Irony Exploitation: DM must tell you one thing your character doesn\'t know' },
      { setId: 'self-aware-slayer', setName: "The Self-Aware Slayer's Kit", piecesRequired: 5, bonus: 'Narrative Control: Once per session, suggest plot development DM must seriously consider' },
      { setId: 'self-aware-slayer', setName: "The Self-Aware Slayer's Kit", piecesRequired: 8, bonus: 'Co-Author Status: Help write story, propose scenes/NPCs, once per arc invoke "executive producer" veto' },
    ],
  },
];
