import { SpellDefinition } from '../types';

export const FIRST_LEVEL_SPELLS: SpellDefinition[] = [
  // ============================================
  // ILLUSION SPELLS
  // ============================================
  {
    id: 'disguise-self',
    name: 'Disguise Self',
    level: 1,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You make yourself—including clothing, armor, weapons, and belongings—look different until the spell ends.',
    iconName: 'User',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Visual identity mask applied. Detection threshold: Investigation check.',
      jarvis: 'A new face for the occasion, Sir. Quite dashing, if I may say.',
      deadpool: 'I can look like ANYONE! Even Ryan Reynolds! Wait, I already— never mind.',
    },
  },
  {
    id: 'silent-image',
    name: 'Silent Image',
    level: 1,
    school: 'illusion',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You create the image of an object, creature, or visible phenomenon that fits within a 15-foot cube.',
    iconName: 'Image',
    pathRestrictions: ['arcane_trickster', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Visual projection manifested. No audio component. Investigation: reveals falsehood.',
      jarvis: 'A silent picture show, Sir. Let the imagination fill the gaps.',
      deadpool: 'Silent movie time! Except no Charlie Chaplin. Unless I make an illusion of him!',
    },
  },
  {
    id: 'color-spray',
    name: 'Color Spray',
    level: 1,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self (15-foot cone)',
    components: { verbal: true, somatic: true, material: 'a pinch of sand or powder colored red, yellow, and blue' },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'A dazzling array of flashing lights springs from your hand. Roll 6d10 to determine hit points of creatures affected (blinded).',
    iconName: 'Palette',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Chromatic assault initiated. 6d10 HP threshold for blindness effect.',
      jarvis: 'A rainbow of incapacitation, Sir. Fabulous and effective.',
      deadpool: 'TASTE THE RAINBOW! Wait, wrong franchise. SEE THE RAINBOW... then DON\'T!',
    },
  },

  // ============================================
  // ENCHANTMENT SPELLS
  // ============================================
  {
    id: 'charm-person',
    name: 'Charm Person',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You attempt to charm a humanoid. It must make a WIS save or regard you as a friendly acquaintance.',
    saveStat: 'WIS',
    iconName: 'Heart',
    higherLevels: 'Target one additional creature for each slot level above 1st.',
    pathRestrictions: ['arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Social override initiated. Target perception: friendly.',
      jarvis: 'A touch of magical charisma, Sir. They\'ll find you quite agreeable.',
      deadpool: 'Make friends and influence people! With MAGIC! Take that, Dale Carnegie!',
    },
  },
  {
    id: 'sleep',
    name: 'Sleep',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of fine sand, rose petals, or a cricket' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Roll 5d8; the total is the HP of creatures this spell can affect. Starting with the lowest, creatures fall unconscious.',
    iconName: 'Moon',
    higherLevels: 'Roll an additional 2d8 for each slot level above 1st.',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Somnolence field deployed. HP threshold: 5d8. Unconsciousness imminent.',
      jarvis: 'Sweet dreams, Sir\'s adversaries.',
      deadpool: 'Sleepy time! Like a lullaby, except instead of mom it\'s MAGIC and instead of bed it\'s THE FLOOR.',
    },
  },
  {
    id: 'hideous-laughter',
    name: 'Hideous Laughter',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'tiny tarts and a feather' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'A creature perceives everything as hilariously funny, falling prone and becoming incapacitated.',
    saveStat: 'WIS',
    iconName: 'Laugh',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Humor override engaged. Target capacity: incapacitated. Side effect: prone.',
      jarvis: 'They\'ll find even the darkest situation... amusing, Sir.',
      deadpool: 'MAKE \'EM LAUGH! I love this spell! It\'s basically my whole personality in magic form!',
    },
  },

  // ============================================
  // ABJURATION SPELLS
  // ============================================
  {
    id: 'shield',
    name: 'Shield',
    level: 1,
    school: 'abjuration',
    castingTime: 'reaction',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'An invisible barrier of magical force appears and protects you. +5 bonus to AC until the start of your next turn.',
    iconName: 'Shield',
    pathRestrictions: ['eldritch_knight', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Barrier deployed. AC bonus: +5. Includes immunity to Magic Missile.',
      jarvis: 'A timely defense, Sir. The attack shall not land.',
      deadpool: 'FORCE FIELD! Like Sue Storm except I\'m way more attractive and humble!',
    },
  },
  {
    id: 'absorb-elements',
    name: 'Absorb Elements',
    level: 1,
    school: 'abjuration',
    castingTime: 'reaction',
    range: 'Self',
    components: { verbal: false, somatic: true },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'Capture incoming elemental energy, reduce damage, and deal extra damage on your next melee hit.',
    iconName: 'Zap',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Elemental absorption active. Energy captured for redirection.',
      jarvis: 'Absorbing the blow and returning the favor, Sir. Efficient.',
      deadpool: 'You hit me with fire? Now MY sword is on fire! SCIENCE!',
    },
  },
  {
    id: 'armor-of-agathys',
    name: 'Armor of Agathys',
    level: 1,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a cup of water' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'A protective magical force surrounds you. Gain 5 temp HP; while you have them, attackers take 5 cold damage.',
    iconName: 'Snowflake',
    higherLevels: 'Both temp HP and cold damage increase by 5 for each slot level above 1st.',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Cryo-retribution armor online. Temp HP: 5. Counter-damage: 5 cold.',
      jarvis: 'Touch and be touched in return, Sir. With frost.',
      deadpool: 'Hit me and YOU get hurt! It\'s like dating me but with more ice damage!',
    },
  },

  // ============================================
  // EVOCATION SPELLS
  // ============================================
  {
    id: 'magic-missile',
    name: 'Magic Missile',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You create three glowing darts of magical force. Each dart hits automatically and deals 1d4+1 force damage.',
    attackType: 'auto',
    damageType: 'force',
    damageFormula: '3d4+3',
    iconName: 'Sparkles',
    higherLevels: 'Create one additional dart for each slot level above 1st.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Force projectiles: 3. Auto-hit confirmed. Total damage: 3d4+3.',
      jarvis: 'Three unerring strikes, Sir. Magic Missile never misses.',
      deadpool: 'PEW PEW PEW! Three little darts that ALWAYS hit! Unlike my love life!',
    },
  },
  {
    id: 'thunderwave',
    name: 'Thunderwave',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (15-foot cube)',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube must make a CON save.',
    saveStat: 'CON',
    damageType: 'thunder',
    damageFormula: '2d8',
    iconName: 'Waves',
    higherLevels: 'Damage increases by 1d8 for each slot level above 1st.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Sonic shockwave deployed. 15-foot cube. Targets pushed 10 feet on fail.',
      jarvis: 'A thunderous entrance, Sir. Or exit, as the case may be.',
      deadpool: 'BOOM! Everyone flies away! It\'s like my personality but with sound damage!',
    },
  },
  {
    id: 'burning-hands',
    name: 'Burning Hands',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (15-foot cone)',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'As you hold your hands together with thumbs touching, a thin sheet of flames shoots forth from your outstretched fingers.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '3d6',
    iconName: 'Flame',
    higherLevels: 'Damage increases by 1d6 for each slot level above 1st.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Thermal projection initiated. 15-foot cone. DEX save for half.',
      jarvis: 'Fire from the fingertips, Sir. Quite dramatic.',
      deadpool: 'HADOUKEN! Wait, that\'s not— FIRE HANDS! Jazz hands but DEADLY!',
    },
  },
  {
    id: 'hellish-rebuke',
    name: 'Hellish Rebuke',
    level: 1,
    school: 'evocation',
    castingTime: 'reaction',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '2d10',
    iconName: 'Flame',
    higherLevels: 'Damage increases by 1d10 for each slot level above 1st.',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Retribution protocol engaged. 2d10 fire damage on trigger.',
      jarvis: 'An eye for an eye, Sir. Delivered in flames.',
      deadpool: 'You hit ME? Enjoy your SPONTANEOUS COMBUSTION, buddy!',
    },
  },

  // ============================================
  // NECROMANCY SPELLS
  // ============================================
  {
    id: 'false-life',
    name: 'False Life',
    level: 1,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a small amount of alcohol' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'Bolstering yourself with a necromantic facsimile of life, you gain 1d4+4 temporary hit points.',
    iconName: 'Heart',
    higherLevels: 'Gain an additional 5 temp HP for each slot level above 1st.',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Temporary life force injection: 1d4+4. Duration: 1 hour.',
      jarvis: 'A bit of borrowed vitality, Sir. Quite useful in a pinch.',
      deadpool: 'Fake health! Like my fake smile! And my fake confidence! Wait, that one\'s real.',
    },
  },
  {
    id: 'ray-of-sickness',
    name: 'Ray of Sickness',
    level: 1,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A ray of sickening greenish energy lashes out. Make a ranged spell attack; hit also poisons target on failed CON save.',
    attackType: 'ranged',
    saveStat: 'CON',
    damageType: 'poison',
    damageFormula: '2d8',
    iconName: 'Biohazard',
    higherLevels: 'Damage increases by 1d8 for each slot level above 1st.',
    pathRestrictions: ['shadow_blade'],
    personalityQuips: {
      thunderhead: 'Pathogenic ray deployed. Poison condition on failed CON save.',
      jarvis: 'A rather unpleasant ailment, Sir. Effective for debilitation.',
      deadpool: 'Gross green laser of YUCK! It\'s like a flu shot but reversed!',
    },
  },

  // ============================================
  // DIVINATION SPELLS
  // ============================================
  {
    id: 'detect-magic',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'For the duration, you sense the presence of magic within 30 feet. You can see a faint aura around any visible magical object or creature.',
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'Arcane detection scan initiated. Range: 30 feet. School identification: enabled.',
      jarvis: 'Scanning for magical signatures, Sir. The results are illuminating.',
      deadpool: 'Magic goggles ON! Ooh, that sword is glowy! That ring is glowy! EVERYTHING IS GLOWY!',
    },
  },
  {
    id: 'hex',
    name: 'Hex',
    level: 1,
    school: 'enchantment',
    castingTime: 'bonus_action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'the petrified eye of a newt' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You curse a target. Deal an extra 1d6 necrotic damage whenever you hit the cursed target with an attack.',
    damageType: 'necrotic',
    damageFormula: '1d6',
    iconName: 'Crosshair',
    higherLevels: 'Duration increases (8 hours at 3rd, 24 hours at 5th).',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Curse protocol active. Bonus damage: 1d6 necrotic per hit.',
      jarvis: 'A persistent curse, Sir. Every blow will sting a little more.',
      deadpool: 'You\'re HEXED now! Like a witch but cooler! Extra damage FOREVER! Well, for an hour.',
    },
  },
  {
    id: 'wrathful-smite',
    name: 'Wrathful Smite',
    level: 1,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: 'Self',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Your next melee weapon hit deals an extra 1d6 psychic damage. Target must make WIS save or be frightened.',
    saveStat: 'WIS',
    damageType: 'psychic',
    damageFormula: '1d6',
    iconName: 'Sword',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Psychic payload armed. Fear condition on failed WIS save.',
      jarvis: 'Your blade carries terror, Sir. Most unsettling for them.',
      deadpool: 'My sword is full of ANGER! And fear! Like my therapist says about me!',
    },
  },
];

export function getFirstLevelSpellsByPath(path: string): SpellDefinition[] {
  return FIRST_LEVEL_SPELLS.filter(
    spell => !spell.pathRestrictions || spell.pathRestrictions.includes(path as any)
  );
}
