import { SpellDefinition } from '../types';

export const SECOND_LEVEL_SPELLS: SpellDefinition[] = [
  // ============================================
  // ILLUSION SPELLS
  // ============================================
  {
    id: 'invisibility',
    name: 'Invisibility',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'an eyelash encased in gum arabic' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is also invisible.',
    iconName: 'EyeOff',
    higherLevels: 'Target one additional creature for each slot level above 2nd.',
    pathRestrictions: ['arcane_trickster', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Optical nullification complete. Visual signature: undetectable.',
      jarvis: 'You\'ve vanished, Sir. Though I can still detect your heat signature.',
      deadpool: 'NOW YOU SEE ME... now you don\'t! Classic! Never gets old! Unlike me! I regenerate!',
    },
  },
  {
    id: 'mirror-image',
    name: 'Mirror Image',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Three illusory duplicates of yourself appear. Each duplicate has AC 10 + DEX modifier and can absorb attacks.',
    iconName: 'Users',
    pathRestrictions: ['arcane_trickster', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Decoy generation complete. Duplicates: 3. Attack absorption: active.',
      jarvis: 'Three of you, Sir. The enemy will have trouble finding the original.',
      deadpool: 'There\'s THREE of me now! My therapist just fainted! Actually, four of me! I have voices!',
    },
  },
  {
    id: 'phantasmal-force',
    name: 'Phantasmal Force',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You craft an illusion that takes root in the mind of a creature. Target perceives the phantasm as real and rationalizes illogical outcomes.',
    saveStat: 'INT',
    damageType: 'psychic',
    damageFormula: '1d6',
    iconName: 'Brain',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Mental projection implanted. Reality perception: compromised.',
      jarvis: 'The illusion becomes their reality, Sir. Quite the mental trap.',
      deadpool: 'Make \'em see things! Like that time I thought the floor was lava! Wait, that was REAL lava.',
    },
  },
  {
    id: 'shadow-blade',
    name: 'Shadow Blade',
    level: 2,
    school: 'illusion',
    castingTime: 'bonus_action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You weave threads of shadow to create a blade of solidified gloom. Deals 2d8 psychic damage and has advantage in dim light or darkness.',
    attackType: 'melee',
    damageType: 'psychic',
    damageFormula: '2d8',
    iconName: 'Sword',
    higherLevels: 'Damage increases (3d8 at 3rd-4th, 4d8 at 5th-6th, 5d8 at 7th+).',
    pathRestrictions: ['shadow_blade', 'arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Umbral weapon manifested. Damage: 2d8 psychic. Darkness bonus: advantage.',
      jarvis: 'A blade forged from shadow itself, Sir. Quite elegant.',
      deadpool: 'Shadow sword! SO EDGY! Literally! Get it? Because it\'s a sword? I\'ll see myself out.',
    },
  },

  // ============================================
  // ABJURATION SPELLS
  // ============================================
  {
    id: 'blur',
    name: 'Blur',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Your body becomes blurred, shifting and wavering. Any creature has disadvantage on attack rolls against you.',
    iconName: 'Wind',
    pathRestrictions: ['eldritch_knight', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Visual distortion field active. Incoming attacks: disadvantage.',
      jarvis: 'You\'re quite difficult to pin down now, Sir.',
      deadpool: 'I\'m all blurry! Like that photo of Bigfoot! Except I\'m real! ...I think?',
    },
  },
  {
    id: 'misty-step',
    name: 'Misty Step',
    level: 2,
    school: 'conjuration',
    castingTime: 'bonus_action',
    range: 'Self',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    iconName: 'Footprints',
    pathRestrictions: ['arcane_trickster', 'shadow_blade', 'eldritch_knight', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Short-range teleport executed. Distance: 30 feet. Status: complete.',
      jarvis: 'A graceful exit, Sir. Or entrance, as the situation warrants.',
      deadpool: 'POOF! I\'m over here now! It\'s like fast travel but without the loading screen!',
    },
  },
  {
    id: 'hold-person',
    name: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a humanoid you can see. Target must succeed on a WIS save or be paralyzed for the duration.',
    saveStat: 'WIS',
    iconName: 'Lock',
    higherLevels: 'Target one additional humanoid for each slot level above 2nd.',
    pathRestrictions: ['arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Motor function lockdown initiated. Target: paralyzed. Attacks: auto-crit.',
      jarvis: 'They won\'t be going anywhere, Sir. Quite stuck.',
      deadpool: 'FREEZE! Like the ice bucket challenge except you\'re the bucket AND the ice!',
    },
  },

  // ============================================
  // EVOCATION SPELLS
  // ============================================
  {
    id: 'scorching-ray',
    name: 'Scorching Ray',
    level: 2,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You create three rays of fire and hurl them at targets. Make a ranged spell attack for each ray.',
    attackType: 'ranged',
    damageType: 'fire',
    damageFormula: '2d6',
    iconName: 'Flame',
    higherLevels: 'Create one additional ray for each slot level above 2nd.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Triple fire beam array online. 3 attacks × 2d6 fire each.',
      jarvis: 'Three beams of concentrated heat, Sir. Divide and conquer.',
      deadpool: 'Three finger guns of FIRE! Pew! Pew! Pew! I\'m basically a fire-breathing Fonzie!',
    },
  },
  {
    id: 'shatter',
    name: 'Shatter',
    level: 2,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a chip of mica' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A sudden loud ringing noise painfully intense erupts. Each creature in a 10-foot radius must make a CON save.',
    saveStat: 'CON',
    damageType: 'thunder',
    damageFormula: '3d8',
    iconName: 'Volume2',
    higherLevels: 'Damage increases by 1d8 for each slot level above 2nd.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Sonic detonation in progress. 10-foot radius. Objects vulnerable.',
      jarvis: 'A cacophonous assault, Sir. Ears will be ringing.',
      deadpool: 'BOOM! Like a dubstep drop but actually HURTS! Take that, glass ceiling! Literally!',
    },
  },

  // ============================================
  // NECROMANCY SPELLS
  // ============================================
  {
    id: 'darkness',
    name: 'Darkness',
    level: 2,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: 'bat fur and a drop of pitch or piece of coal' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Magical darkness spreads from a point within range to fill a 15-foot-radius sphere. Darkvision can\'t penetrate it.',
    iconName: 'Moon',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Light nullification zone deployed. Radius: 15 feet. Darkvision: ineffective.',
      jarvis: 'Complete and utter darkness, Sir. Even enhanced vision fails here.',
      deadpool: 'Now nobody can see! Including me! This seemed like a better idea five seconds ago!',
    },
  },
  {
    id: 'shadow-step',
    name: 'Shadow Step',
    level: 2,
    school: 'conjuration',
    castingTime: 'bonus_action',
    range: 'Self',
    components: { verbal: false, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'When in dim light or darkness, you teleport up to 60 feet to another space in dim light or darkness you can see.',
    iconName: 'Moon',
    pathRestrictions: ['shadow_blade'],
    personalityQuips: {
      thunderhead: 'Shadow transit executed. Requirement: dim light at both points.',
      jarvis: 'From shadow to shadow, Sir. Quite the dramatic entrance.',
      deadpool: 'Shadow hopping! Like a gothic frog! A very handsome, regenerating gothic frog!',
    },
  },

  // ============================================
  // WARLOCK SPELLS
  // ============================================
  {
    id: 'branding-smite',
    name: 'Branding Smite',
    level: 2,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: 'Self',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'The next time you hit with a weapon attack, it deals an extra 2d6 radiant damage and target becomes visible, shedding dim light.',
    damageType: 'radiant',
    damageFormula: '2d6',
    iconName: 'Sun',
    higherLevels: 'Damage increases by 1d6 for each slot level above 2nd.',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Radiant brand prepared. Invisibility countermeasure: active.',
      jarvis: 'Your blade carries the light, Sir. Nowhere to hide.',
      deadpool: 'Glowy sword of \'no hiding allowed\'! It\'s like a magical flashlight that HURTS!',
    },
  },
  {
    id: 'crown-of-madness',
    name: 'Crown of Madness',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'A jagged iron crown appears on target\'s head. On their turn, they must attack a creature you designate before moving.',
    saveStat: 'WIS',
    iconName: 'Crown',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Mental override crown established. Forced attack protocol: engaged.',
      jarvis: 'Puppet strings attached, Sir. They dance to your tune.',
      deadpool: 'WEAR THE CROWN OF CRAZY! Now hit your friends! It\'s like Thanksgiving dinner but faster!',
    },
  },
  {
    id: 'spider-climb',
    name: 'Spider Climb',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a drop of bitumen and a spider' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Until the spell ends, one willing creature gains the ability to move up, down, and across vertical surfaces and upside down along ceilings.',
    iconName: 'Bug',
    personalityQuips: {
      thunderhead: 'Surface adhesion augmentation complete. Gravity: optional.',
      jarvis: 'Wall-crawling capabilities enabled, Sir. Quite the Spider-Man impression.',
      deadpool: 'Spider powers! I can climb walls! Does whatever a spider— wait, Marvel lawyers incoming!',
    },
  },
];

export function getSecondLevelSpellsByPath(path: string): SpellDefinition[] {
  return SECOND_LEVEL_SPELLS.filter(
    spell => !spell.pathRestrictions || spell.pathRestrictions.includes(path as any)
  );
}
