import { SpellDefinition } from '../types';

export const THIRD_LEVEL_SPELLS: SpellDefinition[] = [
  // ============================================
  // ILLUSION SPELLS
  // ============================================
  {
    id: 'major-image',
    name: 'Major Image',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You create the image of an object, creature, or visible phenomenon no larger than a 20-foot cube. It seems completely real, including sounds, smells, and temperature.',
    iconName: 'Image',
    higherLevels: 'At 6th level, the spell lasts until dispelled without requiring concentration.',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Holographic projection matrix: 20-cubic-foot maximum. Sensory fidelity: 99.7%.',
      jarvis: 'A most convincing illusion, Sir. Complete with olfactory and thermal signatures.',
      deadpool: 'I can make ANYTHING appear! Like a taco truck! Or Ryan Reynolds! Wait, that\'s just a mirror...',
    },
  },
  {
    id: 'phantom-steed',
    name: 'Phantom Steed',
    level: 3,
    school: 'illusion',
    castingTime: '1_minute',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: true,
    description: 'A Large quasi-real, horselike creature appears. It has a speed of 100 feet and can travel 10 miles in an hour.',
    iconName: 'Zap',
    pathRestrictions: ['arcane_trickster', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Spectral mount materialized. Velocity: 100 feet per round. Endurance: 1 hour.',
      jarvis: 'Your ethereal steed awaits, Sir. Quite the dramatic entrance it shall provide.',
      deadpool: 'GHOST HORSE! It\'s like a regular horse but you can\'t feed it carrots! Trust me, I tried!',
    },
  },
  {
    id: 'fear',
    name: 'Fear',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self (30-foot cone)',
    components: { verbal: true, somatic: true, material: 'a white feather or the heart of a hen' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You project a phantasmal image of a creature\'s worst fears. Each creature in a 30-foot cone must succeed on a WIS save or drop what it\'s holding and become frightened.',
    saveStat: 'WIS',
    iconName: 'Ghost',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Terror projection initiated. Cone of effect: 30 feet. Psychological impact: severe.',
      jarvis: 'A rather unsettling display, Sir. Their deepest fears made manifest.',
      deadpool: 'BOO! But like, SUPER boo! Their worst nightmare! For me that\'s running out of chimichangas!',
    },
  },
  {
    id: 'hypnotic-pattern',
    name: 'Hypnotic Pattern',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a glowing stick of incense or a crystal vial filled with phosphorescent material' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You create a twisting pattern of colors in a 30-foot cube. Each creature that sees the pattern must make a WIS save or become charmed and incapacitated.',
    saveStat: 'WIS',
    iconName: 'Sparkles',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Mesmerizing pattern deployed. Neural override probability: 73.2%.',
      jarvis: 'A captivating display, Sir. They\'ll be quite... distracted.',
      deadpool: 'Pretty colors! SO pretty! Wait, am I supposed to look at it too? FOCUS, WADE!',
    },
  },

  // ============================================
  // ABJURATION SPELLS
  // ============================================
  {
    id: 'counterspell',
    name: 'Counterspell',
    level: 3,
    school: 'abjuration',
    castingTime: 'reaction',
    range: '60 feet',
    components: { verbal: false, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You attempt to interrupt a creature casting a spell. If it\'s 3rd level or lower, it automatically fails. Higher levels require an ability check.',
    iconName: 'Ban',
    higherLevels: 'Automatically counter spells of the slot level used.',
    pathRestrictions: ['eldritch_knight', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Arcane countermeasure deployed. Spell nullification: complete.',
      jarvis: 'Their spell has been interrupted, Sir. Quite rude of you, really.',
      deadpool: 'NOPE! No magic for you! It\'s like a magical restraining order!',
    },
  },
  {
    id: 'dispel-magic',
    name: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose one creature, object, or magical effect. Any spell of 3rd level or lower ends. Higher level spells require an ability check.',
    iconName: 'XCircle',
    higherLevels: 'Automatically end spells of the slot level used.',
    pathRestrictions: ['eldritch_knight', 'arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Magic nullification field activated. Enchantments: terminated.',
      jarvis: 'All magical effects have been... tidied up, Sir.',
      deadpool: 'BEGONE, MAGIC! Back to the shadow realm! Or wherever magic goes when it\'s embarrassed!',
    },
  },
  {
    id: 'protection-from-energy',
    name: 'Protection from Energy',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'For the duration, the willing creature you touch has resistance to one damage type: acid, cold, fire, lightning, or thunder.',
    iconName: 'Shield',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Elemental resistance matrix active. Damage reduction: 50%.',
      jarvis: 'Energy shielding engaged, Sir. That particular element won\'t be nearly as bothersome.',
      deadpool: 'Fire? Pfft. Cold? Please. I\'m basically a walking thermos now!',
    },
  },

  // ============================================
  // CONJURATION SPELLS
  // ============================================
  {
    id: 'thunder-step',
    name: 'Thunder Step',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You teleport to an unoccupied space you can see within range. Immediately after, a thunderous boom erupts, dealing 3d10 thunder damage to creatures within 10 feet of where you left.',
    damageType: 'thunder',
    damageFormula: '3d10',
    iconName: 'Zap',
    higherLevels: 'Damage increases by 1d10 for each slot level above 3rd.',
    pathRestrictions: ['eldritch_knight', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Sonic teleportation executed. Departure zone: 3d10 thunder damage.',
      jarvis: 'A rather dramatic exit, Sir. Complete with sonic boom.',
      deadpool: 'BAMF! But LOUDER! Like Thor and Nightcrawler had a baby! A very noisy baby!',
    },
  },
  {
    id: 'summon-shadowspawn',
    name: 'Summon Shadowspawn',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'tears inside a gem worth at least 300 gp' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You call forth a shadowy spirit. Choose Fury, Despair, or Fear form, each with unique abilities.',
    iconName: 'Ghost',
    higherLevels: 'The creature gains additional HP for each slot level above 3rd.',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Shadowfell entity summoned. Form selection: awaiting input.',
      jarvis: 'A creature of shadow at your command, Sir. Most... unsettling.',
      deadpool: 'Come here, shadow buddy! You\'re like my imaginary friend but REAL! And terrifying!',
    },
  },

  // ============================================
  // EVOCATION SPELLS
  // ============================================
  {
    id: 'fireball',
    name: 'Fireball',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a tiny ball of bat guano and sulfur' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. 8d6 fire damage in a 20-foot radius.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '8d6',
    iconName: 'Flame',
    higherLevels: 'Damage increases by 1d6 for each slot level above 3rd.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Thermobaric detonation initiated. Radius: 20 feet. Damage: 8d6 fire.',
      jarvis: 'The classic, Sir. Nothing says \'problem solved\' quite like a massive explosion.',
      deadpool: 'FIREBALL! The spell that says "I don\'t care about collateral damage or fire safety regulations!"',
    },
  },
  {
    id: 'lightning-bolt',
    name: 'Lightning Bolt',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (100-foot line)',
    components: { verbal: true, somatic: true, material: 'a bit of fur and a rod of amber, crystal, or glass' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you. Each creature in the line must make a DEX save. 8d6 lightning damage.',
    saveStat: 'DEX',
    damageType: 'lightning',
    damageFormula: '8d6',
    iconName: 'Zap',
    higherLevels: 'Damage increases by 1d6 for each slot level above 3rd.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Electrical discharge: 100-foot linear trajectory. Damage output: 8d6.',
      jarvis: 'Quite the shocking development for anyone in that line, Sir.',
      deadpool: 'UNLIMITED POWER! Wait, wrong franchise. ADEQUATE POWER!',
    },
  },
  {
    id: 'vampiric-touch',
    name: 'Vampiric Touch',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'The touch of your shadow-wreathed hand siphons life force. On a hit, deal 3d6 necrotic damage and regain HP equal to half the damage dealt.',
    attackType: 'melee',
    damageType: 'necrotic',
    damageFormula: '3d6',
    iconName: 'Heart',
    higherLevels: 'Damage increases by 1d6 for each slot level above 3rd.',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Life force extraction protocol active. Self-repair ratio: 50%.',
      jarvis: 'Draining their vitality to restore your own, Sir. Efficient, if macabre.',
      deadpool: 'I\'m basically a spa treatment that HURTS! Stealing youth one touch at a time!',
    },
  },

  // ============================================
  // ENCHANTMENT SPELLS
  // ============================================
  {
    id: 'enemies-abound',
    name: 'Enemies Abound',
    level: 3,
    school: 'enchantment',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You reach into the mind of one creature and plant seeds of paranoia. Target loses ability to distinguish friend from foe, treating all as enemies.',
    saveStat: 'INT',
    iconName: 'Users',
    pathRestrictions: ['arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Paranoia subroutine implanted. Friend/foe recognition: disabled.',
      jarvis: 'They can\'t tell who\'s on their side anymore, Sir. Quite the tactical advantage.',
      deadpool: 'Now EVERYONE is your enemy! Just like my Thanksgiving dinners!',
    },
  },
  {
    id: 'hunger-of-hadar',
    name: 'Hunger of Hadar',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a pickled octopus tentacle' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You open a gateway to the dark between the stars, creating a 20-foot-radius sphere of darkness. Creatures take cold damage at the start and acid damage if they end their turn inside.',
    damageType: 'cold',
    damageFormula: '2d6',
    iconName: 'Moon',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Void breach detected. Hadar\'s hunger: manifesting. Environmental hazard: extreme.',
      jarvis: 'You\'ve opened a door to... somewhere quite unpleasant, Sir.',
      deadpool: 'THE DARKNESS BETWEEN STARS! It\'s like my soul but with more tentacles! Probably!',
    },
  },

  // ============================================
  // TRANSMUTATION SPELLS
  // ============================================
  {
    id: 'haste',
    name: 'Haste',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a shaving of licorice root' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Target gains +2 AC, advantage on DEX saves, doubled speed, and an additional action each turn (limited uses). When the spell ends, target can\'t move or take actions until after its next turn.',
    iconName: 'Zap',
    pathRestrictions: ['eldritch_knight', 'arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Temporal acceleration engaged. Speed: doubled. Combat efficiency: +200%.',
      jarvis: 'Time seems to slow for everyone else, Sir. You\'re operating on an entirely different level.',
      deadpool: 'GOTTA GO FAST! I\'m like Sonic but with more swords and less copyright issues!',
    },
  },
  {
    id: 'slow',
    name: 'Slow',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a drop of molasses' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You alter time around up to six creatures. -2 AC, -2 DEX saves, can\'t use reactions, halved speed. Can only use action OR bonus action, not both.',
    saveStat: 'WIS',
    iconName: 'Clock',
    pathRestrictions: ['eldritch_knight', 'arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Temporal deceleration field active. Target efficiency: reduced by 75%.',
      jarvis: 'They\'re moving through molasses now, Sir. Metaphorically speaking.',
      deadpool: 'Welcome to the SLOW ZONE! It\'s like the DMV but magical!',
    },
  },
  {
    id: 'fly',
    name: 'Fly',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a wing feather from any bird' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You touch a willing creature. The target gains a flying speed of 60 feet for the duration.',
    iconName: 'Wind',
    higherLevels: 'Target one additional creature for each slot level above 3rd.',
    pathRestrictions: ['eldritch_knight', 'arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Anti-gravity field applied. Flight velocity: 60 feet per round.',
      jarvis: 'You\'re airborne, Sir. Do try not to look down.',
      deadpool: 'I CAN FLY! I\'m like Superman but with better wisecracks and worse impulse control!',
    },
  },
];

export function getThirdLevelSpellsByPath(path: string): SpellDefinition[] {
  return THIRD_LEVEL_SPELLS.filter(
    spell => !spell.pathRestrictions || spell.pathRestrictions.includes(path as any)
  );
}
