import { SpellDefinition } from '../types';

export const FOURTH_LEVEL_SPELLS: SpellDefinition[] = [
  // ============================================
  // ILLUSION SPELLS
  // ============================================
  {
    id: 'greater-invisibility',
    name: 'Greater Invisibility',
    level: 4,
    school: 'illusion',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You or a creature you touch becomes invisible until the spell ends. The invisibility doesn\'t end when the target attacks or casts a spell.',
    iconName: 'EyeOff',
    pathRestrictions: ['arcane_trickster', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Advanced optical nullification active. Combat invisibility: maintained.',
      jarvis: 'Complete invisibility, Sir, even during combat. They won\'t see you coming. Or going.',
      deadpool: 'I\'m INVISIBLE and I can ATTACK! It\'s like being a ghost but with more stabbing!',
    },
  },
  {
    id: 'phantasmal-killer',
    name: 'Phantasmal Killer',
    level: 4,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You tap into the nightmares of a creature and create an illusory manifestation of its deepest fears. 4d10 psychic damage on failed save each turn.',
    saveStat: 'WIS',
    damageType: 'psychic',
    damageFormula: '4d10',
    iconName: 'Skull',
    higherLevels: 'Damage increases by 1d10 for each slot level above 4th.',
    pathRestrictions: ['arcane_trickster', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Nightmare extraction complete. Psychic manifestation: lethal.',
      jarvis: 'Their worst fears made real, Sir. A rather... permanent solution.',
      deadpool: 'What\'s YOUR worst nightmare? Mine is a world without tacos! Or Ryan Reynolds retiring!',
    },
  },
  {
    id: 'hallucinatory-terrain',
    name: 'Hallucinatory Terrain',
    level: 4,
    school: 'illusion',
    castingTime: '10_minutes',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a stone, a twig, and a bit of green plant' },
    duration: '24 hours',
    concentration: false,
    ritual: false,
    description: 'You make natural terrain in a 150-foot cube look, sound, and smell like another sort of natural terrain.',
    iconName: 'Mountain',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Environmental hologram deployed. Coverage: 150-foot cube. Duration: 24 hours.',
      jarvis: 'The terrain itself becomes your deception, Sir. Quite the elaborate ruse.',
      deadpool: 'I turned the swamp into a BEACH! Or wait, is it the other way around? I forget!',
    },
  },

  // ============================================
  // ABJURATION SPELLS
  // ============================================
  {
    id: 'fire-shield',
    name: 'Fire Shield',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a bit of phosphorus or a firefly' },
    duration: '10 minutes',
    concentration: false,
    ritual: false,
    description: 'Thin flames wreathe your body, shedding bright light. Choose warm (fire resistance, cold retaliation) or chill (cold resistance, fire retaliation). Melee attackers take 2d8 damage.',
    damageType: 'fire',
    damageFormula: '2d8',
    iconName: 'Flame',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Reactive energy shield online. Melee retaliation: 2d8 elemental damage.',
      jarvis: 'Touch you and they get burned, Sir. Or frozen. Your choice.',
      deadpool: 'HUG ME! I DARE YOU! Actually don\'t, this is gonna hurt YOU more than me!',
    },
  },
  {
    id: 'stoneskin',
    name: 'Stoneskin',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamond dust worth 100 gp, which the spell consumes' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'This spell turns the flesh of a willing creature you touch as hard as stone. The target has resistance to nonmagical bludgeoning, piercing, and slashing damage.',
    iconName: 'Shield',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Dermal hardening complete. Physical damage resistance: 50%.',
      jarvis: 'Your skin is now quite literally rock solid, Sir.',
      deadpool: 'I\'m ROCK HARD! Wait, that came out wrong. I mean my SKIN! My skin is hard! Like The Thing! But prettier!',
    },
  },
  {
    id: 'banishment',
    name: 'Banishment',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'an item distasteful to the target' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You attempt to send one creature to another plane of existence. If native to another plane, they\'re banished permanently. Otherwise, they return when the spell ends.',
    saveStat: 'CHA',
    iconName: 'LogOut',
    higherLevels: 'Target one additional creature for each slot level above 4th.',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Dimensional ejection initiated. Target: relocated to home plane.',
      jarvis: 'They\'ve been sent... elsewhere, Sir. Quite far elsewhere.',
      deadpool: 'GO AWAY! Like, to another DIMENSION! It\'s the ultimate "get out of my face!"',
    },
  },

  // ============================================
  // CONJURATION SPELLS  
  // ============================================
  {
    id: 'dimension-door',
    name: 'Dimension Door',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '500 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You teleport yourself to any spot within range. You can also bring one willing creature of your size or smaller within 5 feet of you.',
    iconName: 'Footprints',
    pathRestrictions: ['arcane_trickster', 'shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Long-range teleportation successful. Distance: up to 500 feet.',
      jarvis: 'A rather impressive jaunt, Sir. 500 feet in the blink of an eye.',
      deadpool: 'DIMENSION DOOR! It\'s like a regular door but way cooler and you don\'t need to clean the hinges!',
    },
  },
  {
    id: 'summon-greater-demon',
    name: 'Summon Greater Demon',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a vial of blood from a humanoid killed within the past 24 hours' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You utter foul words, summoning one demon of CR 5 or lower. The demon is hostile to all creatures but obeys your commands while you maintain a blood barrier.',
    iconName: 'Flame',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Abyssal entity summoned. Control protocol: blood ward active. Caution advised.',
      jarvis: 'A demon, Sir. Might I remind you that these creatures are... unpredictable.',
      deadpool: 'I summoned a DEMON! This is either the best idea I\'ve ever had or my last! Probably both!',
    },
  },
  {
    id: 'shadow-of-moil',
    name: 'Shadow of Moil',
    level: 4,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'an undead eyeball encased in a gem worth at least 150 gp' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Flame-like shadows wreathe your body, granting heavily obscured status, dim light immunity, and 2d8 necrotic retaliation against melee attackers.',
    damageType: 'necrotic',
    damageFormula: '2d8',
    iconName: 'Moon',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Necrotic shroud activated. Visibility: null. Retaliation: 2d8 necrotic.',
      jarvis: 'Wreathed in shadows, Sir. They can\'t see you, and hitting you costs them dearly.',
      deadpool: 'I\'m wrapped in DEATH FLAMES! It\'s like being emo but with actual consequences!',
    },
  },

  // ============================================
  // EVOCATION SPELLS
  // ============================================
  {
    id: 'ice-storm',
    name: 'Ice Storm',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of dust and a few drops of water' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. 2d8 bludgeoning + 4d6 cold damage. Area becomes difficult terrain.',
    saveStat: 'DEX',
    damageType: 'cold',
    damageFormula: '2d8+4d6',
    iconName: 'Cloud',
    higherLevels: 'Bludgeoning damage increases by 1d8 for each slot level above 4th.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Cryogenic bombardment initiated. Impact zone: difficult terrain.',
      jarvis: 'A localized blizzard, Sir. Rather unpleasant for anyone caught in it.',
      deadpool: 'ICE ICE BABY! Too cold! Too cold! Wait, am I allowed to reference that song?',
    },
  },
  {
    id: 'wall-of-fire',
    name: 'Wall of Fire',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a small piece of phosphorus' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You create a wall of fire on a solid surface. The wall can be up to 60 feet long, 20 feet high, and 1 foot thick. 5d8 fire damage when passing through or starting turn near it.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '5d8',
    iconName: 'Flame',
    higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Thermal barrier erected. Dimensions: 60×20 feet. Contact damage: 5d8.',
      jarvis: 'A wall of flames, Sir. I recommend not touching it.',
      deadpool: 'THE FLOOR IS LAVA! But vertical! And I control it! Best. Day. Ever!',
    },
  },

  // ============================================
  // ENCHANTMENT SPELLS
  // ============================================
  {
    id: 'charm-monster',
    name: 'Charm Monster',
    level: 4,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You attempt to charm a creature you can see. It must make a WIS save or be charmed. It regards you as a friendly acquaintance.',
    saveStat: 'WIS',
    iconName: 'Heart',
    higherLevels: 'Target one additional creature for each slot level above 4th.',
    pathRestrictions: ['arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Social override protocol engaged. Target perception: friendly.',
      jarvis: 'They quite like you now, Sir. For the next hour, at least.',
      deadpool: 'Be my friend! My BEST friend! We\'re gonna have sleepovers and braid each other\'s hair!',
    },
  },
  {
    id: 'confusion',
    name: 'Confusion',
    level: 4,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'three nut shells' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Each creature in a 10-foot-radius sphere must succeed on a WIS save or be unable to control their actions, rolling each turn to determine behavior.',
    saveStat: 'WIS',
    iconName: 'HelpCircle',
    higherLevels: 'Radius increases by 5 feet for each slot level above 4th.',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Cognitive disruption field active. Behavior: randomized.',
      jarvis: 'They haven\'t the faintest idea what they\'re doing anymore, Sir.',
      deadpool: 'CONFUSED! Like me at a salad bar! What even IS arugula?!',
    },
  },

  // ============================================
  // NECROMANCY SPELLS
  // ============================================
  {
    id: 'blight',
    name: 'Blight',
    level: 4,
    school: 'necromancy',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Necromantic energy washes over a creature, draining moisture and vitality. 8d8 necrotic damage (half on CON save). Plant creatures have disadvantage.',
    saveStat: 'CON',
    damageType: 'necrotic',
    damageFormula: '8d8',
    iconName: 'Skull',
    higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Life force extraction: 8d8 necrotic. Plants: additional vulnerability detected.',
      jarvis: 'You\'ve drained the very life from them, Sir. Most... efficient.',
      deadpool: 'WITHER AND DIE! It\'s like fast-forwarding through their whole life! But just the end part!',
    },
  },
  {
    id: 'death-ward',
    name: 'Death Ward',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'You touch a creature and grant protection against death. The first time the target would drop to 0 HP, they instead drop to 1 HP. Spell then ends.',
    iconName: 'ShieldPlus',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Fatal damage buffer installed. One-time resurrection protocol: active.',
      jarvis: 'A failsafe against death, Sir. You get one free pass.',
      deadpool: 'CAN\'T KILL ME! Well, you CAN, but the first one\'s free! Like samples at Costco!',
    },
  },
];

export function getFourthLevelSpellsByPath(path: string): SpellDefinition[] {
  return FOURTH_LEVEL_SPELLS.filter(
    spell => !spell.pathRestrictions || spell.pathRestrictions.includes(path as any)
  );
}
