import { SpellDefinition } from '../types';

export const FIFTH_LEVEL_SPELLS: SpellDefinition[] = [
  // ============================================
  // ILLUSION SPELLS
  // ============================================
  {
    id: 'mislead',
    name: 'Mislead',
    level: 5,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: false, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You become invisible and create an illusory double. You can see and hear through the duplicate, speak through it, and swap senses between your body and the illusion.',
    iconName: 'Users',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Decoy deployed. Invisibility active. Dual sensory input: online.',
      jarvis: 'An invisible you and a visible decoy, Sir. The ultimate misdirection.',
      deadpool: 'There\'s two of me! One you can see and one you CAN\'T! Guess which one has the swords!',
    },
  },
  {
    id: 'seeming',
    name: 'Seeming',
    level: 5,
    school: 'illusion',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'You disguise any number of creatures within range. Each target can appear up to 1 foot shorter or taller, thin, fat, or in between. Unwilling targets can make a CHA save.',
    saveStat: 'CHA',
    iconName: 'Users',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Mass disguise protocol active. Targets: all within range. Duration: 8 hours.',
      jarvis: 'Everyone looks like someone else now, Sir. Quite the costume party.',
      deadpool: 'MAKEOVER TIME! Everyone gets a new face! It\'s like witness protection but FUN!',
    },
  },
  {
    id: 'creation',
    name: 'Creation',
    level: 5,
    school: 'illusion',
    castingTime: '1_minute',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a tiny piece of matter of the same type' },
    duration: 'Special',
    concentration: false,
    ritual: false,
    description: 'You pull wisps of shadow material to create a nonliving object of vegetable matter, stone, crystal, or metal. Duration varies by material.',
    iconName: 'Box',
    pathRestrictions: ['arcane_trickster', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Matter synthesis complete. Object: temporary. Composition: shadow-derived.',
      jarvis: 'Created from nothing but shadow and will, Sir. Quite remarkable.',
      deadpool: 'I made a THING! From NOTHING! I\'m basically a 3D printer but magical!',
    },
  },

  // ============================================
  // ABJURATION SPELLS
  // ============================================
  {
    id: 'wall-of-force',
    name: 'Wall of Force',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of powder made by crushing a clear gemstone' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'An invisible wall of force springs into existence. The wall is immune to all damage and can\'t be dispelled by Dispel Magic. Nothing can pass through it.',
    iconName: 'Shield',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Impenetrable force barrier deployed. Damage immunity: absolute.',
      jarvis: 'An invisible, indestructible wall, Sir. Nothing gets through.',
      deadpool: 'INVISIBLE WALL! Like a mime\'s dream come true! Except REAL! And UNBREAKABLE!',
    },
  },
  {
    id: 'steel-wind-strike',
    name: 'Steel Wind Strike',
    level: 5,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a melee weapon worth at least 1 sp' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You flourish your weapon and vanish to strike like the wind. Make melee spell attacks against up to five creatures within range. 6d10 force damage on hit. Teleport to space within 5 feet of one target.',
    attackType: 'melee',
    damageType: 'force',
    damageFormula: '6d10',
    iconName: 'Sword',
    pathRestrictions: ['eldritch_knight', 'shadow_blade'],
    personalityQuips: {
      thunderhead: 'Multi-target teleportation assault initiated. Strikes: 5. Damage: 6d10 force each.',
      jarvis: 'Five strikes in the blink of an eye, Sir. Then you\'re somewhere else entirely.',
      deadpool: 'I\'m EVERYWHERE at once! Stab stab stab stab stab! Then POOF! Anime protagonist ENERGY!',
    },
  },
  {
    id: 'circle-of-power',
    name: 'Circle of Power',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self (30-foot radius)',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Divine energy radiates from you. Friendly creatures in a 30-foot radius have advantage on saves vs. spells and magical effects. On a successful save, they take no damage instead of half.',
    iconName: 'Circle',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Protective aura projected. Radius: 30 feet. Save enhancement: active.',
      jarvis: 'A sphere of protection, Sir. Your allies are significantly harder to affect magically.',
      deadpool: 'PROTECTION BUBBLE! Everyone inside gets magic resistance! It\'s like SPF but for spells!',
    },
  },

  // ============================================
  // CONJURATION SPELLS
  // ============================================
  {
    id: 'far-step',
    name: 'Far Step',
    level: 5,
    school: 'conjuration',
    castingTime: 'bonus_action',
    range: 'Self',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You teleport up to 60 feet to an unoccupied space you can see. Until the spell ends, you can use a bonus action on each of your turns to teleport this way again.',
    iconName: 'Footprints',
    pathRestrictions: ['arcane_trickster', 'shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Continuous teleportation protocol engaged. 60 feet per bonus action.',
      jarvis: 'Repeated short-range teleportation, Sir. Quite impossible to pin down.',
      deadpool: 'BLINK BLINK BLINK! I\'m like a cursor that won\'t sit still! ADHD TELEPORTATION!',
    },
  },
  {
    id: 'teleportation-circle',
    name: 'Teleportation Circle',
    level: 5,
    school: 'conjuration',
    castingTime: '1_minute',
    range: '10 feet',
    components: { verbal: true, somatic: false, material: 'rare chalks and inks infused with precious gems worth 50 gp, which the spell consumes' },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You draw a 10-foot-diameter circle on the ground that links to a permanent teleportation circle whose sigil sequence you know.',
    iconName: 'Circle',
    pathRestrictions: ['arcane_trickster', 'eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Teleportation matrix established. Destination: linked circle. Travel: instantaneous.',
      jarvis: 'A portal to another location, Sir. Do make sure you have the correct sigil sequence.',
      deadpool: 'MAGIC SUBWAY! No tickets, no waiting, no weird smells! Well, maybe some weird smells.',
    },
  },
  {
    id: 'infernal-calling',
    name: 'Infernal Calling',
    level: 5,
    school: 'conjuration',
    castingTime: '1_minute',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a ruby worth at least 999 gp' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You summon a devil of CR 6 or lower. It is hostile unless you have something it wants, know its true name, or have a valuable offering.',
    iconName: 'Flame',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Infernal entity summoned. Control status: negotiable. Risk level: extreme.',
      jarvis: 'A devil, Sir. These creatures are... contract-oriented. Be precise in your dealings.',
      deadpool: 'DEVIL BUDDY! We\'re gonna make DEALS! Hopefully not for my soul! Again!',
    },
  },

  // ============================================
  // EVOCATION SPELLS
  // ============================================
  {
    id: 'cone-of-cold',
    name: 'Cone of Cold',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (60-foot cone)',
    components: { verbal: true, somatic: true, material: 'a small crystal or glass cone' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a CON save. 8d8 cold damage on a failed save, half on success.',
    saveStat: 'CON',
    damageType: 'cold',
    damageFormula: '8d8',
    iconName: 'Wind',
    higherLevels: 'Damage increases by 1d8 for each slot level above 5th.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Cryogenic blast discharged. Cone: 60 feet. Damage: 8d8 cold.',
      jarvis: 'A frigid blast, Sir. Everything in that cone is now considerably colder.',
      deadpool: 'ICE BREATH! Like a dragon but in reverse! And way cooler! Pun INTENDED!',
    },
  },
  {
    id: 'synaptic-static',
    name: 'Synaptic Static',
    level: 5,
    school: 'enchantment',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You unleash a mind-breaking psychic scream. Creatures in a 20-foot radius take 8d6 psychic damage and subtract 1d6 from attack rolls, ability checks, and concentration saves for 1 minute.',
    saveStat: 'INT',
    damageType: 'psychic',
    damageFormula: '8d6',
    iconName: 'Brain',
    pathRestrictions: ['arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Psychic disruption deployed. Cognitive impairment: 1d6 penalty. Duration: 1 minute.',
      jarvis: 'Their minds are... scrambled, Sir. Thinking clearly won\'t be easy for them.',
      deadpool: 'BRAIN FREEZE! But not the ice cream kind! The screaming-inside-your-head kind!',
    },
  },
  {
    id: 'bigbys-hand',
    name: 'Bigby\'s Hand',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'an eggshell and a snakeskin glove' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You create a Large hand of shimmering, translucent force. It can punch (4d8 force), shove, grapple, or interpose to grant half cover.',
    attackType: 'melee',
    damageType: 'force',
    damageFormula: '4d8',
    iconName: 'Hand',
    higherLevels: 'Damage increases by 2d8 for each slot level above 5th.',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Force construct manifested. Configuration: hand. Multi-function: punch, grapple, interpose.',
      jarvis: 'A giant magical hand at your command, Sir. Quite versatile.',
      deadpool: 'GIANT HAND! For high-fives! Or crushing! Or really aggressive waving! THE POSSIBILITIES!',
    },
  },

  // ============================================
  // ENCHANTMENT SPELLS
  // ============================================
  {
    id: 'hold-monster',
    name: 'Hold Monster',
    level: 5,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a creature you can see. The target must succeed on a WIS save or be paralyzed. Works on any creature type, not just humanoids.',
    saveStat: 'WIS',
    iconName: 'Lock',
    higherLevels: 'Target one additional creature for each slot level above 5th.',
    pathRestrictions: ['arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Universal paralysis field applied. Target type: unrestricted.',
      jarvis: 'Frozen in place, Sir. And this works on anything, not just humanoids.',
      deadpool: 'FREEZE, MONSTER! Yeah, that\'s right! Dragons, demons, whatever! NOBODY MOVES!',
    },
  },
  {
    id: 'dominate-person',
    name: 'Dominate Person',
    level: 5,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You attempt to beguile a humanoid. While charmed, you have a telepathic link and can command their actions. They get a new save when damaged.',
    saveStat: 'WIS',
    iconName: 'Crown',
    higherLevels: 'At 6th: 10 min. At 7th: 1 hour. At 8th: 8 hours.',
    pathRestrictions: ['arcane_trickster', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Mind control established. Telepathic command link: active.',
      jarvis: 'Complete mental control, Sir. Their will is now... yours.',
      deadpool: 'PUPPET MASTER TIME! Dance, little humanoid, dance! Actually, go get me a taco!',
    },
  },
  {
    id: 'modify-memory',
    name: 'Modify Memory',
    level: 5,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You attempt to reshape another creature\'s memories. You can eliminate, modify, or create memories of an event within the last 24 hours.',
    saveStat: 'WIS',
    iconName: 'Brain',
    higherLevels: 'Affect memories from further back: 7 days (6th), 30 days (7th), 1 year (8th), any time (9th).',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Memory modification protocol initiated. Timeline access: 24 hours.',
      jarvis: 'Rewriting their recollections, Sir. They\'ll remember it your way.',
      deadpool: 'MEMORY EDITOR! Delete delete delete! Replace with something FUN! Like puppies!',
    },
  },

  // ============================================
  // NECROMANCY SPELLS
  // ============================================
  {
    id: 'enervation',
    name: 'Enervation',
    level: 5,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'A tendril of darkness reaches from you to a creature within range. 4d8 necrotic damage on hit, and you regain HP equal to half the damage dealt. Action to repeat each turn.',
    attackType: 'ranged',
    damageType: 'necrotic',
    damageFormula: '4d8',
    iconName: 'Skull',
    higherLevels: 'Damage increases by 1d8 for each slot level above 5th.',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Life force siphon established. Continuous drain: 4d8 per action. Self-repair: 50%.',
      jarvis: 'A persistent drain on their vitality, Sir. And it heals you in the process.',
      deadpool: 'SOUL STRAW! Slurping up their life force! It\'s like a smoothie but DARK!',
    },
  },
  {
    id: 'negative-energy-flood',
    name: 'Negative Energy Flood',
    level: 5,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: 'a broken bone and a square of black silk' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You send ribbons of negative energy at one creature. 5d12 necrotic damage on failed CON save. If this kills the target, it rises as a zombie under your control.',
    saveStat: 'CON',
    damageType: 'necrotic',
    damageFormula: '5d12',
    iconName: 'Skull',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Negative energy discharge: 5d12 necrotic. Death trigger: zombie reanimation.',
      jarvis: 'Should this prove fatal, Sir, the corpse will rise to serve you. Most efficient.',
      deadpool: 'KILL THEM AND THEY JOIN THE TEAM! It\'s like the worst job offer ever! YOU\'RE HIRED... as a zombie!',
    },
  },
  {
    id: 'danse-macabre',
    name: 'Danse Macabre',
    level: 5,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: true,
    ritual: false,
    description: 'Up to five corpses of Medium or Small humanoids rise as zombies or skeletons under your control. They add your proficiency to attacks and damage.',
    iconName: 'Users',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Undead battalion raised. Units: 5. Damage bonus: proficiency modifier.',
      jarvis: 'Your own personal undead entourage, Sir. They\'re surprisingly effective.',
      deadpool: 'DANCE PARTY OF THE DEAD! Everybody\'s invited! Especially the corpses! ESPECIALLY them!',
    },
  },

  // ============================================
  // TRANSMUTATION SPELLS
  // ============================================
  {
    id: 'telekinesis',
    name: 'Telekinesis',
    level: 5,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You gain the ability to move or manipulate creatures or objects with your mind. Move objects up to 1000 lbs, or restrain/move creatures that fail a STR contest.',
    iconName: 'Move',
    pathRestrictions: ['arcane_trickster', 'eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Psychokinetic field active. Weight limit: 1000 lbs. Control: mental.',
      jarvis: 'Mind over matter, Sir. Quite literally.',
      deadpool: 'JEDI POWERS! I can move stuff with my BRAIN! Which is ironic because I barely USE my brain!',
    },
  },
  {
    id: 'skill-empowerment',
    name: 'Skill Empowerment',
    level: 5,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Your magic deepens a creature\'s understanding of its skills. Target doubles proficiency bonus for one skill of your choice for the duration.',
    iconName: 'Sparkles',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Skill amplification complete. Proficiency multiplier: 2x.',
      jarvis: 'Expertise granted, Sir. They\'re now remarkably good at that particular skill.',
      deadpool: 'SUPER GOOD AT STUFF! Pick a skill! Any skill! You\'re now TWICE as awesome at it!',
    },
  },
];

export function getFifthLevelSpellsByPath(path: string): SpellDefinition[] {
  return FIFTH_LEVEL_SPELLS.filter(
    spell => !spell.pathRestrictions || spell.pathRestrictions.includes(path as any)
  );
}
