// Bard Spell List
// D&D 5e Charisma-based known spellcaster
// Focuses on support, charm, healing, and versatile utility

import { SpellDefinition } from '../types';

// ============================================
// CANTRIPS (Level 0)
// ============================================

export const BARD_CANTRIPS: SpellDefinition[] = [
  {
    id: 'bard-vicious-mockery',
    name: 'Vicious Mockery',
    level: 0,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you, it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.',
    higherLevels: 'This spell\'s damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), and 17th level (4d4).',
    attackType: 'save',
    saveStat: 'WIS',
    damageType: 'psychic',
    damageFormula: '1d4',
    iconName: 'MessageSquare',
    classes: ['bard'],
    personalityQuips: {
      thunderhead: 'Words carry power. Let yours cut deeper than any blade.',
      jarvis: 'Deploying psychic verbal assault. Target morale systems compromised.',
      deadpool: 'Yo momma jokes that LITERALLY hurt! Best. Cantrip. Ever.',
    },
  },
  {
    id: 'bard-friends',
    name: 'Friends',
    level: 0,
    school: 'enchantment',
    castingTime: 'action',
    range: 'Self',
    components: { somatic: true, material: 'a small amount of makeup applied to the face', verbal: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn\'t hostile toward you. When the spell ends, the creature realizes that you used magic to influence its mood and becomes hostile toward you.',
    iconName: 'SmilePlus',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'A dangerous game—charm fades, but resentment lingers.',
      jarvis: 'Social engineering protocol active. Warning: temporary effect only.',
      deadpool: 'Magic makeup that makes people like me? Finally, my Sephora addiction pays off!',
    },
  },
  {
    id: 'bard-minor-illusion',
    name: 'Minor Illusion',
    level: 0,
    school: 'illusion',
    castingTime: 'action',
    range: '30 feet',
    components: { somatic: true, material: 'a bit of fleece', verbal: false },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it or cast this spell again. If you create a sound, it can be any volume and any sound. If you create an image, it must fit within a 5-foot cube and can\'t create light, sound, smell, or any other sensory effect.',
    iconName: 'Image',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Reality is perception. Shape it to your will.',
      jarvis: 'Holographic projection active. Resolution: adequate.',
      deadpool: 'Budget special effects! It\'s like being my own movie studio!',
    },
  },
  {
    id: 'bard-prestidigitation',
    name: 'Prestidigitation',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '10 feet',
    components: { verbal: true, somatic: true },
    duration: 'Up to 1 hour',
    concentration: false,
    ritual: false,
    description: 'A minor magical trick. Create a sensory effect, light or snuff a small flame, clean or soil an object, chill/warm/flavor material, make a symbol appear, or create a trinket or illusory image that fits in your hand.',
    iconName: 'Wand2',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Small magic, but never underestimate cleverness.',
      jarvis: 'Micro-reality alteration active. Applications: limitless.',
      deadpool: 'Party tricks! I can make your drink taste like tacos! ...You\'re welcome.',
    },
  },
  {
    id: 'bard-true-strike',
    name: 'True Strike',
    level: 0,
    school: 'divination',
    castingTime: 'action',
    range: '30 feet',
    components: { somatic: true, verbal: false },
    duration: 'Concentration, up to 1 round',
    concentration: true,
    ritual: false,
    description: 'You point a finger at a target in range. Your magic grants you a brief insight into the target\'s defenses. On your next turn, you gain advantage on your first attack roll against the target, provided this spell hasn\'t ended.',
    iconName: 'Target',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'See the weakness. Strike true.',
      jarvis: 'Tactical analysis complete. Vulnerability identified.',
      deadpool: 'Using a whole action to aim? Bold strategy, Cotton.',
    },
  },
];

// ============================================
// 1ST LEVEL SPELLS
// ============================================

export const BARD_1ST_LEVEL: SpellDefinition[] = [
  {
    id: 'bard-dissonant-whispers',
    name: 'Dissonant Whispers',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You whisper a discordant melody that only one creature of your choice within range can hear, wracking it with terrible pain. The target must make a Wisdom saving throw. On a failed save, it takes 3d6 psychic damage and must immediately use its reaction to move as far as its speed allows away from you. On a successful save, the target takes half damage and doesn\'t have to move away. A deafened creature automatically succeeds.',
    higherLevels: 'Damage increases by 1d6 for each slot level above 1st.',
    attackType: 'save',
    saveStat: 'WIS',
    damageType: 'psychic',
    damageFormula: '3d6',
    iconName: 'Volume2',
    classes: ['bard'],
    personalityQuips: {
      thunderhead: 'Let the discord shatter their resolve. Fear is a melody all its own.',
      jarvis: 'Sonic disruption pattern deployed. Target neural pathways destabilized.',
      deadpool: 'ASMR gone WRONG. Subscribe and hit that bell for more trauma!',
    },
  },
  {
    id: 'bard-faerie-fire',
    name: 'Faerie Fire',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Each object in a 20-foot cube within range is outlined in blue, green, or violet light. Any creature in the area when the spell is cast must succeed on a Dexterity saving throw or also be outlined. An affected creature or object sheds dim light in a 10-foot radius. Attack rolls against an affected creature or object have advantage if the attacker can see it, and the affected creature or object can\'t benefit from being invisible.',
    attackType: 'save',
    saveStat: 'DEX',
    iconName: 'Sparkles',
    classes: ['bard', 'druid'],
    personalityQuips: {
      thunderhead: 'Nowhere to hide when the light reveals all.',
      jarvis: 'Bioluminescent targeting overlay active. Stealth countermeasures engaged.',
      deadpool: 'Glow stick rave! Everyone gets outlined! Invisible people HATE this one trick!',
    },
  },
  {
    id: 'bard-heroism',
    name: 'Heroism',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'A willing creature you touch is imbued with bravery. Until the spell ends, the creature is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier at the start of each of its turns. When the spell ends, the target loses any remaining temporary hit points from this spell.',
    healingFormula: 'mod',
    iconName: 'Shield',
    classes: ['bard'],
    personalityQuips: {
      thunderhead: 'Rise. Fear is beneath you. You are the storm.',
      jarvis: 'Courage subroutine injected. Temporary fortification: active.',
      deadpool: 'Liquid courage without the hangover! ...Okay, I\'m jealous.',
    },
  },
  {
    id: 'bard-hideous-laughter',
    name: 'Hideous Laughter',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'tiny tarts and a feather' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it. The target must succeed on a Wisdom saving throw or fall prone, becoming incapacitated and unable to stand up for the duration. A creature with Intelligence 4 or less isn\'t affected. At the end of each of its turns, and each time it takes damage, the target can make another Wisdom saving throw.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Laugh',
    classes: ['bard', 'wizard'],
    personalityQuips: {
      thunderhead: 'Even in battle, laughter can be the cruelest weapon.',
      jarvis: 'Initiating involuntary humor response. Target motor control: compromised.',
      deadpool: 'I tell jokes that are LITERALLY disabling! My stand-up special writes itself!',
    },
  },
  {
    id: 'bard-sleep',
    name: 'Sleep',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of fine sand, rose petals, or a cricket' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points. Subtract each creature\'s hit points from the total before moving on. Undead and creatures immune to being charmed aren\'t affected.',
    damageFormula: '5d8',
    higherLevels: 'Roll an additional 2d8 for each slot level above 1st.',
    iconName: 'Moon',
    classes: ['bard', 'sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'A lullaby of power. They sleep... whether they wish to or not.',
      jarvis: 'Deploying mass sedation field. Hit point threshold: calculating.',
      deadpool: 'Nap time is NON-NEGOTIABLE. Night night!',
    },
  },
  {
    id: 'bard-thunderwave',
    name: 'Thunderwave',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (15-foot cube)',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half damage and isn\'t pushed.',
    higherLevels: 'Damage increases by 1d8 for each slot level above 1st.',
    attackType: 'save',
    saveStat: 'CON',
    damageType: 'thunder',
    damageFormula: '2d8',
    iconName: 'Zap',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'The thunder answers. Stand clear.',
      jarvis: 'Concussive shockwave deployed. Displacement force: significant.',
      deadpool: 'BASS DROP! *wub wub wub* Everyone gets yeeted!',
    },
  },
  {
    id: 'bard-charm-person',
    name: 'Charm Person',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Heart',
    classes: ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Why fight when you can simply... persuade?',
      jarvis: 'Social override protocol deployed. Target perception altered.',
      deadpool: 'Mind control lite! Now with 50% less evil! ...Okay, 30%.',
    },
  },
  {
    id: 'bard-detect-magic',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Sense the presence of magic within 30 feet. You can see a faint aura around any visible creature or object that bears magic and learn its school.',
    iconName: 'Search',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'The weave reveals its secrets to those who listen.',
      jarvis: 'Arcane frequency scanner activated. Sweep radius: 30 feet.',
      deadpool: 'Magic-Vision goggles ON! Everything is glowy!',
    },
  },
  {
    id: 'bard-healing-word',
    name: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'Healing increases by 1d4 for each slot level above 1st.',
    healingFormula: '1d4+mod',
    iconName: 'MessageCircle',
    classes: ['bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'A word of power to mend what is broken.',
      jarvis: 'Vocal-frequency healing wave transmitted. Recovery initiated.',
      deadpool: 'ABRACADA-HEAL! ...Patent pending.',
    },
  },
  {
    id: 'bard-cure-wounds',
    name: 'Cure Wounds',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 1st.',
    healingFormula: '1d8+mod',
    iconName: 'Heart',
    classes: ['bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'The wounds close. Your melody of life is not yet done.',
      jarvis: 'Cellular regeneration initiated via tactile transfer.',
      deadpool: 'Healing hands! Like a spa day but with more screaming!',
    },
  },
];

// ============================================
// 2ND LEVEL SPELLS
// ============================================

export const BARD_2ND_LEVEL: SpellDefinition[] = [
  {
    id: 'bard-heat-metal',
    name: 'Heat Metal',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a piece of iron and a flame' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a manufactured metal object that you can see within range. You cause the object to glow red-hot. Any creature in physical contact with the object takes 2d8 fire damage. Until the spell ends, you can use a bonus action to cause this damage again. If a creature is holding or wearing the object and takes the damage, it must succeed on a Constitution saving throw or drop the object. If it doesn\'t drop it, it has disadvantage on attack rolls and ability checks until the start of your next turn.',
    higherLevels: 'Damage increases by 1d8 for each slot level above 2nd.',
    damageType: 'fire',
    damageFormula: '2d8',
    saveStat: 'CON',
    iconName: 'Flame',
    classes: ['bard', 'druid'],
    personalityQuips: {
      thunderhead: 'Their armor becomes their prison. The metal remembers fire.',
      jarvis: 'Thermal induction active. Target equipment temperature: critical.',
      deadpool: 'HOT HOT HOT! Drop it like it\'s—well, like it\'s literally on fire!',
    },
  },
  {
    id: 'bard-suggestion',
    name: 'Suggestion',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, material: 'a snake\'s tongue and either a bit of honeycomb or a drop of sweet oil', somatic: false },
    duration: 'Concentration, up to 8 hours',
    concentration: true,
    ritual: false,
    description: 'You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. The suggestion must be worded in such a manner as to make the course of action sound reasonable. The creature must succeed on a Wisdom saving throw or follow the suggested course of action for the duration.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'MessageSquare',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'A carefully chosen word is more powerful than a hundred swords.',
      jarvis: 'Subliminal directive implanted. Compliance probability: high.',
      deadpool: '"Hey, you should totally just... walk away." MIND CONTROL LITE!',
    },
  },
  {
    id: 'bard-invisibility',
    name: 'Invisibility',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'an eyelash encased in gum arabic' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. The spell ends for a target that attacks or casts a spell.',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    iconName: 'EyeOff',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Vanish from sight. Let them fear the unseen.',
      jarvis: 'Optical camouflage engaged. Visual spectrum: bypassed.',
      deadpool: 'Now you see me, now you—wait, you can\'t see me? PANTS OFF!',
    },
  },
  {
    id: 'bard-hold-person',
    name: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
    higherLevels: 'You can target one additional humanoid for each slot level above 2nd.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Lock',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Freeze. Your body answers to a higher power now.',
      jarvis: 'Motor function override engaged. Target immobilized.',
      deadpool: 'FREEZE! And not in the cool Mr. Freeze way!',
    },
  },
  {
    id: 'bard-lesser-restoration',
    name: 'Lesser Restoration',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a creature and end one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.',
    iconName: 'Eraser',
    classes: ['bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'The affliction fades. Your song restores what was broken.',
      jarvis: 'Condition remediation complete. Status effects purged.',
      deadpool: 'Doctor Bardpool prescribes: one magical cure-all! Side effects may include gratitude.',
    },
  },
  {
    id: 'bard-silence',
    name: 'Silence',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Create a 20-foot-radius sphere of silence centered on a point. No sound can be created within or pass through. Creatures in the area are deafened and immune to thunder damage. Verbal spell components cannot be used within the sphere.',
    iconName: 'VolumeX',
    classes: ['bard', 'cleric'],
    personalityQuips: {
      thunderhead: 'Ironic—the bard who commands silence. Let them choke on their own spells.',
      jarvis: 'Acoustic null zone established. Audio frequencies: terminated.',
      deadpool: 'A bard casting Silence is the ultimate power move. "I choose WHEN there\'s music!"',
    },
  },
  {
    id: 'bard-enhance-ability',
    name: 'Enhance Ability',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'fur or a feather from a beast' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects: Bear\'s Endurance (advantage on CON checks, 2d6 temp HP), Bull\'s Strength (advantage on STR checks, carrying capacity doubles), Cat\'s Grace (advantage on DEX checks, no fall damage up to 20 ft), Eagle\'s Splendor (advantage on CHA checks), Fox\'s Cunning (advantage on INT checks), Owl\'s Wisdom (advantage on WIS checks).',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    iconName: 'TrendingUp',
    classes: ['bard', 'cleric', 'druid', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'I amplify what is already within you. Now show them.',
      jarvis: 'Performance enhancement protocol applied. Specified attribute: boosted.',
      deadpool: 'Animal steroids! Totally legal in this universe!',
    },
  },
];

// ============================================
// 3RD LEVEL SPELLS
// ============================================

export const BARD_3RD_LEVEL: SpellDefinition[] = [
  {
    id: 'bard-hypnotic-pattern',
    name: 'Hypnotic Pattern',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { somatic: true, material: 'a glowing stick of incense or a crystal vial filled with phosphorescent material', verbal: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. The pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration. While charmed, the creature is incapacitated and has a speed of 0. The spell ends for an affected creature if it takes any damage or if someone else uses an action to shake the creature out of its stupor.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Shapes',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'The pattern captures the mind. They are yours now.',
      jarvis: 'Mesmeric holographic array deployed. Mass cognitive disruption active.',
      deadpool: 'Disco lights that make people FREEZE! Best rave ever!',
    },
  },
  {
    id: 'bard-dispel-magic',
    name: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability (DC 10 + the spell\'s level). On a successful check, the spell ends.',
    higherLevels: 'You automatically end the effects of a spell on the target if the spell\'s level is equal to or less than the level of the spell slot you used.',
    iconName: 'XCircle',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Your magic unravels before mine. The weave answers to the stronger will.',
      jarvis: 'Counter-arcane protocol engaged. Target enchantments: neutralized.',
      deadpool: 'CTRL+Z for magic! Undo! UNDO!',
    },
  },
  {
    id: 'bard-bestow-curse',
    name: 'Bestow Curse',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Touch a creature and it must succeed on a Wisdom save or be cursed. Choose one: disadvantage on one ability score\'s checks and saves; disadvantage on attacks against you; WIS save each turn or lose action; or your attacks deal an extra 1d8 necrotic damage to the target.',
    higherLevels: 'At 4th level, concentration up to 10 minutes. At 5th level, 8 hours. At 7th level, no concentration, until dispelled. At 9th level, permanent.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Skull',
    classes: ['bard', 'cleric', 'wizard'],
    personalityQuips: {
      thunderhead: 'A dark melody clings to them now. The curse is set.',
      jarvis: 'Hex payload delivered. Target operational efficiency: degraded.',
      deadpool: 'I curse you with... *checks notes* ...disadvantage! THE HORROR!',
    },
  },
  {
    id: 'bard-fear',
    name: 'Fear',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self (30-foot cone)',
    components: { verbal: true, somatic: true, material: 'a white feather or the heart of a hen' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You project a phantasmal image of a creature\'s worst fears. Each creature in a 30-foot cone must succeed on a Wisdom saving throw or drop whatever it is holding and become frightened for the duration. While frightened, a creature must take the Dash action and move away from you by the safest route on each of its turns.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Ghost',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Face your nightmares. They are very, very real now.',
      jarvis: 'Phobia projection active. Mass psychological warfare engaged.',
      deadpool: 'BOO! ...But like, magically traumatizing BOO!',
    },
  },
  {
    id: 'bard-tongues',
    name: 'Tongues',
    level: 3,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, material: 'a small clay model of a ziggurat', somatic: false },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'This spell grants the creature you touch the ability to understand any spoken language it hears. Moreover, when the target speaks, any creature that knows at least one language and can hear the target understands what it says.',
    iconName: 'Languages',
    classes: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'All tongues are one when the magic flows. Speak, and be understood.',
      jarvis: 'Universal translator activated. Language barrier: eliminated.',
      deadpool: 'Babel fish spell! Now I can understand everyone\'s insults! ...Wait.',
    },
  },
  {
    id: 'bard-major-image',
    name: 'Major Image',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You create the image of an object, creature, or other visible phenomenon no larger than a 20-foot cube. The image appears at a spot you can see and lasts for the duration. It seems completely real, including sounds, smells, and temperature. You can use your action to cause the image to move and change appearance in a natural way.',
    higherLevels: 'If cast at 6th level or higher, the spell lasts until dispelled without requiring concentration.',
    iconName: 'Image',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Reality is what I say it is. Behold my masterwork.',
      jarvis: 'Full sensory hologram deployed. Resolution: photorealistic.',
      deadpool: 'Hollywood special effects! Eat your heart out, ILM!',
    },
  },
];

// ============================================
// 4TH LEVEL SPELLS
// ============================================

export const BARD_4TH_LEVEL: SpellDefinition[] = [
  {
    id: 'bard-dimension-door',
    name: 'Dimension Door',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '500 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. You can bring along objects as long as their weight doesn\'t exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity.',
    iconName: 'DoorOpen',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Distance is meaningless. Step through reality itself.',
      jarvis: 'Spatial displacement portal opened. Destination locked.',
      deadpool: 'BAMF! Just like Nightcrawler but with MORE STYLE!',
    },
  },
  {
    id: 'bard-greater-invisibility',
    name: 'Greater Invisibility',
    level: 4,
    school: 'illusion',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. Unlike regular Invisibility, this spell does NOT end when the target attacks or casts a spell.',
    iconName: 'EyeOff',
    classes: ['bard', 'sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'True invisibility. Strike unseen, vanish without trace.',
      jarvis: 'Advanced optical camouflage: persistent mode. Combat-compatible stealth engaged.',
      deadpool: 'Invisible AND I can still stab people? Christmas came early!',
    },
  },
  {
    id: 'bard-polymorph',
    name: 'Polymorph',
    level: 4,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a caterpillar cocoon' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Transform a creature into a new beast form. An unwilling creature must make a Wisdom saving throw. The target\'s game statistics are replaced by the beast\'s statistics, but it retains its alignment and personality. The target\'s HP changes to the beast\'s HP. When it reverts, it returns to its pre-transformation HP. If it reverts as a result of dropping to 0 HP, any excess damage carries over.',
    higherLevels: undefined,
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Cat',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'Form is fluid. Become what this moment demands.',
      jarvis: 'Biological restructuring in progress. New form: confirmed.',
      deadpool: 'GIANT APE TIME! Or a goldfish. Depends on my mood.',
    },
  },
  {
    id: 'bard-freedom-of-movement',
    name: 'Freedom of Movement',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a leather strap, bound around the arm or a similar appendage' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch a willing creature. For the duration, the target\'s movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target\'s speed nor cause the target to be paralyzed or restrained. The target can also spend 5 feet of movement to automatically escape from nonmagical restraints.',
    iconName: 'Wind',
    classes: ['bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'Nothing holds you. Move with the wind.',
      jarvis: 'Kinetic freedom protocol active. Movement restrictions: nullified.',
      deadpool: 'Can\'t restrain THIS! *strikes a pose*',
    },
  },
  {
    id: 'bard-compulsion',
    name: 'Compulsion',
    level: 4,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Creatures of your choice that you can see within range and that can hear you must make a Wisdom saving throw. On a failed save, a target is affected by this spell. Until the spell ends, you can use a bonus action on each of your turns to designate a direction. Each affected target must use as much of its movement as possible to move in that direction on its next turn. After moving in this way, it can make another Wisdom saving throw to try to end the effect.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Navigation',
    classes: ['bard'],
    personalityQuips: {
      thunderhead: 'Dance to my tune. Your feet betray you.',
      jarvis: 'Motor control override engaged. Directional compliance: forced.',
      deadpool: 'DANCE, PUPPETS! ...This is basically DDR but evil!',
    },
  },
];

// ============================================
// 5TH LEVEL SPELLS
// ============================================

export const BARD_5TH_LEVEL: SpellDefinition[] = [
  {
    id: 'bard-animate-objects',
    name: 'Animate Objects',
    level: 5,
    school: 'transmutation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Tiny objects have AC 18, 20 HP, and +8 to hit for 1d4+4 damage each. Medium targets count as two objects, Large as four, Huge as eight. You can command them as a bonus action.',
    higherLevels: 'You can animate two additional objects for each slot level above 5th.',
    iconName: 'Boxes',
    classes: ['bard', 'sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'Even the mundane answers the call. Rise and serve.',
      jarvis: 'Object animation subroutines deployed. Autonomous combat units: online.',
      deadpool: 'EVERYTHING IS ALIVE! The chairs! The forks! IT\'S TOY STORY BUT VIOLENT!',
    },
  },
  {
    id: 'bard-greater-restoration',
    name: 'Greater Restoration',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamond dust worth at least 100 gp, which the spell consumes', materialConsumed: true, materialCost: 100 },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target\'s exhaustion level by one, or end one of the following effects on the target: one effect that charmed or petrified the target, one curse (including the target\'s attunement to a cursed magic item), any reduction to one of the target\'s ability scores, or one effect reducing the target\'s hit point maximum.',
    iconName: 'RefreshCw',
    classes: ['bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'The deepest wounds require the deepest magic. Be whole again.',
      jarvis: 'Advanced restoration protocol engaged. Critical condition: resolved.',
      deadpool: 'The EXPENSIVE healing! Diamond dust?! Do I look like I\'m made of money?!',
    },
  },
  {
    id: 'bard-hold-monster',
    name: 'Hold Monster',
    level: 5,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no type restriction — it works on any creature. At the end of each of its turns, the target can make another Wisdom saving throw.',
    higherLevels: 'You can target one additional creature for each slot level above 5th, within 30 feet of each other.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Lock',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Even monsters bow before true power. Be still.',
      jarvis: 'Universal paralysis field engaged. No creature type restrictions.',
      deadpool: 'Hold Person\'s BIG BROTHER! Works on EVERYTHING! Dragons? YEP!',
    },
  },
  {
    id: 'bard-mass-cure-wounds',
    name: 'Mass Cure Wounds',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A wave of healing energy washes out from a point you choose within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 5th.',
    healingFormula: '3d8+mod',
    iconName: 'HeartPulse',
    classes: ['bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'My song heals all who hear it. Stand, allies. The fight continues.',
      jarvis: 'Mass cellular regeneration wave deployed. Six targets: restored.',
      deadpool: 'GROUP HUG HEALING! Everyone gets health! You get health! And YOU get health!',
    },
  },
  {
    id: 'bard-synaptic-static',
    name: 'Synaptic Static',
    level: 5,
    school: 'enchantment',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You choose a point within range and cause psychic energy to explode there. Each creature in a 20-foot-radius sphere centered on that point must make an Intelligence saving throw. On a failed save, a target takes 8d6 psychic damage and for 1 minute, it must subtract 1d6 from its attack rolls, ability checks, and concentration saving throws. A target can make an INT save at end of each turn to end the 1d6 penalty.',
    damageType: 'psychic',
    damageFormula: '8d6',
    attackType: 'save',
    saveStat: 'INT',
    iconName: 'BrainCircuit',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    personalityQuips: {
      thunderhead: 'Their thoughts shatter like glass. The mind is the most fragile weapon.',
      jarvis: 'Neural disruption blast deployed. Cognitive function: severely impaired.',
      deadpool: 'Brain freeze! And not the fun Slurpee kind!',
    },
  },
];

// ============================================
// COMBINED EXPORT
// ============================================

export const BARD_SPELLS: SpellDefinition[] = [
  ...BARD_CANTRIPS,
  ...BARD_1ST_LEVEL,
  ...BARD_2ND_LEVEL,
  ...BARD_3RD_LEVEL,
  ...BARD_4TH_LEVEL,
  ...BARD_5TH_LEVEL,
];
