import { SpellDefinition } from '../types';

export const CANTRIPS: SpellDefinition[] = [
  // ============================================
  // ILLUSION CANTRIPS
  // ============================================
  {
    id: 'minor-illusion',
    name: 'Minor Illusion',
    level: 0,
    school: 'illusion',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: false, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You create a sound or an image of an object within range that lasts for the duration.',
    iconName: 'Ghost',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Illusory manifestation initiated. Sensory deception parameters: optimal.',
      jarvis: 'A delightful bit of misdirection, Sir. The mark will be none the wiser.',
      deadpool: 'Ooh, I can make a tiny Chimichangas! Wait, can I eat illusion chimichangas? Science needs answers!',
    },
  },
  {
    id: 'prestidigitation',
    name: 'Prestidigitation',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'A minor magical trick that creates harmless sensory effects, cleans or soils small objects, lights or snuffs flames, or creates small trinkets.',
    iconName: 'Sparkles',
    personalityQuips: {
      thunderhead: 'Cantrip utility function engaged. Application possibilities: 47.',
      jarvis: 'A gentleman\'s trick, Sir. Subtle, yet effective.',
      deadpool: 'The ultimate party trick! I can make my mask smell like lavender instead of... well, you don\'t wanna know.',
    },
  },
  {
    id: 'mage-hand',
    name: 'Mage Hand',
    level: 0,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'A spectral, floating hand appears at a point you choose within range. You can use your action to control the hand.',
    iconName: 'Hand',
    pathRestrictions: ['arcane_trickster'],
    personalityQuips: {
      thunderhead: 'Remote manipulation appendage materialized. Operational range: 30 feet.',
      jarvis: 'Your invisible butler, Sir. Ready to pilfer at your command.',
      deadpool: 'Spooky ghost hand! High-five! ...No? Okay, pickpocketing it is.',
    },
  },

  // ============================================
  // EVOCATION CANTRIPS
  // ============================================
  {
    id: 'fire-bolt',
    name: 'Fire Bolt',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack.',
    attackType: 'ranged',
    damageType: 'fire',
    damageFormula: '1d10',
    iconName: 'Flame',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Incendiary projectile launched. Thermal output: 1d10 fire.',
      jarvis: 'A rather direct approach, Sir. Effective nonetheless.',
      deadpool: 'FIREBALL! Wait, no, fire BOLT. Baby fireball. Firebaby? Fire... okay I\'ll stop.',
    },
  },
  {
    id: 'shocking-grasp',
    name: 'Shocking Grasp',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Lightning springs from your hand to deliver a shock to a creature you try to touch.',
    attackType: 'melee',
    damageType: 'lightning',
    damageFormula: '1d8',
    iconName: 'Zap',
    pathRestrictions: ['eldritch_knight'],
    personalityQuips: {
      thunderhead: 'Electrical discharge ready. Contact required. Damage potential: 1d8 lightning.',
      jarvis: 'A shocking touch, Sir. Quite literally.',
      deadpool: 'ZAP! Like a human taser! Except I\'m not human and neither is the taser.',
    },
  },
  {
    id: 'booming-blade',
    name: 'Booming Blade',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (5-foot radius)',
    components: { verbal: false, somatic: true, material: 'a melee weapon worth at least 1 sp' },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You make a melee attack with a weapon. On a hit, the target is sheathed in booming energy—if they move, they take thunder damage.',
    attackType: 'melee',
    damageType: 'thunder',
    iconName: 'Sword',
    personalityQuips: {
      thunderhead: 'Kinetic resonance field applied to blade. Movement penalty: thunder damage.',
      jarvis: 'A clever deterrent, Sir. Move and suffer.',
      deadpool: 'BOOM BOOM POW! Black Eyed Peas would be proud. Or sue me. Probably sue.',
    },
  },
  {
    id: 'green-flame-blade',
    name: 'Green-Flame Blade',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (5-foot radius)',
    components: { verbal: false, somatic: true, material: 'a melee weapon worth at least 1 sp' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You make a melee attack. On hit, green fire leaps from the target to a different creature within 5 feet.',
    attackType: 'melee',
    damageType: 'fire',
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Chain reaction fire initiated. Secondary target: auto-acquire.',
      jarvis: 'Two birds, one flaming sword, Sir.',
      deadpool: 'It\'s green! Like money! Or that weird mold in my apartment! DOUBLE KILL!',
    },
  },

  // ============================================
  // NECROMANCY CANTRIPS
  // ============================================
  {
    id: 'chill-touch',
    name: 'Chill Touch',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You create a ghostly, skeletal hand that assails a target. Hit prevents healing until your next turn.',
    attackType: 'ranged',
    damageType: 'necrotic',
    damageFormula: '1d8',
    iconName: 'Skull',
    pathRestrictions: ['shadow_blade'],
    personalityQuips: {
      thunderhead: 'Necrotic energy projection active. Healing suppression: enabled.',
      jarvis: 'A touch of death, Sir. Quite chilling indeed.',
      deadpool: 'Ghost hand that hurts AND stops healing? That\'s MY move! Copyright infringement!',
    },
  },
  {
    id: 'toll-the-dead',
    name: 'Toll the Dead',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You point at one creature and the sound of a dolorous bell fills the air. Target makes WIS save or takes necrotic damage.',
    saveStat: 'WIS',
    damageType: 'necrotic',
    damageFormula: '1d8',
    iconName: 'Bell',
    pathRestrictions: ['shadow_blade', 'hexblade'],
    personalityQuips: {
      thunderhead: 'Death knell frequency detected. Psychological damage: imminent.',
      jarvis: 'Ask not for whom the bell tolls, Sir. It tolls for them.',
      deadpool: 'DING DONG! Death delivery! Did someone order existential dread?',
    },
  },

  // ============================================
  // WARLOCK CANTRIPS (HEXBLADE)
  // ============================================
  {
    id: 'eldritch-blast',
    name: 'Eldritch Blast',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack.',
    attackType: 'ranged',
    damageType: 'force',
    damageFormula: '1d10',
    iconName: 'Zap',
    pathRestrictions: ['hexblade'],
    personalityQuips: {
      thunderhead: 'Eldritch energy beam: ONLINE. Force damage output: 1d10 per beam.',
      jarvis: 'The warlock\'s signature, Sir. Reliable and devastating.',
      deadpool: 'PEW PEW PEW! The patron-approved finger guns of DOOM!',
    },
  },
  {
    id: 'blade-ward',
    name: 'Blade Ward',
    level: 0,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You extend your hand and trace a sigil of warding. Until the end of your next turn, you have resistance to bludgeoning, piercing, and slashing damage.',
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'Physical damage resistance: 50%. Duration: 1 round.',
      jarvis: 'A protective ward, Sir. Blades shall find you less accommodating.',
      deadpool: 'Half damage from pointy things! Which is great because EVERYTHING is pointy to me.',
    },
  },
  {
    id: 'true-strike',
    name: 'True Strike',
    level: 0,
    school: 'divination',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: false, somatic: true },
    duration: 'Concentration, up to 1 round',
    concentration: true,
    ritual: false,
    description: 'You point a finger at a target. On your next turn, you gain advantage on your first attack roll against it.',
    iconName: 'Target',
    personalityQuips: {
      thunderhead: 'Targeting solution calculated. Next attack accuracy: +advantage.',
      jarvis: 'Taking aim, Sir. A moment of patience for a moment of precision.',
      deadpool: 'Use my whole action to aim? Sounds like something a COWARD would— actually that\'s pretty smart.',
    },
  },
];

export function getCantripsByPath(path: string): SpellDefinition[] {
  return CANTRIPS.filter(
    spell => !spell.pathRestrictions || spell.pathRestrictions.includes(path as any)
  );
}
