// Cleric Spell List
// D&D 5e divine magic - Wisdom-based prepared caster

import { SpellDefinition } from '../types';

export const CLERIC_SPELLS: SpellDefinition[] = [
  // ============================================
  // CANTRIPS (Level 0)
  // ============================================
  {
    id: 'sacred-flame',
    name: 'Sacred Flame',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Flame-like radiance descends on a creature. DEX save or take 1d8 radiant damage. No benefit from cover.',
    higherLevels: 'Damage increases by 1d8 at 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
    saveStat: 'DEX',
    damageType: 'radiant',
    damageFormula: '1d8',
    classes: ['cleric'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Divine fire answers the faithful. The light burns the unworthy.',
      jarvis: 'Sacred thermal projection initiated. Targeting hostile entity.',
      deadpool: 'Holy Ghost Rider vibes! Your soul is stained with the blood of the innocent!',
    },
  },
  {
    id: 'guidance',
    name: 'Guidance',
    level: 0,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Touch a willing creature. Once before the spell ends, the target can roll 1d4 and add it to one ability check.',
    classes: ['cleric', 'druid'],
    iconName: 'Compass',
    personalityQuips: {
      thunderhead: 'Divine wisdom guides your hand. Trust in the path shown.',
      jarvis: 'Probability enhancement active. Success rate increased by 12.5%.',
      deadpool: 'Here\'s a tip: don\'t die! That\'ll be one d4 please.',
    },
  },
  {
    id: 'spare-the-dying',
    name: 'Spare the Dying',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a living creature at 0 HP. It becomes stable.',
    classes: ['cleric'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Not yet. Death must wait for another day.',
      jarvis: 'Vital signs stabilized. Patient no longer in critical condition.',
      deadpool: 'Plot armor activated! You can\'t die yet, we\'re only on episode 3!',
    },
  },
  {
    id: 'thaumaturgy',
    name: 'Thaumaturgy',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: 'Up to 1 minute',
    concentration: false,
    ritual: false,
    description: 'Manifest a minor wonder: booming voice, flickering flames, tremors, thunder sounds, instant door/window opening, or eye appearance change.',
    classes: ['cleric'],
    iconName: 'Sparkles',
    personalityQuips: {
      thunderhead: 'The faithful require signs. Give them spectacle.',
      jarvis: 'Theatrical effect subroutines engaged. Dramatic impact optimized.',
      deadpool: 'BEHOLD MY POWER! *voice cracks* Ahem. BEHOLD MY POWER!',
    },
  },
  {
    id: 'toll-the-dead-cleric',
    name: 'Toll the Dead',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You point at a creature and the sound of a dolorous bell fills the air. WIS save or take 1d8 necrotic damage (1d12 if already damaged).',
    higherLevels: 'Damage increases at 5th level (2d8/2d12), 11th level (3d8/3d12), and 17th level (4d8/4d12).',
    saveStat: 'WIS',
    damageType: 'necrotic',
    damageFormula: '1d8',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Bell',
    personalityQuips: {
      thunderhead: 'For whom does the bell toll? For thee, evermore.',
      jarvis: 'Acoustic neural disruption initiated. Mortality reminder delivered.',
      deadpool: 'DING DONG! Death\'s calling! Oh wait, wrong kind of bell...',
    },
  },
  {
    id: 'word-of-radiance',
    name: 'Word of Radiance',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '5 feet',
    components: { verbal: true, somatic: false, material: 'a holy symbol' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You utter a divine word, and burning radiance erupts from you. Each creature of your choice within range must make a CON save or take 1d6 radiant damage.',
    higherLevels: 'Damage increases at 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
    saveStat: 'CON',
    damageType: 'radiant',
    damageFormula: '1d6',
    classes: ['cleric'],
    iconName: 'Sun',
    personalityQuips: {
      thunderhead: 'The word of the divine burns all who stand too close.',
      jarvis: 'Radiant area effect deployed. Hostile entities within radius affected.',
      deadpool: 'BEGONE THOTS! Wait, wrong word of power. BEGONE EVIL!',
    },
  },

  // --- MISSING CANTRIPS ---
  {
    id: 'light-cleric',
    name: 'Light',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a firefly or phosphorescent moss' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch one object no larger than 10 feet in any dimension. It sheds bright light in a 20-foot radius and dim light for an additional 20 feet. Hostile creature: DEX save or spell takes effect.',
    saveStat: 'DEX',
    classes: ['cleric', 'bard', 'sorcerer', 'wizard'],
    iconName: 'Lightbulb',
    personalityQuips: {
      thunderhead: 'Let there be light. The darkness flees before the faithful.',
      jarvis: 'Illumination protocol engaged. Visible spectrum output: optimal.',
      deadpool: 'FLASHLIGHT SPELL! Because torches are so last century!',
    },
  },
  {
    id: 'mending-cleric',
    name: 'Mending',
    level: 0,
    school: 'transmutation',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. The break must be no larger than 1 foot.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'wizard'],
    iconName: 'Wrench',
    personalityQuips: {
      thunderhead: 'What was broken is made whole. Even small miracles matter.',
      jarvis: 'Molecular repair subroutine initiated. Structural integrity restored.',
      deadpool: 'Duct tape spell! Fixes EVERYTHING! Well, almost everything.',
    },
  },
  {
    id: 'resistance-cleric',
    name: 'Resistance',
    level: 0,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a miniature cloak' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after making the saving throw.',
    classes: ['cleric', 'druid'],
    iconName: 'ShieldCheck',
    personalityQuips: {
      thunderhead: 'The faithful endure. Take this small shield of will.',
      jarvis: 'Saving throw enhancement module active. +1d4 to next save.',
      deadpool: 'Here, take this tiny invisible blanket of protection! Very cozy!',
    },
  },

  // ============================================
  // 1ST LEVEL SPELLS
  // ============================================
  {
    id: 'bless',
    name: 'Bless',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a sprinkling of holy water' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Bless up to 3 creatures. Whenever a target makes an attack roll or saving throw, it can add 1d4 to the roll.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['cleric'],
    iconName: 'Star',
    personalityQuips: {
      thunderhead: 'May the gods smile upon your efforts. Strike true.',
      jarvis: 'Divine enhancement protocol active. Combat efficiency increased.',
      deadpool: 'You get a blessing! And YOU get a blessing! EVERYBODY GETS BLESSINGS!',
    },
  },
  {
    id: 'cure-wounds-cleric',
    name: 'Cure Wounds',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature you touch regains 1d8 + spellcasting modifier HP. No effect on undead or constructs.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 1st.',
    healingFormula: '1d8+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Be healed by divine grace. Rise and fight on.',
      jarvis: 'Tissue regeneration complete. Health points restored.',
      deadpool: 'Boop! All better! That\'ll be 500 gold. Kidding! ...Unless?',
    },
  },
  {
    id: 'guiding-bolt',
    name: 'Guiding Bolt',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A flash of light streaks toward a creature. Make a ranged spell attack. On hit, 4d6 radiant damage and next attack roll against target has advantage.',
    higherLevels: 'Damage increases by 1d6 for each slot level above 1st.',
    attackType: 'ranged',
    damageType: 'radiant',
    damageFormula: '4d6',
    classes: ['cleric'],
    iconName: 'Target',
    personalityQuips: {
      thunderhead: 'The light reveals all. Strike where the gods have shown.',
      jarvis: 'Targeting beacon deployed. Next attack vector optimized.',
      deadpool: 'GPS STRIKE INCOMING! Recalculating... your face!',
    },
  },
  {
    id: 'healing-word-cleric',
    name: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature of your choice that you can see regains 1d4 + spellcasting modifier HP.',
    higherLevels: 'Healing increases by 1d4 for each slot level above 1st.',
    healingFormula: '1d4+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Rise! The battle is not yet done.',
      jarvis: 'Remote healing protocol initiated. Patient stabilizing.',
      deadpool: 'Get up, princess! Beauty sleep is over!',
    },
  },
  {
    id: 'shield-of-faith',
    name: 'Shield of Faith',
    level: 1,
    school: 'abjuration',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small parchment with holy text' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'A shimmering field appears around a creature, granting +2 bonus to AC for the duration.',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'Faith is the truest armor. Let it protect you.',
      jarvis: 'Protective energy matrix deployed. AC increased by 2.',
      deadpool: 'Bubble shield! Now you\'re basically a hamster! A holy hamster!',
    },
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    level: 1,
    school: 'abjuration',
    castingTime: 'bonus_action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a small silver mirror' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You ward a creature. Any creature targeting the warded creature with attack or harmful spell must make WIS save or choose a new target or lose the attack/spell.',
    saveStat: 'WIS',
    classes: ['cleric'],
    iconName: 'Home',
    personalityQuips: {
      thunderhead: 'This one is under divine protection. Strike elsewhere.',
      jarvis: 'Sanctuary protocol engaged. Target marked as non-combatant.',
      deadpool: 'Olly olly oxen free! Can\'t touch this! Da na na na!',
    },
  },
  {
    id: 'inflict-wounds',
    name: 'Inflict Wounds',
    level: 1,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Make a melee spell attack. On hit, target takes 3d10 necrotic damage.',
    higherLevels: 'Damage increases by 1d10 for each slot level above 1st.',
    attackType: 'melee',
    damageType: 'necrotic',
    damageFormula: '3d10',
    classes: ['cleric'],
    iconName: 'Hand',
    personalityQuips: {
      thunderhead: 'The gods can give life... and take it away.',
      jarvis: 'Necrotic energy transfer initiated. Maximum tissue damage.',
      deadpool: 'HIGH FIVE OF DOOM! ...You\'re not gonna high-five me back, are you?',
    },
  },
  {
    id: 'command',
    name: 'Command',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Speak a one-word command to a creature you can see. WIS save or follow the command on its next turn. Common commands: Approach, Drop, Flee, Grovel, Halt.',
    higherLevels: 'You can affect one additional creature for each slot level above 1st.',
    saveStat: 'WIS',
    classes: ['cleric', 'warlock'],
    iconName: 'MessageSquare',
    personalityQuips: {
      thunderhead: 'HALT! When the divine speaks, mortals obey.',
      jarvis: 'Verbal command protocol engaged. Compliance probability: high.',
      deadpool: 'DANCE! No wait, that\'s not one of them. GROVEL! Yeah, that\'s better.',
    },
  },
  {
    id: 'detect-magic-cleric',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Sense the presence of magic within 30 feet. You can see a faint aura around any visible creature or object that bears magic and learn its school.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'wizard'],
    iconName: 'Search',
    personalityQuips: {
      thunderhead: 'The divine eye reveals all enchantments. See truly.',
      jarvis: 'Arcane detection scanners online. Magical signatures identified.',
      deadpool: 'My Spidey sense is tingling! Wait, wrong universe.',
    },
  },

  // --- MISSING 1ST LEVEL ---
  {
    id: 'create-or-destroy-water',
    name: 'Create or Destroy Water',
    level: 1,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a drop of water (create) or a few grains of sand (destroy)' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You either create up to 10 gallons of clean water within range in an open container, or rain in a 30-foot cube. Alternatively, you destroy up to 10 gallons of water in an open container or destroy fog in a 30-foot cube.',
    higherLevels: 'Create or destroy 10 additional gallons or increase cube size by 5 feet for each slot level above 1st.',
    classes: ['cleric', 'druid'],
    iconName: 'Droplets',
    personalityQuips: {
      thunderhead: 'Water flows or vanishes at divine command.',
      jarvis: 'Aquatic generation/elimination protocol initiated.',
      deadpool: 'I\'m basically a water bender now! Or an un-water bender!',
    },
  },
  {
    id: 'detect-evil-and-good',
    name: 'Detect Evil and Good',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you, as well as where the creature is located.',
    classes: ['cleric'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'The divine eye sees beyond mortal sight. Evil cannot hide.',
      jarvis: 'Extraplanar entity scanner online. Hostile signatures detected.',
      deadpool: 'My evil-dar is pinging! Oh wait, that\'s just Greg.',
    },
  },
  {
    id: 'detect-poison-and-disease',
    name: 'Detect Poison and Disease',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a yew leaf' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you. You also identify the kind of poison, poisonous creature, or disease.',
    classes: ['cleric', 'druid'],
    iconName: 'Bug',
    personalityQuips: {
      thunderhead: 'Corruption reveals itself to the faithful. Trust your senses.',
      jarvis: 'Toxicology scanner active. Pathogenic threats identified.',
      deadpool: 'POISON DETECTOR! Beep beep beep! That soup is SUS!',
    },
  },
  {
    id: 'protection-from-evil-and-good',
    name: 'Protection from Evil and Good',
    level: 1,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron, which the spell consumes' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Until the spell ends, one willing creature you touch is protected against aberrations, celestials, elementals, fey, fiends, and undead. Those types have disadvantage on attacks against the target, and the target can\'t be charmed, frightened, or possessed by them.',
    classes: ['cleric', 'druid', 'wizard'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'The ward is set. Otherworldly beings shall not touch you.',
      jarvis: 'Anti-planar defense barrier active. Hostile entity resistance engaged.',
      deadpool: 'SUPERNATURAL RESTRAINING ORDER! 30 feet at all times!',
    },
  },
  {
    id: 'purify-food-and-drink',
    name: 'Purify Food and Drink',
    level: 1,
    school: 'transmutation',
    castingTime: 'action',
    range: '10 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice is rendered free of poison and disease.',
    classes: ['cleric', 'druid'],
    iconName: 'Apple',
    personalityQuips: {
      thunderhead: 'No poison shall taint what is blessed. Eat without fear.',
      jarvis: 'Food safety protocol complete. All contaminants neutralized.',
      deadpool: 'Five-second rule? Nah, PURIFY-second rule! Eat off the floor!',
    },
  },

  // ============================================
  // 2ND LEVEL SPELLS
  // ============================================
  {
    id: 'spiritual-weapon',
    name: 'Spiritual Weapon',
    level: 2,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Create a floating, spectral weapon within range. Make a melee spell attack dealing 1d8 + spellcasting modifier force damage. Move weapon up to 20 feet and attack again as bonus action.',
    higherLevels: 'Damage increases by 1d8 for every two slot levels above 2nd.',
    attackType: 'melee',
    damageType: 'force',
    damageFormula: '1d8+mod',
    classes: ['cleric'],
    iconName: 'Sword',
    personalityQuips: {
      thunderhead: 'The gods fight beside you. Let their weapon strike true.',
      jarvis: 'Autonomous spiritual armament deployed. Combat assist active.',
      deadpool: 'It\'s like a Stand! STAR PLATINUM! ...No wait, that\'s not it either.',
    },
  },
  {
    id: 'hold-person-cleric',
    name: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a humanoid. It must succeed on a WIS save or be paralyzed. It repeats the save at the end of each of its turns.',
    higherLevels: 'You can target one additional humanoid for each slot level above 2nd.',
    saveStat: 'WIS',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'Lock',
    personalityQuips: {
      thunderhead: 'Be still in the presence of the divine.',
      jarvis: 'Motor function override engaged. Target immobilized.',
      deadpool: 'FREEZE! This is a holy intervention!',
    },
  },
  {
    id: 'lesser-restoration',
    name: 'Lesser Restoration',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a creature and end one disease or one condition: blinded, deafened, paralyzed, or poisoned.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Eraser',
    personalityQuips: {
      thunderhead: 'Affliction be purged. The gods cleanse what ails you.',
      jarvis: 'Condition removal subroutine active. Status effect purged.',
      deadpool: 'Cleanse! Purify! Exfoliate! Wait, that last one\'s skincare.',
    },
  },
  {
    id: 'prayer-of-healing',
    name: 'Prayer of Healing',
    level: 2,
    school: 'evocation',
    castingTime: '10_minutes',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Up to 6 creatures regain 2d8 + spellcasting modifier HP each.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 2nd.',
    healingFormula: '2d8+mod',
    classes: ['cleric'],
    iconName: 'Users',
    personalityQuips: {
      thunderhead: 'Gather round—healing for all who are faithful.',
      jarvis: 'Mass healing protocol engaged. Multiple patients treated.',
      deadpool: 'Group therapy session! Everyone gets a cookie and some HP!',
    },
  },
  {
    id: 'aid',
    name: 'Aid',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a tiny strip of white cloth' },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'Choose up to 3 creatures. Each target\'s HP maximum and current HP increase by 5 for the duration.',
    higherLevels: 'HP increase by an additional 5 for each slot level above 2nd.',
    classes: ['cleric'],
    iconName: 'TrendingUp',
    personalityQuips: {
      thunderhead: 'Divine vitality strengthens the worthy. Stand tall.',
      jarvis: 'Temporary hit point allocation complete. Durability increased.',
      deadpool: 'You\'re now 5 HP thicc-er! Use it wisely!',
    },
  },
  {
    id: 'silence',
    name: 'Silence',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Create a 20-foot-radius sphere of silence. No sound can be created within or pass through. Creatures are immune to thunder damage and are deafened. Verbal components are impossible.',
    classes: ['cleric', 'bard'],
    iconName: 'VolumeX',
    personalityQuips: {
      thunderhead: 'Let there be silence. No more spellcasting for you.',
      jarvis: 'Acoustic dampening field deployed. Sound transmission blocked.',
      deadpool: 'SHHHH! Library rules in effect! No talking, no magic!',
    },
  },
  {
    id: 'zone-of-truth',
    name: 'Zone of Truth',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '10 minutes',
    concentration: false,
    ritual: false,
    description: 'Create a 15-foot-radius sphere. Creatures entering must succeed CHA save or be unable to speak a deliberate lie. You know whether each creature succeeds or fails.',
    saveStat: 'CHA',
    classes: ['cleric', 'bard'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'Truth or silence—those are your only options.',
      jarvis: 'Veracity enforcement field active. Deception probability: zero.',
      deadpool: 'Truth time! Did you eat the last pizza slice? CONFESS!',
    },
  },

  // --- MISSING 2ND LEVEL ---
  {
    id: 'augury-cleric',
    name: 'Augury',
    level: 2,
    school: 'divination',
    castingTime: '1_minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'specially marked sticks, bones, or similar tokens worth at least 25 gp' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action within the next 30 minutes: weal, woe, both, or nothing.',
    classes: ['cleric'],
    iconName: 'Dice1',
    personalityQuips: {
      thunderhead: 'The signs are cast. The gods whisper their counsel.',
      jarvis: 'Probability analysis complete. Omen received and decoded.',
      deadpool: 'Magic 8-Ball says... ask again later! Just kidding. Weal!',
    },
  },
  {
    id: 'blindness-deafness',
    name: 'Blindness/Deafness',
    level: 2,
    school: 'necromancy',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You can blind or deafen a foe. Choose one creature that you can see within range. It must succeed on a CON save or be either blinded or deafened (your choice) for the duration. It repeats the save at the end of each of its turns.',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    saveStat: 'CON',
    classes: ['cleric', 'bard', 'sorcerer', 'wizard'],
    iconName: 'EyeOff',
    personalityQuips: {
      thunderhead: 'Be sightless! The divine revokes your senses.',
      jarvis: 'Sensory deprivation protocol engaged. Target input disabled.',
      deadpool: 'SEE NO EVIL! Or hear no evil! Dealer\'s choice!',
    },
  },
  {
    id: 'calm-emotions',
    name: 'Calm Emotions',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere must make a CHA save. On failure, you can suppress any effect causing it to be charmed or frightened, or make it indifferent about hostile creatures.',
    saveStat: 'CHA',
    classes: ['cleric', 'bard'],
    iconName: 'HeartHandshake',
    personalityQuips: {
      thunderhead: 'Peace. Be still. Let wrath and fear depart.',
      jarvis: 'Emotional regulation field active. Hostility levels normalized.',
      deadpool: 'Everybody just CHILL! Group therapy in session!',
    },
  },
  {
    id: 'continual-flame',
    name: 'Continual Flame',
    level: 2,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'ruby dust worth 50 gp, which the spell consumes' },
    duration: 'Until dispelled',
    concentration: false,
    ritual: false,
    description: 'A flame, equivalent in brightness to a torch, springs forth from an object that you touch. The effect looks like a regular flame, but it creates no heat and doesn\'t use oxygen. A continual flame can be covered or hidden but not smothered or quenched.',
    classes: ['cleric', 'wizard'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Eternal flame burns by divine will. It shall never be extinguished.',
      jarvis: 'Perpetual illumination source created. Energy output: indefinite.',
      deadpool: 'Eternal flame! Like the Bangles song! It burns, burns, BURNS!',
    },
  },
  {
    id: 'enhance-ability',
    name: 'Enhance Ability',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'fur or a feather from a beast' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects: Bear\'s Endurance (advantage on CON checks, 2d6 temp HP), Bull\'s Strength (advantage on STR checks, double carrying capacity), Cat\'s Grace (advantage on DEX checks, no fall damage from 20 feet or less), Eagle\'s Splendor (advantage on CHA checks), Fox\'s Cunning (advantage on INT checks), or Owl\'s Wisdom (advantage on WIS checks).',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer'],
    iconName: 'TrendingUp',
    personalityQuips: {
      thunderhead: 'Be empowered. The gods sharpen your natural gifts.',
      jarvis: 'Ability enhancement module loaded. Performance boosted.',
      deadpool: 'SUPER JUICE! Pick your flavor: Bear, Bull, Cat, Eagle, Fox, or Owl!',
    },
  },
  {
    id: 'find-traps',
    name: 'Find Traps',
    level: 2,
    school: 'divination',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You sense the presence of any trap within line of sight and within range. A trap includes anything that would inflict a sudden or unexpected effect you consider harmful or undesirable. You learn the general nature of each trap\'s danger but not exact location.',
    classes: ['cleric', 'druid'],
    iconName: 'AlertTriangle',
    personalityQuips: {
      thunderhead: 'Danger lurks ahead. The faithful are warned.',
      jarvis: 'Trap detection scan complete. Hazards identified in vicinity.',
      deadpool: 'IT\'S A TRAP! ...Sorry, had to say it. Admiral Ackbar would be proud.',
    },
  },
  {
    id: 'gentle-repose',
    name: 'Gentle Repose',
    level: 2,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pinch of salt and one copper piece placed on each of the corpse\'s eyes' },
    duration: '10 days',
    concentration: false,
    ritual: true,
    description: 'You touch a corpse or other remains. For the duration, the target is protected from decay and can\'t become undead. The spell also effectively extends the time limit on raising the target from the dead.',
    classes: ['cleric', 'wizard'],
    iconName: 'Moon',
    personalityQuips: {
      thunderhead: 'Rest peacefully. Decay shall not touch you, nor shall undeath.',
      jarvis: 'Preservation protocol engaged. Decomposition halted for 10 days.',
      deadpool: 'Anti-zombie insurance! Just two copper and a pinch of salt!',
    },
  },
  {
    id: 'locate-object',
    name: 'Locate Object',
    level: 2,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a forked twig' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Describe or name an object that is familiar to you. You sense the direction to the object\'s location, as long as that object is within 1,000 feet of you. If the object is in motion, you know the direction of its movement.',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'MapPin',
    personalityQuips: {
      thunderhead: 'That which is lost shall be found. The gods guide your search.',
      jarvis: 'Object tracking protocol active. Directional lock acquired.',
      deadpool: 'GPS for medieval stuff! Where did I put my other sock?!',
    },
  },
  {
    id: 'protection-from-poison',
    name: 'Protection from Poison',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch a creature. If it is poisoned, you neutralize the poison. For the duration, the target has advantage on saving throws against being poisoned and has resistance to poison damage.',
    classes: ['cleric', 'druid'],
    iconName: 'ShieldCheck',
    personalityQuips: {
      thunderhead: 'Poison cannot fell the protected. The gods purify your blood.',
      jarvis: 'Anti-toxin protocol active. Poison resistance engaged.',
      deadpool: 'POISON PROOF! Go ahead, drink the suspicious potion!',
    },
  },
  {
    id: 'warding-bond',
    name: 'Warding Bond',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pair of platinum rings worth at least 50 gp each, which you and the target must wear' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch a willing creature and create a mystic connection. While the target is within 60 feet, it gains +1 to AC and saving throws and has resistance to all damage. Each time it takes damage, you take the same amount.',
    classes: ['cleric'],
    iconName: 'Link',
    personalityQuips: {
      thunderhead: 'We share this burden. Your pain is mine to bear.',
      jarvis: 'Damage sharing protocol established. Symbiotic defense active.',
      deadpool: 'BFF rings! Except when you get hurt, I get hurt too. Great plan!',
    },
  },

  // ============================================
  // 3RD LEVEL SPELLS
  // ============================================
  {
    id: 'spirit-guardians',
    name: 'Spirit Guardians',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: 'Self (15-foot radius)',
    components: { verbal: true, somatic: true, material: 'a holy symbol' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Spirits surround you in a 15-foot radius. Creatures of your choice entering the area or starting their turn there must make WIS save. 3d8 radiant (good/neutral) or necrotic (evil) damage on failure, half on success.',
    higherLevels: 'Damage increases by 1d8 for each slot level above 3rd.',
    saveStat: 'WIS',
    damageType: 'radiant',
    damageFormula: '3d8',
    classes: ['cleric'],
    iconName: 'Users',
    personalityQuips: {
      thunderhead: 'The faithful dead fight on. Come closer if you dare.',
      jarvis: 'Spiritual defense perimeter established. Area denial active.',
      deadpool: 'I\'ve got GHOST FRIENDS! They\'re very protective!',
    },
  },
  {
    id: 'revivify',
    name: 'Revivify',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamonds worth 300 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a creature that died within the last minute. It returns to life with 1 HP. Cannot restore missing body parts or creatures that died of old age.',
    healingFormula: '1',
    classes: ['cleric', 'druid'],
    iconName: 'RotateCcw',
    personalityQuips: {
      thunderhead: 'Return to us—your time has not yet come.',
      jarvis: 'Revival protocol initiated. Vital signs reestablishing.',
      deadpool: 'CLEAR! *zap* Welcome back! That\'ll be 300 gold!',
    },
  },
  {
    id: 'beacon-of-hope',
    name: 'Beacon of Hope',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose any number of creatures within range. They have advantage on WIS saves and death saving throws, and regain the maximum HP possible from healing.',
    classes: ['cleric'],
    iconName: 'Sunrise',
    personalityQuips: {
      thunderhead: 'Hope blazes brightest in darkness. Be healed fully.',
      jarvis: 'Hope amplification active. Maximum healing efficiency achieved.',
      deadpool: 'MAXIMUM HEALING! It\'s like a spa day but with less cucumber!',
    },
  },
  {
    id: 'dispel-magic-cleric',
    name: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose a creature, object, or magical effect. Any spell of 3rd level or lower ends. For higher-level spells, make an ability check (DC 10 + spell level).',
    higherLevels: 'Automatically end spells of the slot level used or lower.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'XCircle',
    personalityQuips: {
      thunderhead: 'Your magic ends here. Divine will unravels the arcane.',
      jarvis: 'Magical negation field deployed. Spell integrity compromised.',
      deadpool: 'CTRL+Z! UNDO! Your magic is now canceled!',
    },
  },
  {
    id: 'mass-healing-word',
    name: 'Mass Healing Word',
    level: 3,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Up to 6 creatures of your choice that you can see regain 1d4 + spellcasting modifier HP each.',
    higherLevels: 'Healing increases by 1d4 for each slot level above 3rd.',
    healingFormula: '1d4+mod',
    classes: ['cleric', 'bard'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Rise, all of you! The prayer reaches many.',
      jarvis: 'Mass healing broadcast initiated. Multiple patients responding.',
      deadpool: 'EVERYBODY GETS UP! No dying on my watch!',
    },
  },
  {
    id: 'remove-curse',
    name: 'Remove Curse',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'At your touch, all curses affecting one creature or object end. If the object is a cursed magic item, its curse remains but breaks the owner\'s attunement.',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Eraser',
    personalityQuips: {
      thunderhead: 'Curses break before divine will. Be free.',
      jarvis: 'Curse removal protocol successful. Magical binding severed.',
      deadpool: 'CURSE BE GONE! *throws holy water* Wait, was that my coffee?',
    },
  },

  // --- MISSING 3RD LEVEL ---
  {
    id: 'animate-dead',
    name: 'Animate Dead',
    level: 3,
    school: 'necromancy',
    castingTime: '1_minute',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'a drop of blood, a piece of flesh, and a pinch of bone dust' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid. Your spell imbues it with a foul mimicry of life, raising it as a skeleton or zombie. It obeys your verbal commands and acts on your turn in combat.',
    higherLevels: 'You reassert control over two additional undead creatures for each slot level above 3rd.',
    classes: ['cleric', 'wizard'],
    iconName: 'Skull',
    personalityQuips: {
      thunderhead: 'The dead rise at divine command. They serve, willingly or not.',
      jarvis: 'Necromantic reanimation complete. Undead unit online.',
      deadpool: 'ARISE MY MINION! ...Do you do windows?',
    },
  },
  {
    id: 'bestow-curse',
    name: 'Bestow Curse',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You touch a creature, and it must succeed on a WIS save or become cursed. Choose one curse effect: disadvantage on checks/saves with one ability score, disadvantage on attacks against you, WIS save each turn or waste action, or your attacks deal extra 1d8 necrotic.',
    higherLevels: 'At 4th level: concentration up to 10 minutes. At 5th: 8 hours without concentration. At 7th: 24 hours. At 9th: permanent until dispelled.',
    saveStat: 'WIS',
    damageType: 'necrotic',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'CloudLightning',
    personalityQuips: {
      thunderhead: 'A divine curse falls upon you. Suffer for your transgressions.',
      jarvis: 'Curse application successful. Target performance degraded.',
      deadpool: 'CURSED! Like that one email chain you didn\'t forward!',
    },
  },
  {
    id: 'clairvoyance',
    name: 'Clairvoyance',
    level: 3,
    school: 'divination',
    castingTime: '10_minutes',
    range: '1 mile',
    components: { verbal: true, somatic: true, material: 'a focus worth at least 100 gp, either a jeweled horn for hearing or a glass eye for seeing' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You create an invisible sensor within range at a location familiar to you or an obvious one. You can see or hear (your choice) through the sensor as if you were there.',
    classes: ['cleric', 'bard', 'sorcerer', 'wizard'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'The faithful see beyond walls and distance. Observe.',
      jarvis: 'Remote sensory node deployed. Audio/visual feed established.',
      deadpool: 'SPY CAM! Invisible spy cam! I feel like James Bond!',
    },
  },
  {
    id: 'create-food-and-water',
    name: 'Create Food and Water',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You create 45 pounds of food and 30 gallons of water on the ground or in containers. The food is bland but nourishing and spoils after 24 hours if uneaten. The water is clean and doesn\'t go bad.',
    classes: ['cleric'],
    iconName: 'Apple',
    personalityQuips: {
      thunderhead: 'The gods provide for their flock. Eat and drink.',
      jarvis: 'Sustenance materialization complete. Caloric needs met.',
      deadpool: 'DIVINE DOORDASH! 45 pounds of mystery meat! Bon appétit!',
    },
  },
  {
    id: 'daylight',
    name: 'Daylight',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'A 60-foot-radius sphere of light spreads out from a point you choose. The sphere is bright light and sheds dim light for an additional 60 feet. If any of this spell\'s area overlaps with darkness created by a 3rd level spell or lower, the darkness is dispelled.',
    classes: ['cleric', 'druid', 'sorcerer'],
    iconName: 'Sun',
    personalityQuips: {
      thunderhead: 'Let there be LIGHT! Darkness has no dominion here.',
      jarvis: 'Maximum illumination sphere deployed. Magical darkness countered.',
      deadpool: 'SUNRISE IN A CAN! Vampires hate this one weird trick!',
    },
  },
  {
    id: 'feign-death',
    name: 'Feign Death',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pinch of graveyard dirt' },
    duration: '1 hour',
    concentration: false,
    ritual: true,
    description: 'You touch a willing creature and put it into a cataleptic state that is indistinguishable from death. The target appears dead to all outward inspection and to spells used to determine the target\'s status. It is blinded, incapacitated, resistant to all damage except psychic, and diseases and poisons are suspended.',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'Skull',
    personalityQuips: {
      thunderhead: 'Play dead. Even death\'s gaze shall be fooled.',
      jarvis: 'Metabolic suppression complete. Vital signs: undetectable.',
      deadpool: 'Playing possum! Oscar-worthy performance! *fake dies dramatically*',
    },
  },
  {
    id: 'glyph-of-warding',
    name: 'Glyph of Warding',
    level: 3,
    school: 'abjuration',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'incense and powdered diamond worth at least 200 gp, which the spell consumes' },
    duration: 'Until dispelled or triggered',
    concentration: false,
    ritual: false,
    description: 'Inscribe a glyph on a surface or within an object. Choose Explosive Runes (5d8 acid/cold/fire/lightning/thunder damage, DEX save for half) or Spell Glyph (store a spell of 3rd level or lower cast on the triggering creature).',
    higherLevels: 'Explosive runes damage increases by 1d8 for each slot level above 3rd. Spell glyph can store a spell up to the same level.',
    saveStat: 'DEX',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'Pen',
    personalityQuips: {
      thunderhead: 'A divine ward is inscribed. Trespassers beware.',
      jarvis: 'Proximity-triggered defensive glyph inscribed. Armed and ready.',
      deadpool: 'MAGICAL LANDMINE! Step here and KABOOM! Or get spell\'d!',
    },
  },
  {
    id: 'magic-circle',
    name: 'Magic Circle',
    level: 3,
    school: 'abjuration',
    castingTime: '1_minute',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron worth at least 100 gp, which the spell consumes' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'Create a 10-foot-radius, 20-foot-tall cylinder of magical energy. Choose one or more: celestials, elementals, fey, fiends, or undead. The chosen type can\'t willingly enter the cylinder, has disadvantage on attacks against targets within, and can\'t charm, frighten, or possess those inside.',
    higherLevels: 'Duration increases by 1 hour for each slot level above 3rd.',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Circle',
    personalityQuips: {
      thunderhead: 'The circle is drawn. Nothing crosses this sacred boundary.',
      jarvis: 'Planar containment field established. Entity exclusion active.',
      deadpool: 'Stay in your circle! Like a divine time-out corner!',
    },
  },
  {
    id: 'meld-into-stone',
    name: 'Meld into Stone',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: true,
    description: 'You step into a stone object or surface large enough to fully contain your body, melding yourself and all the equipment you carry with the stone for the duration. You can cast no spells while merged. Minor physical damage to the stone doesn\'t harm you, but partial destruction or a change in shape ejects you and deals 6d6 bludgeoning damage.',
    classes: ['cleric', 'druid'],
    iconName: 'Mountain',
    personalityQuips: {
      thunderhead: 'Become one with the earth. The stone shelters the faithful.',
      jarvis: 'Molecular integration with stone matrix complete. Concealment: total.',
      deadpool: 'I AM ONE WITH THE ROCK! Not Dwayne Johnson, the actual rock!',
    },
  },
  {
    id: 'protection-from-energy',
    name: 'Protection from Energy',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'For the duration, the willing creature you touch has resistance to one damage type of your choice: acid, cold, fire, lightning, or thunder.',
    classes: ['cleric', 'druid', 'sorcerer', 'wizard'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'The elements hold no power over the protected.',
      jarvis: 'Elemental resistance shield active. Damage type selected.',
      deadpool: 'FIREPROOF! Or ice-proof! Or lightning-proof! Pick your flavor!',
    },
  },
  {
    id: 'sending',
    name: 'Sending',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: 'Unlimited',
    components: { verbal: true, somatic: true, material: 'a short piece of fine copper wire' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You send a short message of twenty-five words or less to a creature with which you are familiar. The creature hears the message in its mind, recognizes you as the sender, and can answer in a like manner immediately.',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'Send',
    personalityQuips: {
      thunderhead: 'Distance means nothing to the divine word. It shall be heard.',
      jarvis: 'Cross-dimensional communication link established. Message sent.',
      deadpool: 'DIVINE TEXTING! 25 words or less! Like Twitter but magical!',
    },
  },
  {
    id: 'speak-with-dead',
    name: 'Speak with Dead',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'burning incense' },
    duration: '10 minutes',
    concentration: false,
    ritual: false,
    description: 'You grant the semblance of life and intelligence to a corpse, allowing it to answer up to five questions. The corpse knows only what it knew in life and speaks in languages it knew. Answers are usually brief, cryptic, or repetitive.',
    classes: ['cleric', 'bard'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'The dead remember. Ask, and they shall answer.',
      jarvis: 'Posthumous communication interface active. Five queries remaining.',
      deadpool: 'HEY DEAD GUY! Got any hot gossip from the afterlife?',
    },
  },
  {
    id: 'tongues',
    name: 'Tongues',
    level: 3,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a small clay model of a ziggurat' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'This spell grants the creature you touch the ability to understand any spoken language it hears. Moreover, when the target speaks, any creature that knows at least one language and can hear the target understands what it says.',
    classes: ['cleric', 'bard', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'Languages',
    personalityQuips: {
      thunderhead: 'All tongues are one before the divine. Speak and be understood.',
      jarvis: 'Universal translation module active. All languages accessible.',
      deadpool: 'BABEL FISH SPELL! Now I can trash-talk in EVERY language!',
    },
  },
  {
    id: 'water-walk',
    name: 'Water Walk',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a piece of cork' },
    duration: '1 hour',
    concentration: false,
    ritual: true,
    description: 'This spell grants the ability to move across any liquid surface—such as water, acid, mud, snow, quicksand, or lava—as if it were harmless solid ground. Up to ten willing creatures you can see within range gain this ability for the duration.',
    classes: ['cleric', 'druid', 'sorcerer'],
    iconName: 'Waves',
    personalityQuips: {
      thunderhead: 'Walk upon the waters. The faithful need not fear the deep.',
      jarvis: 'Surface tension override active. Liquid traversal enabled.',
      deadpool: 'JESUS MODE ACTIVATED! Walking on water like a BOSS!',
    },
  },

  // ============================================
  // 4TH LEVEL SPELLS
  // ============================================
  {
    id: 'death-ward',
    name: 'Death Ward',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'Touch a creature. The first time it would drop to 0 HP, it drops to 1 HP instead. If subjected to an effect that would kill it instantly without dealing damage, that effect is negated.',
    classes: ['cleric'],
    iconName: 'ShieldCheck',
    personalityQuips: {
      thunderhead: 'Death shall not claim you yet. One chance remains.',
      jarvis: 'Anti-death protocol installed. Emergency revival armed.',
      deadpool: 'FREE EXTRA LIFE! Like a video game power-up! 1-UP!',
    },
  },
  {
    id: 'guardian-of-faith',
    name: 'Guardian of Faith',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'A Large spectral guardian appears. When a hostile creature moves within 10 feet for the first time or starts its turn there, it must make DEX save or take 20 radiant damage (half on success). Guardian vanishes after dealing 60 total damage.',
    saveStat: 'DEX',
    damageType: 'radiant',
    damageFormula: '20',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'An angel stands watch. Pass at your own peril.',
      jarvis: 'Divine sentry deployed. Area denial damage: significant.',
      deadpool: 'Security guard from heaven! Tips not accepted!',
    },
  },
  {
    id: 'banishment-cleric',
    name: 'Banishment',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'an item distasteful to the target' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Attempt to send a creature to another plane. CHA save or be banished. If native to current plane, creature goes to a harmless demiplane; otherwise, it returns to its home plane.',
    higherLevels: 'You can target one additional creature for each slot level above 4th.',
    saveStat: 'CHA',
    classes: ['cleric', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'LogOut',
    personalityQuips: {
      thunderhead: 'Return from whence you came! This plane rejects you.',
      jarvis: 'Planar ejection initiated. Target relocated to origin dimension.',
      deadpool: 'YEET! To another dimension you go! Byeeeee!',
    },
  },
  {
    id: 'freedom-of-movement',
    name: 'Freedom of Movement',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a leather strap' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'Touch a willing creature. Its movement is unaffected by difficult terrain, spells that reduce speed, or paralysis/restraint. It can spend 5 feet of movement to escape nonmagical restraints or grapples.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Move',
    personalityQuips: {
      thunderhead: 'No bonds can hold the faithful. Move freely.',
      jarvis: 'Movement restriction immunity active. Mobility unrestricted.',
      deadpool: 'PARKOUR! Nothing can hold you back now! FREEBIRD!',
    },
  },

  // --- MISSING 4TH LEVEL ---
  {
    id: 'control-water',
    name: 'Control Water',
    level: 4,
    school: 'transmutation',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a drop of water and a pinch of dust' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Until the spell ends, you control any freestanding water inside an area you choose (up to 100 feet on a side). Choose one of: Flood (raise water level up to 20 feet), Part Water (trench through the area), Redirect Flow (change direction of flowing water), or Whirlpool (vortex, 5-foot deep, STR save or 2d8 bludgeoning damage).',
    saveStat: 'STR',
    damageType: 'bludgeoning',
    damageFormula: '2d8',
    classes: ['cleric', 'druid', 'wizard'],
    iconName: 'Waves',
    personalityQuips: {
      thunderhead: 'The waters bend to divine will. Rise, part, or rage!',
      jarvis: 'Hydraulic manipulation system active. Water flow redirected.',
      deadpool: 'MOSES MODE! Part those seas! Or make a whirlpool! Your call!',
    },
  },
  {
    id: 'divination-spell',
    name: 'Divination',
    level: 4,
    school: 'divination',
    castingTime: '10_minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'Your magic and an offering put you in contact with a god or a god\'s servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days. The DM offers a truthful reply—a short phrase, a cryptic rhyme, or an omen.',
    classes: ['cleric'],
    iconName: 'BookOpen',
    personalityQuips: {
      thunderhead: 'The gods answer those who ask with reverence. Listen well.',
      jarvis: 'Divine communication channel open. Response incoming.',
      deadpool: 'Dear God, should I invest in crypto? ...That\'s not how this works.',
    },
  },
  {
    id: 'locate-creature',
    name: 'Locate Creature',
    level: 4,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a bit of fur from a bloodhound' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Describe or name a creature familiar to you. You sense the direction to the creature\'s location, as long as it is within 1,000 feet. If the creature is moving, you know the direction of its movement. Running water blocks this spell.',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'MapPin',
    personalityQuips: {
      thunderhead: 'No creature hides from divine sight. The hunt begins.',
      jarvis: 'Biological tracking system online. Target direction acquired.',
      deadpool: 'CREATURE GPS! Marco! ...POLO! Found you!',
    },
  },
  {
    id: 'stone-shape',
    name: 'Stone Shape',
    level: 4,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'soft clay, which must be worked into roughly the desired shape' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose. You could shape a stone weapon, make a small passage through a wall, or seal a stone door shut.',
    classes: ['cleric', 'druid', 'wizard'],
    iconName: 'Box',
    personalityQuips: {
      thunderhead: 'Stone yields to the divine touch. Shape it as you will.',
      jarvis: 'Geological restructuring complete. Stone reformed to specification.',
      deadpool: 'MINECRAFT but in real life! Stone goes brrrrr into... a key! Or a wall! Or a tiny horse!',
    },
  },

  // ============================================
  // 5TH LEVEL SPELLS
  // ============================================
  {
    id: 'mass-cure-wounds',
    name: 'Mass Cure Wounds',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A wave of healing energy washes out. Choose up to 6 creatures in a 30-foot-radius sphere. Each target regains 3d8 + spellcasting modifier HP.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 5th.',
    healingFormula: '3d8+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Healing for everyone! The gods\' mercy washes over all.',
      jarvis: 'Mass healing surge complete. All targets restored.',
      deadpool: 'HEALING RAIN FROM ABOVE! Catch it in your mouth!',
    },
  },
  {
    id: 'flame-strike',
    name: 'Flame Strike',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of sulfur' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A vertical column of divine fire roars down (10-foot radius, 40 feet high). Creatures in the area must make DEX save or take 4d6 fire + 4d6 radiant damage, half on success.',
    higherLevels: 'Fire or radiant damage (your choice) increases by 1d6 for each slot level above 5th.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '4d6+4d6',
    classes: ['cleric'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Divine fire rains from above! Heaven\'s wrath made manifest.',
      jarvis: 'Celestial napalm strike initiated. Impact zone: designated.',
      deadpool: 'HOLY FIRE COLUMN! It\'s like a divine air strike! INCOMING!',
    },
  },
  {
    id: 'greater-restoration',
    name: 'Greater Restoration',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamond dust worth at least 100 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You imbue a creature with positive energy to undo a debilitating effect. Reduce exhaustion by 1 level, or end one of: charmed, petrified, a curse, any ability score reduction, or HP maximum reduction.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Sparkles',
    personalityQuips: {
      thunderhead: 'Be restored to full glory. Even the worst afflictions fade.',
      jarvis: 'Maximum restoration protocol complete. All debuffs purged.',
      deadpool: 'ULTIMATE CLEANSE! You\'re now shiny and new!',
    },
  },
  {
    id: 'raise-dead',
    name: 'Raise Dead',
    level: 5,
    school: 'necromancy',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a diamond worth at least 500 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Return a dead creature to life (died within 10 days). It returns with 1 HP. Cannot restore missing body parts. Target takes -4 penalty to attack rolls, saves, and ability checks; penalty reduces by 1 after each long rest.',
    healingFormula: '1',
    classes: ['cleric', 'bard'],
    iconName: 'RotateCcw',
    personalityQuips: {
      thunderhead: 'Rise from death\'s embrace. The gods grant a second chance.',
      jarvis: 'Full resurrection protocol complete. Side effects expected.',
      deadpool: '500 gold to cheat death! Bargain bin resurrection!',
    },
  },
  {
    id: 'holy-weapon',
    name: 'Holy Weapon',
    level: 5,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Imbue a weapon with holy power. It deals an extra 2d8 radiant damage on hit and emits bright light in 30 feet. You can dismiss as bonus action for 4d8 radiant damage burst (30-foot radius, CON save for half) and targets are blinded.',
    damageType: 'radiant',
    damageFormula: '2d8',
    classes: ['cleric'],
    iconName: 'Sword',
    personalityQuips: {
      thunderhead: 'This blade blazes with divine fury. Strike true.',
      jarvis: 'Holy weapon enchantment active. Radiant damage module online.',
      deadpool: 'LIGHTSABER! ...I mean, HOLYSABER! May the gods be with you!',
    },
  },
  {
    id: 'dispel-evil-and-good',
    name: 'Dispel Evil and Good',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Shimmering energy surrounds you. Celestials, elementals, fey, fiends, and undead have disadvantage on attacks against you. You can end the spell to break enchantment, dismiss creature, or end possession.',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'Otherworldly beings fear my presence. Begone!',
      jarvis: 'Anti-planar defense matrix active. Hostile entities repelled.',
      deadpool: 'I\'m toxic to supernatural beings! Finally, a superpower!',
    },
  },

  // --- MISSING 5TH LEVEL ---
  {
    id: 'commune',
    name: 'Commune',
    level: 5,
    school: 'divination',
    castingTime: '1_minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'incense and a vial of holy or unholy water' },
    duration: '1 minute',
    concentration: false,
    ritual: true,
    description: 'You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no. You receive a correct answer for each question. Divine beings aren\'t necessarily omniscient, so you might receive "unclear" as an answer.',
    classes: ['cleric'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Speak to the heavens. Three questions—choose wisely.',
      jarvis: 'Divine hotline connected. Three binary queries authorized.',
      deadpool: 'Dear God: 1) Am I awesome? 2) Are tacos divine? 3) ...Right?',
    },
  },
  {
    id: 'contagion',
    name: 'Contagion',
    level: 5,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '7 days',
    concentration: false,
    ritual: false,
    description: 'Your touch inflicts disease. Make a melee spell attack. On hit, you afflict the creature with a disease of your choice: Blinding Sickness, Filth Fever, Flesh Rot, Mindfire, Seizure, or Slimy Doom. The target must make CON saves at the end of each of its turns. After 3 failures, the disease lasts for 7 days. After 3 successes, it recovers.',
    attackType: 'melee',
    saveStat: 'CON',
    classes: ['cleric', 'druid'],
    iconName: 'Bug',
    personalityQuips: {
      thunderhead: 'Plague follows the unrighteous. Suffer the divine pestilence.',
      jarvis: 'Pathogenic transfer complete. Disease vector established.',
      deadpool: 'COOTIES! Except way worse! Choose your plague flavor!',
    },
  },
  {
    id: 'geas',
    name: 'Geas',
    level: 5,
    school: 'enchantment',
    castingTime: '1_minute',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: '30 days',
    concentration: false,
    ritual: false,
    description: 'You place a magical command on a creature that you can see. It must succeed on a WIS save or become charmed for the duration. While charmed, it takes 5d10 psychic damage each time it acts in a manner contrary to your instructions.',
    higherLevels: 'At 7th level: 1 year. At 9th level: until dispelled.',
    saveStat: 'WIS',
    damageType: 'psychic',
    damageFormula: '5d10',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'Crown',
    personalityQuips: {
      thunderhead: 'You are bound by sacred oath. Disobey and suffer.',
      jarvis: 'Compulsion protocol installed. Compliance enforced for 30 days.',
      deadpool: 'You WILL do my bidding! Or your brain goes ZAP! Fun times!',
    },
  },
  {
    id: 'hallow',
    name: 'Hallow',
    level: 5,
    school: 'evocation',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'herbs, oils, and incense worth at least 1,000 gp, which the spell consumes' },
    duration: 'Until dispelled',
    concentration: false,
    ritual: false,
    description: 'You touch a point and infuse an area around it with holy (or unholy) power. The area can have a radius up to 60 feet. Celestials, elementals, fey, fiends, and undead can\'t enter the area, and such creatures can\'t charm, frighten, or possess creatures within. You can bind an extra effect: Courage, Darkness, Daylight, Energy Protection, Energy Vulnerability, Everlasting Rest, Extradimensional Interference, Fear, Silence, or Tongues.',
    classes: ['cleric'],
    iconName: 'Church',
    personalityQuips: {
      thunderhead: 'This ground is consecrated. Evil shall not tread here.',
      jarvis: 'Area sanctification complete. Divine protection permanent.',
      deadpool: 'HOLY GROUND! Like in Highlander! There can be only one!',
    },
  },
  {
    id: 'insect-plague',
    name: 'Insect Plague',
    level: 5,
    school: 'conjuration',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a few grains of sugar, some kernels of grain, and a smear of fat' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose. The sphere spreads around corners. The sphere\'s space is lightly obscured and difficult terrain. When a creature enters the area or starts its turn there, it must make a CON save, taking 4d10 piercing damage on a failed save, or half on success.',
    higherLevels: 'Damage increases by 1d10 for each slot level above 5th.',
    saveStat: 'CON',
    damageType: 'piercing',
    damageFormula: '4d10',
    classes: ['cleric', 'druid', 'sorcerer'],
    iconName: 'Bug',
    personalityQuips: {
      thunderhead: 'A plague of locusts descends! Biblical wrath unleashed!',
      jarvis: 'Entomological weapon deployed. Swarm density: maximum.',
      deadpool: 'BEEEES! Well, locusts. But the screaming is the same!',
    },
  },
  {
    id: 'legend-lore',
    name: 'Legend Lore',
    level: 5,
    school: 'divination',
    castingTime: '10_minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Name or describe a person, place, or object. The spell brings to your mind a brief summary of the significant lore about the thing you named. The lore might consist of current tales, forgotten stories, or even secret lore that has never been widely known.',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'BookOpen',
    personalityQuips: {
      thunderhead: 'Ancient knowledge flows to the faithful. The legends speak.',
      jarvis: 'Historical database queried. Lore compilation complete.',
      deadpool: 'WIKIPEDIA but MAGICAL! Let me tell you about this sword...',
    },
  },
  {
    id: 'planar-binding',
    name: 'Planar Binding',
    level: 5,
    school: 'abjuration',
    castingTime: '1_minute',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a jewel worth at least 1,000 gp, which the spell consumes' },
    duration: '24 hours',
    concentration: false,
    ritual: false,
    description: 'You attempt to bind a celestial, an elemental, a fey, or a fiend to your service. The creature must be within range for the entire casting. It must make a CHA save. On a failure, it is bound to serve you for the duration. It must follow your instructions to the best of its ability.',
    higherLevels: 'At 6th level: 10 days. At 7th: 30 days. At 8th: 180 days. At 9th: a year and a day.',
    saveStat: 'CHA',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'Link',
    personalityQuips: {
      thunderhead: 'You are bound to divine service. Resist not.',
      jarvis: 'Extraplanar entity contract established. Service term: 24 hours.',
      deadpool: 'GENIE IN A BOTTLE! Except it\'s a demon! And there are no wishes!',
    },
  },
  {
    id: 'scrying',
    name: 'Scrying',
    level: 5,
    school: 'divination',
    castingTime: '10_minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You can see and hear a particular creature you choose that is on the same plane of existence. The target must make a WIS save (modified by how well you know the target and any physical connection you have). On failure, you can see and hear the target and its immediate surroundings.',
    saveStat: 'WIS',
    classes: ['cleric', 'bard', 'druid', 'warlock', 'wizard'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'The all-seeing eye opens. No plane can hide from divine sight.',
      jarvis: 'Remote viewing protocol active. Target surveillance established.',
      deadpool: 'CREEPY CRYSTAL BALL TIME! Let\'s see what Karen is up to!',
    },
  },
];
