// Cleric Spell List — D&D 5e PHB Complete (3rd–5th Level)
// Split from cleric-spells.ts for build performance

import { SpellDefinition } from '../types';

export const CLERIC_SPELLS_HIGHER: SpellDefinition[] = [
  // ============================================
  // 3RD LEVEL SPELLS
  // ============================================
  {
    id: 'spirit-guardians',
    name: 'Spirit Guardians',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: 'Self (15-foot radius)',
    components: { verbal: true, somatic: true, material: 'a holy symbol' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Spirits surround you in a 15-foot radius. Creatures of your choice entering the area or starting their turn there must make WIS save. 3d8 radiant (good/neutral) or necrotic (evil) damage on failure, half on success.',
    higherLevels: 'Damage increases by 1d8 for each slot level above 3rd.',
    saveStat: 'WIS',
    damageType: 'radiant',
    damageFormula: '3d8',
    classes: ['cleric'],
    iconName: 'Users',
    personalityQuips: {
      thunderhead: 'The faithful dead fight on. Come closer if you dare.',
      jarvis: 'Spiritual defense perimeter established. Area denial active.',
      deadpool: 'I\'ve got GHOST FRIENDS! They\'re very protective!',
    },
  },
  {
    id: 'revivify',
    name: 'Revivify',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamonds worth 300 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a creature that died within the last minute. It returns to life with 1 HP. Cannot restore missing body parts or creatures that died of old age.',
    healingFormula: '1',
    classes: ['cleric', 'druid'],
    iconName: 'RotateCcw',
    personalityQuips: {
      thunderhead: 'Return to us—your time has not yet come.',
      jarvis: 'Revival protocol initiated. Vital signs reestablishing.',
      deadpool: 'CLEAR! *zap* Welcome back! That\'ll be 300 gold!',
    },
  },
  {
    id: 'beacon-of-hope',
    name: 'Beacon of Hope',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose any number of creatures within range. They have advantage on WIS saves and death saving throws, and regain the maximum HP possible from healing.',
    classes: ['cleric'],
    iconName: 'Sunrise',
    personalityQuips: {
      thunderhead: 'Hope blazes brightest in darkness. Be healed fully.',
      jarvis: 'Hope amplification active. Maximum healing efficiency achieved.',
      deadpool: 'MAXIMUM HEALING! It\'s like a spa day but with less cucumber!',
    },
  },
  {
    id: 'dispel-magic-cleric',
    name: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose a creature, object, or magical effect. Any spell of 3rd level or lower ends. For higher-level spells, make an ability check (DC 10 + spell level).',
    higherLevels: 'Automatically end spells of the slot level used or lower.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'XCircle',
    personalityQuips: {
      thunderhead: 'Your magic ends here. Divine will unravels the arcane.',
      jarvis: 'Magical negation field deployed. Spell integrity compromised.',
      deadpool: 'CTRL+Z! UNDO! Your magic is now canceled!',
    },
  },
  {
    id: 'mass-healing-word',
    name: 'Mass Healing Word',
    level: 3,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Up to 6 creatures of your choice that you can see regain 1d4 + spellcasting modifier HP each.',
    higherLevels: 'Healing increases by 1d4 for each slot level above 3rd.',
    healingFormula: '1d4+mod',
    classes: ['cleric', 'bard'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Rise, all of you! The prayer reaches many.',
      jarvis: 'Mass healing broadcast initiated. Multiple patients responding.',
      deadpool: 'EVERYBODY GETS UP! No dying on my watch!',
    },
  },
  {
    id: 'remove-curse',
    name: 'Remove Curse',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'At your touch, all curses affecting one creature or object end. If the object is a cursed magic item, its curse remains but breaks the owner\'s attunement.',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Eraser',
    personalityQuips: {
      thunderhead: 'Curses break before divine will. Be free.',
      jarvis: 'Curse removal protocol successful. Magical binding severed.',
      deadpool: 'CURSE BE GONE! *throws holy water* Wait, was that my coffee?',
    },
  },

  // --- MISSING 3RD LEVEL ---
  {
    id: 'animate-dead',
    name: 'Animate Dead',
    level: 3,
    school: 'necromancy',
    castingTime: '1_minute',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'a drop of blood, a piece of flesh, and a pinch of bone dust' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid. Your spell imbues it with a foul mimicry of life, raising it as a skeleton or zombie. It obeys your verbal commands and acts on your turn in combat.',
    higherLevels: 'You reassert control over two additional undead creatures for each slot level above 3rd.',
    classes: ['cleric', 'wizard'],
    iconName: 'Skull',
    personalityQuips: {
      thunderhead: 'The dead rise at divine command. They serve, willingly or not.',
      jarvis: 'Necromantic reanimation complete. Undead unit online.',
      deadpool: 'ARISE MY MINION! ...Do you do windows?',
    },
  },
  {
    id: 'bestow-curse',
    name: 'Bestow Curse',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You touch a creature, and it must succeed on a WIS save or become cursed. Choose one curse effect: disadvantage on checks/saves with one ability score, disadvantage on attacks against you, WIS save each turn or waste action, or your attacks deal extra 1d8 necrotic.',
    higherLevels: 'At 4th level: concentration up to 10 minutes. At 5th: 8 hours without concentration. At 7th: 24 hours. At 9th: permanent until dispelled.',
    saveStat: 'WIS',
    damageType: 'necrotic',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'CloudLightning',
    personalityQuips: {
      thunderhead: 'A divine curse falls upon you. Suffer for your transgressions.',
      jarvis: 'Curse application successful. Target performance degraded.',
      deadpool: 'CURSED! Like that one email chain you didn\'t forward!',
    },
  },
  {
    id: 'clairvoyance',
    name: 'Clairvoyance',
    level: 3,
    school: 'divination',
    castingTime: '10_minutes',
    range: '1 mile',
    components: { verbal: true, somatic: true, material: 'a focus worth at least 100 gp, either a jeweled horn for hearing or a glass eye for seeing' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You create an invisible sensor within range at a location familiar to you or an obvious one. You can see or hear (your choice) through the sensor as if you were there.',
    classes: ['cleric', 'bard', 'sorcerer', 'wizard'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'The faithful see beyond walls and distance. Observe.',
      jarvis: 'Remote sensory node deployed. Audio/visual feed established.',
      deadpool: 'SPY CAM! Invisible spy cam! I feel like James Bond!',
    },
  },
  {
    id: 'create-food-and-water',
    name: 'Create Food and Water',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You create 45 pounds of food and 30 gallons of water on the ground or in containers. The food is bland but nourishing and spoils after 24 hours if uneaten. The water is clean and doesn\'t go bad.',
    classes: ['cleric'],
    iconName: 'Apple',
    personalityQuips: {
      thunderhead: 'The gods provide for their flock. Eat and drink.',
      jarvis: 'Sustenance materialization complete. Caloric needs met.',
      deadpool: 'DIVINE DOORDASH! 45 pounds of mystery meat! Bon appétit!',
    },
  },
  {
    id: 'daylight',
    name: 'Daylight',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'A 60-foot-radius sphere of light spreads out from a point you choose. The sphere is bright light and sheds dim light for an additional 60 feet. If any of this spell\'s area overlaps with darkness created by a 3rd level spell or lower, the darkness is dispelled.',
    classes: ['cleric', 'druid', 'sorcerer'],
    iconName: 'Sun',
    personalityQuips: {
      thunderhead: 'Let there be LIGHT! Darkness has no dominion here.',
      jarvis: 'Maximum illumination sphere deployed. Magical darkness countered.',
      deadpool: 'SUNRISE IN A CAN! Vampires hate this one weird trick!',
    },
  },
  {
    id: 'feign-death',
    name: 'Feign Death',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pinch of graveyard dirt' },
    duration: '1 hour',
    concentration: false,
    ritual: true,
    description: 'You touch a willing creature and put it into a cataleptic state that is indistinguishable from death. The target appears dead to all outward inspection and to spells used to determine the target\'s status. It is blinded, incapacitated, resistant to all damage except psychic, and diseases and poisons are suspended.',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'Skull',
    personalityQuips: {
      thunderhead: 'Play dead. Even death\'s gaze shall be fooled.',
      jarvis: 'Metabolic suppression complete. Vital signs: undetectable.',
      deadpool: 'Playing possum! Oscar-worthy performance! *fake dies dramatically*',
    },
  },
  {
    id: 'glyph-of-warding',
    name: 'Glyph of Warding',
    level: 3,
    school: 'abjuration',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'incense and powdered diamond worth at least 200 gp, which the spell consumes' },
    duration: 'Until dispelled or triggered',
    concentration: false,
    ritual: false,
    description: 'Inscribe a glyph on a surface or within an object. Choose Explosive Runes (5d8 acid/cold/fire/lightning/thunder damage, DEX save for half) or Spell Glyph (store a spell of 3rd level or lower cast on the triggering creature).',
    higherLevels: 'Explosive runes damage increases by 1d8 for each slot level above 3rd. Spell glyph can store a spell up to the same level.',
    saveStat: 'DEX',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'Pen',
    personalityQuips: {
      thunderhead: 'A divine ward is inscribed. Trespassers beware.',
      jarvis: 'Proximity-triggered defensive glyph inscribed. Armed and ready.',
      deadpool: 'MAGICAL LANDMINE! Step here and KABOOM! Or get spell\'d!',
    },
  },
  {
    id: 'magic-circle',
    name: 'Magic Circle',
    level: 3,
    school: 'abjuration',
    castingTime: '1_minute',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron worth at least 100 gp, which the spell consumes' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'Create a 10-foot-radius, 20-foot-tall cylinder of magical energy. Choose one or more: celestials, elementals, fey, fiends, or undead. The chosen type can\'t willingly enter the cylinder, has disadvantage on attacks against targets within, and can\'t charm, frighten, or possess those inside.',
    higherLevels: 'Duration increases by 1 hour for each slot level above 3rd.',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Circle',
    personalityQuips: {
      thunderhead: 'The circle is drawn. Nothing crosses this sacred boundary.',
      jarvis: 'Planar containment field established. Entity exclusion active.',
      deadpool: 'Stay in your circle! Like a divine time-out corner!',
    },
  },
  {
    id: 'meld-into-stone',
    name: 'Meld into Stone',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: true,
    description: 'You step into a stone object or surface large enough to fully contain your body, melding yourself and all the equipment you carry with the stone for the duration. You can cast no spells while merged. Minor physical damage to the stone doesn\'t harm you, but partial destruction or a change in shape ejects you and deals 6d6 bludgeoning damage.',
    classes: ['cleric', 'druid'],
    iconName: 'Mountain',
    personalityQuips: {
      thunderhead: 'Become one with the earth. The stone shelters the faithful.',
      jarvis: 'Molecular integration with stone matrix complete. Concealment: total.',
      deadpool: 'I AM ONE WITH THE ROCK! Not Dwayne Johnson, the actual rock!',
    },
  },
  {
    id: 'protection-from-energy',
    name: 'Protection from Energy',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'For the duration, the willing creature you touch has resistance to one damage type of your choice: acid, cold, fire, lightning, or thunder.',
    classes: ['cleric', 'druid', 'sorcerer', 'wizard'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'The elements hold no power over the protected.',
      jarvis: 'Elemental resistance shield active. Damage type selected.',
      deadpool: 'FIREPROOF! Or ice-proof! Or lightning-proof! Pick your flavor!',
    },
  },
  {
    id: 'sending',
    name: 'Sending',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: 'Unlimited',
    components: { verbal: true, somatic: true, material: 'a short piece of fine copper wire' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You send a short message of twenty-five words or less to a creature with which you are familiar. The creature hears the message in its mind, recognizes you as the sender, and can answer in a like manner immediately.',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'Send',
    personalityQuips: {
      thunderhead: 'Distance means nothing to the divine word. It shall be heard.',
      jarvis: 'Cross-dimensional communication link established. Message sent.',
      deadpool: 'DIVINE TEXTING! 25 words or less! Like Twitter but magical!',
    },
  },
  {
    id: 'speak-with-dead',
    name: 'Speak with Dead',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: 'burning incense' },
    duration: '10 minutes',
    concentration: false,
    ritual: false,
    description: 'You grant the semblance of life and intelligence to a corpse, allowing it to answer up to five questions. The corpse knows only what it knew in life and speaks in languages it knew. Answers are usually brief, cryptic, or repetitive.',
    classes: ['cleric', 'bard'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'The dead remember. Ask, and they shall answer.',
      jarvis: 'Posthumous communication interface active. Five queries remaining.',
      deadpool: 'HEY DEAD GUY! Got any hot gossip from the afterlife?',
    },
  },
  {
    id: 'tongues',
    name: 'Tongues',
    level: 3,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a small clay model of a ziggurat' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'This spell grants the creature you touch the ability to understand any spoken language it hears. Moreover, when the target speaks, any creature that knows at least one language and can hear the target understands what it says.',
    classes: ['cleric', 'bard', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'Languages',
    personalityQuips: {
      thunderhead: 'All tongues are one before the divine. Speak and be understood.',
      jarvis: 'Universal translation module active. All languages accessible.',
      deadpool: 'BABEL FISH SPELL! Now I can trash-talk in EVERY language!',
    },
  },
  {
    id: 'water-walk',
    name: 'Water Walk',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a piece of cork' },
    duration: '1 hour',
    concentration: false,
    ritual: true,
    description: 'This spell grants the ability to move across any liquid surface—such as water, acid, mud, snow, quicksand, or lava—as if it were harmless solid ground. Up to ten willing creatures you can see within range gain this ability for the duration.',
    classes: ['cleric', 'druid', 'sorcerer'],
    iconName: 'Waves',
    personalityQuips: {
      thunderhead: 'Walk upon the waters. The faithful need not fear the deep.',
      jarvis: 'Surface tension override active. Liquid traversal enabled.',
      deadpool: 'JESUS MODE ACTIVATED! Walking on water like a BOSS!',
    },
  },

  // ============================================
  // 4TH LEVEL SPELLS
  // ============================================
  {
    id: 'death-ward',
    name: 'Death Ward',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'Touch a creature. The first time it would drop to 0 HP, it drops to 1 HP instead. If subjected to an effect that would kill it instantly without dealing damage, that effect is negated.',
    classes: ['cleric'],
    iconName: 'ShieldCheck',
    personalityQuips: {
      thunderhead: 'Death shall not claim you yet. One chance remains.',
      jarvis: 'Anti-death protocol installed. Emergency revival armed.',
      deadpool: 'FREE EXTRA LIFE! Like a video game power-up! 1-UP!',
    },
  },
  {
    id: 'guardian-of-faith',
    name: 'Guardian of Faith',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'A Large spectral guardian appears. When a hostile creature moves within 10 feet for the first time or starts its turn there, it must make DEX save or take 20 radiant damage (half on success). Guardian vanishes after dealing 60 total damage.',
    saveStat: 'DEX',
    damageType: 'radiant',
    damageFormula: '20',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'An angel stands watch. Pass at your own peril.',
      jarvis: 'Divine sentry deployed. Area denial damage: significant.',
      deadpool: 'Security guard from heaven! Tips not accepted!',
    },
  },
  {
    id: 'banishment-cleric',
    name: 'Banishment',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'an item distasteful to the target' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Attempt to send a creature to another plane. CHA save or be banished. If native to current plane, creature goes to a harmless demiplane; otherwise, it returns to its home plane.',
    higherLevels: 'You can target one additional creature for each slot level above 4th.',
    saveStat: 'CHA',
    classes: ['cleric', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'LogOut',
    personalityQuips: {
      thunderhead: 'Return from whence you came! This plane rejects you.',
      jarvis: 'Planar ejection initiated. Target relocated to origin dimension.',
      deadpool: 'YEET! To another dimension you go! Byeeeee!',
    },
  },
  {
    id: 'freedom-of-movement',
    name: 'Freedom of Movement',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a leather strap' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'Touch a willing creature. Its movement is unaffected by difficult terrain, spells that reduce speed, or paralysis/restraint. It can spend 5 feet of movement to escape nonmagical restraints or grapples.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Move',
    personalityQuips: {
      thunderhead: 'No bonds can hold the faithful. Move freely.',
      jarvis: 'Movement restriction immunity active. Mobility unrestricted.',
      deadpool: 'PARKOUR! Nothing can hold you back now! FREEBIRD!',
    },
  },

  // --- MISSING 4TH LEVEL ---
  {
    id: 'control-water',
    name: 'Control Water',
    level: 4,
    school: 'transmutation',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a drop of water and a pinch of dust' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Until the spell ends, you control any freestanding water inside an area you choose (up to 100 feet on a side). Choose one of: Flood (raise water level up to 20 feet), Part Water (trench through the area), Redirect Flow (change direction of flowing water), or Whirlpool (vortex, 5-foot deep, STR save or 2d8 bludgeoning damage).',
    saveStat: 'STR',
    damageType: 'bludgeoning',
    damageFormula: '2d8',
    classes: ['cleric', 'druid', 'wizard'],
    iconName: 'Waves',
    personalityQuips: {
      thunderhead: 'The waters bend to divine will. Rise, part, or rage!',
      jarvis: 'Hydraulic manipulation system active. Water flow redirected.',
      deadpool: 'MOSES MODE! Part those seas! Or make a whirlpool! Your call!',
    },
  },
  {
    id: 'divination-spell',
    name: 'Divination',
    level: 4,
    school: 'divination',
    castingTime: '10_minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'Your magic and an offering put you in contact with a god or a god\'s servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days. The DM offers a truthful reply—a short phrase, a cryptic rhyme, or an omen.',
    classes: ['cleric'],
    iconName: 'BookOpen',
    personalityQuips: {
      thunderhead: 'The gods answer those who ask with reverence. Listen well.',
      jarvis: 'Divine communication channel open. Response incoming.',
      deadpool: 'Dear God, should I invest in crypto? ...That\'s not how this works.',
    },
  },
  {
    id: 'locate-creature',
    name: 'Locate Creature',
    level: 4,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a bit of fur from a bloodhound' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Describe or name a creature familiar to you. You sense the direction to the creature\'s location, as long as it is within 1,000 feet. If the creature is moving, you know the direction of its movement. Running water blocks this spell.',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'MapPin',
    personalityQuips: {
      thunderhead: 'No creature hides from divine sight. The hunt begins.',
      jarvis: 'Biological tracking system online. Target direction acquired.',
      deadpool: 'CREATURE GPS! Marco! ...POLO! Found you!',
    },
  },
  {
    id: 'stone-shape',
    name: 'Stone Shape',
    level: 4,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'soft clay, which must be worked into roughly the desired shape' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose. You could shape a stone weapon, make a small passage through a wall, or seal a stone door shut.',
    classes: ['cleric', 'druid', 'wizard'],
    iconName: 'Box',
    personalityQuips: {
      thunderhead: 'Stone yields to the divine touch. Shape it as you will.',
      jarvis: 'Geological restructuring complete. Stone reformed to specification.',
      deadpool: 'MINECRAFT but in real life! Stone goes brrrrr into... a key! Or a wall! Or a tiny horse!',
    },
  },

  // ============================================
  // 5TH LEVEL SPELLS
  // ============================================
  {
    id: 'mass-cure-wounds',
    name: 'Mass Cure Wounds',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A wave of healing energy washes out. Choose up to 6 creatures in a 30-foot-radius sphere. Each target regains 3d8 + spellcasting modifier HP.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 5th.',
    healingFormula: '3d8+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Healing for everyone! The gods\' mercy washes over all.',
      jarvis: 'Mass healing surge complete. All targets restored.',
      deadpool: 'HEALING RAIN FROM ABOVE! Catch it in your mouth!',
    },
  },
  {
    id: 'flame-strike',
    name: 'Flame Strike',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of sulfur' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A vertical column of divine fire roars down (10-foot radius, 40 feet high). Creatures in the area must make DEX save or take 4d6 fire + 4d6 radiant damage, half on success.',
    higherLevels: 'Fire or radiant damage (your choice) increases by 1d6 for each slot level above 5th.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '4d6+4d6',
    classes: ['cleric'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Divine fire rains from above! Heaven\'s wrath made manifest.',
      jarvis: 'Celestial napalm strike initiated. Impact zone: designated.',
      deadpool: 'HOLY FIRE COLUMN! It\'s like a divine air strike! INCOMING!',
    },
  },
  {
    id: 'greater-restoration',
    name: 'Greater Restoration',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamond dust worth at least 100 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You imbue a creature with positive energy to undo a debilitating effect. Reduce exhaustion by 1 level, or end one of: charmed, petrified, a curse, any ability score reduction, or HP maximum reduction.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Sparkles',
    personalityQuips: {
      thunderhead: 'Be restored to full glory. Even the worst afflictions fade.',
      jarvis: 'Maximum restoration protocol complete. All debuffs purged.',
      deadpool: 'ULTIMATE CLEANSE! You\'re now shiny and new!',
    },
  },
  {
    id: 'raise-dead',
    name: 'Raise Dead',
    level: 5,
    school: 'necromancy',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a diamond worth at least 500 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Return a dead creature to life (died within 10 days). It returns with 1 HP. Cannot restore missing body parts. Target takes -4 penalty to attack rolls, saves, and ability checks; penalty reduces by 1 after each long rest.',
    healingFormula: '1',
    classes: ['cleric', 'bard'],
    iconName: 'RotateCcw',
    personalityQuips: {
      thunderhead: 'Rise from death\'s embrace. The gods grant a second chance.',
      jarvis: 'Full resurrection protocol complete. Side effects expected.',
      deadpool: '500 gold to cheat death! Bargain bin resurrection!',
    },
  },
  {
    id: 'holy-weapon',
    name: 'Holy Weapon',
    level: 5,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Imbue a weapon with holy power. It deals an extra 2d8 radiant damage on hit and emits bright light in 30 feet. You can dismiss as bonus action for 4d8 radiant damage burst (30-foot radius, CON save for half) and targets are blinded.',
    damageType: 'radiant',
    damageFormula: '2d8',
    classes: ['cleric'],
    iconName: 'Sword',
    personalityQuips: {
      thunderhead: 'This blade blazes with divine fury. Strike true.',
      jarvis: 'Holy weapon enchantment active. Radiant damage module online.',
      deadpool: 'LIGHTSABER! ...I mean, HOLYSABER! May the gods be with you!',
    },
  },
  {
    id: 'dispel-evil-and-good',
    name: 'Dispel Evil and Good',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Shimmering energy surrounds you. Celestials, elementals, fey, fiends, and undead have disadvantage on attacks against you. You can end the spell to break enchantment, dismiss creature, or end possession.',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'Otherworldly beings fear my presence. Begone!',
      jarvis: 'Anti-planar defense matrix active. Hostile entities repelled.',
      deadpool: 'I\'m toxic to supernatural beings! Finally, a superpower!',
    },
  },

  // --- MISSING 5TH LEVEL ---
  {
    id: 'commune',
    name: 'Commune',
    level: 5,
    school: 'divination',
    castingTime: '1_minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'incense and a vial of holy or unholy water' },
    duration: '1 minute',
    concentration: false,
    ritual: true,
    description: 'You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no. You receive a correct answer for each question. Divine beings aren\'t necessarily omniscient, so you might receive "unclear" as an answer.',
    classes: ['cleric'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Speak to the heavens. Three questions—choose wisely.',
      jarvis: 'Divine hotline connected. Three binary queries authorized.',
      deadpool: 'Dear God: 1) Am I awesome? 2) Are tacos divine? 3) ...Right?',
    },
  },
  {
    id: 'contagion',
    name: 'Contagion',
    level: 5,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '7 days',
    concentration: false,
    ritual: false,
    description: 'Your touch inflicts disease. Make a melee spell attack. On hit, you afflict the creature with a disease of your choice: Blinding Sickness, Filth Fever, Flesh Rot, Mindfire, Seizure, or Slimy Doom. The target must make CON saves at the end of each of its turns. After 3 failures, the disease lasts for 7 days. After 3 successes, it recovers.',
    attackType: 'melee',
    saveStat: 'CON',
    classes: ['cleric', 'druid'],
    iconName: 'Bug',
    personalityQuips: {
      thunderhead: 'Plague follows the unrighteous. Suffer the divine pestilence.',
      jarvis: 'Pathogenic transfer complete. Disease vector established.',
      deadpool: 'COOTIES! Except way worse! Choose your plague flavor!',
    },
  },
  {
    id: 'geas',
    name: 'Geas',
    level: 5,
    school: 'enchantment',
    castingTime: '1_minute',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: '30 days',
    concentration: false,
    ritual: false,
    description: 'You place a magical command on a creature that you can see. It must succeed on a WIS save or become charmed for the duration. While charmed, it takes 5d10 psychic damage each time it acts in a manner contrary to your instructions.',
    higherLevels: 'At 7th level: 1 year. At 9th level: until dispelled.',
    saveStat: 'WIS',
    damageType: 'psychic',
    damageFormula: '5d10',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'Crown',
    personalityQuips: {
      thunderhead: 'You are bound by sacred oath. Disobey and suffer.',
      jarvis: 'Compulsion protocol installed. Compliance enforced for 30 days.',
      deadpool: 'You WILL do my bidding! Or your brain goes ZAP! Fun times!',
    },
  },
  {
    id: 'hallow',
    name: 'Hallow',
    level: 5,
    school: 'evocation',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'herbs, oils, and incense worth at least 1,000 gp, which the spell consumes' },
    duration: 'Until dispelled',
    concentration: false,
    ritual: false,
    description: 'You touch a point and infuse an area around it with holy (or unholy) power. The area can have a radius up to 60 feet. Celestials, elementals, fey, fiends, and undead can\'t enter the area, and such creatures can\'t charm, frighten, or possess creatures within. You can bind an extra effect: Courage, Darkness, Daylight, Energy Protection, Energy Vulnerability, Everlasting Rest, Extradimensional Interference, Fear, Silence, or Tongues.',
    classes: ['cleric'],
    iconName: 'Church',
    personalityQuips: {
      thunderhead: 'This ground is consecrated. Evil shall not tread here.',
      jarvis: 'Area sanctification complete. Divine protection permanent.',
      deadpool: 'HOLY GROUND! Like in Highlander! There can be only one!',
    },
  },
  {
    id: 'insect-plague',
    name: 'Insect Plague',
    level: 5,
    school: 'conjuration',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a few grains of sugar, some kernels of grain, and a smear of fat' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose. The sphere spreads around corners. The sphere\'s space is lightly obscured and difficult terrain. When a creature enters the area or starts its turn there, it must make a CON save, taking 4d10 piercing damage on a failed save, or half on success.',
    higherLevels: 'Damage increases by 1d10 for each slot level above 5th.',
    saveStat: 'CON',
    damageType: 'piercing',
    damageFormula: '4d10',
    classes: ['cleric', 'druid', 'sorcerer'],
    iconName: 'Bug',
    personalityQuips: {
      thunderhead: 'A plague of locusts descends! Biblical wrath unleashed!',
      jarvis: 'Entomological weapon deployed. Swarm density: maximum.',
      deadpool: 'BEEEES! Well, locusts. But the screaming is the same!',
    },
  },
  {
    id: 'legend-lore',
    name: 'Legend Lore',
    level: 5,
    school: 'divination',
    castingTime: '10_minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Name or describe a person, place, or object. The spell brings to your mind a brief summary of the significant lore about the thing you named. The lore might consist of current tales, forgotten stories, or even secret lore that has never been widely known.',
    classes: ['cleric', 'bard', 'wizard'],
    iconName: 'BookOpen',
    personalityQuips: {
      thunderhead: 'Ancient knowledge flows to the faithful. The legends speak.',
      jarvis: 'Historical database queried. Lore compilation complete.',
      deadpool: 'WIKIPEDIA but MAGICAL! Let me tell you about this sword...',
    },
  },
  {
    id: 'planar-binding',
    name: 'Planar Binding',
    level: 5,
    school: 'abjuration',
    castingTime: '1_minute',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a jewel worth at least 1,000 gp, which the spell consumes' },
    duration: '24 hours',
    concentration: false,
    ritual: false,
    description: 'You attempt to bind a celestial, an elemental, a fey, or a fiend to your service. The creature must be within range for the entire casting. It must make a CHA save. On a failure, it is bound to serve you for the duration. It must follow your instructions to the best of its ability.',
    higherLevels: 'At 6th level: 10 days. At 7th: 30 days. At 8th: 180 days. At 9th: a year and a day.',
    saveStat: 'CHA',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'Link',
    personalityQuips: {
      thunderhead: 'You are bound to divine service. Resist not.',
      jarvis: 'Extraplanar entity contract established. Service term: 24 hours.',
      deadpool: 'GENIE IN A BOTTLE! Except it\'s a demon! And there are no wishes!',
    },
  },
  {
    id: 'scrying',
    name: 'Scrying',
    level: 5,
    school: 'divination',
    castingTime: '10_minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You can see and hear a particular creature you choose that is on the same plane of existence. The target must make a WIS save (modified by how well you know the target and any physical connection you have). On failure, you can see and hear the target and its immediate surroundings.',
    saveStat: 'WIS',
    classes: ['cleric', 'bard', 'druid', 'warlock', 'wizard'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'The all-seeing eye opens. No plane can hide from divine sight.',
      jarvis: 'Remote viewing protocol active. Target surveillance established.',
      deadpool: 'CREEPY CRYSTAL BALL TIME! Let\'s see what Karen is up to!',
    },
  },
];
