// Cleric Spell List
// D&D 5e divine magic - Wisdom-based prepared caster

import { SpellDefinition } from '../types';

export const CLERIC_SPELLS: SpellDefinition[] = [
  // ============================================
  // CANTRIPS (Level 0)
  // ============================================
  {
    id: 'sacred-flame',
    name: 'Sacred Flame',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Flame-like radiance descends on a creature. DEX save or take 1d8 radiant damage. No benefit from cover.',
    higherLevels: 'Damage increases by 1d8 at 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
    saveStat: 'DEX',
    damageType: 'radiant',
    damageFormula: '1d8',
    classes: ['cleric'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Divine fire answers the faithful. The light burns the unworthy.',
      jarvis: 'Sacred thermal projection initiated. Targeting hostile entity.',
      deadpool: 'Holy Ghost Rider vibes! Your soul is stained with the blood of the innocent!',
    },
  },
  {
    id: 'guidance',
    name: 'Guidance',
    level: 0,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Touch a willing creature. Once before the spell ends, the target can roll 1d4 and add it to one ability check.',
    classes: ['cleric', 'druid'],
    iconName: 'Compass',
    personalityQuips: {
      thunderhead: 'Divine wisdom guides your hand. Trust in the path shown.',
      jarvis: 'Probability enhancement active. Success rate increased by 12.5%.',
      deadpool: 'Here\'s a tip: don\'t die! That\'ll be one d4 please.',
    },
  },
  {
    id: 'spare-the-dying',
    name: 'Spare the Dying',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a living creature at 0 HP. It becomes stable.',
    classes: ['cleric'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Not yet. Death must wait for another day.',
      jarvis: 'Vital signs stabilized. Patient no longer in critical condition.',
      deadpool: 'Plot armor activated! You can\'t die yet, we\'re only on episode 3!',
    },
  },
  {
    id: 'thaumaturgy',
    name: 'Thaumaturgy',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: 'Up to 1 minute',
    concentration: false,
    ritual: false,
    description: 'Manifest a minor wonder: booming voice, flickering flames, tremors, thunder sounds, instant door/window opening, or eye appearance change.',
    classes: ['cleric'],
    iconName: 'Sparkles',
    personalityQuips: {
      thunderhead: 'The faithful require signs. Give them spectacle.',
      jarvis: 'Theatrical effect subroutines engaged. Dramatic impact optimized.',
      deadpool: 'BEHOLD MY POWER! *voice cracks* Ahem. BEHOLD MY POWER!',
    },
  },
  {
    id: 'toll-the-dead-cleric',
    name: 'Toll the Dead',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You point at a creature and the sound of a dolorous bell fills the air. WIS save or take 1d8 necrotic damage (1d12 if already damaged).',
    higherLevels: 'Damage increases at 5th level (2d8/2d12), 11th level (3d8/3d12), and 17th level (4d8/4d12).',
    saveStat: 'WIS',
    damageType: 'necrotic',
    damageFormula: '1d8',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Bell',
    personalityQuips: {
      thunderhead: 'For whom does the bell toll? For thee, evermore.',
      jarvis: 'Acoustic neural disruption initiated. Mortality reminder delivered.',
      deadpool: 'DING DONG! Death\'s calling! Oh wait, wrong kind of bell...',
    },
  },
  {
    id: 'word-of-radiance',
    name: 'Word of Radiance',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '5 feet',
    components: { verbal: true, somatic: false, material: 'a holy symbol' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You utter a divine word, and burning radiance erupts from you. Each creature of your choice within range must make a CON save or take 1d6 radiant damage.',
    higherLevels: 'Damage increases at 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
    saveStat: 'CON',
    damageType: 'radiant',
    damageFormula: '1d6',
    classes: ['cleric'],
    iconName: 'Sun',
    personalityQuips: {
      thunderhead: 'The word of the divine burns all who stand too close.',
      jarvis: 'Radiant area effect deployed. Hostile entities within radius affected.',
      deadpool: 'BEGONE THOTS! Wait, wrong word of power. BEGONE EVIL!',
    },
  },

  // ============================================
  // 1ST LEVEL SPELLS
  // ============================================
  {
    id: 'bless',
    name: 'Bless',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a sprinkling of holy water' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Bless up to 3 creatures. Whenever a target makes an attack roll or saving throw, it can add 1d4 to the roll.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['cleric'],
    iconName: 'Star',
    personalityQuips: {
      thunderhead: 'May the gods smile upon your efforts. Strike true.',
      jarvis: 'Divine enhancement protocol active. Combat efficiency increased.',
      deadpool: 'You get a blessing! And YOU get a blessing! EVERYBODY GETS BLESSINGS!',
    },
  },
  {
    id: 'cure-wounds-cleric',
    name: 'Cure Wounds',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature you touch regains 1d8 + spellcasting modifier HP. No effect on undead or constructs.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 1st.',
    healingFormula: '1d8+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Be healed by divine grace. Rise and fight on.',
      jarvis: 'Tissue regeneration complete. Health points restored.',
      deadpool: 'Boop! All better! That\'ll be 500 gold. Kidding! ...Unless?',
    },
  },
  {
    id: 'guiding-bolt',
    name: 'Guiding Bolt',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A flash of light streaks toward a creature. Make a ranged spell attack. On hit, 4d6 radiant damage and next attack roll against target has advantage.',
    higherLevels: 'Damage increases by 1d6 for each slot level above 1st.',
    attackType: 'ranged',
    damageType: 'radiant',
    damageFormula: '4d6',
    classes: ['cleric'],
    iconName: 'Target',
    personalityQuips: {
      thunderhead: 'The light reveals all. Strike where the gods have shown.',
      jarvis: 'Targeting beacon deployed. Next attack vector optimized.',
      deadpool: 'GPS STRIKE INCOMING! Recalculating... your face!',
    },
  },
  {
    id: 'healing-word-cleric',
    name: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature of your choice that you can see regains 1d4 + spellcasting modifier HP.',
    higherLevels: 'Healing increases by 1d4 for each slot level above 1st.',
    healingFormula: '1d4+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Rise! The battle is not yet done.',
      jarvis: 'Remote healing protocol initiated. Patient stabilizing.',
      deadpool: 'Get up, princess! Beauty sleep is over!',
    },
  },
  {
    id: 'shield-of-faith',
    name: 'Shield of Faith',
    level: 1,
    school: 'abjuration',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small parchment with holy text' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'A shimmering field appears around a creature, granting +2 bonus to AC for the duration.',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'Faith is the truest armor. Let it protect you.',
      jarvis: 'Protective energy matrix deployed. AC increased by 2.',
      deadpool: 'Bubble shield! Now you\'re basically a hamster! A holy hamster!',
    },
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    level: 1,
    school: 'abjuration',
    castingTime: 'bonus_action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a small silver mirror' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You ward a creature. Any creature targeting the warded creature with attack or harmful spell must make WIS save or choose a new target or lose the attack/spell.',
    saveStat: 'WIS',
    classes: ['cleric'],
    iconName: 'Home',
    personalityQuips: {
      thunderhead: 'This one is under divine protection. Strike elsewhere.',
      jarvis: 'Sanctuary protocol engaged. Target marked as non-combatant.',
      deadpool: 'Olly olly oxen free! Can\'t touch this! Da na na na!',
    },
  },
  {
    id: 'inflict-wounds',
    name: 'Inflict Wounds',
    level: 1,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Make a melee spell attack. On hit, target takes 3d10 necrotic damage.',
    higherLevels: 'Damage increases by 1d10 for each slot level above 1st.',
    attackType: 'melee',
    damageType: 'necrotic',
    damageFormula: '3d10',
    classes: ['cleric'],
    iconName: 'Hand',
    personalityQuips: {
      thunderhead: 'The gods can give life... and take it away.',
      jarvis: 'Necrotic energy transfer initiated. Maximum tissue damage.',
      deadpool: 'HIGH FIVE OF DOOM! ...You\'re not gonna high-five me back, are you?',
    },
  },
  {
    id: 'command',
    name: 'Command',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Speak a one-word command to a creature you can see. WIS save or follow the command on its next turn. Common commands: Approach, Drop, Flee, Grovel, Halt.',
    higherLevels: 'You can affect one additional creature for each slot level above 1st.',
    saveStat: 'WIS',
    classes: ['cleric', 'warlock'],
    iconName: 'MessageSquare',
    personalityQuips: {
      thunderhead: 'HALT! When the divine speaks, mortals obey.',
      jarvis: 'Verbal command protocol engaged. Compliance probability: high.',
      deadpool: 'DANCE! No wait, that\'s not one of them. GROVEL! Yeah, that\'s better.',
    },
  },
  {
    id: 'detect-magic-cleric',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Sense the presence of magic within 30 feet. You can see a faint aura around any visible creature or object that bears magic and learn its school.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'wizard'],
    iconName: 'Search',
    personalityQuips: {
      thunderhead: 'The divine eye reveals all enchantments. See truly.',
      jarvis: 'Arcane detection scanners online. Magical signatures identified.',
      deadpool: 'My Spidey sense is tingling! Wait, wrong universe.',
    },
  },

  // ============================================
  // 2ND LEVEL SPELLS
  // ============================================
  {
    id: 'spiritual-weapon',
    name: 'Spiritual Weapon',
    level: 2,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Create a floating, spectral weapon within range. Make a melee spell attack dealing 1d8 + spellcasting modifier force damage. Move weapon up to 20 feet and attack again as bonus action.',
    higherLevels: 'Damage increases by 1d8 for every two slot levels above 2nd.',
    attackType: 'melee',
    damageType: 'force',
    damageFormula: '1d8+mod',
    classes: ['cleric'],
    iconName: 'Sword',
    personalityQuips: {
      thunderhead: 'The gods fight beside you. Let their weapon strike true.',
      jarvis: 'Autonomous spiritual armament deployed. Combat assist active.',
      deadpool: 'It\'s like a Stand! STAR PLATINUM! ...No wait, that\'s not it either.',
    },
  },
  {
    id: 'hold-person-cleric',
    name: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a humanoid. It must succeed on a WIS save or be paralyzed. It repeats the save at the end of each of its turns.',
    higherLevels: 'You can target one additional humanoid for each slot level above 2nd.',
    saveStat: 'WIS',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'Lock',
    personalityQuips: {
      thunderhead: 'Be still in the presence of the divine.',
      jarvis: 'Motor function override engaged. Target immobilized.',
      deadpool: 'FREEZE! This is a holy intervention!',
    },
  },
  {
    id: 'lesser-restoration',
    name: 'Lesser Restoration',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a creature and end one disease or one condition: blinded, deafened, paralyzed, or poisoned.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Eraser',
    personalityQuips: {
      thunderhead: 'Affliction be purged. The gods cleanse what ails you.',
      jarvis: 'Condition removal subroutine active. Status effect purged.',
      deadpool: 'Cleanse! Purify! Exfoliate! Wait, that last one\'s skincare.',
    },
  },
  {
    id: 'prayer-of-healing',
    name: 'Prayer of Healing',
    level: 2,
    school: 'evocation',
    castingTime: '10_minutes',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Up to 6 creatures regain 2d8 + spellcasting modifier HP each.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 2nd.',
    healingFormula: '2d8+mod',
    classes: ['cleric'],
    iconName: 'Users',
    personalityQuips: {
      thunderhead: 'Gather round—healing for all who are faithful.',
      jarvis: 'Mass healing protocol engaged. Multiple patients treated.',
      deadpool: 'Group therapy session! Everyone gets a cookie and some HP!',
    },
  },
  {
    id: 'aid',
    name: 'Aid',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a tiny strip of white cloth' },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'Choose up to 3 creatures. Each target\'s HP maximum and current HP increase by 5 for the duration.',
    higherLevels: 'HP increase by an additional 5 for each slot level above 2nd.',
    classes: ['cleric'],
    iconName: 'TrendingUp',
    personalityQuips: {
      thunderhead: 'Divine vitality strengthens the worthy. Stand tall.',
      jarvis: 'Temporary hit point allocation complete. Durability increased.',
      deadpool: 'You\'re now 5 HP thicc-er! Use it wisely!',
    },
  },
  {
    id: 'silence',
    name: 'Silence',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Create a 20-foot-radius sphere of silence. No sound can be created within or pass through. Creatures are immune to thunder damage and are deafened. Verbal components are impossible.',
    classes: ['cleric', 'bard'],
    iconName: 'VolumeX',
    personalityQuips: {
      thunderhead: 'Let there be silence. No more spellcasting for you.',
      jarvis: 'Acoustic dampening field deployed. Sound transmission blocked.',
      deadpool: 'SHHHH! Library rules in effect! No talking, no magic!',
    },
  },
  {
    id: 'zone-of-truth',
    name: 'Zone of Truth',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '10 minutes',
    concentration: false,
    ritual: false,
    description: 'Create a 15-foot-radius sphere. Creatures entering must succeed CHA save or be unable to speak a deliberate lie. You know whether each creature succeeds or fails.',
    saveStat: 'CHA',
    classes: ['cleric', 'bard'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'Truth or silence—those are your only options.',
      jarvis: 'Veracity enforcement field active. Deception probability: zero.',
      deadpool: 'Truth time! Did you eat the last pizza slice? CONFESS!',
    },
  },

  // ============================================
  // 3RD LEVEL SPELLS
  // ============================================
  {
    id: 'spirit-guardians',
    name: 'Spirit Guardians',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: 'Self (15-foot radius)',
    components: { verbal: true, somatic: true, material: 'a holy symbol' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Spirits surround you in a 15-foot radius. Creatures of your choice entering the area or starting their turn there must make WIS save. 3d8 radiant (good/neutral) or necrotic (evil) damage on failure, half on success.',
    higherLevels: 'Damage increases by 1d8 for each slot level above 3rd.',
    saveStat: 'WIS',
    damageType: 'radiant',
    damageFormula: '3d8',
    classes: ['cleric'],
    iconName: 'Users',
    personalityQuips: {
      thunderhead: 'The faithful dead fight on. Come closer if you dare.',
      jarvis: 'Spiritual defense perimeter established. Area denial active.',
      deadpool: 'I\'ve got GHOST FRIENDS! They\'re very protective!',
    },
  },
  {
    id: 'revivify',
    name: 'Revivify',
    level: 3,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamonds worth 300 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a creature that died within the last minute. It returns to life with 1 HP. Cannot restore missing body parts or creatures that died of old age.',
    healingFormula: '1',
    classes: ['cleric', 'druid'],
    iconName: 'RotateCcw',
    personalityQuips: {
      thunderhead: 'Return to us—your time has not yet come.',
      jarvis: 'Revival protocol initiated. Vital signs reestablishing.',
      deadpool: 'CLEAR! *zap* Welcome back! That\'ll be 300 gold!',
    },
  },
  {
    id: 'beacon-of-hope',
    name: 'Beacon of Hope',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose any number of creatures within range. They have advantage on WIS saves and death saving throws, and regain the maximum HP possible from healing.',
    classes: ['cleric'],
    iconName: 'Sunrise',
    personalityQuips: {
      thunderhead: 'Hope blazes brightest in darkness. Be healed fully.',
      jarvis: 'Hope amplification active. Maximum healing efficiency achieved.',
      deadpool: 'MAXIMUM HEALING! It\'s like a spa day but with less cucumber!',
    },
  },
  {
    id: 'dispel-magic-cleric',
    name: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose a creature, object, or magical effect. Any spell of 3rd level or lower ends. For higher-level spells, make an ability check (DC 10 + spell level).',
    higherLevels: 'Automatically end spells of the slot level used or lower.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'XCircle',
    personalityQuips: {
      thunderhead: 'Your magic ends here. Divine will unravels the arcane.',
      jarvis: 'Magical negation field deployed. Spell integrity compromised.',
      deadpool: 'CTRL+Z! UNDO! Your magic is now canceled!',
    },
  },
  {
    id: 'mass-healing-word',
    name: 'Mass Healing Word',
    level: 3,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Up to 6 creatures of your choice that you can see regain 1d4 + spellcasting modifier HP each.',
    higherLevels: 'Healing increases by 1d4 for each slot level above 3rd.',
    healingFormula: '1d4+mod',
    classes: ['cleric', 'bard'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Rise, all of you! The prayer reaches many.',
      jarvis: 'Mass healing broadcast initiated. Multiple patients responding.',
      deadpool: 'EVERYBODY GETS UP! No dying on my watch!',
    },
  },
  {
    id: 'remove-curse',
    name: 'Remove Curse',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'At your touch, all curses affecting one creature or object end. If the object is a cursed magic item, its curse remains but breaks the owner\'s attunement.',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Eraser',
    personalityQuips: {
      thunderhead: 'Curses break before divine will. Be free.',
      jarvis: 'Curse removal protocol successful. Magical binding severed.',
      deadpool: 'CURSE BE GONE! *throws holy water* Wait, was that my coffee?',
    },
  },

  // ============================================
  // 4TH LEVEL SPELLS
  // ============================================
  {
    id: 'death-ward',
    name: 'Death Ward',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'Touch a creature. The first time it would drop to 0 HP, it drops to 1 HP instead. If subjected to an effect that would kill it instantly without dealing damage, that effect is negated.',
    classes: ['cleric'],
    iconName: 'ShieldCheck',
    personalityQuips: {
      thunderhead: 'Death shall not claim you yet. One chance remains.',
      jarvis: 'Anti-death protocol installed. Emergency revival armed.',
      deadpool: 'FREE EXTRA LIFE! Like a video game power-up! 1-UP!',
    },
  },
  {
    id: 'guardian-of-faith',
    name: 'Guardian of Faith',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'A Large spectral guardian appears. When a hostile creature moves within 10 feet for the first time or starts its turn there, it must make DEX save or take 20 radiant damage (half on success). Guardian vanishes after dealing 60 total damage.',
    saveStat: 'DEX',
    damageType: 'radiant',
    damageFormula: '20',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'An angel stands watch. Pass at your own peril.',
      jarvis: 'Divine sentry deployed. Area denial damage: significant.',
      deadpool: 'Security guard from heaven! Tips not accepted!',
    },
  },
  {
    id: 'banishment-cleric',
    name: 'Banishment',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'an item distasteful to the target' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Attempt to send a creature to another plane. CHA save or be banished. If native to current plane, creature goes to a harmless demiplane; otherwise, it returns to its home plane.',
    higherLevels: 'You can target one additional creature for each slot level above 4th.',
    saveStat: 'CHA',
    classes: ['cleric', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'LogOut',
    personalityQuips: {
      thunderhead: 'Return from whence you came! This plane rejects you.',
      jarvis: 'Planar ejection initiated. Target relocated to origin dimension.',
      deadpool: 'YEET! To another dimension you go! Byeeeee!',
    },
  },
  {
    id: 'freedom-of-movement',
    name: 'Freedom of Movement',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a leather strap' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'Touch a willing creature. Its movement is unaffected by difficult terrain, spells that reduce speed, or paralysis/restraint. It can spend 5 feet of movement to escape nonmagical restraints or grapples.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Move',
    personalityQuips: {
      thunderhead: 'No bonds can hold the faithful. Move freely.',
      jarvis: 'Movement restriction immunity active. Mobility unrestricted.',
      deadpool: 'PARKOUR! Nothing can hold you back now! FREEBIRD!',
    },
  },

  // ============================================
  // 5TH LEVEL SPELLS
  // ============================================
  {
    id: 'mass-cure-wounds',
    name: 'Mass Cure Wounds',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A wave of healing energy washes out. Choose up to 6 creatures in a 30-foot-radius sphere. Each target regains 3d8 + spellcasting modifier HP.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 5th.',
    healingFormula: '3d8+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Healing for everyone! The gods\' mercy washes over all.',
      jarvis: 'Mass healing surge complete. All targets restored.',
      deadpool: 'HEALING RAIN FROM ABOVE! Catch it in your mouth!',
    },
  },
  {
    id: 'flame-strike',
    name: 'Flame Strike',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of sulfur' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A vertical column of divine fire roars down (10-foot radius, 40 feet high). Creatures in the area must make DEX save or take 4d6 fire + 4d6 radiant damage, half on success.',
    higherLevels: 'Fire or radiant damage (your choice) increases by 1d6 for each slot level above 5th.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '4d6+4d6',
    classes: ['cleric'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Divine fire rains from above! Heaven\'s wrath made manifest.',
      jarvis: 'Celestial napalm strike initiated. Impact zone: designated.',
      deadpool: 'HOLY FIRE COLUMN! It\'s like a divine air strike! INCOMING!',
    },
  },
  {
    id: 'greater-restoration',
    name: 'Greater Restoration',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamond dust worth at least 100 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You imbue a creature with positive energy to undo a debilitating effect. Reduce exhaustion by 1 level, or end one of: charmed, petrified, a curse, any ability score reduction, or HP maximum reduction.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Sparkles',
    personalityQuips: {
      thunderhead: 'Be restored to full glory. Even the worst afflictions fade.',
      jarvis: 'Maximum restoration protocol complete. All debuffs purged.',
      deadpool: 'ULTIMATE CLEANSE! You\'re now shiny and new!',
    },
  },
  {
    id: 'raise-dead',
    name: 'Raise Dead',
    level: 5,
    school: 'necromancy',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a diamond worth at least 500 gp, which the spell consumes' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Return a dead creature to life (died within 10 days). It returns with 1 HP. Cannot restore missing body parts. Target takes -4 penalty to attack rolls, saves, and ability checks; penalty reduces by 1 after each long rest.',
    healingFormula: '1',
    classes: ['cleric', 'bard'],
    iconName: 'RotateCcw',
    personalityQuips: {
      thunderhead: 'Rise from death\'s embrace. The gods grant a second chance.',
      jarvis: 'Full resurrection protocol complete. Side effects expected.',
      deadpool: '500 gold to cheat death! Bargain bin resurrection!',
    },
  },
  {
    id: 'holy-weapon',
    name: 'Holy Weapon',
    level: 5,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Imbue a weapon with holy power. It deals an extra 2d8 radiant damage on hit and emits bright light in 30 feet. You can dismiss as bonus action for 4d8 radiant damage burst (30-foot radius, CON save for half) and targets are blinded.',
    damageType: 'radiant',
    damageFormula: '2d8',
    classes: ['cleric'],
    iconName: 'Sword',
    personalityQuips: {
      thunderhead: 'This blade blazes with divine fury. Strike true.',
      jarvis: 'Holy weapon enchantment active. Radiant damage module online.',
      deadpool: 'LIGHTSABER! ...I mean, HOLYSABER! May the gods be with you!',
    },
  },
  {
    id: 'dispel-evil-and-good',
    name: 'Dispel Evil and Good',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Shimmering energy surrounds you. Celestials, elementals, fey, fiends, and undead have disadvantage on attacks against you. You can end the spell to break enchantment, dismiss creature, or end possession.',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'Otherworldly beings fear my presence. Begone!',
      jarvis: 'Anti-planar defense matrix active. Hostile entities repelled.',
      deadpool: 'I\'m toxic to supernatural beings! Finally, a superpower!',
    },
  },
];
