// Cleric Spell List — D&D 5e PHB Complete
// Wisdom-based prepared caster — all cantrips through 5th level

import { SpellDefinition } from '../types';
import { CLERIC_SPELLS_HIGHER } from './cleric-spells-higher';

export const CLERIC_SPELLS_BASE: SpellDefinition[] = [
  // ============================================
  // CANTRIPS (Level 0)
  // ============================================
  {
    id: 'sacred-flame',
    name: 'Sacred Flame',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Flame-like radiance descends on a creature. DEX save or take 1d8 radiant damage. No benefit from cover.',
    higherLevels: 'Damage increases by 1d8 at 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
    saveStat: 'DEX',
    damageType: 'radiant',
    damageFormula: '1d8',
    classes: ['cleric'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Divine fire answers the faithful. The light burns the unworthy.',
      jarvis: 'Sacred thermal projection initiated. Targeting hostile entity.',
      deadpool: 'Holy Ghost Rider vibes! Your soul is stained with the blood of the innocent!',
    },
  },
  {
    id: 'guidance',
    name: 'Guidance',
    level: 0,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Touch a willing creature. Once before the spell ends, the target can roll 1d4 and add it to one ability check.',
    classes: ['cleric', 'druid'],
    iconName: 'Compass',
    personalityQuips: {
      thunderhead: 'Divine wisdom guides your hand. Trust in the path shown.',
      jarvis: 'Probability enhancement active. Success rate increased by 12.5%.',
      deadpool: 'Here\'s a tip: don\'t die! That\'ll be one d4 please.',
    },
  },
  {
    id: 'spare-the-dying',
    name: 'Spare the Dying',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a living creature at 0 HP. It becomes stable.',
    classes: ['cleric'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Not yet. Death must wait for another day.',
      jarvis: 'Vital signs stabilized. Patient no longer in critical condition.',
      deadpool: 'Plot armor activated! You can\'t die yet, we\'re only on episode 3!',
    },
  },
  {
    id: 'thaumaturgy',
    name: 'Thaumaturgy',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: 'Up to 1 minute',
    concentration: false,
    ritual: false,
    description: 'Manifest a minor wonder: booming voice, flickering flames, tremors, thunder sounds, instant door/window opening, or eye appearance change.',
    classes: ['cleric'],
    iconName: 'Sparkles',
    personalityQuips: {
      thunderhead: 'The faithful require signs. Give them spectacle.',
      jarvis: 'Theatrical effect subroutines engaged. Dramatic impact optimized.',
      deadpool: 'BEHOLD MY POWER! *voice cracks* Ahem. BEHOLD MY POWER!',
    },
  },
  {
    id: 'toll-the-dead-cleric',
    name: 'Toll the Dead',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You point at a creature and the sound of a dolorous bell fills the air. WIS save or take 1d8 necrotic damage (1d12 if already damaged).',
    higherLevels: 'Damage increases at 5th level (2d8/2d12), 11th level (3d8/3d12), and 17th level (4d8/4d12).',
    saveStat: 'WIS',
    damageType: 'necrotic',
    damageFormula: '1d8',
    classes: ['cleric', 'warlock', 'wizard'],
    iconName: 'Bell',
    personalityQuips: {
      thunderhead: 'For whom does the bell toll? For thee, evermore.',
      jarvis: 'Acoustic neural disruption initiated. Mortality reminder delivered.',
      deadpool: 'DING DONG! Death\'s calling! Oh wait, wrong kind of bell...',
    },
  },
  {
    id: 'word-of-radiance',
    name: 'Word of Radiance',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '5 feet',
    components: { verbal: true, somatic: false, material: 'a holy symbol' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You utter a divine word, and burning radiance erupts from you. Each creature of your choice within range must make a CON save or take 1d6 radiant damage.',
    higherLevels: 'Damage increases at 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
    saveStat: 'CON',
    damageType: 'radiant',
    damageFormula: '1d6',
    classes: ['cleric'],
    iconName: 'Sun',
    personalityQuips: {
      thunderhead: 'The word of the divine burns all who stand too close.',
      jarvis: 'Radiant area effect deployed. Hostile entities within radius affected.',
      deadpool: 'BEGONE THOTS! Wait, wrong word of power. BEGONE EVIL!',
    },
  },

  // --- MISSING CANTRIPS ---
  {
    id: 'light-cleric',
    name: 'Light',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a firefly or phosphorescent moss' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch one object no larger than 10 feet in any dimension. It sheds bright light in a 20-foot radius and dim light for an additional 20 feet. Hostile creature: DEX save or spell takes effect.',
    saveStat: 'DEX',
    classes: ['cleric', 'bard', 'sorcerer', 'wizard'],
    iconName: 'Lightbulb',
    personalityQuips: {
      thunderhead: 'Let there be light. The darkness flees before the faithful.',
      jarvis: 'Illumination protocol engaged. Visible spectrum output: optimal.',
      deadpool: 'FLASHLIGHT SPELL! Because torches are so last century!',
    },
  },
  {
    id: 'mending-cleric',
    name: 'Mending',
    level: 0,
    school: 'transmutation',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. The break must be no larger than 1 foot.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'wizard'],
    iconName: 'Wrench',
    personalityQuips: {
      thunderhead: 'What was broken is made whole. Even small miracles matter.',
      jarvis: 'Molecular repair subroutine initiated. Structural integrity restored.',
      deadpool: 'Duct tape spell! Fixes EVERYTHING! Well, almost everything.',
    },
  },
  {
    id: 'resistance-cleric',
    name: 'Resistance',
    level: 0,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a miniature cloak' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after making the saving throw.',
    classes: ['cleric', 'druid'],
    iconName: 'ShieldCheck',
    personalityQuips: {
      thunderhead: 'The faithful endure. Take this small shield of will.',
      jarvis: 'Saving throw enhancement module active. +1d4 to next save.',
      deadpool: 'Here, take this tiny invisible blanket of protection! Very cozy!',
    },
  },

  // ============================================
  // 1ST LEVEL SPELLS
  // ============================================
  {
    id: 'bless',
    name: 'Bless',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a sprinkling of holy water' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Bless up to 3 creatures. Whenever a target makes an attack roll or saving throw, it can add 1d4 to the roll.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['cleric'],
    iconName: 'Star',
    personalityQuips: {
      thunderhead: 'May the gods smile upon your efforts. Strike true.',
      jarvis: 'Divine enhancement protocol active. Combat efficiency increased.',
      deadpool: 'You get a blessing! And YOU get a blessing! EVERYBODY GETS BLESSINGS!',
    },
  },
  {
    id: 'cure-wounds-cleric',
    name: 'Cure Wounds',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature you touch regains 1d8 + spellcasting modifier HP. No effect on undead or constructs.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 1st.',
    healingFormula: '1d8+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Heart',
    personalityQuips: {
      thunderhead: 'Be healed by divine grace. Rise and fight on.',
      jarvis: 'Tissue regeneration complete. Health points restored.',
      deadpool: 'Boop! All better! That\'ll be 500 gold. Kidding! ...Unless?',
    },
  },
  {
    id: 'guiding-bolt',
    name: 'Guiding Bolt',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A flash of light streaks toward a creature. Make a ranged spell attack. On hit, 4d6 radiant damage and next attack roll against target has advantage.',
    higherLevels: 'Damage increases by 1d6 for each slot level above 1st.',
    attackType: 'ranged',
    damageType: 'radiant',
    damageFormula: '4d6',
    classes: ['cleric'],
    iconName: 'Target',
    personalityQuips: {
      thunderhead: 'The light reveals all. Strike where the gods have shown.',
      jarvis: 'Targeting beacon deployed. Next attack vector optimized.',
      deadpool: 'GPS STRIKE INCOMING! Recalculating... your face!',
    },
  },
  {
    id: 'healing-word-cleric',
    name: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A creature of your choice that you can see regains 1d4 + spellcasting modifier HP.',
    higherLevels: 'Healing increases by 1d4 for each slot level above 1st.',
    healingFormula: '1d4+mod',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'MessageCircle',
    personalityQuips: {
      thunderhead: 'Rise! The battle is not yet done.',
      jarvis: 'Remote healing protocol initiated. Patient stabilizing.',
      deadpool: 'Get up, princess! Beauty sleep is over!',
    },
  },
  {
    id: 'shield-of-faith',
    name: 'Shield of Faith',
    level: 1,
    school: 'abjuration',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small parchment with holy text' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'A shimmering field appears around a creature, granting +2 bonus to AC for the duration.',
    classes: ['cleric'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'Faith is the truest armor. Let it protect you.',
      jarvis: 'Protective energy matrix deployed. AC increased by 2.',
      deadpool: 'Bubble shield! Now you\'re basically a hamster! A holy hamster!',
    },
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    level: 1,
    school: 'abjuration',
    castingTime: 'bonus_action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a small silver mirror' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You ward a creature. Any creature targeting the warded creature with attack or harmful spell must make WIS save or choose a new target or lose the attack/spell.',
    saveStat: 'WIS',
    classes: ['cleric'],
    iconName: 'Home',
    personalityQuips: {
      thunderhead: 'This one is under divine protection. Strike elsewhere.',
      jarvis: 'Sanctuary protocol engaged. Target marked as non-combatant.',
      deadpool: 'Olly olly oxen free! Can\'t touch this! Da na na na!',
    },
  },
  {
    id: 'inflict-wounds',
    name: 'Inflict Wounds',
    level: 1,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Make a melee spell attack. On hit, target takes 3d10 necrotic damage.',
    higherLevels: 'Damage increases by 1d10 for each slot level above 1st.',
    attackType: 'melee',
    damageType: 'necrotic',
    damageFormula: '3d10',
    classes: ['cleric'],
    iconName: 'Hand',
    personalityQuips: {
      thunderhead: 'The gods can give life... and take it away.',
      jarvis: 'Necrotic energy transfer initiated. Maximum tissue damage.',
      deadpool: 'HIGH FIVE OF DOOM! ...You\'re not gonna high-five me back, are you?',
    },
  },
  {
    id: 'command',
    name: 'Command',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Speak a one-word command to a creature you can see. WIS save or follow the command on its next turn. Common commands: Approach, Drop, Flee, Grovel, Halt.',
    higherLevels: 'You can affect one additional creature for each slot level above 1st.',
    saveStat: 'WIS',
    classes: ['cleric', 'warlock'],
    iconName: 'MessageSquare',
    personalityQuips: {
      thunderhead: 'HALT! When the divine speaks, mortals obey.',
      jarvis: 'Verbal command protocol engaged. Compliance probability: high.',
      deadpool: 'DANCE! No wait, that\'s not one of them. GROVEL! Yeah, that\'s better.',
    },
  },
  {
    id: 'detect-magic-cleric',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Sense the presence of magic within 30 feet. You can see a faint aura around any visible creature or object that bears magic and learn its school.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'wizard'],
    iconName: 'Search',
    personalityQuips: {
      thunderhead: 'The divine eye reveals all enchantments. See truly.',
      jarvis: 'Arcane detection scanners online. Magical signatures identified.',
      deadpool: 'My Spidey sense is tingling! Wait, wrong universe.',
    },
  },

  // --- MISSING 1ST LEVEL ---
  {
    id: 'create-or-destroy-water',
    name: 'Create or Destroy Water',
    level: 1,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a drop of water (create) or a few grains of sand (destroy)' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You either create up to 10 gallons of clean water within range in an open container, or rain in a 30-foot cube. Alternatively, you destroy up to 10 gallons of water in an open container or destroy fog in a 30-foot cube.',
    higherLevels: 'Create or destroy 10 additional gallons or increase cube size by 5 feet for each slot level above 1st.',
    classes: ['cleric', 'druid'],
    iconName: 'Droplets',
    personalityQuips: {
      thunderhead: 'Water flows or vanishes at divine command.',
      jarvis: 'Aquatic generation/elimination protocol initiated.',
      deadpool: 'I\'m basically a water bender now! Or an un-water bender!',
    },
  },
  {
    id: 'detect-evil-and-good',
    name: 'Detect Evil and Good',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you, as well as where the creature is located.',
    classes: ['cleric'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'The divine eye sees beyond mortal sight. Evil cannot hide.',
      jarvis: 'Extraplanar entity scanner online. Hostile signatures detected.',
      deadpool: 'My evil-dar is pinging! Oh wait, that\'s just Greg.',
    },
  },
  {
    id: 'detect-poison-and-disease',
    name: 'Detect Poison and Disease',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a yew leaf' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you. You also identify the kind of poison, poisonous creature, or disease.',
    classes: ['cleric', 'druid'],
    iconName: 'Bug',
    personalityQuips: {
      thunderhead: 'Corruption reveals itself to the faithful. Trust your senses.',
      jarvis: 'Toxicology scanner active. Pathogenic threats identified.',
      deadpool: 'POISON DETECTOR! Beep beep beep! That soup is SUS!',
    },
  },
  {
    id: 'protection-from-evil-and-good',
    name: 'Protection from Evil and Good',
    level: 1,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'holy water or powdered silver and iron, which the spell consumes' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Until the spell ends, one willing creature you touch is protected against aberrations, celestials, elementals, fey, fiends, and undead. Those types have disadvantage on attacks against the target, and the target can\'t be charmed, frightened, or possessed by them.',
    classes: ['cleric', 'druid', 'wizard'],
    iconName: 'Shield',
    personalityQuips: {
      thunderhead: 'The ward is set. Otherworldly beings shall not touch you.',
      jarvis: 'Anti-planar defense barrier active. Hostile entity resistance engaged.',
      deadpool: 'SUPERNATURAL RESTRAINING ORDER! 30 feet at all times!',
    },
  },
  {
    id: 'purify-food-and-drink',
    name: 'Purify Food and Drink',
    level: 1,
    school: 'transmutation',
    castingTime: 'action',
    range: '10 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice is rendered free of poison and disease.',
    classes: ['cleric', 'druid'],
    iconName: 'Apple',
    personalityQuips: {
      thunderhead: 'No poison shall taint what is blessed. Eat without fear.',
      jarvis: 'Food safety protocol complete. All contaminants neutralized.',
      deadpool: 'Five-second rule? Nah, PURIFY-second rule! Eat off the floor!',
    },
  },

  // ============================================
  // 2ND LEVEL SPELLS
  // ============================================
  {
    id: 'spiritual-weapon',
    name: 'Spiritual Weapon',
    level: 2,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Create a floating, spectral weapon within range. Make a melee spell attack dealing 1d8 + spellcasting modifier force damage. Move weapon up to 20 feet and attack again as bonus action.',
    higherLevels: 'Damage increases by 1d8 for every two slot levels above 2nd.',
    attackType: 'melee',
    damageType: 'force',
    damageFormula: '1d8+mod',
    classes: ['cleric'],
    iconName: 'Sword',
    personalityQuips: {
      thunderhead: 'The gods fight beside you. Let their weapon strike true.',
      jarvis: 'Autonomous spiritual armament deployed. Combat assist active.',
      deadpool: 'It\'s like a Stand! STAR PLATINUM! ...No wait, that\'s not it either.',
    },
  },
  {
    id: 'hold-person-cleric',
    name: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a humanoid. It must succeed on a WIS save or be paralyzed. It repeats the save at the end of each of its turns.',
    higherLevels: 'You can target one additional humanoid for each slot level above 2nd.',
    saveStat: 'WIS',
    classes: ['cleric', 'bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
    iconName: 'Lock',
    personalityQuips: {
      thunderhead: 'Be still in the presence of the divine.',
      jarvis: 'Motor function override engaged. Target immobilized.',
      deadpool: 'FREEZE! This is a holy intervention!',
    },
  },
  {
    id: 'lesser-restoration',
    name: 'Lesser Restoration',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Touch a creature and end one disease or one condition: blinded, deafened, paralyzed, or poisoned.',
    classes: ['cleric', 'bard', 'druid'],
    iconName: 'Eraser',
    personalityQuips: {
      thunderhead: 'Affliction be purged. The gods cleanse what ails you.',
      jarvis: 'Condition removal subroutine active. Status effect purged.',
      deadpool: 'Cleanse! Purify! Exfoliate! Wait, that last one\'s skincare.',
    },
  },
  {
    id: 'prayer-of-healing',
    name: 'Prayer of Healing',
    level: 2,
    school: 'evocation',
    castingTime: '10_minutes',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Up to 6 creatures regain 2d8 + spellcasting modifier HP each.',
    higherLevels: 'Healing increases by 1d8 for each slot level above 2nd.',
    healingFormula: '2d8+mod',
    classes: ['cleric'],
    iconName: 'Users',
    personalityQuips: {
      thunderhead: 'Gather round—healing for all who are faithful.',
      jarvis: 'Mass healing protocol engaged. Multiple patients treated.',
      deadpool: 'Group therapy session! Everyone gets a cookie and some HP!',
    },
  },
  {
    id: 'aid',
    name: 'Aid',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a tiny strip of white cloth' },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'Choose up to 3 creatures. Each target\'s HP maximum and current HP increase by 5 for the duration.',
    higherLevels: 'HP increase by an additional 5 for each slot level above 2nd.',
    classes: ['cleric'],
    iconName: 'TrendingUp',
    personalityQuips: {
      thunderhead: 'Divine vitality strengthens the worthy. Stand tall.',
      jarvis: 'Temporary hit point allocation complete. Durability increased.',
      deadpool: 'You\'re now 5 HP thicc-er! Use it wisely!',
    },
  },
  {
    id: 'silence',
    name: 'Silence',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'Create a 20-foot-radius sphere of silence. No sound can be created within or pass through. Creatures are immune to thunder damage and are deafened. Verbal components are impossible.',
    classes: ['cleric', 'bard'],
    iconName: 'VolumeX',
    personalityQuips: {
      thunderhead: 'Let there be silence. No more spellcasting for you.',
      jarvis: 'Acoustic dampening field deployed. Sound transmission blocked.',
      deadpool: 'SHHHH! Library rules in effect! No talking, no magic!',
    },
  },
  {
    id: 'zone-of-truth',
    name: 'Zone of Truth',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '10 minutes',
    concentration: false,
    ritual: false,
    description: 'Create a 15-foot-radius sphere. Creatures entering must succeed CHA save or be unable to speak a deliberate lie. You know whether each creature succeeds or fails.',
    saveStat: 'CHA',
    classes: ['cleric', 'bard'],
    iconName: 'Eye',
    personalityQuips: {
      thunderhead: 'Truth or silence—those are your only options.',
      jarvis: 'Veracity enforcement field active. Deception probability: zero.',
      deadpool: 'Truth time! Did you eat the last pizza slice? CONFESS!',
    },
  },

  // --- MISSING 2ND LEVEL ---
  {
    id: 'augury-cleric',
    name: 'Augury',
    level: 2,
    school: 'divination',
    castingTime: '1_minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'specially marked sticks, bones, or similar tokens worth at least 25 gp' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action within the next 30 minutes: weal, woe, both, or nothing.',
    classes: ['cleric'],
    iconName: 'Dice1',
    personalityQuips: {
      thunderhead: 'The signs are cast. The gods whisper their counsel.',
      jarvis: 'Probability analysis complete. Omen received and decoded.',
      deadpool: 'Magic 8-Ball says... ask again later! Just kidding. Weal!',
    },
  },
  {
    id: 'blindness-deafness',
    name: 'Blindness/Deafness',
    level: 2,
    school: 'necromancy',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You can blind or deafen a foe. Choose one creature that you can see within range. It must succeed on a CON save or be either blinded or deafened (your choice) for the duration. It repeats the save at the end of each of its turns.',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    saveStat: 'CON',
    classes: ['cleric', 'bard', 'sorcerer', 'wizard'],
    iconName: 'EyeOff',
    personalityQuips: {
      thunderhead: 'Be sightless! The divine revokes your senses.',
      jarvis: 'Sensory deprivation protocol engaged. Target input disabled.',
      deadpool: 'SEE NO EVIL! Or hear no evil! Dealer\'s choice!',
    },
  },
  {
    id: 'calm-emotions',
    name: 'Calm Emotions',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere must make a CHA save. On failure, you can suppress any effect causing it to be charmed or frightened, or make it indifferent about hostile creatures.',
    saveStat: 'CHA',
    classes: ['cleric', 'bard'],
    iconName: 'HeartHandshake',
    personalityQuips: {
      thunderhead: 'Peace. Be still. Let wrath and fear depart.',
      jarvis: 'Emotional regulation field active. Hostility levels normalized.',
      deadpool: 'Everybody just CHILL! Group therapy in session!',
    },
  },
  {
    id: 'continual-flame',
    name: 'Continual Flame',
    level: 2,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'ruby dust worth 50 gp, which the spell consumes' },
    duration: 'Until dispelled',
    concentration: false,
    ritual: false,
    description: 'A flame, equivalent in brightness to a torch, springs forth from an object that you touch. The effect looks like a regular flame, but it creates no heat and doesn\'t use oxygen. A continual flame can be covered or hidden but not smothered or quenched.',
    classes: ['cleric', 'wizard'],
    iconName: 'Flame',
    personalityQuips: {
      thunderhead: 'Eternal flame burns by divine will. It shall never be extinguished.',
      jarvis: 'Perpetual illumination source created. Energy output: indefinite.',
      deadpool: 'Eternal flame! Like the Bangles song! It burns, burns, BURNS!',
    },
  },
  {
    id: 'enhance-ability',
    name: 'Enhance Ability',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'fur or a feather from a beast' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects: Bear\'s Endurance (advantage on CON checks, 2d6 temp HP), Bull\'s Strength (advantage on STR checks, double carrying capacity), Cat\'s Grace (advantage on DEX checks, no fall damage from 20 feet or less), Eagle\'s Splendor (advantage on CHA checks), Fox\'s Cunning (advantage on INT checks), or Owl\'s Wisdom (advantage on WIS checks).',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    classes: ['cleric', 'bard', 'druid', 'sorcerer'],
    iconName: 'TrendingUp',
    personalityQuips: {
      thunderhead: 'Be empowered. The gods sharpen your natural gifts.',
      jarvis: 'Ability enhancement module loaded. Performance boosted.',
      deadpool: 'SUPER JUICE! Pick your flavor: Bear, Bull, Cat, Eagle, Fox, or Owl!',
    },
  },
  {
    id: 'find-traps',
    name: 'Find Traps',
    level: 2,
    school: 'divination',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You sense the presence of any trap within line of sight and within range. A trap includes anything that would inflict a sudden or unexpected effect you consider harmful or undesirable. You learn the general nature of each trap\'s danger but not exact location.',
    classes: ['cleric', 'druid'],
    iconName: 'AlertTriangle',
    personalityQuips: {
      thunderhead: 'Danger lurks ahead. The faithful are warned.',
      jarvis: 'Trap detection scan complete. Hazards identified in vicinity.',
      deadpool: 'IT\'S A TRAP! ...Sorry, had to say it. Admiral Ackbar would be proud.',
    },
  },
  {
    id: 'gentle-repose',
    name: 'Gentle Repose',
    level: 2,
    school: 'necromancy',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pinch of salt and one copper piece placed on each of the corpse\'s eyes' },
    duration: '10 days',
    concentration: false,
    ritual: true,
    description: 'You touch a corpse or other remains. For the duration, the target is protected from decay and can\'t become undead. The spell also effectively extends the time limit on raising the target from the dead.',
    classes: ['cleric', 'wizard'],
    iconName: 'Moon',
    personalityQuips: {
      thunderhead: 'Rest peacefully. Decay shall not touch you, nor shall undeath.',
      jarvis: 'Preservation protocol engaged. Decomposition halted for 10 days.',
      deadpool: 'Anti-zombie insurance! Just two copper and a pinch of salt!',
    },
  },
  {
    id: 'locate-object',
    name: 'Locate Object',
    level: 2,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a forked twig' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Describe or name an object that is familiar to you. You sense the direction to the object\'s location, as long as that object is within 1,000 feet of you. If the object is in motion, you know the direction of its movement.',
    classes: ['cleric', 'bard', 'druid', 'wizard'],
    iconName: 'MapPin',
    personalityQuips: {
      thunderhead: 'That which is lost shall be found. The gods guide your search.',
      jarvis: 'Object tracking protocol active. Directional lock acquired.',
      deadpool: 'GPS for medieval stuff! Where did I put my other sock?!',
    },
  },
  {
    id: 'protection-from-poison',
    name: 'Protection from Poison',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch a creature. If it is poisoned, you neutralize the poison. For the duration, the target has advantage on saving throws against being poisoned and has resistance to poison damage.',
    classes: ['cleric', 'druid'],
    iconName: 'ShieldCheck',
    personalityQuips: {
      thunderhead: 'Poison cannot fell the protected. The gods purify your blood.',
      jarvis: 'Anti-toxin protocol active. Poison resistance engaged.',
      deadpool: 'POISON PROOF! Go ahead, drink the suspicious potion!',
    },
  },
  {
    id: 'warding-bond',
    name: 'Warding Bond',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pair of platinum rings worth at least 50 gp each, which you and the target must wear' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch a willing creature and create a mystic connection. While the target is within 60 feet, it gains +1 to AC and saving throws and has resistance to all damage. Each time it takes damage, you take the same amount.',
    classes: ['cleric'],
    iconName: 'Link',
    personalityQuips: {
      thunderhead: 'We share this burden. Your pain is mine to bear.',
      jarvis: 'Damage sharing protocol established. Symbiotic defense active.',
      deadpool: 'BFF rings! Except when you get hurt, I get hurt too. Great plan!',
    },
  },
];

export const CLERIC_SPELLS: SpellDefinition[] = [
  ...CLERIC_SPELLS_BASE,
  ...CLERIC_SPELLS_HIGHER,
];
