// Druid Spell List
// Wisdom-based prepared caster with nature magic, healing, and shapeshifting support
// Shares some spells with Cleric (healing) and has unique nature/elemental spells

import { SpellDefinition } from '../types';

export const DRUID_SPELLS: SpellDefinition[] = [
  // ============================================
  // CANTRIPS (Level 0)
  // ============================================
  {
    id: 'druidcraft',
    name: 'Druidcraft',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    description: 'Whispering to the spirits of nature, you create one of several minor effects: predict weather, bloom a flower, create sensory effects, or light/snuff small flames.',
    iconName: 'Leaf',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The natural world responds to those who listen.',
      jarvis: 'A versatile cantrip for environmental manipulation and nature communion.',
      deadpool: 'Look at me, I\'m basically a Disney princess now! Birds, come to me!',
    },
  },
  {
    id: 'produce-flame',
    name: 'Produce Flame',
    level: 0,
    school: 'conjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '10 minutes',
    description: 'A flickering flame appears in your hand, shedding bright light in a 10-foot radius. You can hurl it at a creature within 30 feet, making a ranged spell attack for 1d8 fire damage. Damage increases to 2d8 at 5th level, 3d8 at 11th level, and 4d8 at 17th level.',
    damageFormula: '1d8',
    damageType: 'fire',
    iconName: 'Flame',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    personalityQuips: {
      thunderhead: 'Fire is but one aspect of nature\'s power.',
      jarvis: 'Dual-purpose illumination and ranged attack capability.',
      deadpool: 'Hot hands! Literally! Don\'t high-five anyone.',
    },
  },
  {
    id: 'shillelagh',
    name: 'Shillelagh',
    level: 0,
    school: 'transmutation',
    castingTime: 'bonus_action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'mistletoe, a shamrock leaf, and a club or quarterstaff' },
    duration: '1 minute',
    description: 'The wood of a club or quarterstaff you hold is imbued with nature\'s power. For the duration, you can use your spellcasting ability instead of Strength for attack and damage rolls, and the weapon\'s damage die becomes a d8.',
    iconName: 'Wand2',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The forest lends its strength to the worthy.',
      jarvis: 'Converts physical combat to spellcasting ability scaling.',
      deadpool: 'My walking stick is now a BONKING stick! Nature is metal!',
    },
  },
  {
    id: 'thorn-whip',
    name: 'Thorn Whip',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'the stem of a plant with thorns' },
    duration: 'Instantaneous',
    description: 'You create a long, vine-like whip covered in thorns that lashes out at a creature in range. Make a melee spell attack. On hit, the creature takes 1d6 piercing damage, and if Large or smaller, is pulled up to 10 feet closer to you. Damage increases to 2d6 at 5th level, 3d6 at 11th level, and 4d6 at 17th level.',
    damageFormula: '1d6',
    damageType: 'piercing',
    iconName: 'TreeDeciduous',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    personalityQuips: {
      thunderhead: 'Nature reaches out to grasp the unwary.',
      jarvis: 'Damage plus forced movement—excellent tactical control.',
      deadpool: 'GET OVER HERE! Scorpion would be so proud!',
    },
  },
  {
    id: 'druid-guidance',
    name: 'Guidance',
    level: 0,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.',
    iconName: 'Compass',
    classes: ['cleric', 'druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The spirits guide those who seek wisdom.',
      jarvis: 'A reliable bonus to any skill check. Use liberally.',
      deadpool: 'Here\'s a little divine nudge! You\'re welcome!',
    },
  },

  // ============================================
  // 1ST LEVEL SPELLS
  // ============================================
  {
    id: 'entangle',
    name: 'Entangle',
    level: 1,
    school: 'conjuration',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    description: 'Grasping weeds and vines sprout from the ground in a 20-foot square. Creatures in the area must succeed on a Strength saving throw or be restrained. A creature can use its action to make a Strength check against your spell save DC to free itself.',
    iconName: 'TreeDeciduous',
    saveStat: 'STR',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The earth itself rises to bind your foes.',
      jarvis: 'Area denial and restraint. Excellent battlefield control.',
      deadpool: 'It\'s like nature\'s own bondage party! Kinky plants!',
    },
  },
  {
    id: 'druid-faerie-fire',
    name: 'Faerie Fire',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 1 minute',
    description: 'Each object in a 20-foot cube is outlined in blue, green, or violet light. Creatures that fail a Dexterity save are also outlined. Affected creatures and objects shed dim light in a 10-foot radius, and attack rolls against them have advantage. They can\'t benefit from being invisible.',
    iconName: 'Sparkles',
    saveStat: 'DEX',
    classes: ['bard', 'druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'No shadow can hide from nature\'s revealing light.',
      jarvis: 'Grants advantage to all attacks and negates invisibility.',
      deadpool: 'You\'re literally glowing! Like a rave, but deadly!',
    },
  },
  {
    id: 'druid-fog-cloud',
    name: 'Fog Cloud',
    level: 1,
    school: 'conjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    description: 'You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. The radius increases by 20 feet for each slot level above 1st.',
    iconName: 'Cloud',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    higherLevels: 'The radius increases by 20 feet for each slot level above 1st.',
    personalityQuips: {
      thunderhead: 'Mist rises to cloak your movements.',
      jarvis: 'Creates heavily obscured area. Useful for escape or ambush.',
      deadpool: 'Smoke machine activated! Now where\'s my laser show?',
    },
  },
  {
    id: 'goodberry',
    name: 'Goodberry',
    level: 1,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a sprig of mistletoe' },
    duration: 'Instantaneous',
    description: 'Up to ten berries appear in your hand and are infused with magic. Eating a berry restores 1 hit point, and the berry provides enough nourishment to sustain a creature for one day. The berries lose their potency after 24 hours.',
    healingFormula: '1 per berry (10 total)',
    iconName: 'Cherry',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    personalityQuips: {
      thunderhead: 'Nature provides sustenance for the faithful.',
      jarvis: 'Ten points of healing and sustenance. Excellent utility.',
      deadpool: 'Magic snacks! They taste like... optimism and dirt!',
    },
  },
  {
    id: 'druid-healing-word',
    name: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: 'bonus_action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    description: 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier.',
    healingFormula: '1d4 + modifier',
    iconName: 'Heart',
    classes: ['bard', 'cleric', 'druid'],
    concentration: false,
    ritual: false,
    higherLevels: 'Healing increases by 1d4 for each slot level above 1st.',
    personalityQuips: {
      thunderhead: 'A word of power mends the wounded.',
      jarvis: 'Bonus action ranged healing. Highly efficient action economy.',
      deadpool: 'Pew pew! Healing lasers! Except they\'re words!',
    },
  },
  {
    id: 'speak-with-animals',
    name: 'Speak with Animals',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '10 minutes',
    description: 'You gain the ability to comprehend and verbally communicate with beasts for the duration. The knowledge and awareness of many beasts is limited, but they can provide information about nearby locations and monsters.',
    iconName: 'Bird',
    classes: ['bard', 'druid'],
    concentration: false,
    ritual: true,
    personalityQuips: {
      thunderhead: 'The voices of all creatures become clear.',
      jarvis: 'Intelligence gathering from local fauna. Ritual-castable.',
      deadpool: 'Finally! I can ask squirrels what they\'re REALLY up to!',
    },
  },
  {
    id: 'druid-thunderwave',
    name: 'Thunderwave',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (15-foot cube)',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you.',
    damageFormula: '2d8',
    damageType: 'thunder',
    iconName: 'Zap',
    saveStat: 'CON',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    higherLevels: 'Damage increases by 1d8 for each slot level above 1st.',
    personalityQuips: {
      thunderhead: 'The storm answers to my call.',
      jarvis: 'Area damage with knockback. Excellent for creating space.',
      deadpool: 'BOOM! Personal space ENFORCED!',
    },
  },

  // ============================================
  // 2ND LEVEL SPELLS
  // ============================================
  {
    id: 'barkskin',
    name: 'Barkskin',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a handful of oak bark' },
    duration: 'Concentration, up to 1 hour',
    description: 'You touch a willing creature. Until the spell ends, the target\'s skin has a rough, bark-like appearance, and the target\'s AC can\'t be less than 16, regardless of what kind of armor it is wearing.',
    iconName: 'Shield',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The forest\'s protection becomes your shield.',
      jarvis: 'Guarantees minimum AC 16. Useful for low-armor allies.',
      deadpool: 'I am Groot! Wait, wrong franchise. I am... Barky!',
    },
  },
  {
    id: 'druid-flaming-sphere',
    name: 'Flaming Sphere',
    level: 2,
    school: 'conjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of tallow, a pinch of brimstone, and a dusting of powdered iron' },
    duration: 'Concentration, up to 1 minute',
    description: 'A 5-foot-diameter sphere of fire appears in an unoccupied space. Any creature that ends its turn within 5 feet must make a Dexterity save, taking 2d6 fire damage on a failure. As a bonus action, you can move the sphere up to 30 feet.',
    damageFormula: '2d6',
    damageType: 'fire',
    iconName: 'Flame',
    saveStat: 'DEX',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    higherLevels: 'Damage increases by 1d6 for each slot level above 2nd.',
    personalityQuips: {
      thunderhead: 'Fire given form, burning with purpose.',
      jarvis: 'Sustained area denial with bonus action repositioning.',
      deadpool: 'It\'s a beach ball! A FIRE beach ball! Don\'t catch it!',
    },
  },
  {
    id: 'heat-metal',
    name: 'Heat Metal',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a piece of iron and a flame' },
    duration: 'Concentration, up to 1 minute',
    description: 'Choose a manufactured metal object. Any creature in physical contact with the object takes 2d8 fire damage. If holding the object, it must succeed on a Constitution save or drop it. On subsequent turns, you can use a bonus action to cause this damage again.',
    damageFormula: '2d8',
    damageType: 'fire',
    iconName: 'Thermometer',
    saveStat: 'CON',
    classes: ['bard', 'druid'],
    concentration: true,
    ritual: false,
    higherLevels: 'Damage increases by 1d8 for each slot level above 2nd.',
    personalityQuips: {
      thunderhead: 'Metal remembers the forge that shaped it.',
      jarvis: 'Devastating against armored foes. Repeatable damage.',
      deadpool: 'Your armor is now a MICROWAVE! Ding!',
    },
  },
  {
    id: 'moonbeam',
    name: 'Moonbeam',
    level: 2,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'several seeds of any moonseed plant and a piece of opalescent feldspar' },
    duration: 'Concentration, up to 1 minute',
    description: 'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder. Creatures entering or starting their turn in the area must make a Constitution save, taking 2d10 radiant damage on a failure. Shapechangers have disadvantage on this save.',
    damageFormula: '2d10',
    damageType: 'radiant',
    iconName: 'Moon',
    saveStat: 'CON',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    higherLevels: 'Damage increases by 1d10 for each slot level above 2nd.',
    personalityQuips: {
      thunderhead: 'The moon\'s light reveals and purifies.',
      jarvis: 'Excellent anti-shapechanger utility and solid radiant damage.',
      deadpool: 'Moon laser! Sailor Moon would be so jealous!',
    },
  },
  {
    id: 'pass-without-trace',
    name: 'Pass Without Trace',
    level: 2,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'ashes from a burned leaf of mistletoe and a sprig of spruce' },
    duration: 'Concentration, up to 1 hour',
    description: 'A veil of shadows and silence radiates from you. For the duration, each creature you choose within 30 feet has a +10 bonus to Dexterity (Stealth) checks and can\'t be tracked except by magical means.',
    iconName: 'Ghost',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The shadows embrace those who walk with nature.',
      jarvis: 'Massive +10 to Stealth for entire party. Exceptional utility.',
      deadpool: 'We\'re all ninjas now! Stealthy nature ninjas!',
    },
  },
  {
    id: 'spike-growth',
    name: 'Spike Growth',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'seven sharp thorns or seven small twigs, each sharpened to a point' },
    duration: 'Concentration, up to 10 minutes',
    description: 'The ground in a 20-foot radius twists and sprouts hard spikes and thorns. The area becomes difficult terrain, and when a creature moves through, it takes 2d4 piercing damage for every 5 feet it travels.',
    damageFormula: '2d4 per 5 feet',
    damageType: 'piercing',
    iconName: 'Swords',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The earth defends itself with nature\'s teeth.',
      jarvis: 'Synergizes excellently with forced movement effects.',
      deadpool: 'Floor is lava! No wait, floor is STABBY!',
    },
  },

  // ============================================
  // 3RD LEVEL SPELLS
  // ============================================
  {
    id: 'call-lightning',
    name: 'Call Lightning',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 10 minutes',
    description: 'A storm cloud appears 100 feet above you. When you cast this spell, and as an action on subsequent turns, you can call down a bolt of lightning on a point beneath the cloud. Each creature within 5 feet must make a Dexterity save, taking 3d10 lightning damage on a failure (4d10 outdoors in storm).',
    damageFormula: '3d10',
    damageType: 'lightning',
    iconName: 'Zap',
    saveStat: 'DEX',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    higherLevels: 'Damage increases by 1d10 for each slot level above 3rd.',
    personalityQuips: {
      thunderhead: 'I AM the storm. Hear my voice.',
      jarvis: 'Sustained damage output. Enhanced in stormy conditions.',
      deadpool: 'UNLIMITED POWER! *cackles in Palpatine*',
    },
  },
  {
    id: 'conjure-animals',
    name: 'Conjure Animals',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    description: 'You summon fey spirits that take the form of beasts. Choose one option: one beast of CR 2 or lower, two beasts of CR 1 or lower, four beasts of CR 1/2 or lower, or eight beasts of CR 1/4 or lower. They obey your verbal commands.',
    iconName: 'PawPrint',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    higherLevels: 'You summon twice as many beasts when cast using a 5th level slot.',
    personalityQuips: {
      thunderhead: 'The spirits of the wild answer my summons.',
      jarvis: 'Action economy multiplication. Eight wolves is... significant.',
      deadpool: 'It\'s a zoo! MY zoo! Attack, my pretties!',
    },
  },
  {
    id: 'plant-growth',
    name: 'Plant Growth',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '150 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    description: 'Action: All normal plants in a 100-foot radius become thick and overgrown. A creature moving through the area must spend 4 feet of movement for every 1 foot. 8 Hours version: All plants in a half-mile radius become enriched, yielding twice the normal harvest for 1 year.',
    iconName: 'Flower2',
    classes: ['bard', 'druid'],
    concentration: false,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The land flourishes at nature\'s command.',
      jarvis: 'Devastating movement restriction or agricultural blessing.',
      deadpool: 'JUNGLE TIME! Tarzan would be proud! AHHHH-AH-AH-AHHH!',
    },
  },
  {
    id: 'druid-sleet-storm',
    name: 'Sleet Storm',
    level: 3,
    school: 'conjuration',
    castingTime: 'action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of dust and a few drops of water' },
    duration: 'Concentration, up to 1 minute',
    description: 'Freezing rain and sleet fall in a 40-foot-tall, 20-foot-radius cylinder. The area is heavily obscured, and exposed flames are extinguished. The ground becomes difficult terrain, and creatures must make Dexterity saves or fall prone.',
    iconName: 'Snowflake',
    saveStat: 'DEX',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'Winter\'s wrath descends upon my enemies.',
      jarvis: 'Heavy obscurement plus difficult terrain plus prone checks.',
      deadpool: 'It\'s raining ice! Hallelujah, it\'s raining pain!',
    },
  },
  {
    id: 'wind-wall',
    name: 'Wind Wall',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a tiny fan and a feather of exotic origin' },
    duration: 'Concentration, up to 1 minute',
    description: 'A wall of strong wind rises from the ground. The wall is up to 50 feet long, 15 feet high, and 1 foot thick. Creatures that enter the wall must make a Strength save or take 3d8 bludgeoning damage. The wall deflects arrows, bolts, and other projectiles.',
    damageFormula: '3d8',
    damageType: 'bludgeoning',
    iconName: 'Wind',
    saveStat: 'STR',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The winds themselves become a barrier.',
      jarvis: 'Negates ranged attacks and provides zone control.',
      deadpool: 'Industrial fan ACTIVATED! No arrows for you!',
    },
  },

  // ============================================
  // 4TH LEVEL SPELLS
  // ============================================
  {
    id: 'druid-blight',
    name: 'Blight',
    level: 4,
    school: 'necromancy',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    description: 'Necromantic energy washes over a creature, draining moisture and vitality. The target must make a Constitution saving throw, taking 8d8 necrotic damage on a failure. Plant creatures and magical plants have disadvantage and take maximum damage.',
    damageFormula: '8d8',
    damageType: 'necrotic',
    iconName: 'Skull',
    saveStat: 'CON',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    personalityQuips: {
      thunderhead: 'Even nature has its darker aspects.',
      jarvis: 'High single-target damage. Devastating against plants.',
      deadpool: 'I just gave that tree depression! MAXIMUM damage!',
    },
  },
  {
    id: 'conjure-woodland-beings',
    name: 'Conjure Woodland Beings',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'one holly berry per creature summoned' },
    duration: 'Concentration, up to 1 hour',
    description: 'You summon fey creatures: one fey of CR 2 or lower, two of CR 1 or lower, four of CR 1/2 or lower, or eight of CR 1/4 or lower. They are friendly and obey your verbal commands.',
    iconName: 'Trees',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The fey answer the call of one who respects their realm.',
      jarvis: 'Pixies can cast polymorph. Eight of them is... problematic.',
      deadpool: 'Tinkerbell and friends! But angrier! Much angrier!',
    },
  },
  {
    id: 'grasping-vine',
    name: 'Grasping Vine',
    level: 4,
    school: 'conjuration',
    castingTime: 'bonus_action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    description: 'A vine sprouts from a surface and lashes out at a creature within 30 feet of it. The target must succeed on a Dexterity save or be pulled 20 feet directly toward the vine. On subsequent turns, you can direct the vine to attack again as a bonus action.',
    iconName: 'TreeDeciduous',
    saveStat: 'DEX',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The vine hungers for those who stray too close.',
      jarvis: 'Bonus action repositioning. Excellent combo potential.',
      deadpool: 'Tentacle time! No wait, it\'s a VINE. Family friendly!',
    },
  },
  {
    id: 'druid-ice-storm',
    name: 'Ice Storm',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of dust and a few drops of water' },
    duration: 'Instantaneous',
    description: 'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. Each creature in the area must make a Dexterity save, taking 2d8 bludgeoning and 4d6 cold damage on a failure. The area becomes difficult terrain until the end of your next turn.',
    damageFormula: '2d8 bludgeoning + 4d6 cold',
    damageType: 'cold',
    iconName: 'Snowflake',
    saveStat: 'DEX',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    higherLevels: 'Bludgeoning damage increases by 1d8 for each slot level above 4th.',
    personalityQuips: {
      thunderhead: 'The fury of winter made manifest.',
      jarvis: 'Solid AoE damage with difficult terrain. Excellent range.',
      deadpool: 'HAIL YEAH! Get it? Hail? Because ice? I\'ll see myself out.',
    },
  },
  {
    id: 'druid-polymorph',
    name: 'Polymorph',
    level: 4,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a caterpillar cocoon' },
    duration: 'Concentration, up to 1 hour',
    description: 'Transform a creature into a new beast form. The target\'s game statistics are replaced by the beast\'s, but it retains its alignment and personality. The transformation lasts until the target drops to 0 hit points or the spell ends.',
    iconName: 'Shapes',
    saveStat: 'WIS',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'All forms are but expressions of nature\'s will.',
      jarvis: 'Offensive or defensive shapeshifting. T-Rex has 136 HP.',
      deadpool: 'DINOSAUR TIME! Everyone\'s a T-Rex! RAWR!',
    },
  },
  {
    id: 'druid-wall-of-fire',
    name: 'Wall of Fire',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a small piece of phosphorus' },
    duration: 'Concentration, up to 1 minute',
    description: 'You create a wall of fire on a solid surface. The wall can be up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter. Creatures that enter the wall or start their turn within 10 feet of one side take 5d8 fire damage.',
    damageFormula: '5d8',
    damageType: 'fire',
    iconName: 'Flame',
    saveStat: 'DEX',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    personalityQuips: {
      thunderhead: 'Fire divides the battlefield at my command.',
      jarvis: 'Excellent zone control. One-sided damage is key.',
      deadpool: 'The floor is ACTUALLY lava now! I wasn\'t lying before!',
    },
  },

  // ============================================
  // 5TH LEVEL SPELLS
  // ============================================
  {
    id: 'antilife-shell',
    name: 'Antilife Shell',
    level: 5,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Self (10-foot radius)',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    description: 'A shimmering barrier extends from you in a 10-foot radius. Living creatures can\'t willingly enter the sphere, and if they try to, they are stopped. Creatures inside the sphere when you cast are pushed out.',
    iconName: 'ShieldOff',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'A sanctuary where life itself cannot trespass.',
      jarvis: 'Impenetrable to living creatures. Excellent defensive option.',
      deadpool: 'PERSONAL BUBBLE! No one can touch me! I\'m UNTOUCHABLE!',
    },
  },
  {
    id: 'awaken',
    name: 'Awaken',
    level: 5,
    school: 'transmutation',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'an agate worth at least 1,000 gp, which the spell consumes', materialConsumed: true, materialCost: 1000 },
    duration: 'Instantaneous',
    description: 'After 8 hours of tracing magical pathways, a Huge or smaller beast or plant with Intelligence 3 or less gains Intelligence 10 and the ability to speak one language you know. It is charmed by you for 30 days.',
    iconName: 'Lightbulb',
    classes: ['bard', 'druid'],
    concentration: false,
    ritual: false,
    personalityQuips: {
      thunderhead: 'True consciousness is nature\'s greatest gift.',
      jarvis: 'Creates a permanent intelligent ally. Long-term investment.',
      deadpool: 'Congratulations, tree! You can think now! And regret everything!',
    },
  },
  {
    id: 'druid-conjure-elemental',
    name: 'Conjure Elemental',
    level: 5,
    school: 'conjuration',
    castingTime: '1_minute',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water' },
    duration: 'Concentration, up to 1 hour',
    description: 'You call forth an elemental servant of CR 5 or lower. The elemental is friendly and obeys your verbal commands. If your concentration is broken, the elemental becomes hostile to all creatures and attacks the nearest.',
    iconName: 'Sparkles',
    classes: ['druid', 'wizard'],
    concentration: true,
    ritual: false,
    higherLevels: 'CR increases by 1 for each slot level above 5th.',
    personalityQuips: {
      thunderhead: 'The primal forces answer to those who command respect.',
      jarvis: 'Powerful summon. Caution: hostile if concentration breaks.',
      deadpool: 'I summon... CAPTAIN PLANET! No wait, just a regular elemental.',
    },
  },
  {
    id: 'druid-insect-plague',
    name: 'Insect Plague',
    level: 5,
    school: 'conjuration',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a few grains of sugar, some kernels of grain, and a smear of fat' },
    duration: 'Concentration, up to 10 minutes',
    description: 'Swarming, biting locusts fill a 20-foot-radius sphere. The area is lightly obscured. Creatures in the area when it appears or that enter it must make a Constitution save, taking 4d10 piercing damage on a failure.',
    damageFormula: '4d10',
    damageType: 'piercing',
    iconName: 'Bug',
    saveStat: 'CON',
    classes: ['cleric', 'druid', 'sorcerer'],
    concentration: true,
    ritual: false,
    higherLevels: 'Damage increases by 1d10 for each slot level above 5th.',
    personalityQuips: {
      thunderhead: 'The swarm consumes all in its path.',
      jarvis: 'Large area, sustained damage, light obscurement.',
      deadpool: 'BEES! Wait, locusts. LOCUSTS! Still terrifying!',
    },
  },
  {
    id: 'tree-stride',
    name: 'Tree Stride',
    level: 5,
    school: 'conjuration',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    description: 'You gain the ability to enter a tree and move to another tree of the same kind within 500 feet. Using 5 feet of movement, you enter the tree and appear within 5 feet of another tree of your choice, using another 5 feet of movement. You can use this once per round.',
    iconName: 'Trees',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'The forest becomes a network of pathways.',
      jarvis: '500-foot teleportation per round. Exceptional mobility.',
      deadpool: 'I AM ONE WITH THE TREES! *pops out of oak* SURPRISE!',
    },
  },
  {
    id: 'druid-wall-of-stone',
    name: 'Wall of Stone',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a small block of granite' },
    duration: 'Concentration, up to 10 minutes',
    description: 'A nonmagical wall of solid stone springs into existence. The wall is composed of ten 10-foot-by-10-foot panels. If maintained for the full duration, the wall becomes permanent and can\'t be dispelled.',
    iconName: 'SquareStack',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    personalityQuips: {
      thunderhead: 'Stone rises at nature\'s command.',
      jarvis: 'Battlefield reshaping. Permanent if concentration maintained.',
      deadpool: 'I built a WALL! And the monsters are gonna PAY for it!',
    },
  },
];
