// Sorcerer Spell List
// CHA-based full caster, known spells (not prepared)
// Focuses on damage, metamagic-friendly spells, and innate magical effects

import { SpellDefinition } from '../types';

// ============================================
// CANTRIPS (Level 0)
// ============================================

export const SORCERER_CANTRIPS: SpellDefinition[] = [
  {
    id: 'sorc-acid-splash',
    name: 'Acid Splash',
    level: 0,
    school: 'conjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You hurl a bubble of acid. Choose one or two creatures within range. If you choose two, they must be within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.',
    higherLevels: 'This spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
    attackType: 'save',
    saveStat: 'DEX',
    damageType: 'acid',
    damageFormula: '1d6',
    iconName: 'Droplets',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'Corrosive power answers your call—dissolve all that stands against you.',
      jarvis: 'Acidic projectile launched. Splash radius allows for multi-target engagement.',
      deadpool: 'Acid rain! But tiny! And aimed at faces! Science is fun!',
    },
  },
  {
    id: 'sorc-dancing-lights',
    name: 'Dancing Lights',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a bit of phosphorus or wychwood, or a glowworm' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. Each light sheds dim light in a 10-foot radius.',
    iconName: 'Lightbulb',
    classes: ['sorcerer', 'wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'Lights dance at your whim—let them lead or deceive as you choose.',
      jarvis: 'Four autonomous light sources deployed. Positioning at your discretion.',
      deadpool: 'Look! Fireflies! Magic fireflies! That I control! ULTIMATE POWER!',
    },
  },
  {
    id: 'sorc-message',
    name: 'Message',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a short piece of copper wire' },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear.',
    iconName: 'MessageSquare',
    classes: ['sorcerer', 'wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'Words carried on invisible winds—secrets shared between minds.',
      jarvis: 'Secure communication channel established. Encryption: magical.',
      deadpool: '*whispers* Hey... hey you... yeah, you... BUTTS. Hehe.',
    },
  },
  {
    id: 'sorc-true-strike',
    name: 'True Strike',
    level: 0,
    school: 'divination',
    castingTime: 'action',
    range: '30 feet',
    components: { somatic: true, verbal: false },
    duration: 'Concentration, up to 1 round',
    concentration: true,
    ritual: false,
    description: 'You point a finger at a target in range. Your magic grants you a brief insight into the target\'s defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn\'t ended.',
    iconName: 'Target',
    classes: ['sorcerer', 'wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'Foresight guides your hand—the next strike shall not miss.',
      jarvis: 'Targeting analysis complete. Attack probability significantly increased.',
      deadpool: 'Next attack: ADVANTAGE! This turn: I wasted my action! ...wait.',
    },
  },
  {
    id: 'sorc-infestation',
    name: 'Infestation',
    level: 0,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a living flea' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You cause a cloud of mites, fleas, and other parasites to appear momentarily on one creature you can see within range. The target must succeed on a Constitution saving throw, or it takes 1d6 poison damage and moves 5 feet in a random direction.',
    higherLevels: 'This spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
    attackType: 'save',
    saveStat: 'CON',
    damageType: 'poison',
    damageFormula: '1d6',
    iconName: 'Bug',
    classes: ['sorcerer', 'druid'],
    personalityQuips: {
      thunderhead: 'Nature\'s smallest creatures become your instruments of chaos.',
      jarvis: 'Parasitic swarm deployed. Target coordination compromised.',
      deadpool: 'BUGS! EVERYWHERE! *scratches vigorously* Even I\'m itchy now!',
    },
  },
  {
    id: 'sorc-mind-sliver',
    name: 'Mind Sliver',
    level: 0,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You drive a disorienting spike of psychic energy into the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.',
    higherLevels: 'This spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
    attackType: 'save',
    saveStat: 'INT',
    damageType: 'psychic',
    damageFormula: '1d6',
    iconName: 'Brain',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'A splinter of thought pierces their mind—doubt follows.',
      jarvis: 'Psychic interference deployed. Target cognitive functions degraded.',
      deadpool: 'Brain freeze! But like, ACTUAL brain freeze! With math problems!',
    },
  },
];

// ============================================
// 1ST LEVEL SPELLS
// ============================================

export const SORCERER_1ST_LEVEL: SpellDefinition[] = [
  {
    id: 'sorc-chaos-bolt',
    name: 'Chaos Bolt',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You hurl an undulating, warbling mass of chaotic energy at one creature in range. Make a ranged spell attack. On a hit, the target takes 2d8 + 1d6 damage. Choose one of the d8s. The number rolled determines the damage type. If you roll the same number on both d8s, the chaotic energy leaps to a different creature within 30 feet.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, each target takes 1d6 extra damage for each slot level above 1st.',
    attackType: 'ranged',
    damageFormula: '2d8 + 1d6',
    iconName: 'Zap',
    classes: ['sorcerer'],
    personalityQuips: {
      thunderhead: 'Entropy given form—even you do not know what devastation awaits.',
      jarvis: 'Chaotic energy matrix unstable. Damage type: random. Potential cascade: likely.',
      deadpool: 'It\'s like playing damage roulette! Spin the wheel of pain!',
    },
  },
  {
    id: 'sorc-catapult',
    name: 'Catapult',
    level: 1,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { somatic: true, verbal: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose one object weighing 1 to 5 pounds within range that isn\'t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground. If it would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and deals 3d8 bludgeoning damage.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects increases by 5 pounds, and the damage increases by 1d8, for each slot level above 1st.',
    attackType: 'save',
    saveStat: 'DEX',
    damageType: 'bludgeoning',
    damageFormula: '3d8',
    iconName: 'ArrowRightCircle',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'The mundane becomes a weapon—all things answer to force.',
      jarvis: 'Kinetic acceleration applied. Object velocity: terminal.',
      deadpool: 'YEET! I just yeeted a rock at your face! YEEEET!',
    },
  },
  {
    id: 'sorc-witch-bolt',
    name: 'Witch Bolt',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a twig from a tree that has been struck by lightning' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'A beam of crackling, blue energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack. On a hit, the target takes 1d12 lightning damage, and on each of your turns for the duration, you can use your action to deal 1d12 lightning damage automatically.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the initial damage increases by 1d12 for each slot level above 1st.',
    attackType: 'ranged',
    damageType: 'lightning',
    damageFormula: '1d12',
    iconName: 'Zap',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'A tether of pure energy binds your foe to their doom.',
      jarvis: 'Sustained electrical discharge established. Damage: automatic each turn.',
      deadpool: 'ZAP ZAP ZAP! It\'s like a lightning leash! Bad guy, NO!',
    },
  },
  {
    id: 'sorc-color-spray',
    name: 'Color Spray',
    level: 1,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self (15-foot cone)',
    components: { verbal: true, somatic: true, material: 'a pinch of powder or sand that is colored red, yellow, and blue' },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'A dazzling array of flashing, colored light springs from your hand. Roll 6d10; the total is how many hit points of creatures this spell can affect. Creatures in a 15-foot cone are affected in ascending order of their current hit points (ignoring unconscious creatures and creatures that can\'t see).',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d10 for each slot level above 1st.',
    iconName: 'Rainbow',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'A cascade of light overwhelms the senses—blindness follows beauty.',
      jarvis: 'Photonic overload initiated. Target visual cortex: saturated.',
      deadpool: 'TASTE THE RAINBOW! ...but like, with your eyes. It blinds you.',
    },
  },
  {
    id: 'sorc-earth-tremor',
    name: 'Earth Tremor',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '10 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You cause a tremor in the ground within range. Each creature other than you in that area must make a Dexterity saving throw. On a failed save, a creature takes 1d6 bludgeoning damage and is knocked prone. If the ground in that area is loose earth or stone, it becomes difficult terrain.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
    attackType: 'save',
    saveStat: 'DEX',
    damageType: 'bludgeoning',
    damageFormula: '1d6',
    iconName: 'Mountain',
    classes: ['sorcerer', 'wizard', 'druid', 'bard'],
    personalityQuips: {
      thunderhead: 'The earth itself rises against your enemies—the ground is your ally.',
      jarvis: 'Seismic disruption initiated. Ground stability: compromised.',
      deadpool: 'EARTHQUAKE! *shakes aggressively* EVERYBODY FALL DOWN!',
    },
  },
  {
    id: 'sorc-fog-cloud',
    name: 'Fog Cloud',
    level: 1,
    school: 'conjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the radius of the fog increases by 20 feet for each slot level above 1st.',
    iconName: 'Cloud',
    classes: ['sorcerer', 'wizard', 'druid'],
    personalityQuips: {
      thunderhead: 'Mist rises to cloak your movements—let them grope in blindness.',
      jarvis: 'Atmospheric condensation field deployed. Visibility: zero.',
      deadpool: 'Fog machine activated! Every fight needs dramatic atmosphere!',
    },
  },
];

// ============================================
// 2ND LEVEL SPELLS
// ============================================

export const SORCERER_2ND_LEVEL: SpellDefinition[] = [
  {
    id: 'sorc-dragon-breath',
    name: 'Dragon\'s Breath',
    level: 2,
    school: 'transmutation',
    castingTime: 'bonus_action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a hot pepper' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You touch one willing creature and imbue it with the power to spew magical energy from its mouth. Choose acid, cold, fire, lightning, or poison. Until the spell ends, the creature can use an action to exhale energy of the chosen type in a 15-foot cone. Each creature in that area must make a Dexterity saving throw, taking 3d6 damage on a failed save.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level above 2nd.',
    attackType: 'save',
    saveStat: 'DEX',
    damageFormula: '3d6',
    iconName: 'Flame',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'The dragon\'s gift flows through you—become the beast.',
      jarvis: 'Elemental breath weapon enabled. Type: configurable.',
      deadpool: 'DRAGON BREATH! Now I can be Godzilla! RAHHHH!',
    },
  },
  {
    id: 'sorc-levitate',
    name: 'Levitate',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'One creature or loose object of your choice that you can see within range rises vertically, up to 20 feet, and remains suspended there for the duration. An unwilling creature that succeeds on a Constitution saving throw is unaffected.',
    attackType: 'save',
    saveStat: 'CON',
    iconName: 'ArrowUp',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'Defy gravity—rise above the mundane earth.',
      jarvis: 'Anti-gravitational field applied. Vertical movement: 20 feet per turn.',
      deadpool: 'I\'m flying! I\'m—wait, I can only go up and down? Lame but okay!',
    },
  },
  {
    id: 'sorc-blindness-deafness',
    name: 'Blindness/Deafness',
    level: 2,
    school: 'necromancy',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution saving throw.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
    attackType: 'save',
    saveStat: 'CON',
    iconName: 'EyeOff',
    classes: ['sorcerer', 'wizard', 'cleric', 'bard'],
    personalityQuips: {
      thunderhead: 'Strip away their senses—let them fight in darkness.',
      jarvis: 'Sensory deprivation protocol executed. Target perception: nullified.',
      deadpool: 'See no evil, hear no evil! But still FEEL all the evil! Mwahaha!',
    },
  },
  {
    id: 'sorc-knock',
    name: 'Knock',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose an object that you can see within range. The object can be a door, a box, a chest, a set of manacles, a padlock, or another object that contains a mundane or magical means that prevents access. A loud knock audible from 300 feet away emanates from the object, and it is unlocked.',
    iconName: 'Key',
    classes: ['sorcerer', 'wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'No door remains closed to one who commands the arcane.',
      jarvis: 'Mechanical bypass initiated. Lock status: disengaged.',
      deadpool: 'KNOCK KNOCK! Who\'s there? ME! Breaking in! ...I\'m bad at jokes.',
    },
  },
  {
    id: 'sorc-detect-thoughts',
    name: 'Detect Thoughts',
    level: 2,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a copper piece' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'For the duration, you can read the thoughts of certain creatures. When you cast the spell and as your action on each turn until the spell ends, you can focus your mind on any one creature that you can see within 30 feet of you.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Brain',
    classes: ['sorcerer', 'wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'Minds are open books to those who know how to read.',
      jarvis: 'Telepathic scanner active. Surface thoughts: accessible.',
      deadpool: 'Reading minds! *concentrates* Ooh, they\'re thinking about lunch. Same, buddy.',
    },
  },
  {
    id: 'sorc-spider-climb',
    name: 'Spider Climb',
    level: 2,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a drop of bitumen and a spider' },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces and upside down along ceilings, while leaving its hands free. The target also gains a climbing speed equal to its walking speed.',
    iconName: 'Grip',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'Walls become floors—defy the expectations of terrain.',
      jarvis: 'Surface adhesion enabled. All orientations now traversable.',
      deadpool: 'Spider-man, Spider-man! Does whatever a—ACTUAL SPIDER can!',
    },
  },
];

// ============================================
// 3RD LEVEL SPELLS
// ============================================

export const SORCERER_3RD_LEVEL: SpellDefinition[] = [
  {
    id: 'sorc-erupting-earth',
    name: 'Erupting Earth',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a piece of obsidian' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose a point you can see on the ground within range. A fountain of churned earth and stone erupts in a 20-foot cube centered on that point. Each creature in that area must make a Dexterity saving throw. A creature takes 3d12 bludgeoning damage on a failed save, or half as much on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d12 for each slot level above 3rd.',
    attackType: 'save',
    saveStat: 'DEX',
    damageType: 'bludgeoning',
    damageFormula: '3d12',
    iconName: 'Mountain',
    classes: ['sorcerer', 'wizard', 'druid'],
    personalityQuips: {
      thunderhead: 'The earth revolts at your command—stone becomes shrapnel.',
      jarvis: 'Geological upheaval initiated. Impact zone: 20-foot cube.',
      deadpool: 'FLOOR IS LAVA! Wait, no, floor is EXPLODING! Even better!',
    },
  },
  {
    id: 'sorc-tongues',
    name: 'Tongues',
    level: 3,
    school: 'divination',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a small clay model of a ziggurat' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'This spell grants the creature you touch the ability to understand any spoken language it hears. Moreover, when the target speaks, any creature that knows at least one language and can hear the target understands what it says.',
    iconName: 'Languages',
    classes: ['sorcerer', 'wizard', 'cleric', 'bard'],
    personalityQuips: {
      thunderhead: 'All tongues become one—communication transcends barriers.',
      jarvis: 'Universal translation protocol active. Language barriers: eliminated.',
      deadpool: 'Now I can understand EVERYONE! ...including the guy yelling at me in Elvish.',
    },
  },
  {
    id: 'sorc-blink',
    name: 'Blink',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Roll a d20 at the end of each of your turns for the duration of the spell. On a roll of 11 or higher, you vanish from your current plane of existence and appear in the Ethereal Plane. At the start of your next turn, you return to an unoccupied space of your choice within 10 feet of where you vanished.',
    iconName: 'Sparkles',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'You flicker between worlds—here and gone in the same breath.',
      jarvis: 'Dimensional phase shifting enabled. 50% evasion probability.',
      deadpool: 'Now you see me, now you—*rolls poorly*—still see me. Dang it.',
    },
  },
  {
    id: 'sorc-clairvoyance',
    name: 'Clairvoyance',
    level: 3,
    school: 'divination',
    castingTime: '10_minutes',
    range: '1 mile',
    components: { verbal: true, somatic: true, material: 'a focus worth at least 100 gp, either a jeweled horn for hearing or a glass eye for seeing' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You create an invisible sensor within range in a location familiar to you (a place you have visited or seen before) or in an obvious location that is unfamiliar to you. The sensor remains in place for the duration, and it can\'t be attacked or otherwise interacted with.',
    iconName: 'Eye',
    classes: ['sorcerer', 'wizard', 'cleric', 'bard'],
    personalityQuips: {
      thunderhead: 'Distance means nothing—your senses reach where your body cannot.',
      jarvis: 'Remote sensing node deployed. Audio/visual feed available.',
      deadpool: 'Spy cam activated! Very legal, very cool surveillance!',
    },
  },
  {
    id: 'sorc-daylight',
    name: 'Daylight',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'A 60-foot-radius sphere of light spreads out from a point you choose within range. The sphere is bright light and sheds dim light for an additional 60 feet. If the point you choose is on an object you are holding or one that isn\'t being worn or carried, the light shines from the object.',
    iconName: 'Sun',
    classes: ['sorcerer', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'Banish the darkness with the fury of the sun itself.',
      jarvis: 'Maximum luminosity achieved. Light radius: 60 feet bright, 120 feet total.',
      deadpool: 'GOOD MORNING VIETNAM! Wait, I mean... whatever cave we\'re in!',
    },
  },
  {
    id: 'sorc-protection-from-energy',
    name: 'Protection from Energy',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'For the duration, the willing creature you touch has resistance to one damage type of your choice: acid, cold, fire, lightning, or thunder.',
    iconName: 'Shield',
    classes: ['sorcerer', 'wizard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'A ward against the elements—their fury breaks upon your shield.',
      jarvis: 'Elemental resistance protocol active. Damage reduction: 50%.',
      deadpool: 'Pick a flavor of pain to ignore! Fire? Cold? I\'m going with fire. Always fire.',
    },
  },
  {
    id: 'sorc-major-image',
    name: 'Major Image',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a bit of fleece' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 20-foot cube. The image appears at a spot within range and lasts for the duration. It seems completely real, including sounds, smells, and temperature.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the spell lasts until dispelled, without requiring your concentration.',
    iconName: 'Image',
    classes: ['sorcerer', 'wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'Reality bends to your imagination—what is real, if not what others perceive?',
      jarvis: 'Holographic projection deployed. Full sensory simulation active.',
      deadpool: 'I\'m going to make a GIANT ME! No wait, a DRAGON! No wait, GIANT DRAGON ME!',
    },
  },
];

// ============================================
// 4TH LEVEL SPELLS
// ============================================

export const SORCERER_4TH_LEVEL: SpellDefinition[] = [
  {
    id: 'sorc-vitriolic-sphere',
    name: 'Vitriolic Sphere',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a drop of giant slug bile' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You point at a location within range, and a glowing, 1-foot-diameter ball of emerald acid streaks there and explodes in a 20-foot-radius sphere. Each creature in that area must make a Dexterity saving throw. On a failed save, a creature takes 10d4 acid damage and another 5d4 acid damage at the end of its next turn.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the initial damage increases by 2d4 for each slot level above 4th.',
    attackType: 'save',
    saveStat: 'DEX',
    damageType: 'acid',
    damageFormula: '10d4',
    iconName: 'Droplets',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'Caustic destruction spreads like a plague—nothing survives the dissolution.',
      jarvis: 'Acid sphere detonated. Damage: 10d4 initial plus 5d4 residual.',
      deadpool: 'It\'s a SNOT BOMB! But like, deadly snot. Gross but effective!',
    },
  },
  {
    id: 'sorc-dominate-beast',
    name: 'Dominate Beast',
    level: 4,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw.',
    higherLevels: 'When you cast this spell using a 5th-level slot, the duration is concentration, up to 10 minutes. At 6th level, up to 1 hour. At 7th level, up to 8 hours.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'Paw',
    classes: ['sorcerer', 'druid'],
    personalityQuips: {
      thunderhead: 'The beast\'s will bends to yours—predator becomes servant.',
      jarvis: 'Fauna control protocol active. Beast autonomy: overridden.',
      deadpool: 'Come here, big guy! Who\'s a good murder-beast? YOU ARE!',
    },
  },
  {
    id: 'sorc-confusion',
    name: 'Confusion',
    level: 4,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'three nut shells' },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'This spell assaults and twists creatures\' minds, spawning delusions and provoking uncontrolled action. Each creature in a 10-foot-radius sphere centered on a point you choose within range must succeed on a Wisdom saving throw when you cast this spell or be affected by it.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the radius of the sphere increases by 5 feet for each slot level above 4th.',
    attackType: 'save',
    saveStat: 'WIS',
    iconName: 'HelpCircle',
    classes: ['sorcerer', 'wizard', 'bard', 'druid'],
    personalityQuips: {
      thunderhead: 'Madness descends—friend and foe become indistinguishable.',
      jarvis: 'Cognitive disruption field active. Target actions: randomized.',
      deadpool: 'CHAOS! Beautiful, beautiful chaos! They don\'t know which way is up!',
    },
  },
  {
    id: 'sorc-blight',
    name: 'Blight',
    level: 4,
    school: 'necromancy',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much damage on a successful one. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
    attackType: 'save',
    saveStat: 'CON',
    damageType: 'necrotic',
    damageFormula: '8d8',
    iconName: 'Skull',
    classes: ['sorcerer', 'wizard', 'druid'],
    personalityQuips: {
      thunderhead: 'Life withers at your touch—entropy made manifest.',
      jarvis: 'Bio-degradation wave initiated. Cellular moisture: extracted.',
      deadpool: 'DRAIN THE SWAMP! But the swamp is their life force! Dark, I know.',
    },
  },
];

// ============================================
// 5TH LEVEL SPELLS
// ============================================

export const SORCERER_5TH_LEVEL: SpellDefinition[] = [
  {
    id: 'sorc-immolation',
    name: 'Immolation',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: false },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Flames wreathe one creature you can see within range. The target must make a Dexterity saving throw. It takes 8d6 fire damage on a failed save, or half as much damage on a successful one. On a failed save, the target also burns for the spell\'s duration. The burning target sheds bright light in a 30-foot radius.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d6 for each slot level above 5th.',
    attackType: 'save',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '8d6',
    iconName: 'Flame',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'They become the fire—consumed from within by hungering flames.',
      jarvis: 'Spontaneous combustion initiated. Target temperature: critical.',
      deadpool: 'YOU\'RE ON FIRE! Literally! Not a compliment this time!',
    },
  },
  {
    id: 'sorc-insect-plague',
    name: 'Insect Plague',
    level: 5,
    school: 'conjuration',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a few grains of sugar, some kernels of grain, and a smear of fat' },
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose within range. The sphere spreads around corners. When a creature enters the spell\'s area for the first time on a turn or starts its turn there, it must make a Constitution saving throw, taking 4d10 piercing damage on a failed save.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d10 for each slot level above 5th.',
    attackType: 'save',
    saveStat: 'CON',
    damageType: 'piercing',
    damageFormula: '4d10',
    iconName: 'Bug',
    classes: ['sorcerer', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'A swarm of hungry locusts descends—biblical in its devastation.',
      jarvis: 'Locust swarm deployed. Coverage area: 20-foot radius. Duration: 10 minutes.',
      deadpool: 'THE BEES! Wait no, locusts. THE LOCUSTS! THEY\'RE IN MY EYES!',
    },
  },
  {
    id: 'sorc-seeming',
    name: 'Seeming',
    level: 5,
    school: 'illusion',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'This spell allows you to change the appearance of any number of creatures that you can see within range. You give each target you choose a new, illusory appearance. An unwilling target can make a Charisma saving throw, and if it succeeds, it is unaffected by this spell.',
    attackType: 'save',
    saveStat: 'CHA',
    iconName: 'Users',
    classes: ['sorcerer', 'wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'Faces shift like masks—the whole party remade in new guises.',
      jarvis: 'Mass holographic overlay initiated. All targets: visually transformed.',
      deadpool: 'MAKEOVER TIME! Everyone gets a new face! It\'s like witness protection but fun!',
    },
  },
  {
    id: 'sorc-enervation',
    name: 'Enervation',
    level: 5,
    school: 'necromancy',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'A tendril of inky darkness reaches out from you, touching a creature you can see within range to drain life from it. The target must make a Dexterity saving throw. On a failed save, the target takes 4d8 necrotic damage, and until the spell ends, you can use your action to deal 4d8 necrotic damage to the target automatically. The spell ends if you use your action to do anything else, if the target is ever outside the spell\'s range, or if the target has total cover from you.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
    attackType: 'save',
    saveStat: 'DEX',
    damageType: 'necrotic',
    damageFormula: '4d8',
    iconName: 'Skull',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'A tether of shadow drains their essence—their life sustains you.',
      jarvis: 'Life force extraction in progress. Energy transfer: sustained.',
      deadpool: 'Vampiric tentacle! *slurp slurp* Tastes like... regret.',
    },
  },
  {
    id: 'sorc-creation',
    name: 'Creation',
    level: 5,
    school: 'illusion',
    castingTime: '1_minute',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a tiny piece of matter of the same type of the item you plan to create' },
    duration: 'Special',
    concentration: false,
    ritual: false,
    description: 'You pull wisps of shadow material from the Shadowfell to create a nonliving object of vegetable matter within range: soft goods, rope, wood, or something similar. You can also use this spell to create mineral objects such as stone, crystal, or metal.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the cube increases by 5 feet for each slot level above 5th.',
    iconName: 'Package',
    classes: ['sorcerer', 'wizard'],
    personalityQuips: {
      thunderhead: 'Shadow becomes substance—conjure what you need from nothing.',
      jarvis: 'Matter synthesis complete. Object durability: temporary.',
      deadpool: 'I just made a chair! Out of NOTHING! ...it\'s going to disappear soon. Sit fast!',
    },
  },
];

// ============================================
// EXPORT ALL SORCERER SPELLS
// ============================================

export const SORCERER_SPELLS: SpellDefinition[] = [
  ...SORCERER_CANTRIPS,
  ...SORCERER_1ST_LEVEL,
  ...SORCERER_2ND_LEVEL,
  ...SORCERER_3RD_LEVEL,
  ...SORCERER_4TH_LEVEL,
  ...SORCERER_5TH_LEVEL,
];

// Helper to get Sorcerer spells by level
export function getSorcererSpellsByLevel(level: number): SpellDefinition[] {
  return SORCERER_SPELLS.filter(spell => spell.level === level);
}

// Count spells by level
export function getSorcererSpellCounts(): Record<number, number> {
  const counts: Record<number, number> = {};
  SORCERER_SPELLS.forEach(spell => {
    counts[spell.level] = (counts[spell.level] || 0) + 1;
  });
  return counts;
}
