// Wizard Spell List
// D&D 5e Wizard spells organized by level

import { SpellDefinition } from '../types';

// ============================================
// CANTRIPS
// ============================================

export const WIZARD_CANTRIPS: SpellDefinition[] = [
  {
    id: 'fire-bolt-wizard',
    name: 'Fire Bolt',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried.',
    higherLevels: 'This spell\'s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).',
    attackType: 'ranged',
    damageType: 'fire',
    damageFormula: '1d10',
    iconName: 'Flame',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'The flames of arcane power surge forth. Let your enemies burn.',
      jarvis: 'Projecting thermal energy bolt. Targeting system engaged.',
      deadpool: 'Pew pew! Fire go brrrr! ...Wait, that\'s cold. Fire go FWOOSH!',
    },
  },
  {
    id: 'ray-of-frost-wizard',
    name: 'Ray of Frost',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.',
    higherLevels: 'This spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
    attackType: 'ranged',
    damageType: 'cold',
    damageFormula: '1d8',
    iconName: 'Snowflake',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Winter\'s grasp reaches out. The cold slows all things.',
      jarvis: 'Cryogenic beam activated. Target velocity reduction calculated.',
      deadpool: 'Let it go, let it gooo! Wait, wrong franchise. ICE ICE BABY!',
    },
  },
  {
    id: 'prestidigitation-wizard',
    name: 'Prestidigitation',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '10 feet',
    components: { verbal: true, somatic: true },
    duration: 'Up to 1 hour',
    concentration: false,
    ritual: false,
    description: 'This spell is a minor magical trick that novice spellcasters use for practice. You create one of several minor effects: a harmless sensory effect, light or snuff a small flame, clean or soil an object, chill/warm/flavor nonliving material, make a small mark or symbol, or create a trinket that fits in your hand.',
    iconName: 'Sparkles',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Even small magics have their purpose. Practice the fundamentals.',
      jarvis: 'Minor manipulation subroutines engaged. Utility functions ready.',
      deadpool: 'Party tricks! I can make your drink taste like tacos. You\'re welcome.',
    },
  },
  {
    id: 'light-wizard',
    name: 'Light',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a firefly or phosphorescent moss' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light.',
    iconName: 'Sun',
    classes: ['wizard', 'sorcerer', 'cleric', 'bard'],
    personalityQuips: {
      thunderhead: 'Illuminate the darkness. Knowledge awaits in the light.',
      jarvis: 'Photon emission enabled. Luminosity at optimal levels.',
      deadpool: 'And God said, let there be light! And I said, DONE!',
    },
  },
  {
    id: 'mage-hand-wizard',
    name: 'Mage Hand',
    level: 0,
    school: 'conjuration',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it. The hand can manipulate objects, open doors and containers, stow or retrieve items from open containers, or pour the contents of a vial. The hand can\'t attack, activate magic items, or carry more than 10 pounds.',
    iconName: 'Hand',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Extend your reach beyond the physical. The arcane serves.',
      jarvis: 'Remote manipulation unit deployed. Precise control established.',
      deadpool: 'It\'s like Thing from Addams Family but MAGICAL! High five! ...Anyone?',
    },
  },
  {
    id: 'minor-illusion-wizard',
    name: 'Minor Illusion',
    level: 0,
    school: 'illusion',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: false, somatic: true, material: 'a bit of fleece' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it or cast this spell again. If you create an image, it must fit within a 5-foot cube. The image can\'t create sound, light, smell, or any other sensory effect. Physical interaction reveals it as an illusion.',
    iconName: 'Eye',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Reality is but perception. Master illusion, master minds.',
      jarvis: 'Holographic projection initiated. Sensory parameters configured.',
      deadpool: 'Is it real? Is it fake? Nobody knows! *wiggly finger noises*',
    },
  },
  {
    id: 'shocking-grasp-wizard',
    name: 'Shocking Grasp',
    level: 0,
    school: 'evocation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can\'t take reactions until the start of its next turn.',
    higherLevels: 'This spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
    attackType: 'melee',
    damageType: 'lightning',
    damageFormula: '1d8',
    iconName: 'Zap',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Lightning arcs through your fingers. Strike true.',
      jarvis: 'Electromagnetic discharge ready. Contact required for delivery.',
      deadpool: 'ZAP! No reactions for you! It\'s like a timeout but SHOCKING!',
    },
  },
  {
    id: 'chill-touch-wizard',
    name: 'Chill Touch',
    level: 0,
    school: 'necromancy',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature. On a hit, the target takes 1d8 necrotic damage, and it can\'t regain hit points until the start of your next turn. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.',
    higherLevels: 'This spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
    attackType: 'ranged',
    damageType: 'necrotic',
    damageFormula: '1d8',
    iconName: 'Skull',
    classes: ['wizard', 'sorcerer', 'warlock'],
    personalityQuips: {
      thunderhead: 'Death\'s cold grip reaches across the void. Deny them healing.',
      jarvis: 'Necrotic energy projection. Regeneration suppression active.',
      deadpool: 'Spooky scary skeletons send shivers down your... wait, it\'s just a hand.',
    },
  },
  {
    id: 'message-wizard',
    name: 'Message',
    level: 0,
    school: 'transmutation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a short piece of copper wire' },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier.',
    iconName: 'MessageCircle',
    classes: ['wizard', 'sorcerer', 'bard'],
    personalityQuips: {
      thunderhead: 'Words carry across the arcane. Secrets travel unseen.',
      jarvis: 'Secure communication channel established. Encrypted transmission.',
      deadpool: '*whispers* Hey... hey... HEY! I know you can hear me!',
    },
  },
  {
    id: 'mending-wizard',
    name: 'Mending',
    level: 0,
    school: 'transmutation',
    castingTime: '1_minute',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'two lodestones' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage.',
    iconName: 'Wrench',
    classes: ['wizard', 'sorcerer', 'bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'Restore what was broken. Time reverses for small things.',
      jarvis: 'Molecular reconstruction in progress. Structural integrity restored.',
      deadpool: 'Flex Tape ain\'t got nothing on this! Magic fixes EVERYTHING!',
    },
  },
];

// ============================================
// 1ST LEVEL SPELLS
// ============================================

export const WIZARD_1ST_LEVEL: SpellDefinition[] = [
  {
    id: 'magic-missile-wizard',
    name: 'Magic Missile',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
    attackType: 'auto',
    damageType: 'force',
    damageFormula: '1d4+1',
    iconName: 'Zap',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Force incarnate. These darts never miss their mark.',
      jarvis: 'Guided projectiles launched. Impact guaranteed.',
      deadpool: 'Pew pew pew! Three for the price of one! Can\'t miss, won\'t miss!',
    },
  },
  {
    id: 'shield-wizard',
    name: 'Shield',
    level: 1,
    school: 'abjuration',
    castingTime: 'reaction',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 round',
    concentration: false,
    ritual: false,
    description: 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
    iconName: 'Shield',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'The barrier rises. No harm shall pass.',
      jarvis: 'Defensive shield deployed. +5 AC bonus active.',
      deadpool: 'NOPE! Not today, buddy! *invisible wall slam*',
    },
  },
  {
    id: 'mage-armor-wizard',
    name: 'Mage Armor',
    level: 1,
    school: 'abjuration',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a piece of cured leather' },
    duration: '8 hours',
    concentration: false,
    ritual: false,
    description: 'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it until the spell ends. The target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
    iconName: 'ShieldCheck',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Arcane protection weaves around you. Be bold.',
      jarvis: 'Magical armor matrix established. Base AC set to 13 + DEX.',
      deadpool: 'Invisible armor! It\'s like being naked but SAFE!',
    },
  },
  {
    id: 'detect-magic-wizard',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: 'Up to 10 minutes',
    concentration: true,
    ritual: true,
    description: 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.',
    iconName: 'Search',
    classes: ['wizard', 'sorcerer', 'bard', 'cleric', 'druid'],
    personalityQuips: {
      thunderhead: 'Open your senses to the weave. See what is hidden.',
      jarvis: 'Magical signature scanner active. Detecting arcane emanations.',
      deadpool: 'My spidey senses are tingling! Wait, wrong universe. MAGIC VISION!',
    },
  },
  {
    id: 'find-familiar-wizard',
    name: 'Find Familiar',
    level: 1,
    school: 'conjuration',
    castingTime: 'ritual',
    range: '10 feet',
    components: { verbal: true, somatic: true, material: '10 gp worth of charcoal, incense, and herbs consumed in a brass brazier', materialConsumed: true, materialCost: 10 },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog, hawk, lizard, octopus, owl, poisonous snake, fish, rat, raven, sea horse, spider, or weasel. The familiar acts independently but obeys your commands. You can communicate telepathically with it while within 100 feet.',
    iconName: 'Cat',
    classes: ['wizard'],
    personalityQuips: {
      thunderhead: 'A spirit companion answers your call. Treat it well.',
      jarvis: 'Familiar spirit bound. Telepathic link established.',
      deadpool: 'BEST. SPELL. EVER. I want an owl. No wait, a cat. NO WAIT, A SPIDER!',
    },
  },
  {
    id: 'sleep-wizard',
    name: 'Sleep',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of fine sand, rose petals, or a cricket' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.',
    iconName: 'Moon',
    classes: ['wizard', 'sorcerer', 'bard'],
    personalityQuips: {
      thunderhead: 'Dreams claim the weak-willed. Rest now, foes.',
      jarvis: 'Sleep induction field activated. Calculating hit point thresholds.',
      deadpool: 'Nighty night! Don\'t let the bed bugs... actually, just sleep forever.',
    },
  },
  {
    id: 'charm-person-wizard',
    name: 'Charm Person',
    level: 1,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails, it is charmed by you until the spell ends or until you or your companions do anything harmful to it.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
    saveStat: 'WIS',
    iconName: 'Heart',
    classes: ['wizard', 'sorcerer', 'bard', 'druid', 'warlock'],
    personalityQuips: {
      thunderhead: 'Bend their will. Friends are useful tools.',
      jarvis: 'Social manipulation subroutine engaged. Charm protocols active.',
      deadpool: 'Be my friend! BE MY FRIEND! ...Or else. Just kidding! Maybe.',
    },
  },
  {
    id: 'disguise-self-wizard',
    name: 'Disguise Self',
    level: 1,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'You make yourself—including your clothing, armor, weapons, and other belongings on your person—look different until the spell ends or until you use your action to dismiss it. You can seem 1 foot shorter or taller and can appear thin, fat, or in between. You can\'t change your body type.',
    iconName: 'User',
    classes: ['wizard', 'sorcerer', 'bard'],
    personalityQuips: {
      thunderhead: 'Become another. Identity is but a mask.',
      jarvis: 'Holographic disguise matrix active. Appearance modified.',
      deadpool: 'I\'m Ryan Reynolds! Wait, no, I\'m already... nevermind. I\'m SOMEONE ELSE!',
    },
  },
  {
    id: 'identify-wizard',
    name: 'Identify',
    level: 1,
    school: 'divination',
    castingTime: 'ritual',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a pearl worth at least 100 gp and an owl feather', materialCost: 100 },
    duration: 'Instantaneous',
    concentration: false,
    ritual: true,
    description: 'You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any.',
    iconName: 'Search',
    classes: ['wizard', 'bard'],
    personalityQuips: {
      thunderhead: 'Secrets of the arcane reveal themselves. Knowledge is power.',
      jarvis: 'Item analysis complete. Properties catalogued.',
      deadpool: 'Ooh, what does THIS button do? Oh wait, now I KNOW what it does!',
    },
  },
  {
    id: 'feather-fall-wizard',
    name: 'Feather Fall',
    level: 1,
    school: 'transmutation',
    castingTime: 'reaction',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: 'a small feather or piece of down' },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Choose up to five falling creatures within range. A falling creature\'s rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its feet, and the spell ends for that creature.',
    iconName: 'Feather',
    classes: ['wizard', 'sorcerer', 'bard'],
    personalityQuips: {
      thunderhead: 'Gravity bends to your will. Fall like a leaf.',
      jarvis: 'Gravitational dampeners engaged. Safe landing assured.',
      deadpool: 'YEET yourself off cliffs without consequences! ...I love magic.',
    },
  },
  {
    id: 'thunderwave-wizard',
    name: 'Thunderwave',
    level: 1,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (15-foot cube)',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
    saveStat: 'CON',
    damageType: 'thunder',
    damageFormula: '2d8',
    iconName: 'Volume2',
    classes: ['wizard', 'sorcerer', 'bard', 'druid'],
    personalityQuips: {
      thunderhead: 'Thunder rolls from your hands. Push them back.',
      jarvis: 'Sonic shockwave generated. Area effect initiated.',
      deadpool: 'BOOM BOOM BOOM! Get off my lawn! YEET!',
    },
  },
];

// ============================================
// 2ND LEVEL SPELLS
// ============================================

export const WIZARD_2ND_LEVEL: SpellDefinition[] = [
  {
    id: 'misty-step-wizard',
    name: 'Misty Step',
    level: 2,
    school: 'conjuration',
    castingTime: 'bonus_action',
    range: 'Self',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    iconName: 'Sparkles',
    classes: ['wizard', 'sorcerer', 'warlock'],
    personalityQuips: {
      thunderhead: 'Step through the veil. Distance is illusion.',
      jarvis: 'Short-range teleportation executed. Destination reached.',
      deadpool: 'BAMF! I\'m Nightcrawler now! ...Kinda.',
    },
  },
  {
    id: 'invisibility-wizard',
    name: 'Invisibility',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'an eyelash encased in gum arabic' },
    duration: 'Up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. The spell ends for a target that attacks or casts a spell.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
    iconName: 'EyeOff',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Vanish from sight. Unseen, unstoppable.',
      jarvis: 'Light refraction matrix active. Visual signature eliminated.',
      deadpool: 'Now you see me... now you don\'t! Peek-a-BOO!',
    },
  },
  {
    id: 'hold-person-wizard',
    name: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.',
    saveStat: 'WIS',
    iconName: 'Lock',
    classes: ['wizard', 'sorcerer', 'bard', 'cleric', 'druid', 'warlock'],
    personalityQuips: {
      thunderhead: 'Freeze their very essence. They cannot move.',
      jarvis: 'Paralysis field engaged. Motor functions suspended.',
      deadpool: 'FREEZE! No, literally. You can\'t move. It\'s hilarious.',
    },
  },
  {
    id: 'mirror-image-wizard',
    name: 'Mirror Image',
    level: 2,
    school: 'illusion',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true },
    duration: '1 minute',
    concentration: false,
    ritual: false,
    description: 'Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions. Each time a creature targets you with an attack, roll a d20 to determine whether the attack instead targets one of your duplicates.',
    iconName: 'Users',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Multiply yourself. Confusion is a weapon.',
      jarvis: 'Holographic decoys deployed. Attack diversion active.',
      deadpool: 'There\'s THREE of me now! The world is NOT ready!',
    },
  },
  {
    id: 'scorching-ray-wizard',
    name: 'Scorching Ray',
    level: 2,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.',
    attackType: 'ranged',
    damageType: 'fire',
    damageFormula: '2d6',
    iconName: 'Flame',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Flames streak from your fingers. Burn them all.',
      jarvis: 'Triple thermal lance targeting. Fire at will.',
      deadpool: 'Pew pew pew! Three fire beams! I\'m basically a dragon now!',
    },
  },
  {
    id: 'web-wizard',
    name: 'Web',
    level: 2,
    school: 'conjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of spiderweb' },
    duration: 'Up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area. Each creature that enters the webs or starts its turn there must succeed on a Dexterity saving throw or be restrained.',
    saveStat: 'DEX',
    iconName: 'Globe',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Trap them in strands of arcane silk. None escape.',
      jarvis: 'Web matrix deployed. Area denial established.',
      deadpool: 'Spider-Man vibes! Thwip thwip! ...But stickier and grosser.',
    },
  },
  {
    id: 'suggestion-wizard',
    name: 'Suggestion',
    level: 2,
    school: 'enchantment',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: false, material: 'a snake\'s tongue and either a bit of honeycomb or a drop of sweet oil' },
    duration: 'Up to 8 hours',
    concentration: true,
    ritual: false,
    description: 'You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. The suggestion must be worded in such a manner as to make the course of action sound reasonable.',
    saveStat: 'WIS',
    iconName: 'MessageCircle',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Plant the seed. Let it grow in their mind.',
      jarvis: 'Subconscious influence initiated. Suggestion implanted.',
      deadpool: 'Hey, you should totally give me all your money. It\'s a GREAT idea!',
    },
  },
  {
    id: 'see-invisibility-wizard',
    name: 'See Invisibility',
    level: 2,
    school: 'divination',
    castingTime: 'action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a pinch of talc and a small sprinkling of powdered silver' },
    duration: '1 hour',
    concentration: false,
    ritual: false,
    description: 'For the duration, you see invisible creatures and objects as if they were visible, and you can see into the Ethereal Plane. Ethereal creatures and objects appear ghostly and translucent.',
    iconName: 'Eye',
    classes: ['wizard', 'sorcerer', 'bard'],
    personalityQuips: {
      thunderhead: 'Pierce the veil. Nothing hides from true sight.',
      jarvis: 'Enhanced visual spectrum enabled. Invisible signatures detected.',
      deadpool: 'I SEE YOU! Sneaky invisible people can\'t hide from ME!',
    },
  },
];

// ============================================
// 3RD LEVEL SPELLS
// ============================================

export const WIZARD_3RD_LEVEL: SpellDefinition[] = [
  {
    id: 'fireball-wizard',
    name: 'Fireball',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a tiny ball of bat guano and sulfur' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '8d6',
    iconName: 'Flame',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'The ultimate destruction spell. Let them burn.',
      jarvis: 'Thermobaric detonation initiated. Blast radius: 20 feet.',
      deadpool: 'EXPLOOOOSION! This is why everyone plays Wizard!',
    },
  },
  {
    id: 'counterspell-wizard',
    name: 'Counterspell',
    level: 3,
    school: 'abjuration',
    castingTime: 'reaction',
    range: '60 feet',
    components: { verbal: false, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell\'s level.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
    iconName: 'XCircle',
    classes: ['wizard', 'sorcerer', 'warlock'],
    personalityQuips: {
      thunderhead: 'Their magic fades to nothing. Assert dominance.',
      jarvis: 'Spell disruption field activated. Countermeasures deployed.',
      deadpool: 'NOPE! That\'s a big fat NOPE to your spell! Get countered, nerd!',
    },
  },
  {
    id: 'dispel-magic-wizard',
    name: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell\'s level.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell\'s level is equal to or less than the level of the spell slot you used.',
    iconName: 'Trash2',
    classes: ['wizard', 'sorcerer', 'bard', 'cleric', 'druid', 'warlock'],
    personalityQuips: {
      thunderhead: 'Unravel their enchantments. Magic bows to greater magic.',
      jarvis: 'Magical signature nullification in progress. Effects terminated.',
      deadpool: 'Magic be GONE! Alakazam your buffs are TOAST!',
    },
  },
  {
    id: 'fly-wizard',
    name: 'Fly',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a wing feather from any bird' },
    duration: 'Up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.',
    iconName: 'Feather',
    classes: ['wizard', 'sorcerer', 'warlock'],
    personalityQuips: {
      thunderhead: 'Defy gravity. The sky belongs to you now.',
      jarvis: 'Anti-gravity field engaged. Flight capability granted.',
      deadpool: 'I believe I can fly! I believe I can touch the sky! *actually does*',
    },
  },
  {
    id: 'haste-wizard',
    name: 'Haste',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a shaving of licorice root' },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a willing creature that you can see within range. Until the spell ends, the target\'s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns. When the spell ends, the target can\'t move or take actions until after its next turn.',
    iconName: 'Zap',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Time bends. Move faster than thought.',
      jarvis: 'Temporal acceleration active. Performance enhanced 200%.',
      deadpool: 'GOTTA GO FAST! I\'m the blue hedgehog now! Woooosh!',
    },
  },
  {
    id: 'lightning-bolt-wizard',
    name: 'Lightning Bolt',
    level: 3,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (100-foot line)',
    components: { verbal: true, somatic: true, material: 'a bit of fur and a rod of amber, crystal, or glass' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    saveStat: 'DEX',
    damageType: 'lightning',
    damageFormula: '8d6',
    iconName: 'Zap',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Lightning answers your call. Strike them down.',
      jarvis: 'Electrical discharge: 100-foot vector. 8d6 damage output.',
      deadpool: 'UNLIMITED POWER! *Palpatine hands* BZZZZZZT!',
    },
  },
  {
    id: 'slow-wizard',
    name: 'Slow',
    level: 3,
    school: 'transmutation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a drop of molasses' },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a Wisdom saving throw or be affected for the duration. An affected target\'s speed is halved, it takes a −2 penalty to AC and Dexterity saving throws, and it can\'t use reactions.',
    saveStat: 'WIS',
    iconName: 'Clock',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Time crawls for them. You have eternity.',
      jarvis: 'Temporal deceleration field active. Target efficiency reduced.',
      deadpool: 'Everything is in slow-mo! Like an action movie but REAL!',
    },
  },
  {
    id: 'hypnotic-pattern-wizard',
    name: 'Hypnotic Pattern',
    level: 3,
    school: 'illusion',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: false, somatic: true, material: 'a glowing stick of incense or a crystal vial filled with phosphorescent material' },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. Each creature in the area must make a Wisdom saving throw. On a failure, the creature becomes charmed for the duration. While charmed, the creature is incapacitated and has a speed of 0.',
    saveStat: 'WIS',
    iconName: 'Eye',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Mesmerizing beauty. They cannot look away.',
      jarvis: 'Cognitive overload pattern deployed. Mass incapacitation.',
      deadpool: 'Pretty colors! So pretty! Everyone just... stare at them forever.',
    },
  },
];

// ============================================
// 4TH LEVEL SPELLS
// ============================================

export const WIZARD_4TH_LEVEL: SpellDefinition[] = [
  {
    id: 'polymorph-wizard',
    name: 'Polymorph',
    level: 4,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a caterpillar cocoon' },
    duration: 'Up to 1 hour',
    concentration: true,
    ritual: false,
    description: 'This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The target\'s game statistics, including mental ability scores, are replaced by the statistics of the chosen beast. It retains its alignment and personality.',
    saveStat: 'WIS',
    iconName: 'Rabbit',
    classes: ['wizard', 'sorcerer', 'bard', 'druid'],
    personalityQuips: {
      thunderhead: 'Reshape reality. Become the beast within.',
      jarvis: 'Biological reconfiguration initiated. Form alteration complete.',
      deadpool: 'Turn the bad guy into a TURTLE! Or your friend into a T-REX!',
    },
  },
  {
    id: 'greater-invisibility-wizard',
    name: 'Greater Invisibility',
    level: 4,
    school: 'illusion',
    castingTime: 'action',
    range: 'Touch',
    components: { verbal: true, somatic: true },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person.',
    iconName: 'EyeOff',
    classes: ['wizard', 'sorcerer', 'bard'],
    personalityQuips: {
      thunderhead: 'True invisibility. Attack without breaking the veil.',
      jarvis: 'Advanced cloaking system engaged. Persistent invisibility active.',
      deadpool: 'Invisible AND can still attack? This is BROKEN! I love it!',
    },
  },
  {
    id: 'dimension-door-wizard',
    name: 'Dimension Door',
    level: 4,
    school: 'conjuration',
    castingTime: 'action',
    range: '500 feet',
    components: { verbal: true, somatic: false },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction.',
    iconName: 'ArrowRightCircle',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Step through dimensions. Distance means nothing.',
      jarvis: 'Long-range teleportation executing. Destination coordinates locked.',
      deadpool: '500 feet of NOPE! Bye! See you somewhere else!',
    },
  },
  {
    id: 'wall-of-fire-wizard',
    name: 'Wall of Fire',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a small piece of phosphorus' },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter. One side of the wall deals 5d8 fire damage to each creature that ends its turn within 10 feet of it.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
    saveStat: 'DEX',
    damageType: 'fire',
    damageFormula: '5d8',
    iconName: 'Flame',
    classes: ['wizard', 'sorcerer', 'druid'],
    personalityQuips: {
      thunderhead: 'A barrier of flame. None shall pass.',
      jarvis: 'Thermal barrier erected. Zone denial established.',
      deadpool: 'A WALL OF FIRE! Like a really hot fence! Don\'t touch it!',
    },
  },
  {
    id: 'banishment-wizard',
    name: 'Banishment',
    level: 4,
    school: 'abjuration',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'an item distasteful to the target' },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to a different plane than the one you\'re on, it returns to its home plane when the spell ends.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.',
    saveStat: 'CHA',
    iconName: 'LogOut',
    classes: ['wizard', 'sorcerer', 'cleric', 'warlock'],
    personalityQuips: {
      thunderhead: 'Be gone from this realm. Return whence you came.',
      jarvis: 'Dimensional displacement initiated. Target removed from plane.',
      deadpool: 'You don\'t belong here! Go home! YEET to another dimension!',
    },
  },
  {
    id: 'ice-storm-wizard',
    name: 'Ice Storm',
    level: 4,
    school: 'evocation',
    castingTime: 'action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of dust and a few drops of water' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 cold damage on a failed save, or half as much on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the bludgeoning damage increases by 1d8 for each slot level above 4th.',
    saveStat: 'DEX',
    damageType: 'cold',
    damageFormula: '2d8+4d6',
    iconName: 'Snowflake',
    classes: ['wizard', 'sorcerer', 'druid'],
    personalityQuips: {
      thunderhead: 'Winter descends in fury. Freeze and shatter.',
      jarvis: 'Cryogenic bombardment initiated. Impact zone calculated.',
      deadpool: 'It\'s hailing! REALLY BIG HAIL! Like bowling ball sized ICE!',
    },
  },
];

// ============================================
// 5TH LEVEL SPELLS
// ============================================

export const WIZARD_5TH_LEVEL: SpellDefinition[] = [
  {
    id: 'telekinesis-wizard',
    name: 'Telekinesis',
    level: 5,
    school: 'transmutation',
    castingTime: 'action',
    range: '60 feet',
    components: { verbal: true, somatic: true },
    duration: 'Up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect.',
    iconName: 'Hand',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'Mind over matter. Your will becomes reality.',
      jarvis: 'Psychokinetic field active. Remote manipulation enabled.',
      deadpool: 'I\'m moving things WITH MY MIND! I\'m basically Jean Grey!',
    },
  },
  {
    id: 'hold-monster-wizard',
    name: 'Hold Monster',
    level: 5,
    school: 'enchantment',
    castingTime: 'action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, you can target one additional creature for each slot level above 5th.',
    saveStat: 'WIS',
    iconName: 'Lock',
    classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    personalityQuips: {
      thunderhead: 'Even the mightiest beasts bow to mental domination.',
      jarvis: 'Universal paralysis protocol active. No creature type restrictions.',
      deadpool: 'Freeze! Even if you\'re a dragon or a demon or whatever! FREEZE!',
    },
  },
  {
    id: 'cone-of-cold-wizard',
    name: 'Cone of Cold',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: 'Self (60-foot cone)',
    components: { verbal: true, somatic: true, material: 'a small crystal or glass cone' },
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature killed by this spell becomes a frozen statue.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
    saveStat: 'CON',
    damageType: 'cold',
    damageFormula: '8d8',
    iconName: 'Snowflake',
    classes: ['wizard', 'sorcerer'],
    personalityQuips: {
      thunderhead: 'The bitter cold of the void. Freeze solid.',
      jarvis: 'Cryogenic cone blast initiated. 60-foot area affected.',
      deadpool: 'Brain freeze! But like... for your WHOLE BODY! Popsicle time!',
    },
  },
  {
    id: 'wall-of-force-wizard',
    name: 'Wall of Force',
    level: 5,
    school: 'evocation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of powder made by crushing a clear gemite' },
    duration: 'Up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose: horizontally, vertically, or diagonally. Nothing can physically pass through the wall. It is immune to all damage.',
    iconName: 'Shield',
    classes: ['wizard'],
    personalityQuips: {
      thunderhead: 'An unbreakable barrier. Pure force given form.',
      jarvis: 'Impenetrable force field generated. Maximum durability achieved.',
      deadpool: 'Invisible wall of NOPE! You can\'t hit it, you can\'t break it!',
    },
  },
  {
    id: 'animate-objects-wizard',
    name: 'Animate Objects',
    level: 5,
    school: 'transmutation',
    castingTime: 'action',
    range: '120 feet',
    components: { verbal: true, somatic: true },
    duration: 'Up to 1 minute',
    concentration: true,
    ritual: false,
    description: 'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four, and Huge targets count as eight. The animated objects fight for you.',
    iconName: 'Box',
    classes: ['wizard', 'sorcerer', 'bard'],
    personalityQuips: {
      thunderhead: 'Life springs from the inanimate. Your army awaits.',
      jarvis: 'Object animation subroutines active. Combat units deployed.',
      deadpool: 'ATTACK FURNITURE! Attack of the killer chairs! This is amazing!',
    },
  },
  {
    id: 'scrying-wizard',
    name: 'Scrying',
    level: 5,
    school: 'divination',
    castingTime: '10_minutes',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water', materialCost: 1000 },
    duration: 'Up to 10 minutes',
    concentration: true,
    ritual: false,
    description: 'You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a Wisdom saving throw, which is modified by how well you know the target and the sort of physical connection you have to it.',
    saveStat: 'WIS',
    iconName: 'Eye',
    classes: ['wizard', 'bard', 'cleric', 'druid', 'warlock'],
    personalityQuips: {
      thunderhead: 'The eye sees all. Distance cannot hide them.',
      jarvis: 'Long-range surveillance initiated. Target location acquired.',
      deadpool: 'Creepy crystal ball time! I\'m watching yooooou! *waves*',
    },
  },
];

// ============================================
// COMBINED EXPORT
// ============================================

export const WIZARD_SPELLS: SpellDefinition[] = [
  ...WIZARD_CANTRIPS,
  ...WIZARD_1ST_LEVEL,
  ...WIZARD_2ND_LEVEL,
  ...WIZARD_3RD_LEVEL,
  ...WIZARD_4TH_LEVEL,
  ...WIZARD_5TH_LEVEL,
];

/**
 * Get all Wizard spells by level
 */
export function getWizardSpellsByLevel(level: number): SpellDefinition[] {
  return WIZARD_SPELLS.filter(spell => spell.level === level);
}
