import { Consumable } from './types';

export const poisons: Consumable[] = [
  // Ingested Poisons
  {
    id: 'poison-assassins-blood',
    name: "Assassin's Blood",
    type: 'poison',
    rarity: 'uncommon',
    effect: 'DC 10 Con save or take 1d12 poison damage and be poisoned for 24 hours',
    duration: '24 hours if poisoned',
    description: 'A creature that ingests this poison must make a DC 10 Constitution saving throw. On a failed save, it takes 1d12 poison damage and is poisoned for 24 hours.',
    usageType: 'ingested',
    icon: 'Droplets',
  },
  {
    id: 'poison-midnight-tears',
    name: 'Midnight Tears',
    type: 'poison',
    rarity: 'very_rare',
    effect: 'DC 17 Con save at midnight or take 9d6 poison damage (no effect until midnight)',
    duration: 'Triggers at midnight',
    description: 'A creature that ingests this poison suffers no effect until midnight. If the poison has not been neutralized, the creature must make a DC 17 Constitution saving throw.',
    usageType: 'ingested',
    icon: 'Moon',
  },
  {
    id: 'poison-torpor',
    name: 'Torpor',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 15 Con save or be poisoned for 4d6 hours (unconscious, wake if damaged)',
    duration: '4d6 hours',
    description: 'A creature that ingests this poison must succeed on a DC 15 Constitution saving throw or become poisoned for 4d6 hours. The poisoned creature is incapacitated.',
    usageType: 'ingested',
    icon: 'BedDouble',
  },

  // Contact Poisons
  {
    id: 'poison-essence-of-ether',
    name: 'Essence of Ether',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 15 Con save or be poisoned for 8 hours (unconscious, wake if damaged)',
    duration: '8 hours',
    description: 'A creature subjected to this poison must succeed on a DC 15 Constitution saving throw or become poisoned for 8 hours. The poisoned creature is unconscious.',
    usageType: 'contact',
    icon: 'Wind',
  },
  {
    id: 'poison-malice',
    name: 'Malice',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 15 Con save or be poisoned for 1 hour (blinded)',
    duration: '1 hour',
    description: 'A creature subjected to this poison must succeed on a DC 15 Constitution saving throw or become poisoned for 1 hour. The poisoned creature is blinded.',
    usageType: 'contact',
    icon: 'EyeOff',
  },
  {
    id: 'poison-oil-of-taggit',
    name: 'Oil of Taggit',
    type: 'poison',
    rarity: 'uncommon',
    effect: 'DC 13 Con save or be poisoned for 24 hours (unconscious, wake if damaged)',
    duration: '24 hours',
    description: 'A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or become poisoned for 24 hours. The poisoned creature is unconscious.',
    usageType: 'contact',
    icon: 'Droplet',
  },

  // Inhaled Poisons
  {
    id: 'poison-burnt-othur-fumes',
    name: 'Burnt Othur Fumes',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 13 Con save or take 3d6 poison damage, repeat save every minute for 1 minute',
    duration: '1 minute (repeated saves)',
    description: 'A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or take 3d6 poison damage, and must repeat the saving throw at the start of each of its turns.',
    usageType: 'inhale',
    icon: 'CloudFog',
  },
  {
    id: 'poison-truth-serum',
    name: 'Truth Serum',
    type: 'poison',
    rarity: 'uncommon',
    effect: "DC 11 Con save or can't lie for 1 hour",
    duration: '1 hour',
    description: "A creature subjected to this poison must succeed on a DC 11 Constitution saving throw or become poisoned for 1 hour. The poisoned creature can't knowingly speak a lie.",
    usageType: 'inhale',
    icon: 'MessageCircle',
  },

  // Injury Poisons
  {
    id: 'poison-basic',
    name: 'Basic Poison',
    type: 'poison',
    rarity: 'common',
    effect: 'DC 10 Con save or take 1d4 poison damage',
    duration: 'Instant',
    description: 'The most common form of injury poison. Apply to a weapon to deal extra poison damage on the next hit.',
    usageType: 'injury',
    icon: 'Syringe',
  },
  {
    id: 'poison-drow',
    name: 'Drow Poison',
    type: 'poison',
    rarity: 'uncommon',
    effect: 'DC 13 Con save or be poisoned for 1 hour (unconscious if failed by 5+)',
    duration: '1 hour',
    description: 'This poison is typically made only by the drow. A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or be poisoned for 1 hour.',
    usageType: 'injury',
    icon: 'Spider',
  },
  {
    id: 'poison-serpent-venom',
    name: 'Serpent Venom',
    type: 'poison',
    rarity: 'uncommon',
    effect: 'DC 11 Con save or take 3d6 poison damage',
    duration: 'Instant',
    description: 'This poison is harvested from a dead or incapacitated giant poisonous snake. A creature subjected to this poison must succeed on a DC 11 Constitution saving throw.',
    usageType: 'injury',
    icon: 'Waves',
  },
  {
    id: 'poison-wyvern',
    name: 'Wyvern Poison',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 15 Con save or take 7d6 poison damage',
    duration: 'Instant',
    description: 'This poison is harvested from a dead or incapacitated wyvern. A creature subjected to this poison must succeed on a DC 15 Constitution saving throw.',
    usageType: 'injury',
    icon: 'Bird',
  },
  {
    id: 'poison-purple-worm',
    name: 'Purple Worm Poison',
    type: 'poison',
    rarity: 'very_rare',
    effect: 'DC 19 Con save or take 12d6 poison damage',
    duration: 'Instant',
    description: 'This poison is harvested from a dead or incapacitated purple worm. A creature subjected to this poison must succeed on a DC 19 Constitution saving throw.',
    usageType: 'injury',
    icon: 'Bug',
  },
  {
    id: 'poison-carrion-crawler',
    name: 'Carrion Crawler Mucus',
    type: 'poison',
    rarity: 'uncommon',
    effect: 'DC 13 Con save or be poisoned for 1 minute (paralyzed)',
    duration: '1 minute',
    description: 'A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or be poisoned for 1 minute. The poisoned creature is paralyzed.',
    usageType: 'injury',
    icon: 'Bug',
  },

  // ── New Expanded Poisons ──

  // Uncommon
  {
    id: 'poison-pale-tincture',
    name: 'Pale Tincture',
    type: 'poison',
    rarity: 'uncommon',
    effect: 'DC 16 Con save or take 1d6 poison damage and poisoned; repeat every 24 hours for 7 days',
    duration: '7 days',
    description: 'A creature that ingests this odorless, colorless poison must succeed on a DC 16 Constitution saving throw or take 1d6 poison damage and become poisoned. The save repeats every 24 hours.',
    usageType: 'ingested',
    icon: 'Droplet',
  },
  {
    id: 'poison-lolths-sting',
    name: "Lolth's Sting",
    type: 'poison',
    rarity: 'uncommon',
    effect: 'DC 14 Con save or take 2d6 poison damage and be paralyzed for 1 round',
    duration: '1 round',
    description: 'A venom blessed by the Spider Queen. On a failed save, the target takes 2d6 poison damage and is paralyzed until the end of its next turn.',
    usageType: 'injury',
    icon: 'Spider',
  },

  // Rare
  {
    id: 'poison-dragon-bile',
    name: 'Dragon Bile',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 18 Con save or take 6d6 poison damage and be poisoned for 1 hour',
    duration: '1 hour',
    description: 'Harvested from the glands of a slain dragon. A creature subjected to this viscous green liquid must make a DC 18 Constitution saving throw.',
    usageType: 'contact',
    icon: 'Flame',
  },
  {
    id: 'poison-demon-ichor',
    name: 'Demon Ichor',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 16 Con save or take 4d6 necrotic damage and gain 1 level of exhaustion',
    duration: 'Instant',
    description: 'This bubbling black ichor was extracted from a fiend. On a failed save, the creature takes necrotic damage and gains a level of exhaustion.',
    usageType: 'injury',
    icon: 'Skull',
  },
  {
    id: 'poison-nightmare-vapor',
    name: 'Nightmare Vapor',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 15 Wis save or be frightened and incapacitated for 1 minute',
    duration: '1 minute',
    description: 'This dark purple gas induces vivid hallucinations of the victim\'s worst fears. On a failed save, the creature is frightened and incapacitated.',
    usageType: 'inhale',
    icon: 'CloudFog',
  },
  {
    id: 'poison-shadowfell-essence',
    name: 'Shadowfell Essence',
    type: 'poison',
    rarity: 'rare',
    effect: 'DC 16 Con save or take 4d6 necrotic damage and speed halved for 1 hour',
    duration: '1 hour',
    description: 'Distilled from the very stuff of the Shadowfell. This black mist drains life energy and slows those who breathe it in.',
    usageType: 'inhale',
    icon: 'Moon',
  },

  // Very Rare
  {
    id: 'poison-pit-fiend-venom',
    name: 'Pit Fiend Venom',
    type: 'poison',
    rarity: 'very_rare',
    effect: 'DC 21 Con save or take 10d6 poison damage; save for half',
    duration: 'Instant',
    description: 'Extracted from the stinger of a pit fiend, this is among the most lethal poisons known. Even a successful save results in half damage.',
    usageType: 'injury',
    icon: 'Flame',
  },
  {
    id: 'poison-eye-of-basilisk',
    name: 'Eye of Basilisk',
    type: 'poison',
    rarity: 'very_rare',
    effect: 'DC 18 Con save or be restrained, then petrified on a second failed save',
    duration: 'Permanent (petrification)',
    description: 'Made from a basilisk\'s dissolved eye. A creature subjected to this poison must make two consecutive saves or be turned to stone.',
    usageType: 'contact',
    icon: 'Eye',
  },

  // Legendary
  {
    id: 'poison-primordial-blight',
    name: 'Primordial Blight',
    type: 'poison',
    rarity: 'legendary',
    effect: 'DC 22 Con save or take 15d6 poison damage and be poisoned for 24 hours (cannot be cured by lesser restoration)',
    duration: '24 hours',
    description: 'A substance so toxic it predates civilization itself. Glows with a sickly green light. Only Greater Restoration or Wish can cure its effects.',
    usageType: 'injury',
    icon: 'Skull',
  },
];
