import { Consumable } from './types';

export const potions: Consumable[] = [
  // Common Potions
  {
    id: 'potion-healing',
    name: 'Potion of Healing',
    type: 'potion',
    rarity: 'common',
    effect: 'Restores 2d4+2 HP instantly',
    duration: 'Instant',
    description: 'A red liquid that shimmers when agitated, this healing potion is the most common of its kind.',
    usageType: 'drink',
    icon: 'Heart',
  },
  {
    id: 'potion-climbing',
    name: 'Potion of Climbing',
    type: 'potion',
    rarity: 'common',
    effect: 'Gain climbing speed equal to walking speed for 1 hour',
    duration: '1 hour',
    description: 'When you drink this potion, you gain a climbing speed equal to your walking speed. During this time, you have advantage on Strength (Athletics) checks you make to climb.',
    usageType: 'drink',
    icon: 'Mountain',
  },

  // Uncommon Potions
  {
    id: 'potion-greater-healing',
    name: 'Potion of Greater Healing',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Restores 4d4+4 HP instantly',
    duration: 'Instant',
    description: 'A crimson liquid that glows faintly, more potent than a standard healing potion.',
    usageType: 'drink',
    icon: 'HeartPulse',
  },
  {
    id: 'potion-animal-friendship',
    name: 'Potion of Animal Friendship',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Cast Animal Friendship (save DC 13) for 1 hour',
    duration: '1 hour',
    description: 'When you drink this potion, you can cast Animal Friendship at will for 1 hour. Agitating the murky liquid reveals leaf and scale bits floating in it.',
    usageType: 'drink',
    icon: 'Squirrel',
  },
  {
    id: 'potion-fire-breath',
    name: 'Potion of Fire Breath',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Exhale fire in 30-foot cone (4d6 fire damage, DC 13 Dex save) 3 times over 1 hour',
    duration: '1 hour (3 uses)',
    description: 'After drinking this orange liquid, you can use a bonus action to exhale fire. This effect can be used 3 times within the hour.',
    usageType: 'drink',
    icon: 'Flame',
  },
  {
    id: 'potion-growth',
    name: 'Potion of Growth',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Enlarge effect for 1d4 hours (double size, advantage on Strength checks/saves, +1d4 weapon damage)',
    duration: '1d4 hours',
    description: 'When you drink this potion, you gain the "enlarge" effect of the Enlarge/Reduce spell. Red in the potion\'s liquid continuously expands and contracts.',
    usageType: 'drink',
    icon: 'Maximize',
  },
  {
    id: 'potion-hill-giant-strength',
    name: 'Potion of Hill Giant Strength',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Strength becomes 21 for 1 hour',
    duration: '1 hour',
    description: 'This murky, yellowish liquid tastes of soil and stone. Your Strength score changes to 21 for the duration.',
    usageType: 'drink',
    icon: 'Dumbbell',
  },
  {
    id: 'potion-poison',
    name: 'Potion of Poison',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Take 3d6 poison damage and make DC 13 Con save or be poisoned for 1 hour',
    duration: '1 hour if failed',
    description: 'This appears to be a Potion of Healing or another beneficial potion. However, it is actually poison masked by illusion magic.',
    usageType: 'drink',
    icon: 'Skull',
  },
  {
    id: 'potion-resistance',
    name: 'Potion of Resistance',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Gain resistance to one damage type for 1 hour',
    duration: '1 hour',
    description: 'When you drink this potion, you gain resistance to one type of damage for 1 hour. The DM determines the type or picks from available options.',
    usageType: 'drink',
    icon: 'Shield',
  },
  {
    id: 'potion-water-breathing',
    name: 'Potion of Water Breathing',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Breathe underwater for 1 hour',
    duration: '1 hour',
    description: 'This cloudy blue liquid smells of the sea. Drinking it grants you the ability to breathe underwater for 1 hour.',
    usageType: 'drink',
    icon: 'Waves',
  },

  // Rare Potions
  {
    id: 'potion-superior-healing',
    name: 'Potion of Superior Healing',
    type: 'potion',
    rarity: 'rare',
    effect: 'Restores 8d4+8 HP instantly',
    duration: 'Instant',
    description: 'A brilliant scarlet liquid that pulses with inner light, this healing potion can mend even grievous wounds.',
    usageType: 'drink',
    icon: 'Sparkles',
  },
  {
    id: 'potion-clairvoyance',
    name: 'Potion of Clairvoyance',
    type: 'potion',
    rarity: 'rare',
    effect: 'Cast Clairvoyance (no concentration required)',
    duration: '10 minutes',
    description: 'When you drink this clear liquid, you gain the ability to cast the Clairvoyance spell without needing to concentrate.',
    usageType: 'drink',
    icon: 'Eye',
  },
  {
    id: 'potion-diminution',
    name: 'Potion of Diminution',
    type: 'potion',
    rarity: 'rare',
    effect: 'Reduce effect for 1d4 hours (half size, disadvantage on Strength checks/saves, -1d4 weapon damage)',
    duration: '1d4 hours',
    description: 'When you drink this potion, you gain the "reduce" effect of the Enlarge/Reduce spell. Red in the potion\'s liquid continuously contracts.',
    usageType: 'drink',
    icon: 'Minimize',
  },
  {
    id: 'potion-gaseous-form',
    name: 'Potion of Gaseous Form',
    type: 'potion',
    rarity: 'rare',
    effect: 'Gaseous Form effect for 1 hour',
    duration: '1 hour',
    description: 'When you drink this potion, you gain the effect of the Gaseous Form spell. The cloudy gray liquid swirls and pulses inside its container.',
    usageType: 'drink',
    icon: 'Cloud',
  },
  {
    id: 'potion-frost-giant-strength',
    name: 'Potion of Frost Giant Strength',
    type: 'potion',
    rarity: 'rare',
    effect: 'Strength becomes 23 for 1 hour',
    duration: '1 hour',
    description: 'This icy blue liquid is cold to the touch. Your Strength score changes to 23 for the duration.',
    usageType: 'drink',
    icon: 'Snowflake',
  },
  {
    id: 'potion-stone-giant-strength',
    name: 'Potion of Stone Giant Strength',
    type: 'potion',
    rarity: 'rare',
    effect: 'Strength becomes 23 for 1 hour',
    duration: '1 hour',
    description: 'This grayish liquid seems almost like stone in a liquid form. Your Strength score changes to 23 for the duration.',
    usageType: 'drink',
    icon: 'Mountain',
  },
  {
    id: 'potion-heroism',
    name: 'Potion of Heroism',
    type: 'potion',
    rarity: 'rare',
    effect: 'Gain 10 temporary HP and bless effect for 1 hour',
    duration: '1 hour',
    description: 'This blue potion bubbles and steams as if boiling. You gain 10 temporary hit points and are under the effect of the Bless spell.',
    usageType: 'drink',
    icon: 'Sparkle',
  },
  {
    id: 'potion-invulnerability',
    name: 'Potion of Invulnerability',
    type: 'potion',
    rarity: 'rare',
    effect: 'Resistance to all damage for 1 minute',
    duration: '1 minute',
    description: 'For 1 minute after you drink this syrupy silver liquid, you have resistance to all damage.',
    usageType: 'drink',
    icon: 'ShieldCheck',
  },
  {
    id: 'potion-mind-reading',
    name: 'Potion of Mind Reading',
    type: 'potion',
    rarity: 'rare',
    effect: 'Cast Detect Thoughts (save DC 13) for 1 minute',
    duration: '1 minute',
    description: 'When you drink this potion, you can cast Detect Thoughts at will. The liquid is dense and purple with an ovoid cloud floating in it.',
    usageType: 'drink',
    icon: 'Brain',
  },

  // Very Rare Potions
  {
    id: 'potion-supreme-healing',
    name: 'Potion of Supreme Healing',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Restores 10d4+20 HP instantly',
    duration: 'Instant',
    description: 'A blazing crimson liquid that seems to contain captured starlight, the most powerful healing potion known.',
    usageType: 'drink',
    icon: 'Stars',
  },
  {
    id: 'potion-fire-giant-strength',
    name: 'Potion of Fire Giant Strength',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Strength becomes 25 for 1 hour',
    duration: '1 hour',
    description: 'This fiery orange liquid seems to contain a small flame within. Your Strength score changes to 25 for the duration.',
    usageType: 'drink',
    icon: 'Flame',
  },
  {
    id: 'potion-cloud-giant-strength',
    name: 'Potion of Cloud Giant Strength',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Strength becomes 27 for 1 hour',
    duration: '1 hour',
    description: 'This pale white liquid constantly roils and shifts like clouds. Your Strength score changes to 27 for the duration.',
    usageType: 'drink',
    icon: 'Cloud',
  },
  {
    id: 'potion-flying',
    name: 'Potion of Flying',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Gain flying speed of 60 feet for 1 hour',
    duration: '1 hour',
    description: 'When you drink this potion, you gain a flying speed of 60 feet. The clear liquid floats at the top of its container.',
    usageType: 'drink',
    icon: 'Feather',
  },
  {
    id: 'potion-invisibility',
    name: 'Potion of Invisibility',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Invisibility effect for 1 hour (ends if you attack or cast)',
    duration: '1 hour',
    description: 'This potion\'s container looks empty but feels as though it holds liquid. When you drink it, you become invisible for 1 hour.',
    usageType: 'drink',
    icon: 'Eye',
  },
  {
    id: 'potion-longevity',
    name: 'Potion of Longevity',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Reduce age by 1d6+6 years, DC 10 Con save or age 1d6+6 years instead',
    duration: 'Permanent',
    description: 'The amber liquid in this potion glitters with golden light. Drinking it may reduce your age, but repeated use carries risk.',
    usageType: 'drink',
    icon: 'Hourglass',
  },
  {
    id: 'potion-speed',
    name: 'Potion of Speed',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Haste effect for 1 minute',
    duration: '1 minute',
    description: 'When you drink this yellow fluid, you gain the effect of the Haste spell. The liquid seems to vibrate intensely.',
    usageType: 'drink',
    icon: 'Zap',
  },
  {
    id: 'potion-vitality',
    name: 'Potion of Vitality',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Remove exhaustion and cure diseases/poisons, gain immunity to both for 24 hours',
    duration: '24 hours',
    description: 'This crimson liquid constantly shifts between colors. It removes exhaustion, cures disease and poison, and grants immunity to both.',
    usageType: 'drink',
    icon: 'Activity',
  },

  // Legendary Potions
  {
    id: 'potion-storm-giant-strength',
    name: 'Potion of Storm Giant Strength',
    type: 'potion',
    rarity: 'legendary',
    effect: 'Strength becomes 29 for 1 hour',
    duration: '1 hour',
    description: 'Lightning crackles within this deep blue liquid. Your Strength score changes to 29 for the duration—the might of a storm giant.',
    usageType: 'drink',
    icon: 'Zap',
  },

  // ── New Expanded Potions ──

  // Common
  {
    id: 'potion-swimming',
    name: 'Potion of Swimming',
    type: 'potion',
    rarity: 'common',
    effect: 'Gain swimming speed of 40 feet for 1 hour',
    duration: '1 hour',
    description: 'This blue-green liquid tastes of sea salt. You gain a swimming speed of 40 feet for the duration.',
    usageType: 'drink',
    icon: 'Waves',
  },

  // Uncommon
  {
    id: 'potion-philter-of-love',
    name: 'Philter of Love',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Next creature seen within 10 minutes becomes charmed for 1 hour',
    duration: '1 hour',
    description: 'A rose-pink liquid that sparkles with tiny golden motes. The next time you see a creature within 10 minutes, you become charmed by that creature.',
    usageType: 'drink',
    icon: 'Heart',
  },
  {
    id: 'potion-oil-of-slipperiness',
    name: 'Oil of Slipperiness',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Freedom of Movement effect for 8 hours, or coat ground to create difficult terrain',
    duration: '8 hours',
    description: 'This sticky black oil can be applied to a creature or poured on the ground. When applied, grants Freedom of Movement for 8 hours.',
    usageType: 'apply',
    icon: 'Droplet',
  },
  {
    id: 'potion-watchful-rest',
    name: 'Potion of Watchful Rest',
    type: 'potion',
    rarity: 'uncommon',
    effect: 'Gain benefits of long rest in 4 hours, remain semiconscious',
    duration: '4 hours',
    description: 'A silvery liquid that tastes of moonlight. You fall into a light trance and gain the benefits of a long rest in only 4 hours while remaining semiconscious.',
    usageType: 'drink',
    icon: 'Moon',
  },

  // Rare
  {
    id: 'potion-elixir-of-health',
    name: 'Elixir of Health',
    type: 'potion',
    rarity: 'rare',
    effect: 'Cure all diseases, remove blinded, deafened, paralyzed, poisoned conditions',
    duration: 'Instant',
    description: 'This clear red liquid has tiny bubbles of light floating in it. It cures any disease and removes the blinded, deafened, paralyzed, and poisoned conditions.',
    usageType: 'drink',
    icon: 'Sparkles',
  },
  {
    id: 'potion-truesight',
    name: 'Potion of Truesight',
    type: 'potion',
    rarity: 'rare',
    effect: 'Gain truesight out to 120 feet for 1 hour',
    duration: '1 hour',
    description: 'A crystal-clear liquid that reveals all hidden things. You gain truesight out to 120 feet, seeing through illusions, darkness, and shapechangers.',
    usageType: 'drink',
    icon: 'Eye',
  },
  {
    id: 'potion-oil-of-etherealness',
    name: 'Oil of Etherealness',
    type: 'potion',
    rarity: 'rare',
    effect: 'Etherealness effect for 1 hour',
    duration: '1 hour',
    description: 'Beads of this cloudy gray oil form on the outside of its container. Apply to yourself to gain the effect of the Etherealness spell for 1 hour.',
    usageType: 'apply',
    icon: 'Ghost',
  },
  {
    id: 'potion-maximum-power',
    name: 'Potion of Maximum Power',
    type: 'potion',
    rarity: 'rare',
    effect: 'Next spell you cast within 1 minute deals maximum damage',
    duration: '1 minute',
    description: 'A blazing white liquid that crackles with arcane energy. The next damage-dealing spell you cast within 1 minute deals maximum damage instead of rolling.',
    usageType: 'drink',
    icon: 'Zap',
  },
  {
    id: 'potion-possibility',
    name: 'Potion of Possibility',
    type: 'potion',
    rarity: 'rare',
    effect: 'Gain 2d4 "possibility dice" (d6) to add to any roll within 1 hour',
    duration: '1 hour',
    description: 'Shimmering with fractal patterns that change when observed. You gain 2d4 d6 dice that you can add to any attack roll, ability check, or saving throw within the next hour.',
    usageType: 'drink',
    icon: 'Dice5',
  },

  // Very Rare
  {
    id: 'potion-giant-size',
    name: 'Potion of Giant Size',
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Grow to Huge size for 24 hours (STR 25, +2d6 weapon damage, 60 temp HP)',
    duration: '24 hours',
    description: 'A thick, bubbling orange liquid. You grow to Huge size, your Strength becomes 25, your weapons deal an extra 2d6 damage, and you gain 60 temporary hit points.',
    usageType: 'drink',
    icon: 'Maximize',
  },
  {
    id: 'potion-dragons-majesty',
    name: "Potion of Dragon's Majesty",
    type: 'potion',
    rarity: 'very_rare',
    effect: 'Gain dragon scales (+7 AC), breath weapon (8d6), and frightful presence for 1 hour',
    duration: '1 hour',
    description: 'Swirling with iridescent scales. You sprout dragon scales (natural armor 17), gain a breath weapon dealing 8d6 damage, and frightful presence in 30 feet.',
    usageType: 'drink',
    icon: 'Flame',
  },

  // Legendary
  {
    id: 'potion-undying',
    name: 'Potion of Undying',
    type: 'potion',
    rarity: 'legendary',
    effect: 'For 24 hours, you cannot die from damage; dropping to 0 HP stabilizes you with 1 HP at start of next turn',
    duration: '24 hours',
    description: 'A liquid that shifts between blood red and midnight black. For 24 hours, when you drop to 0 hit points you are automatically stabilized and regain 1 HP at the start of your next turn.',
    usageType: 'drink',
    icon: 'ShieldCheck',
  },
  {
    id: 'potion-sovereign-glue',
    name: 'Sovereign Glue',
    type: 'potion',
    rarity: 'legendary',
    effect: 'Permanently bonds two objects; only Universal Solvent or Wish can separate them',
    duration: 'Permanent',
    description: 'This viscous, milky-white substance can permanently bond any two objects together. Once set after 1 minute, only Universal Solvent or a Wish spell can break the bond.',
    usageType: 'apply',
    icon: 'Link',
  },
  {
    id: 'potion-universal-solvent',
    name: 'Universal Solvent',
    type: 'potion',
    rarity: 'legendary',
    effect: 'Dissolves any adhesive including Sovereign Glue; can eat through 1 foot of material',
    duration: 'Instant',
    description: 'This sticky, silvery liquid can dissolve any adhesive it touches, including Sovereign Glue. It can also eat through up to 1 foot of any non-magical material.',
    usageType: 'apply',
    icon: 'Droplets',
  },
];
