import { Consumable } from './types';

export const scrolls: Consumable[] = [
  // Utility & Infiltration (1st-2nd level)
  {
    id: 'scroll-disguise-self',
    name: 'Scroll of Disguise Self',
    type: 'scroll',
    rarity: 'common',
    effect: 'Change appearance for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll casts Disguise Self, allowing you to change your appearance including clothing, armor, weapons, and other belongings.',
    usageType: 'read',
    icon: 'User',
    spellLevel: 1,
  },
  {
    id: 'scroll-invisibility',
    name: 'Scroll of Invisibility',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Become invisible for 1 hour or until attack/cast',
    duration: '1 hour',
    description: 'Reading this scroll casts Invisibility on yourself or a creature you touch. The spell ends if the target attacks or casts a spell.',
    usageType: 'read',
    icon: 'Eye',
    spellLevel: 2,
  },
  {
    id: 'scroll-pass-without-trace',
    name: 'Scroll of Pass Without Trace',
    type: 'scroll',
    rarity: 'uncommon',
    effect: '+10 to Stealth for party for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll casts Pass Without Trace, granting you and each creature you choose within 30 feet a +10 bonus to Dexterity (Stealth) checks.',
    usageType: 'read',
    icon: 'Footprints',
    spellLevel: 2,
  },
  {
    id: 'scroll-silence',
    name: 'Scroll of Silence',
    type: 'scroll',
    rarity: 'uncommon',
    effect: '20-foot radius sphere of silence for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll creates a 20-foot-radius sphere of silence centered on a point you choose. No sound can be created or pass through the area.',
    usageType: 'read',
    icon: 'VolumeX',
    spellLevel: 2,
  },
  {
    id: 'scroll-misty-step',
    name: 'Scroll of Misty Step',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Teleport up to 30 feet as bonus action',
    duration: 'Instant',
    description: 'Reading this scroll briefly envelops you in silvery mist, and you teleport up to 30 feet to an unoccupied space you can see.',
    usageType: 'read',
    icon: 'Sparkles',
    spellLevel: 2,
  },

  // Utility & Infiltration (3rd-4th level)
  {
    id: 'scroll-gaseous-form',
    name: 'Scroll of Gaseous Form',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Transform into mist for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll transforms you or a willing creature into a misty cloud. You gain a fly speed of 10 feet and can pass through small holes.',
    usageType: 'read',
    icon: 'Cloud',
    spellLevel: 3,
  },
  {
    id: 'scroll-nondetection',
    name: 'Scroll of Nondetection',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Hide from divination for 8 hours',
    duration: '8 hours',
    description: 'Reading this scroll makes you hidden from divination magic for 8 hours. You cannot be targeted by divination magic or perceived through magical scrying sensors.',
    usageType: 'read',
    icon: 'ShieldOff',
    spellLevel: 3,
  },
  {
    id: 'scroll-greater-invisibility',
    name: 'Scroll of Greater Invisibility',
    type: 'scroll',
    rarity: 'very_rare',
    effect: "Invisibility that doesn't break on attack for 1 minute",
    duration: '1 minute',
    description: "Reading this scroll makes you or a creature you touch invisible. Unlike normal invisibility, attacking or casting spells doesn't end this effect.",
    usageType: 'read',
    icon: 'Ghost',
    spellLevel: 4,
  },

  // Combat & Assassination
  {
    id: 'scroll-sleep',
    name: 'Scroll of Sleep',
    type: 'scroll',
    rarity: 'common',
    effect: '5d8 HP worth of creatures fall unconscious',
    duration: '1 minute',
    description: 'Reading this scroll causes 5d8 hit points worth of creatures within 20 feet of a point to fall unconscious, starting with the lowest current hit points.',
    usageType: 'read',
    icon: 'Moon',
    spellLevel: 1,
  },
  {
    id: 'scroll-hold-person',
    name: 'Scroll of Hold Person',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Paralyze humanoid (auto-crit melee attacks)',
    duration: '1 minute',
    description: 'Reading this scroll causes a humanoid you can see to be paralyzed on a failed save. A paralyzed creature automatically fails Strength and Dexterity saves.',
    usageType: 'read',
    icon: 'Lock',
    spellLevel: 2,
  },
  {
    id: 'scroll-darkness',
    name: 'Scroll of Darkness',
    type: 'scroll',
    rarity: 'uncommon',
    effect: '15-foot radius magical darkness for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll creates a 15-foot-radius sphere of magical darkness. Darkvision cannot penetrate this darkness, and no natural light can illuminate it.',
    usageType: 'read',
    icon: 'CircleOff',
    spellLevel: 2,
  },
  {
    id: 'scroll-blindness-deafness',
    name: 'Scroll of Blindness/Deafness',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Blind or deafen target',
    duration: '1 minute',
    description: 'Reading this scroll can blind or deafen a creature of your choice. The target must succeed on a Constitution saving throw or be affected.',
    usageType: 'read',
    icon: 'EyeOff',
    spellLevel: 2,
  },
  {
    id: 'scroll-suggestion',
    name: 'Scroll of Suggestion',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Suggest reasonable course of action for 8 hours',
    duration: '8 hours',
    description: 'Reading this scroll lets you suggest a course of activity to a creature. The suggestion must be worded reasonably, and the creature pursues the course of action to the best of its ability.',
    usageType: 'read',
    icon: 'MessageSquare',
    spellLevel: 2,
  },
  {
    id: 'scroll-haste',
    name: 'Scroll of Haste',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Double speed, +2 AC, advantage on Dex saves, extra attack for 1 minute',
    duration: '1 minute',
    description: 'Reading this scroll grants a creature you touch doubled speed, +2 bonus to AC, advantage on Dexterity saving throws, and an additional action each turn.',
    usageType: 'read',
    icon: 'Zap',
    spellLevel: 3,
  },
  {
    id: 'scroll-fear',
    name: 'Scroll of Fear',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Frighten creatures in 30-foot cone',
    duration: '1 minute',
    description: 'Reading this scroll projects a phantasmal image of your worst fears. Each creature in a 30-foot cone must succeed on a Wisdom save or be frightened.',
    usageType: 'read',
    icon: 'AlertTriangle',
    spellLevel: 3,
  },
  {
    id: 'scroll-dimension-door',
    name: 'Scroll of Dimension Door',
    type: 'scroll',
    rarity: 'very_rare',
    effect: 'Teleport up to 500 feet',
    duration: 'Instant',
    description: 'Reading this scroll teleports you and up to one willing creature to a destination you choose within 500 feet. You can specify direction and distance or visualize the destination.',
    usageType: 'read',
    icon: 'DoorOpen',
    spellLevel: 4,
  },

  // Information Gathering
  {
    id: 'scroll-detect-magic',
    name: 'Scroll of Detect Magic',
    type: 'scroll',
    rarity: 'common',
    effect: 'Sense magic within 30 feet for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll lets you sense the presence of magic within 30 feet. You can use your action to see a faint aura around any visible magical creature or object.',
    usageType: 'read',
    icon: 'Wand2',
    spellLevel: 1,
  },
  {
    id: 'scroll-detect-poison-disease',
    name: 'Scroll of Detect Poison and Disease',
    type: 'scroll',
    rarity: 'common',
    effect: 'Sense poisons/diseases within 30 feet for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll lets you sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet.',
    usageType: 'read',
    icon: 'AlertCircle',
    spellLevel: 1,
  },
  {
    id: 'scroll-comprehend-languages',
    name: 'Scroll of Comprehend Languages',
    type: 'scroll',
    rarity: 'common',
    effect: 'Understand any language for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll grants you the ability to understand the literal meaning of any spoken language you hear, and to read any written language.',
    usageType: 'read',
    icon: 'Languages',
    spellLevel: 1,
  },
  {
    id: 'scroll-detect-thoughts',
    name: 'Scroll of Detect Thoughts',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Read surface thoughts for 1 minute',
    duration: '1 minute',
    description: 'Reading this scroll lets you read the surface thoughts of creatures within 30 feet. You can probe deeper into their mind with a contested Intelligence check.',
    usageType: 'read',
    icon: 'Brain',
    spellLevel: 2,
  },
  {
    id: 'scroll-locate-object',
    name: 'Scroll of Locate Object',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Sense direction to object within 1000 feet for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll lets you sense the direction to a specific object within 1,000 feet. You can search for a general type of object or a specific object you have seen.',
    usageType: 'read',
    icon: 'Compass',
    spellLevel: 2,
  },
  {
    id: 'scroll-clairvoyance',
    name: 'Scroll of Clairvoyance',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Create invisible sensor to see/hear distant location for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll creates an invisible sensor at a location within 1 mile that is either familiar to you or an obvious location. You can see and hear through the sensor.',
    usageType: 'read',
    icon: 'Radar',
    spellLevel: 3,
  },
  {
    id: 'scroll-tongues',
    name: 'Scroll of Tongues',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Understand and speak any language for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll grants a creature you touch the ability to understand any spoken language it hears and to speak intelligibly to any creature that knows a language.',
    usageType: 'read',
    icon: 'MessageCircle',
    spellLevel: 3,
  },
];
