import { Consumable } from './types';

export const scrolls: Consumable[] = [
  // Utility & Infiltration (1st-2nd level)
  {
    id: 'scroll-disguise-self',
    name: 'Scroll of Disguise Self',
    type: 'scroll',
    rarity: 'common',
    effect: 'Change appearance for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll casts Disguise Self, allowing you to change your appearance including clothing, armor, weapons, and other belongings.',
    usageType: 'read',
    icon: 'User',
    spellLevel: 1,
  },
  {
    id: 'scroll-invisibility',
    name: 'Scroll of Invisibility',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Become invisible for 1 hour or until attack/cast',
    duration: '1 hour',
    description: 'Reading this scroll casts Invisibility on yourself or a creature you touch. The spell ends if the target attacks or casts a spell.',
    usageType: 'read',
    icon: 'Eye',
    spellLevel: 2,
  },
  {
    id: 'scroll-pass-without-trace',
    name: 'Scroll of Pass Without Trace',
    type: 'scroll',
    rarity: 'uncommon',
    effect: '+10 to Stealth for party for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll casts Pass Without Trace, granting you and each creature you choose within 30 feet a +10 bonus to Dexterity (Stealth) checks.',
    usageType: 'read',
    icon: 'Footprints',
    spellLevel: 2,
  },
  {
    id: 'scroll-silence',
    name: 'Scroll of Silence',
    type: 'scroll',
    rarity: 'uncommon',
    effect: '20-foot radius sphere of silence for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll creates a 20-foot-radius sphere of silence centered on a point you choose. No sound can be created or pass through the area.',
    usageType: 'read',
    icon: 'VolumeX',
    spellLevel: 2,
  },
  {
    id: 'scroll-misty-step',
    name: 'Scroll of Misty Step',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Teleport up to 30 feet as bonus action',
    duration: 'Instant',
    description: 'Reading this scroll briefly envelops you in silvery mist, and you teleport up to 30 feet to an unoccupied space you can see.',
    usageType: 'read',
    icon: 'Sparkles',
    spellLevel: 2,
  },

  // Utility & Infiltration (3rd-4th level)
  {
    id: 'scroll-gaseous-form',
    name: 'Scroll of Gaseous Form',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Transform into mist for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll transforms you or a willing creature into a misty cloud. You gain a fly speed of 10 feet and can pass through small holes.',
    usageType: 'read',
    icon: 'Cloud',
    spellLevel: 3,
  },
  {
    id: 'scroll-nondetection',
    name: 'Scroll of Nondetection',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Hide from divination for 8 hours',
    duration: '8 hours',
    description: 'Reading this scroll makes you hidden from divination magic for 8 hours. You cannot be targeted by divination magic or perceived through magical scrying sensors.',
    usageType: 'read',
    icon: 'ShieldOff',
    spellLevel: 3,
  },
  {
    id: 'scroll-greater-invisibility',
    name: 'Scroll of Greater Invisibility',
    type: 'scroll',
    rarity: 'very_rare',
    effect: "Invisibility that doesn't break on attack for 1 minute",
    duration: '1 minute',
    description: "Reading this scroll makes you or a creature you touch invisible. Unlike normal invisibility, attacking or casting spells doesn't end this effect.",
    usageType: 'read',
    icon: 'Ghost',
    spellLevel: 4,
  },

  // Combat & Assassination
  {
    id: 'scroll-sleep',
    name: 'Scroll of Sleep',
    type: 'scroll',
    rarity: 'common',
    effect: '5d8 HP worth of creatures fall unconscious',
    duration: '1 minute',
    description: 'Reading this scroll causes 5d8 hit points worth of creatures within 20 feet of a point to fall unconscious, starting with the lowest current hit points.',
    usageType: 'read',
    icon: 'Moon',
    spellLevel: 1,
  },
  {
    id: 'scroll-hold-person',
    name: 'Scroll of Hold Person',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Paralyze humanoid (auto-crit melee attacks)',
    duration: '1 minute',
    description: 'Reading this scroll causes a humanoid you can see to be paralyzed on a failed save. A paralyzed creature automatically fails Strength and Dexterity saves.',
    usageType: 'read',
    icon: 'Lock',
    spellLevel: 2,
  },
  {
    id: 'scroll-darkness',
    name: 'Scroll of Darkness',
    type: 'scroll',
    rarity: 'uncommon',
    effect: '15-foot radius magical darkness for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll creates a 15-foot-radius sphere of magical darkness. Darkvision cannot penetrate this darkness, and no natural light can illuminate it.',
    usageType: 'read',
    icon: 'CircleOff',
    spellLevel: 2,
  },
  {
    id: 'scroll-blindness-deafness',
    name: 'Scroll of Blindness/Deafness',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Blind or deafen target',
    duration: '1 minute',
    description: 'Reading this scroll can blind or deafen a creature of your choice. The target must succeed on a Constitution saving throw or be affected.',
    usageType: 'read',
    icon: 'EyeOff',
    spellLevel: 2,
  },
  {
    id: 'scroll-suggestion',
    name: 'Scroll of Suggestion',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Suggest reasonable course of action for 8 hours',
    duration: '8 hours',
    description: 'Reading this scroll lets you suggest a course of activity to a creature. The suggestion must be worded reasonably, and the creature pursues the course of action to the best of its ability.',
    usageType: 'read',
    icon: 'MessageSquare',
    spellLevel: 2,
  },
  {
    id: 'scroll-haste',
    name: 'Scroll of Haste',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Double speed, +2 AC, advantage on Dex saves, extra attack for 1 minute',
    duration: '1 minute',
    description: 'Reading this scroll grants a creature you touch doubled speed, +2 bonus to AC, advantage on Dexterity saving throws, and an additional action each turn.',
    usageType: 'read',
    icon: 'Zap',
    spellLevel: 3,
  },
  {
    id: 'scroll-fear',
    name: 'Scroll of Fear',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Frighten creatures in 30-foot cone',
    duration: '1 minute',
    description: 'Reading this scroll projects a phantasmal image of your worst fears. Each creature in a 30-foot cone must succeed on a Wisdom save or be frightened.',
    usageType: 'read',
    icon: 'AlertTriangle',
    spellLevel: 3,
  },
  {
    id: 'scroll-dimension-door',
    name: 'Scroll of Dimension Door',
    type: 'scroll',
    rarity: 'very_rare',
    effect: 'Teleport up to 500 feet',
    duration: 'Instant',
    description: 'Reading this scroll teleports you and up to one willing creature to a destination you choose within 500 feet. You can specify direction and distance or visualize the destination.',
    usageType: 'read',
    icon: 'DoorOpen',
    spellLevel: 4,
  },

  // Information Gathering
  {
    id: 'scroll-detect-magic',
    name: 'Scroll of Detect Magic',
    type: 'scroll',
    rarity: 'common',
    effect: 'Sense magic within 30 feet for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll lets you sense the presence of magic within 30 feet. You can use your action to see a faint aura around any visible magical creature or object.',
    usageType: 'read',
    icon: 'Wand2',
    spellLevel: 1,
  },
  {
    id: 'scroll-detect-poison-disease',
    name: 'Scroll of Detect Poison and Disease',
    type: 'scroll',
    rarity: 'common',
    effect: 'Sense poisons/diseases within 30 feet for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll lets you sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet.',
    usageType: 'read',
    icon: 'AlertCircle',
    spellLevel: 1,
  },
  {
    id: 'scroll-comprehend-languages',
    name: 'Scroll of Comprehend Languages',
    type: 'scroll',
    rarity: 'common',
    effect: 'Understand any language for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll grants you the ability to understand the literal meaning of any spoken language you hear, and to read any written language.',
    usageType: 'read',
    icon: 'Languages',
    spellLevel: 1,
  },
  {
    id: 'scroll-detect-thoughts',
    name: 'Scroll of Detect Thoughts',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Read surface thoughts for 1 minute',
    duration: '1 minute',
    description: 'Reading this scroll lets you read the surface thoughts of creatures within 30 feet. You can probe deeper into their mind with a contested Intelligence check.',
    usageType: 'read',
    icon: 'Brain',
    spellLevel: 2,
  },
  {
    id: 'scroll-locate-object',
    name: 'Scroll of Locate Object',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Sense direction to object within 1000 feet for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll lets you sense the direction to a specific object within 1,000 feet. You can search for a general type of object or a specific object you have seen.',
    usageType: 'read',
    icon: 'Compass',
    spellLevel: 2,
  },
  {
    id: 'scroll-clairvoyance',
    name: 'Scroll of Clairvoyance',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Create invisible sensor to see/hear distant location for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll creates an invisible sensor at a location within 1 mile that is either familiar to you or an obvious location. You can see and hear through the sensor.',
    usageType: 'read',
    icon: 'Radar',
    spellLevel: 3,
  },
  {
    id: 'scroll-tongues',
    name: 'Scroll of Tongues',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Understand and speak any language for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll grants a creature you touch the ability to understand any spoken language it hears and to speak intelligibly to any creature that knows a language.',
    usageType: 'read',
    icon: 'MessageCircle',
    spellLevel: 3,
  },

  // ── New Expanded Scrolls ──

  // Common (1st level)
  {
    id: 'scroll-feather-fall',
    name: 'Scroll of Feather Fall',
    type: 'scroll',
    rarity: 'common',
    effect: 'Up to 5 creatures fall at 60 feet per round and take no falling damage',
    duration: 'Instant',
    description: 'Reading this scroll slows the descent of up to five falling creatures within 60 feet. Each descends at 60 feet per round and takes no falling damage.',
    usageType: 'read',
    icon: 'Feather',
    spellLevel: 1,
  },
  {
    id: 'scroll-fog-cloud',
    name: 'Scroll of Fog Cloud',
    type: 'scroll',
    rarity: 'common',
    effect: '20-foot radius sphere of fog (heavily obscured) for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll creates a 20-foot-radius sphere of fog centered on a point within 120 feet. The area is heavily obscured.',
    usageType: 'read',
    icon: 'Cloud',
    spellLevel: 1,
  },
  {
    id: 'scroll-charm-person',
    name: 'Scroll of Charm Person',
    type: 'scroll',
    rarity: 'common',
    effect: 'Charm one humanoid (Wis save) for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll attempts to charm a humanoid you can see within 30 feet. It must succeed on a Wisdom saving throw or be charmed by you.',
    usageType: 'read',
    icon: 'Heart',
    spellLevel: 1,
  },
  {
    id: 'scroll-healing-word',
    name: 'Scroll of Healing Word',
    type: 'scroll',
    rarity: 'common',
    effect: 'Heal a creature you can see within 60 feet for 1d4+modifier HP as a bonus action',
    duration: 'Instant',
    description: 'Reading this scroll sends a word of healing to a creature within 60 feet, restoring 1d4 hit points plus your spellcasting modifier.',
    usageType: 'read',
    icon: 'Heart',
    spellLevel: 1,
  },

  // Uncommon (2nd level)
  {
    id: 'scroll-spider-climb',
    name: 'Scroll of Spider Climb',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Walk on walls and ceilings, climb speed equal to walk speed for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll grants the ability to move on vertical surfaces and ceilings while leaving your hands free. You gain a climbing speed equal to your walking speed.',
    usageType: 'read',
    icon: 'Bug',
    spellLevel: 2,
  },
  {
    id: 'scroll-mirror-image',
    name: 'Scroll of Mirror Image',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Create 3 illusory duplicates that absorb attacks for 1 minute',
    duration: '1 minute',
    description: 'Reading this scroll creates three illusory duplicates of yourself. When attacked, a random target is rolled; duplicates have AC 10 + your DEX modifier.',
    usageType: 'read',
    icon: 'Users',
    spellLevel: 2,
  },
  {
    id: 'scroll-knock',
    name: 'Scroll of Knock',
    type: 'scroll',
    rarity: 'uncommon',
    effect: 'Open one locked door, chest, or shackle; suppresses Arcane Lock for 10 minutes',
    duration: 'Instant',
    description: 'Reading this scroll produces a loud knock audible 300 feet away and unlocks a single locked object. Arcane Lock is suppressed for 10 minutes.',
    usageType: 'read',
    icon: 'DoorOpen',
    spellLevel: 2,
  },
  {
    id: 'scroll-web',
    name: 'Scroll of Web',
    type: 'scroll',
    rarity: 'uncommon',
    effect: '20-foot cube of sticky webs (restrained, Dex save) for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll conjures a mass of thick, sticky webbing in a 20-foot cube. Creatures caught must make a Dex save or be restrained.',
    usageType: 'read',
    icon: 'Globe',
    spellLevel: 2,
  },

  // Rare (3rd level)
  {
    id: 'scroll-counterspell',
    name: 'Scroll of Counterspell',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Interrupt and negate a spell of 3rd level or lower being cast',
    duration: 'Instant',
    description: 'Reading this scroll as a reaction attempts to interrupt a creature casting a spell. Spells of 3rd level or lower automatically fail.',
    usageType: 'read',
    icon: 'ShieldOff',
    spellLevel: 3,
  },
  {
    id: 'scroll-fly',
    name: 'Scroll of Fly',
    type: 'scroll',
    rarity: 'rare',
    effect: 'Gain flying speed of 60 feet for 10 minutes',
    duration: '10 minutes',
    description: 'Reading this scroll grants a willing creature you touch a flying speed of 60 feet for the duration.',
    usageType: 'read',
    icon: 'Feather',
    spellLevel: 3,
  },
  {
    id: 'scroll-dispel-magic',
    name: 'Scroll of Dispel Magic',
    type: 'scroll',
    rarity: 'rare',
    effect: 'End one spell of 3rd level or lower on a target; higher spells require ability check',
    duration: 'Instant',
    description: 'Reading this scroll ends spells of 3rd level or lower on one creature, object, or area. For higher-level spells, an ability check is required.',
    usageType: 'read',
    icon: 'Wand2',
    spellLevel: 3,
  },
  {
    id: 'scroll-fireball',
    name: 'Scroll of Fireball',
    type: 'scroll',
    rarity: 'rare',
    effect: '8d6 fire damage in a 20-foot radius sphere (Dex save for half)',
    duration: 'Instant',
    description: 'Reading this scroll hurls a bright streak of flame to a point within 150 feet, which erupts in a 20-foot-radius sphere of fire.',
    usageType: 'read',
    icon: 'Flame',
    spellLevel: 3,
  },

  // Very Rare (4th-5th level)
  {
    id: 'scroll-polymorph',
    name: 'Scroll of Polymorph',
    type: 'scroll',
    rarity: 'very_rare',
    effect: 'Transform a creature into a beast of equal or lower CR for 1 hour',
    duration: '1 hour',
    description: 'Reading this scroll transforms a creature you can see into a new beast form. The target\'s game statistics are replaced by the chosen beast\'s stats.',
    usageType: 'read',
    icon: 'Squirrel',
    spellLevel: 4,
  },
  {
    id: 'scroll-banishment',
    name: 'Scroll of Banishment',
    type: 'scroll',
    rarity: 'very_rare',
    effect: 'Banish creature to demiplane for 1 minute (Cha save); extraplanar creatures are permanently banished',
    duration: '1 minute',
    description: 'Reading this scroll attempts to banish a creature you can see. If native to the current plane, it\'s sent to a harmless demiplane. Otherwise, it\'s sent to its home plane.',
    usageType: 'read',
    icon: 'LogOut',
    spellLevel: 4,
  },
  {
    id: 'scroll-wall-of-force',
    name: 'Scroll of Wall of Force',
    type: 'scroll',
    rarity: 'very_rare',
    effect: 'Create an invisible wall of force (up to 10 panels) for 10 minutes; nothing can pass through',
    duration: '10 minutes',
    description: 'Reading this scroll creates an invisible wall of force at a point you choose. Nothing can physically pass through, and it is immune to all damage.',
    usageType: 'read',
    icon: 'Shield',
    spellLevel: 5,
  },
];
