// Drizzt's Legacy - All 48 Prestige Abilities
// Organized by branch: Dual Wielding, Guenhwyvar, Drow Abilities, Monk Abilities

import { PrestigeAbility, PrestigeBranch, HIGH_TIER_GATES } from './types';

// ============================================
// DUAL WIELDING BRANCH (12 abilities)
// ============================================

const dualWieldingAbilities: PrestigeAbility[] = [
  // Tier 1 - Foundation
  {
    id: 'scimitar_mastery',
    name: 'Scimitar Mastery',
    branch: 'dual_wielding',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: '+2 to attack rolls with scimitars. Your blade work becomes legendary.',
    aiPrompt: `"I draw my enchanted scimitars, their blades glinting with magical light as I assume my defensive stance, ready to dance between my foes."`,
    mechanicalContext: '[+2 to attack rolls with scimitars. Passive ability that applies to all scimitar attacks.]',
    effects: { mechanicalBonus: '+2 attack with scimitars' },
    icon: 'Swords',
  },
  {
    id: 'twin_blade_grip',
    name: 'Twin Blade Grip',
    branch: 'dual_wielding',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Attack with both scimitars as bonus action once per turn.',
    aiPrompt: `"In a fluid motion, I execute a coordinated strike with both blades, weaving an intricate pattern of steel."`,
    mechanicalContext: '[Bonus action to attack with off-hand scimitar once per turn. No ability modifier to damage.]',
    effects: { cooldown: 'Once per turn' },
    icon: 'Zap',
  },
  {
    id: 'icingdeath_bond',
    name: 'Icingdeath Bond',
    branch: 'dual_wielding',
    tier: 1,
    prestigeCost: 3,
    prerequisites: [],
    description: 'Unlock Icingdeath (frost scimitar) mechanics—attacks deal +1d4 cold damage.',
    aiPrompt: `"My scimitar Icingdeath crackles with ancient frost magic as I prepare to strike, the blade emanating a chill that freezes the air itself."`,
    mechanicalContext: '[Attacks with primary scimitar deal an additional 1d4 cold damage. Grants resistance to fire damage while wielding Icingdeath.]',
    effects: { mechanicalBonus: '+1d4 cold damage' },
    icon: 'Snowflake',
  },
  {
    id: 'twinkle_bond',
    name: 'Twinkle Bond',
    branch: 'dual_wielding',
    tier: 1,
    prestigeCost: 3,
    prerequisites: [],
    description: 'Unlock Twinkle (starlight scimitar) mechanics—attacks deal +1d4 radiant damage.',
    aiPrompt: `"My magical scimitar Twinkle glows with ethereal starlight, ready to pierce the darkness and illuminate evil."`,
    mechanicalContext: '[Attacks with off-hand scimitar deal an additional 1d4 radiant damage. Twinkle can glow as a signal—visible up to 1 mile when danger approaches.]',
    effects: { mechanicalBonus: '+1d4 radiant damage' },
    icon: 'Star',
  },

  // Tier 2 - Intermediate
  {
    id: 'dance_of_blades',
    name: 'Dance of Blades',
    branch: 'dual_wielding',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['scimitar_mastery'],
    description: '+1 AC when wielding two scimitars. You become a whirling dervish of steel.',
    aiPrompt: `"I enter the dance of blades, my body weaving between strikes as my scimitars form an impenetrable defensive barrier."`,
    mechanicalContext: '[+1 AC while wielding two light melee weapons. Passive defensive stance.]',
    effects: { mechanicalBonus: '+1 AC' },
    icon: 'Shuffle',
  },
  {
    id: 'whirlwind_assault',
    name: 'Whirlwind Assault',
    branch: 'dual_wielding',
    tier: 2,
    prestigeCost: 5,
    minimumPrestigeLevel: 5,
    prerequisites: ['twin_blade_grip'],
    description: 'Spin attack hitting all adjacent enemies. Uses action, refreshes per short rest.',
    aiPrompt: `"I become a cyclone of flashing steel, spinning with both blades extended to strike every foe within reach."`,
    mechanicalContext: '[Action: Make one attack against each creature within 5 feet. Recharges on short rest.]',
    effects: { cooldown: 'Short rest' },
    icon: 'Wind',
  },
  {
    id: 'perfect_parry',
    name: 'Perfect Parry',
    branch: 'dual_wielding',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['dance_of_blades'],
    description: 'Reaction to deflect ranged attacks when wielding both blades.',
    aiPrompt: `"With preternatural reflexes, I cross my blades and deflect the incoming projectile harmlessly aside."`,
    mechanicalContext: '[Reaction: When hit by a ranged attack, reduce damage by 1d10 + DEX mod. If reduced to 0, deflect the projectile.]',
    effects: { cooldown: 'Once per turn' },
    icon: 'Shield',
  },
  {
    id: 'riposte_mastery',
    name: 'Riposte Mastery',
    branch: 'dual_wielding',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['perfect_parry'],
    description: 'After successfully parrying, make a bonus melee attack.',
    aiPrompt: `"The moment their attack slides harmlessly past my crossed blades, I strike back with devastating precision."`,
    mechanicalContext: '[When you successfully deflect an attack with Perfect Parry, you may make one melee attack as part of the same reaction.]',
    effects: {},
    icon: 'Target',
  },

  // Tier 3 - Advanced
  {
    id: 'form_of_crow',
    name: 'Form of the Crow',
    branch: 'dual_wielding',
    tier: 3,
    prestigeCost: 8,
    minimumPrestigeLevel: 8,
    prerequisites: ['dance_of_blades', 'whirlwind_assault'],
    description: 'Legendary dual-wielding stance granting advantage on DEX saves and +10 movement.',
    aiPrompt: `"I shift into the Form of the Crow, a legendary drow fighting stance that makes me as swift and elusive as the shadow itself."`,
    mechanicalContext: '[Bonus action to enter stance. While active: Advantage on DEX saves, +10 feet movement, attacks of opportunity against you have disadvantage. Lasts 1 minute, recharges on short rest.]',
    effects: { mechanicalBonus: '+10 movement, advantage on DEX saves', duration: '1 minute' },
    icon: 'Bird',
  },
  {
    id: 'blade_echo',
    name: 'Blade Echo',
    branch: 'dual_wielding',
    tier: 3,
    prestigeCost: 8,
    minimumPrestigeLevel: 8,
    prerequisites: ['icingdeath_bond', 'twinkle_bond'],
    description: 'Attacks with both scimitars can hit the same target twice.',
    aiPrompt: `"My blades become blurs of motion, each strike echoing a phantom second blow that lands before the first can be perceived."`,
    mechanicalContext: '[When you hit a creature with both Icingdeath and Twinkle in the same turn, you may immediately make one additional attack with either weapon against that creature.]',
    effects: {},
    icon: 'Copy',
  },
  {
    id: 'legacy_of_lolth',
    name: "Legacy of Lolth's Nemesis",
    branch: 'dual_wielding',
    tier: 3,
    prestigeCost: 12,
    minimumPrestigeLevel: HIGH_TIER_GATES['legacy_of_lolth'],
    prerequisites: ['form_of_crow', 'blade_echo', 'riposte_mastery'],
    description: 'Once per day, both scimitars glow with ancestral power—next attack is automatically critical.',
    aiPrompt: `"I channel the defiance of my ancestors, those who rejected the Spider Queen. My blades ignite with the power of generations of rebellion, ready to deliver a blow that will be sung of for centuries."`,
    mechanicalContext: '[Once per long rest: As a bonus action, empower your next attack. If it hits, it automatically becomes a critical hit. Both weapon damage dice (Icingdeath and Twinkle bonuses) are doubled.]',
    effects: { cooldown: 'Long rest' },
    icon: 'Crown',
  },
  {
    id: 'dual_weapon_finale',
    name: 'Symphony of Steel',
    branch: 'dual_wielding',
    tier: 3,
    prestigeCost: 10,
    minimumPrestigeLevel: 10,
    prerequisites: ['blade_echo'],
    description: 'Once per encounter, make 4 attacks in a single action.',
    aiPrompt: `"I unleash the Symphony of Steel—a devastating flurry where both blades become invisible arcs of death, striking with perfect coordination."`,
    mechanicalContext: '[Once per short rest: As an action, make 4 melee attacks with your scimitars. You may divide these attacks among any targets within reach.]',
    effects: { cooldown: 'Short rest' },
    icon: 'Sparkles',
  },
];

// ============================================
// GUENHWYVAR BRANCH (12 abilities)
// ============================================

const guenhwyvarAbilities: PrestigeAbility[] = [
  // Tier 1 - Foundation
  {
    id: 'call_guenhwyvar',
    name: 'Call Guenhwyvar',
    branch: 'guenhwyvar',
    tier: 1,
    prestigeCost: 3,
    prerequisites: [],
    description: 'Summon the magical panther as a companion. Guenhwyvar acts on your turn.',
    aiPrompt: `"I call upon the astral plane, and my beloved Guenhwyvar materializes beside me—her sleek obsidian form shimmering as she crosses from her dimension to mine, golden eyes already fixed on our enemies."`,
    mechanicalContext: '[Action to summon. Guenhwyvar has stats of a Panther with enhanced HP (40). She acts on your initiative, can attack, and remains until dismissed or reduced to 0 HP. Must rest 12 hours on Astral Plane before re-summoning if defeated.]',
    effects: { cooldown: '12 hours if defeated' },
    icon: 'Cat',
  },
  {
    id: 'guenhwyvar_bond',
    name: "Guenhwyvar's Bond",
    branch: 'guenhwyvar',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Establish telepathic link with Guenhwyvar; direct her actions mid-combat.',
    aiPrompt: `"Through our bond forged across planes and centuries, I reach out to Guenhwyvar's mind. She knows my intent before I form the thought."`,
    mechanicalContext: '[Passive: Telepathic communication with Guenhwyvar up to 1 mile. You can direct her actions without speaking or using actions. She understands complex tactical commands.]',
    effects: {},
    icon: 'Link',
  },
  {
    id: 'panther_pounce',
    name: "Panther's Pounce",
    branch: 'guenhwyvar',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: "Guenhwyvar's melee attack gains advantage when attacking enemy you just attacked.",
    aiPrompt: `"As my blade finds its mark, Guenhwyvar is already in motion—a shadow given form, she strikes the moment my foe is distracted."`,
    mechanicalContext: "[Passive: When you hit a creature with a melee attack, Guenhwyvar's next attack against that creature before the end of her next turn has advantage.]",
    effects: {},
    icon: 'Footprints',
  },
  {
    id: 'guenhwyvar_grace',
    name: "Guenhwyvar's Grace",
    branch: 'guenhwyvar',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Your panther companion gains +1 AC and +1 to attack rolls.',
    aiPrompt: `"Centuries of hunting across dimensions have honed Guenhwyvar's instincts to supernatural sharpness. She moves with an otherworldly grace."`,
    mechanicalContext: "[Passive: Guenhwyvar gains +1 to AC and +1 to all attack rolls. Stacks with other bonuses.]",
    effects: { mechanicalBonus: '+1 AC, +1 attack' },
    icon: 'Heart',
  },

  // Tier 2 - Intermediate
  {
    id: 'shared_senses',
    name: 'Shared Senses',
    branch: 'guenhwyvar',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['guenhwyvar_bond'],
    description: "See through Guenhwyvar's eyes; gain darkvision up to 120 ft.",
    aiPrompt: `"I close my eyes and open Guenhwyvar's, seeing the world through her predator's vision—every shadow becomes transparent, every hidden enemy revealed."`,
    mechanicalContext: "[Action: See through Guenhwyvar's senses for up to 10 minutes. Gain her Darkvision (120 ft) and Keen Smell. You are blinded and deafened to your own surroundings while doing this.]",
    effects: { duration: '10 minutes' },
    icon: 'Eye',
  },
  {
    id: 'coordinated_strike',
    name: 'Coordinated Strike',
    branch: 'guenhwyvar',
    tier: 2,
    prestigeCost: 5,
    minimumPrestigeLevel: 5,
    prerequisites: ['panther_pounce'],
    description: 'If both you and Guenhwyvar attack same target, target has disadvantage on DEX saves.',
    aiPrompt: `"Guenhwyvar and I have fought together so long that we are one weapon in two bodies. When we strike together, no foe can evade us."`,
    mechanicalContext: '[Passive: If both you and Guenhwyvar hit the same target in a round, that creature has disadvantage on DEX saving throws until the start of your next turn.]',
    effects: {},
    icon: 'Users',
  },
  {
    id: 'spectral_guard',
    name: 'Spectral Guardianship',
    branch: 'guenhwyvar',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['guenhwyvar_grace'],
    description: 'Guenhwyvar can block one attack per turn targeting you.',
    aiPrompt: `"Guenhwyvar interposes herself between me and danger, her astral form partially shifting to absorb the blow meant for me."`,
    mechanicalContext: '[Reaction: When you are hit by an attack, Guenhwyvar can use her reaction to impose disadvantage on that attack roll. If the attack still hits, she takes half the damage instead of you.]',
    effects: { cooldown: 'Once per turn' },
    icon: 'ShieldCheck',
  },
  {
    id: 'guenhwyvar_roar',
    name: "Guenhwyvar's Roar",
    branch: 'guenhwyvar',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['call_guenhwyvar'],
    description: 'Once per short rest, Guenhwyvar roars—enemies within 15 ft. must save or be frightened.',
    aiPrompt: `"Guenhwyvar releases a roar that echoes across planes—a sound of primal terror that freezes the blood of all who hear it."`,
    mechanicalContext: '[Action: Guenhwyvar roars. Each creature of your choice within 15 feet must succeed on a WIS save (DC 14) or be frightened for 1 minute. They can repeat the save at end of each turn.]',
    effects: { saveDC: 14, cooldown: 'Short rest' },
    icon: 'Volume2',
  },

  // Tier 3 - Advanced
  {
    id: 'guenhwyvar_ascension',
    name: 'Guenhwyvar Ascension',
    branch: 'guenhwyvar',
    tier: 3,
    prestigeCost: 8,
    minimumPrestigeLevel: 8,
    prerequisites: ['coordinated_strike', 'spectral_guard'],
    description: 'Companion gains second attack per turn; damage increased +2d6.',
    aiPrompt: `"Guenhwyvar ascends to her true form—no longer merely a companion, but a force of nature. Her attacks become devastating."`,
    mechanicalContext: '[Passive: Guenhwyvar can make two attacks per turn instead of one. Her claw and bite attacks deal an additional 2d6 force damage.]',
    effects: { mechanicalBonus: '+2d6 damage, 2 attacks' },
    icon: 'TrendingUp',
  },
  {
    id: 'soul_link',
    name: 'Soul Link',
    branch: 'guenhwyvar',
    tier: 3,
    prestigeCost: 8,
    minimumPrestigeLevel: 8,
    prerequisites: ['shared_senses'],
    description: 'When you take damage, can redirect half to Guenhwyvar (once per long rest).',
    aiPrompt: `"Our souls are intertwined across the planes. When death comes for me, Guenhwyvar shares my burden, her astral form absorbing the killing blow."`,
    mechanicalContext: '[Reaction, 1/long rest: When you take damage that would reduce you to 0 HP, you may instead take half the damage. Guenhwyvar takes the other half.]',
    effects: { cooldown: 'Long rest' },
    icon: 'HeartHandshake',
  },
  {
    id: 'eternal_companion',
    name: 'Eternal Companion',
    branch: 'guenhwyvar',
    tier: 3,
    prestigeCost: 10,
    minimumPrestigeLevel: 10,
    prerequisites: ['guenhwyvar_ascension'],
    description: 'Guenhwyvar can remain summoned indefinitely; recovery time reduced to 6 hours.',
    aiPrompt: `"The bond between us has grown beyond mortal limits. Guenhwyvar need no longer return to the Astral Plane—she exists in both worlds simultaneously."`,
    mechanicalContext: '[Passive: Guenhwyvar no longer has a time limit on summoning. If reduced to 0 HP, she only needs 6 hours on the Astral Plane before re-summoning.]',
    effects: { cooldown: '6 hours if defeated' },
    icon: 'Infinity',
  },
  {
    id: 'avatar_panther',
    name: 'Avatar of the Panther',
    branch: 'guenhwyvar',
    tier: 3,
    prestigeCost: 10,
    minimumPrestigeLevel: HIGH_TIER_GATES['avatar_panther'],
    prerequisites: ['soul_link', 'eternal_companion'],
    description: 'Once per day, you and Guenhwyvar can swap positions as a bonus action (teleportation).',
    aiPrompt: `"For a heartbeat, Guenhwyvar and I are one—our forms blur and exchange across space itself, confounding our enemies."`,
    mechanicalContext: '[Bonus Action, 1/long rest: You and Guenhwyvar instantly swap positions. This is a teleportation effect and does not provoke attacks of opportunity.]',
    effects: { cooldown: 'Long rest' },
    icon: 'Sparkle',
  },
];

// ============================================
// DROW ABILITIES BRANCH (12 abilities)
// ============================================

const drowAbilities: PrestigeAbility[] = [
  // Tier 1 - Foundation
  {
    id: 'superior_darkvision',
    name: 'Superior Darkvision',
    branch: 'drow_abilities',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'See in dim/darkness up to 120 ft. (beyond standard drow 60 ft.).',
    aiPrompt: `"My eyes pierce the absolute darkness, revealing every detail as if lit by daylight. Nothing hides from a son of the Underdark."`,
    mechanicalContext: '[Passive: Your Darkvision extends to 120 feet. You can see in magical darkness out to 60 feet as if it were dim light.]',
    effects: { mechanicalBonus: 'Darkvision 120 ft' },
    icon: 'Eye',
  },
  {
    id: 'drow_magic',
    name: 'Drow Magic Attunement',
    branch: 'drow_abilities',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Cast Faerie Fire 1/day (DC 16 WIS save).',
    aiPrompt: `"I weave drow magic, surrounding my enemies in dancing faerie fire that outlines their forms in ethereal light."`,
    mechanicalContext: '[1/long rest: Cast Faerie Fire. Objects and creatures in a 20-foot cube are outlined in light (blue, green, or violet). Attack rolls against affected creatures have advantage. DC 16 DEX save to resist.]',
    effects: { saveDC: 16, cooldown: 'Long rest' },
    icon: 'Wand2',
  },
  {
    id: 'dancing_lights',
    name: 'Dancing Lights',
    branch: 'drow_abilities',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Cast Dancing Lights as cantrip (instant, no action cost).',
    aiPrompt: `"Arcane lights swirl around the battlefield at my command, dancing motes of magical illumination."`,
    mechanicalContext: '[Cantrip: Create up to 4 torch-sized lights within 120 feet. Can move them 60 feet as a bonus action. Last 1 minute or until dismissed.]',
    effects: {},
    icon: 'Lightbulb',
  },
  {
    id: 'shadow_affinity',
    name: 'Shadow Affinity',
    branch: 'drow_abilities',
    tier: 1,
    prestigeCost: 3,
    prerequisites: [],
    description: 'Gain advantage on Stealth checks in dim light or darkness.',
    aiPrompt: `"I am a child of the Underdark. Shadows embrace me like an old friend, hiding my presence from prying eyes."`,
    mechanicalContext: '[Passive: You have advantage on Dexterity (Stealth) checks made in dim light or darkness.]',
    effects: {},
    icon: 'Moon',
  },

  // Tier 2 - Intermediate
  {
    id: 'darkness_veil',
    name: 'Darkness Veil',
    branch: 'drow_abilities',
    tier: 2,
    prestigeCost: 5,
    minimumPrestigeLevel: 5,
    prerequisites: ['shadow_affinity'],
    description: 'Cast Darkness spell 1/day (DC 16 WIS save to see through).',
    aiPrompt: `"Magical darkness envelops the area—a sphere of absolute night that swallows all light."`,
    mechanicalContext: '[1/long rest: Cast Darkness. 15-foot radius sphere of magical darkness. Lasts 10 minutes. Creatures with darkvision cannot see through it. You can see through it normally.]',
    effects: { saveDC: 16, cooldown: 'Long rest', duration: '10 minutes' },
    icon: 'CloudMoon',
  },
  {
    id: 'fey_ancestry',
    name: 'Fey Ancestry',
    branch: 'drow_abilities',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['drow_magic'],
    description: "Advantage on saves vs. being charmed; can't be put to sleep by magic.",
    aiPrompt: `"The blood of the fey runs in my veins, ancient and potent. No enchantment can cloud my mind or steal my consciousness."`,
    mechanicalContext: "[Passive: You have advantage on saving throws against being charmed, and magic can't put you to sleep.]",
    effects: {},
    icon: 'Leaf',
  },
  {
    id: 'drow_resilience',
    name: 'Drow Resilience',
    branch: 'drow_abilities',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['shadow_affinity'],
    description: 'Resistance to poison damage and advantage vs. poison saves.',
    aiPrompt: `"Centuries of exposure to Underdark toxins have rendered me nearly immune to poisons that would fell lesser beings."`,
    mechanicalContext: '[Passive: You have resistance to poison damage and advantage on saving throws against being poisoned.]',
    effects: { mechanicalBonus: 'Poison resistance' },
    icon: 'Shield',
  },
  {
    id: 'shadow_step_drow',
    name: 'Shadow Step',
    branch: 'drow_abilities',
    tier: 2,
    prestigeCost: 5,
    minimumPrestigeLevel: 5,
    prerequisites: ['darkness_veil'],
    description: 'Bonus action to become invisible in dim light/darkness for 1 round.',
    aiPrompt: `"I step into shadow and disappear—for a heartbeat, I exist only as darkness itself."`,
    mechanicalContext: '[Bonus Action: When in dim light or darkness, become invisible until start of next turn. Moving into bright light, attacking, or casting a spell ends the effect early.]',
    effects: { cooldown: 'Once per turn' },
    icon: 'Footprints',
  },

  // Tier 3 - Advanced
  {
    id: 'lolth_endurance',
    name: "Lolth's Endurance",
    branch: 'drow_abilities',
    tier: 3,
    prestigeCost: 10,
    minimumPrestigeLevel: 10,
    prerequisites: ['drow_resilience', 'fey_ancestry'],
    description: 'Once per day, automatically succeed on a death save.',
    aiPrompt: `"I refuse to die—not here, not now. The strength of my ancestors flows through me, pulling me back from the brink."`,
    mechanicalContext: "[1/long rest: When you fail a death saving throw, you can choose to succeed instead. Additionally, you gain advantage on your next two death saves if you don't use this feature.]",
    effects: { cooldown: 'Long rest' },
    icon: 'HeartPulse',
  },
  {
    id: 'web_of_shadows',
    name: 'Web of Shadows',
    branch: 'drow_abilities',
    tier: 3,
    prestigeCost: 8,
    minimumPrestigeLevel: 8,
    prerequisites: ['shadow_step_drow'],
    description: 'Cast Web spell 1/day without components.',
    aiPrompt: `"Ghostly webbing materializes from the shadows, entangling all in its path with strands of pure darkness."`,
    mechanicalContext: '[1/long rest: Cast Web without verbal, somatic, or material components. 20-foot cube of webs restrains creatures. STR save DC 16 to break free. Webs are flammable.]',
    effects: { saveDC: 16, cooldown: 'Long rest' },
    icon: 'Network',
  },
  {
    id: 'seldarine_grace',
    name: "Seldarine's Grace",
    branch: 'drow_abilities',
    tier: 3,
    prestigeCost: 8,
    minimumPrestigeLevel: 8,
    prerequisites: ['fey_ancestry'],
    description: 'Channel elven deity power—next spell within 1 minute gains +2 to DC and attack.',
    aiPrompt: `"I call upon Mielikki, goddess of the forest, and feel her grace flow through me. My next incantation will carry divine weight."`,
    mechanicalContext: '[1/short rest: As a bonus action, empower yourself. Your next spell cast within 1 minute gains +2 to spell attack rolls and +2 to spell save DC.]',
    effects: { cooldown: 'Short rest', duration: '1 minute' },
    icon: 'Sun',
  },
  {
    id: 'drow_lord_authority',
    name: "Drow Lord's Authority",
    branch: 'drow_abilities',
    tier: 3,
    prestigeCost: 10,
    minimumPrestigeLevel: HIGH_TIER_GATES['drow_lord_authority'],
    prerequisites: ['lolth_endurance', 'web_of_shadows', 'seldarine_grace'],
    description: 'Creatures of lower CR/level must pass WIS save or be frightened on first encounter.',
    aiPrompt: `"I am Drizzt Do'Urden, slayer of demons and champion of the light. The force of my legend alone is enough to break the will of lesser foes."`,
    mechanicalContext: "[Passive: When a creature with CR less than your level sees you for the first time in an encounter, it must succeed on a WIS save (DC 16) or be frightened of you for 1 minute. They can repeat the save at end of each turn. Once a creature succeeds, it's immune for 24 hours.]",
    effects: { saveDC: 16 },
    icon: 'Crown',
  },
];

// ============================================
// MONK ABILITIES BRANCH (12 abilities)
// ============================================

const monkAbilities: PrestigeAbility[] = [
  // Tier 1 - Foundation
  {
    id: 'monastic_discipline',
    name: 'Monastic Discipline',
    branch: 'monk_abilities',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Unarmed strikes deal +1d6 damage (counts as magical for resistance).',
    aiPrompt: `"I channel the teachings of my monastic training, my fists glowing with spiritual energy as I strike."`,
    mechanicalContext: '[Passive: Your unarmed strikes deal 1d6 + STR or DEX mod damage. They count as magical for overcoming resistance and immunity.]',
    effects: { mechanicalBonus: '+1d6 unarmed damage' },
    icon: 'Flame',
  },
  {
    id: 'flurry_of_blows',
    name: 'Flurry of Blows',
    branch: 'monk_abilities',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Bonus action to make two unarmed strikes after attacking.',
    aiPrompt: `"In a blur of motion, I strike with rapid-fire precision—fist, elbow, knee—each blow flows into the next."`,
    mechanicalContext: '[Bonus Action: After you take the Attack action, make two unarmed strikes. Usable a number of times equal to your proficiency bonus per short rest.]',
    effects: { cooldown: 'Prof bonus/short rest' },
    icon: 'Zap',
  },
  {
    id: 'unarmored_defense',
    name: 'Unarmored Defense',
    branch: 'monk_abilities',
    tier: 1,
    prestigeCost: 3,
    prerequisites: [],
    description: 'AC = 10 + DEX mod + WIS mod when not wearing armor.',
    aiPrompt: `"I need no armor—my body is my fortress, my awareness my shield. I feel the flow of combat around me."`,
    mechanicalContext: "[Passive: While wearing no armor and not wielding a shield, your AC equals 10 + DEX mod + WIS mod. This stacks with other AC bonuses that don't set your base AC.]",
    effects: { mechanicalBonus: 'AC = 10 + DEX + WIS' },
    icon: 'User',
  },
  {
    id: 'deflect_missiles',
    name: 'Deflect Missiles',
    branch: 'monk_abilities',
    tier: 1,
    prestigeCost: 2,
    prerequisites: [],
    description: 'Reaction to reduce ranged damage by 1d10 + DEX mod.',
    aiPrompt: `"I snatch the arrow from the air with supernatural speed, turning their attack into nothing."`,
    mechanicalContext: '[Reaction: When hit by a ranged weapon attack, reduce damage by 1d10 + DEX mod. If reduced to 0, you catch the missile and can throw it back (ranged attack, 20/60 ft, 1d6 + DEX damage).]',
    effects: {},
    icon: 'ShieldOff',
  },

  // Tier 2 - Intermediate
  {
    id: 'patient_defense',
    name: 'Patient Defense',
    branch: 'monk_abilities',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['unarmored_defense'],
    description: 'Bonus action dodge—gain advantage on DEX saves until next turn.',
    aiPrompt: `"I center myself, breathing deeply, anticipating every incoming attack before it comes."`,
    mechanicalContext: '[Bonus Action: Take the Dodge action. Until the start of your next turn, attack rolls against you have disadvantage and you have advantage on DEX saves. Uses same resource pool as Flurry of Blows.]',
    effects: {},
    icon: 'Timer',
  },
  {
    id: 'step_of_wind',
    name: 'Step of the Wind',
    branch: 'monk_abilities',
    tier: 2,
    prestigeCost: 4,
    minimumPrestigeLevel: 5,
    prerequisites: ['flurry_of_blows'],
    description: 'Bonus action dash or disengage; ignore difficult terrain.',
    aiPrompt: `"I move like the wind itself—flowing around obstacles, gliding across treacherous ground as if it were smooth stone."`,
    mechanicalContext: '[Bonus Action: Take the Dash or Disengage action. Your jump distance is doubled for the turn and you ignore difficult terrain. Uses same resource pool as Flurry of Blows.]',
    effects: {},
    icon: 'Wind',
  },
  {
    id: 'slow_fall',
    name: 'Slow Fall',
    branch: 'monk_abilities',
    tier: 2,
    prestigeCost: 3,
    minimumPrestigeLevel: 5,
    prerequisites: ['deflect_missiles'],
    description: 'Reduce fall damage by 5× your level (no damage from falls under 50 ft).',
    aiPrompt: `"I twist in the air, dispersing the force of impact across my body, landing as gently as a falling leaf."`,
    mechanicalContext: '[Reaction: When you fall, reduce any falling damage you take by an amount equal to 5 × your character level.]',
    effects: {},
    icon: 'Feather',
  },
  {
    id: 'stunning_strike',
    name: 'Stunning Strike',
    branch: 'monk_abilities',
    tier: 2,
    prestigeCost: 5,
    minimumPrestigeLevel: 5,
    prerequisites: ['monastic_discipline'],
    description: 'Melee attack can stun target (CON save DC 16) for 1 round.',
    aiPrompt: `"My strike disrupts their chi, sending a shock through their nervous system that leaves them momentarily paralyzed."`,
    mechanicalContext: '[When you hit a creature with a melee weapon attack, you can attempt to stun. Target must succeed on a CON save (DC 16) or be stunned until the end of your next turn. Usable 3/short rest.]',
    effects: { saveDC: 16, cooldown: '3/short rest' },
    icon: 'Zap',
  },

  // Tier 3 - Advanced
  {
    id: 'diamond_soul',
    name: 'Diamond Soul',
    branch: 'monk_abilities',
    tier: 3,
    prestigeCost: 8,
    minimumPrestigeLevel: 8,
    prerequisites: ['patient_defense', 'stunning_strike'],
    description: 'Proficiency bonus added to all saving throws.',
    aiPrompt: `"My discipline is absolute. My body and mind are one—immune to fear, resistant to all corruption."`,
    mechanicalContext: '[Passive: You gain proficiency in all saving throws. Additionally, when you fail a saving throw, you can reroll it (1/short rest).]',
    effects: {},
    icon: 'Gem',
  },
  {
    id: 'timeless_body',
    name: 'Timeless Body',
    branch: 'monk_abilities',
    tier: 3,
    prestigeCost: 6,
    minimumPrestigeLevel: 8,
    prerequisites: ['slow_fall'],
    description: 'No longer age; immunity to disease; advantage vs. poison.',
    aiPrompt: `"Time has lost its hold on me. Disease cannot touch my perfected form. I am beyond such mortal concerns."`,
    mechanicalContext: '[Passive: You no longer age. You are immune to disease. You have advantage on saving throws against poison, and you have resistance to poison damage.]',
    effects: { mechanicalBonus: 'Ageless, disease immunity' },
    icon: 'Clock',
  },
  {
    id: 'empty_body',
    name: 'Empty Body',
    branch: 'monk_abilities',
    tier: 3,
    prestigeCost: 10,
    minimumPrestigeLevel: 10,
    prerequisites: ['step_of_wind', 'diamond_soul'],
    description: 'Become invisible for 1 minute; resistance to all damage except force.',
    aiPrompt: `"I empty myself of all presence, becoming one with the void. My form fades from sight as I transcend the material."`,
    mechanicalContext: '[Action, 1/long rest: Become invisible and have resistance to all damage except force damage for 1 minute. You can end this effect early as a bonus action.]',
    effects: { cooldown: 'Long rest', duration: '1 minute' },
    icon: 'Ghost',
  },
  {
    id: 'perfect_consciousness',
    name: 'Perfect Consciousness',
    branch: 'monk_abilities',
    tier: 3,
    prestigeCost: 10,
    minimumPrestigeLevel: HIGH_TIER_GATES['perfect_consciousness'],
    prerequisites: ['diamond_soul', 'timeless_body', 'empty_body'],
    description: "Gain truesight 120 ft; can't be surprised; always act first in initiative.",
    aiPrompt: `"My awareness expands beyond mortal limits. I perceive all things as they truly are—past illusion, through deception, beyond time itself."`,
    mechanicalContext: "[Passive: You have truesight out to 120 feet. You cannot be surprised while conscious. You always act first in initiative order (if multiple creatures have this, roll normally among them).]",
    effects: { mechanicalBonus: 'Truesight 120 ft' },
    icon: 'Brain',
  },
];

// ============================================
// COMBINED EXPORTS
// ============================================

export const prestigeAbilities: PrestigeAbility[] = [
  ...dualWieldingAbilities,
  ...guenhwyvarAbilities,
  ...drowAbilities,
  ...monkAbilities,
];

export function getPrestigeAbilityById(id: string): PrestigeAbility | undefined {
  return prestigeAbilities.find(a => a.id === id);
}

export function getAbilitiesByBranch(branch: PrestigeBranch): PrestigeAbility[] {
  return prestigeAbilities.filter(a => a.branch === branch);
}

export function getAbilitiesByTier(tier: 1 | 2 | 3): PrestigeAbility[] {
  return prestigeAbilities.filter(a => a.tier === tier);
}

export function getTotalPrestigeCost(): number {
  return prestigeAbilities.reduce((sum, a) => sum + a.prestigeCost, 0);
}

// Ability count by branch for progress tracking
export const ABILITY_COUNTS = {
  dual_wielding: dualWieldingAbilities.length,
  guenhwyvar: guenhwyvarAbilities.length,
  drow_abilities: drowAbilities.length,
  monk_abilities: monkAbilities.length,
  total: prestigeAbilities.length,
};
