import { useState, useMemo, useCallback } from 'react';
import { Wind, Shuffle, Copy, Check, Download, ChevronDown, ChevronUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { EMPYREAN_TONE_GUIDES, type EmpyreanGuide } from '@/lib/empyreanGMGuides';

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] as const;
const WIZARD_GUIDE_ID = 'empyrean-air-wizard-weekly';
const WIZARD_GUIDE_NAME = 'Weekly Tone Schedule';
const NONE = '__none__';

interface AirWizardProps {
  addGuide: (name: string, content: string, customId?: string) => boolean;
  updateGuide: (id: string, updates: { content?: string; enabled?: boolean }) => boolean;
  guides: { id: string; name: string }[];
}

function getToneCondensed(tone: EmpyreanGuide): string {
  // Extract the core directives section for the weekly guide
  const lines = tone.content.split('\n');
  const coreIdx = lines.findIndex(l => /narrative priority/i.test(l));
  const toneIdx = lines.findIndex((l, i) => i > coreIdx && /^###\s*tone/i.test(l));
  
  if (coreIdx === -1) {
    // Fallback: first 4 non-empty content lines after the header
    const contentLines = lines.filter(l => l.trim() && !l.startsWith('#') && !l.startsWith('**'));
    return contentLines.slice(0, 4).join('\n');
  }
  
  // Get from Narrative Priority through Scene Design (or first ~12 directive lines)
  const directiveLines: string[] = [];
  for (let i = coreIdx; i < lines.length && directiveLines.length < 12; i++) {
    const line = lines[i].trim();
    if (line.startsWith('### Tone') || line.startsWith('## ')) {
      if (directiveLines.length > 2) break;
    }
    if (line && !line.startsWith('## Core')) {
      directiveLines.push(lines[i]);
    }
  }
  return directiveLines.join('\n');
}

function generateWeeklyGuide(schedule: Record<string, string>): string {
  const assignedDays = DAYS.filter(d => schedule[d] && schedule[d] !== NONE);
  if (assignedDays.length === 0) return '';

  let guide = `# Weekly Tone Schedule — Dynamic Campaign Guide

You are an AI Dungeon Master. The PLAYER who gave you this guide has assigned a different narrative tone to each day of the real-world week.

## How This Works
- The PLAYER will tell you what day of the week it is. They may say "It's Wednesday" or their messages may include a real-world timestamp prefix (e.g., "[Wed 3:42 PM]").
- When the player indicates the current day, match your narration style to the tone assigned for that day in the schedule below.
- Transitions between tones should feel organic and seamless — like weather changing, not a light switch.
- Find narrative bridges: a change in setting, a time skip, a new NPC encounter, or a mood shift in the environment.
- NEVER announce the tone change. The player should feel the shift without being told about it.
- If the player has not yet indicated what day it is, ask them casually in-character (e.g., "Before we continue — what day greets you in the waking world?").

## Important
- The player is your source of real-world time. Do not guess or assume the day.
- The player controls when the tone shifts by telling you the day has changed.
- Ease into the new tone over the first few exchanges after a day change — do not switch abruptly.

## Weekly Schedule\n`;

  for (const day of DAYS) {
    const toneId = schedule[day];
    if (!toneId || toneId === NONE) {
      guide += `\n### ${day}: No Assigned Tone\nContinue with whatever tone feels natural for the current narrative.\n`;
      continue;
    }
    const tone = EMPYREAN_TONE_GUIDES.find(t => t.id === toneId);
    if (!tone) continue;
    
    guide += `\n### ${day}: ${tone.name}\n`;
    guide += getToneCondensed(tone);
    guide += '\n';
  }

  guide += `\n---\n\n*This guide was generated by the player using the Empyrean Campaign Pack's Air Wizard. The player is the sole source of real-world day information.*`;
  
  return guide;
}

export function AirWizard({ addGuide, updateGuide, guides }: AirWizardProps) {
  const [expanded, setExpanded] = useState(false);
  const [schedule, setSchedule] = useState<Record<string, string>>({});
  const [generatedGuide, setGeneratedGuide] = useState('');
  const [copied, setCopied] = useState(false);

  const assignedCount = useMemo(
    () => DAYS.filter(d => schedule[d] && schedule[d] !== NONE).length,
    [schedule],
  );

  const setDay = useCallback((day: string, toneId: string) => {
    setSchedule(prev => ({ ...prev, [day]: toneId }));
    setGeneratedGuide(''); // Clear preview when schedule changes
  }, []);

  const surpriseMe = useCallback(() => {
    const shuffled = [...EMPYREAN_TONE_GUIDES].sort(() => Math.random() - 0.5);
    const newSchedule: Record<string, string> = {};
    DAYS.forEach((day, i) => {
      newSchedule[day] = shuffled[i % shuffled.length].id;
    });
    setSchedule(newSchedule);
    setGeneratedGuide('');
    toast.success('Random tones assigned!');
  }, []);

  const generate = useCallback(() => {
    const guide = generateWeeklyGuide(schedule);
    setGeneratedGuide(guide);
  }, [schedule]);

  const copyGuide = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(generatedGuide);
      setCopied(true);
      toast.success('Weekly guide copied!');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  }, [generatedGuide]);

  const installGuide = useCallback(() => {
    const existing = guides.find(g => g.id === WIZARD_GUIDE_ID);
    if (existing) {
      updateGuide(WIZARD_GUIDE_ID, { content: generatedGuide, enabled: true });
      toast.success('Weekly Tone Schedule updated!');
    } else {
      const success = addGuide(WIZARD_GUIDE_NAME, generatedGuide, WIZARD_GUIDE_ID);
      if (success) toast.success('Weekly Tone Schedule installed!');
    }
  }, [generatedGuide, guides, addGuide, updateGuide]);

  return (
    <div className="rounded-lg border border-amber-500/20 bg-amber-500/5 overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-amber-500/10 transition-colors min-h-[44px]"
      >
        <Wind className="w-5 h-5 text-amber-400 shrink-0" />
        <div className="flex-1 min-w-0">
          <p className="text-sm font-cinzel font-bold text-amber-400">Air Wizard</p>
          <p className="text-[11px] text-muted-foreground">Build a weekly tone schedule for your AI DM</p>
        </div>
        {expanded ? (
          <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0" />
        ) : (
          <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0" />
        )}
      </button>

      {expanded && (
        <div className="px-4 pb-4 space-y-4 border-t border-amber-500/10 pt-4">
          {/* Explanation */}
          <p className="text-[11px] text-muted-foreground leading-relaxed">
            Assign a tone to each day of the week, then generate a guide you paste into your 3rd-party AI DM.
            <strong> You</strong> tell the AI what day it is — the AI follows your schedule.
          </p>

          {/* Surprise Me */}
          <Button
            variant="outline"
            size="sm"
            onClick={surpriseMe}
            className="w-full gap-2 h-10 border-amber-500/30 hover:bg-amber-500/10 text-amber-400"
          >
            <Shuffle className="w-4 h-4" />
            Surprise Me
          </Button>

          {/* Day selectors */}
          <div className="space-y-2">
            {DAYS.map(day => (
              <div key={day} className="flex items-center gap-3">
                <span className="text-xs font-medium w-[72px] shrink-0 text-muted-foreground">{day.slice(0, 3)}</span>
                <Select
                  value={schedule[day] || NONE}
                  onValueChange={(val) => setDay(day, val)}
                >
                  <SelectTrigger className="h-9 text-xs flex-1">
                    <SelectValue placeholder="None" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={NONE}>None</SelectItem>
                    {EMPYREAN_TONE_GUIDES.map(tone => (
                      <SelectItem key={tone.id} value={tone.id}>
                        {tone.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            ))}
          </div>

          {/* Generate button */}
          <Button
            variant="default"
            size="sm"
            onClick={generate}
            disabled={assignedCount === 0}
            className="w-full h-11 gap-2 font-cinzel"
          >
            Generate Guide ({assignedCount}/7 days)
          </Button>

          {/* Generated preview */}
          {generatedGuide && (
            <div className="space-y-3">
              <pre className="text-[11px] font-mono whitespace-pre-wrap text-muted-foreground leading-relaxed bg-background/60 rounded-lg p-3 max-h-[40vh] overflow-y-auto border border-border/30">
                {generatedGuide}
              </pre>
              <div className="flex items-center justify-between">
                <p className="text-[10px] text-muted-foreground">
                  {generatedGuide.length.toLocaleString()} characters
                </p>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={copyGuide}
                    className={cn(
                      'h-9 gap-2 min-w-[44px]',
                      copied && 'bg-green-500/20 border-green-500/40 text-green-400',
                    )}
                  >
                    {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied' : 'Copy'}
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={installGuide}
                    className="h-9 gap-2 min-w-[44px] border-cyan-500/30 hover:bg-cyan-500/10 text-cyan-400"
                  >
                    <Download className="w-4 h-4" />
                    Install
                  </Button>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
